dynamic: install


all: install


install:
	cp -f wlssk_96764LGW_WLTOB.save $(INSTALL_DIR)/bin/wlssk
	cp -f wldataeld_96764LGW_WLTOB.save $(INSTALL_DIR)/bin/wldataeld
	cp -f nvram_96764LGW_WLTOB.save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_96764LGW_WLTOB.save $(INSTALL_DIR)/lib/libnvram.so
