/***********************************************************************
 *
 *  Copyright (c) 2019  Broadcom
 *  All Rights Reserved
 *
 <:label-BRCM:2019:proprietary:standard

 This program is the proprietary software of Broadcom and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").  Except as set forth in
 an Authorized License, Broadcom grants no license (express or implied), right
 to use, or waiver of any kind with respect to the Software, and Broadcom
 expressly reserves all rights in and to the Software and all intellectual
 property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU HAVE
 NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY
 BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

 Except as expressly set forth in the Authorized License,

 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use
    all reasonable efforts to protect the confidentiality thereof, and to
    use this information only in connection with your use of Broadcom
    integrated circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
    RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND
    ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT,
    FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR
    COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE
    TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR
    PERFORMANCE OF THE SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR
    ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
    INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY
    WAY RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN
    IF BROADCOM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES;
    OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE
    SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE LIMITATIONS
    SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY
    LIMITED REMEDY.
:>
 *
 ************************************************************************/var TARGET_DBUS=1;var TARGET_RUNNER=5;var TARGET_CONTAINER=6;var TARGET_BEEP=7;var TARGET_BEEP_DEMO=8;var TARGET_AIRIQ=9;var TARGET_SPDTEST=10;var CMD_DBUS_INTROSPECT=0;var CMD_DBUS_METHOD=CMD_DBUS_INTROSPECT+1;var CMD_DBUS_PROGET=CMD_DBUS_INTROSPECT+2;var CMD_DBUS_PROSET=CMD_DBUS_INTROSPECT+3;var CMD_DBUS_LIST=CMD_DBUS_INTROSPECT+4;var CMD_RUNNER_LOAD=0;var CMD_RUNNER_SAVE=CMD_RUNNER_LOAD+1;var CMD_RUNNER_GET=CMD_RUNNER_LOAD+2;var CMD_RUNNER_APPLY=CMD_RUNNER_LOAD+3;var CMD_CONTAINER_LIST=0;var CMD_CONTAINER_INFO=CMD_CONTAINER_LIST+1;var CMD_BEEP_EU_LIST=0;var CMD_BEEP_EU_START=CMD_BEEP_EU_LIST+1;var CMD_BEEP_EU_STOP=CMD_BEEP_EU_LIST+2;var CMD_BEEP_DU_LIST=CMD_BEEP_EU_LIST+3;var CMD_BEEP_DU_REMOVE=CMD_BEEP_EU_LIST+4;var CMD_BEEP_DU_INSTALL=CMD_BEEP_EU_LIST+5;var CMD_BEEP_DU_AVLLIST=CMD_BEEP_EU_LIST+6;var CMD_BEEP_EE_LIST=CMD_BEEP_EU_LIST+7;var CMD_BEEP_EE_AVLLIST=CMD_BEEP_EU_LIST+8;var CMD_BEEP_EE_ENABLE=CMD_BEEP_EU_LIST+9;var CMD_BEEP_EE_INSTALL=CMD_BEEP_EU_LIST+10;var CMD_BEEP_EE_UPGRADE=CMD_BEEP_EU_LIST+11;var CMD_BEEP_EE_REMOVE=CMD_BEEP_EU_LIST+12;var CMD_BEEP_EE_SUPPORT=CMD_BEEP_EU_LIST+13;var CMD_BEEP_INIT=CMD_BEEP_EU_LIST+14;var CMD_BEEP_UNINIT=CMD_BEEP_EU_LIST+15;var BEEP_ACTION_INSTALL=1;var BEEP_ACTION_UPDATE=BEEP_ACTION_INSTALL+1;var BEEP_ACTION_REMOVE=BEEP_ACTION_INSTALL+2;var BEEP_EE_REMOVABLE=1;var BEEP_EE_UPGRADABLE=2;var CMD_DEMO_GET=0;var CMD_DEMO_START_FDEMO=CMD_DEMO_GET+1;var CMD_DEMO_START_CDEMO=CMD_DEMO_GET+2;var CMD_DEMO_START_MDEMO=CMD_DEMO_GET+3;var CMD_DEMO_GET_DUMP=CMD_DEMO_GET+4;var CMD_DEMO_PREREQ_CHK=CMD_DEMO_GET+5;var CMD_DEMO_STATUS_GET=CMD_DEMO_GET+6;var CMD_DEMO_START_EU=CMD_DEMO_GET+7;var CMD_AIRIQ_PREREQ_CHK=0;var CMD_AIRIQ_REG_SHUTDOWN=CMD_AIRIQ_PREREQ_CHK+1;var CMD_AIRIQ_REG_IFACE_LIST=CMD_AIRIQ_PREREQ_CHK+2;var CMD_AIRIQ_START_SCAN=CMD_AIRIQ_PREREQ_CHK+3;var CMD_AIRIQ_STOP_SCAN=CMD_AIRIQ_PREREQ_CHK+4;var CMD_SPDTEST_PREREQ_CHK=0;var CMD_SPDTEST_SHUTDOWN=CMD_SPDTEST_PREREQ_CHK+1;var CMD_SPDTEST_START=CMD_SPDTEST_PREREQ_CHK+2;var CMD_SPDTEST_RESUME=CMD_SPDTEST_PREREQ_CHK+3;var CMD_SPDTEST_GETSTATUS=CMD_SPDTEST_PREREQ_CHK+4;
