MENU_DEVICE_INFO                       =  0
MENU_DEVICE_SUMMARY                    =  1
MENU_DEVICE_WAN                        =  2
MENU_STATISTICS                        =  3
MENU_ST_LAN                            =  4
MENU_ST_ATM                            =  5
MENU_ST_ADSL                           =  6
MENU_DEVICE_ROUTE                      =  7
MENU_RT_ARP                            =  8
MENU_QUICK_SETUP                       =  9
MENU_ADVANCED_SETUP                    = 10
MENU_DSL                               = 11
MENU_WAN                               = 12
MENU_LAN                               = 13
MENU_SC_NAT                            = 14
MENU_SC_VIRTUAL_SERVER                 = 15
MENU_SC_PORT_TRIGGER                   = 16
MENU_SC_DMZ_HOST                       = 17
MENU_SC_SECURITY                       = 18
MENU_SC_IP_FILTER                      = 19
MENU_SC_INCOMING                       = 20
MENU_SC_OUTGOING                       = 21
MENU_MAC_FILTER                        = 22
MENU_QOS                               = 23
MENU_ROUTING                           = 24
MENU_RT_STATIC_ROUTE                   = 25
MENU_RT_RIP                            = 26
MENU_RT_DEFAULT_ROUTE                  = 27
MENU_DNS                               = 28
MENU_DIAGNOSTICS                       = 29
MENU_MANAGEMENT                        = 30
MENU_TL_SYSTEM_LOG                     = 31
MENU_TL_SNMP                           = 32
MENU_TL_UPDATE_SOFTWARE                = 33
MENU_TL_SETTINGS                       = 34
MENU_TL_SETTINGS_BACKUP                = 35
MENU_TL_SETTINGS_UPDATE                = 36
MENU_TL_SETTINGS_DEFAULT               = 37
MENU_WIRELESS_SETTINGS                 = 38
MENU_WL_BASIC                          = 39
MENU_WL_SECURITY                       = 40
MENU_WL_MAC_FILTERING                  = 41
MENU_WL_WDS                            = 42
MENU_WL_ADVANCED                       = 43
MENU_VOICE_SETTINGS                    = 44
MENU_VOICE_SIP_BASIC                   = 45
MENU_VOICE_STATS                       = 46
MENU_RESET_ROUTER                      = 47
MENU_ACC_CNTR                          = 48
MENU_ACC_CNTR_PASSWORD                 = 49
MENU_DNS_SETUP                         = 50
MENU_DDNS                              = 51
MENU_NTPD                              = 52
MENU_PARENTAL_CNTL                     = 53
MENU_WL_STATION_LIST                   = 54
MENU_ALGS                              = 55
MENU_DHCPINFO                          = 56
MENU_INTF_GROUPING                     = 57
MENU_IPP                               = 58
MENU_WL_SES                            = 59 //SUPPORT_SES
MENU_SC_IPSEC                          = 60
MENU_CERT                              = 61
MENU_CERT_LOCAL                        = 62
MENU_CERT_CA                           = 63
MENU_WL_QOS                            = 64
MENU_TR69C                             = 65
MENU_ST_VDSL                           = 66
MENU_QOS_CLASS                         = 67
MENU_QOS_QUEUE                         = 68
MENU_VOICE_SIP_ADVANCED                = 69
MENU_VOICE_SIP_DEBUG                   = 70
MENU_UPNP                              = 71
MENU_LAN_PORTS                         = 72
MENU_URLFILTER                         = 73
MENU_TOD                               = 74
MENU_LAN6                              = 75
MENU_RT_STATIC_ROUTE6                  = 76
MENU_DNSPROXY                          = 77
MENU_POLICY_ROUTING                    = 78
MENU_LAYER2_INTERFACE                  = 79
MENU_DSL_ATM_INTERFACE                 = 80
MENU_DSL_PTM_INTERFACE                 = 81
MENU_ACC_CNTR_IPV6_ADDR                = 82
MENU_DIAGP8021AG                       = 83
MENU_OMCI_CFG                          = 84
MENU_OMCI_GET_SET                      = 85
MENU_OMCI_CREATE                       = 86
MENU_OMCI_GET_NEXT                     = 87
MENU_OMCI_MACRO                        = 88
MENU_OMCI_DOWNLOAD                     = 89
MENU_OMCI_SYSTEM                       = 90
MENU_ETH_INTERFACE                     = 91
MENU_PWRMNGT                           = 92
MENU_VOICE_NTR                         = 93
MENU_VOICE_DECT                        = 94
MENU_DSL_BONDING                       = 95
MENU_MULTICAST                         = 96
MENU_VPN                               = 97
MENU_VPN_L2TPAC                        = 98
MENU_STORAGESERVICE                    = 99
MENU_STORAGE_INFO                      = 100
MENU_STORAGE_USERACCOUNT               = 101
MENU_STANDBY                           = 102
MENU_DLNA                              = 103
MENU_WL_WAPI_AS                        = 104
MENU_TL_SECURITY_LOG                   = 105
MENU_AUTODETECTION                     = 106
MENU_GPONWAN_INTERFACE                 = 107
MENU_QOS_POLICER                       = 108
MENU_MODSW                             = 109
MENU_MODSW_EE                          = 110
MENU_MODSW_DU                          = 111
MENU_MODSW_EU                          = 112
MENU_EPONWAN_INTERFACE                 = 113
MENU_IP_TUNNEL                         = 114
MENU_6IN4_TUNNEL                       = 115
MENU_4IN6_TUNNEL                       = 116
MENU_BMU                               = 117
MENU_LAN_VLAN                          = 118
MENU_OPTICAL                           = 119
MENU_WIFI_INTERFACE                    = 120
MENU_QOS_PORT_SHAPING                  = 121
MENU_DIAGETHOAM                        = 122
MENU_SPDSVC                            = 123
MENU_QUEUE_CFG                         = 124
MENU_WL_QUEUE                          = 125
MENU_XMPP_CONN                         = 126
MENU_UNUSED                            = 127
MENU_CPU_MEM_GRAPH                     = 128
MENU_WL_VISUALIZATION                  = 129
MENU_WL_VISUALIZATION_SITESURVEY       = 130
MENU_WL_VISUALIZATION_CONFIGURE        = 131
MENU_WL_VISUALIZATION_CHANNELSTAT      = 132
MENU_WL_VISUALIZATION_METRICS          = 133
MENU_VOICE_SIP_CCTK                    = 134
MENU_USB_HOSTS                         = 135
MENU_DPI                               = 136
MENU_DPI_GRAPH                         = 137
MENU_DPI_APP_INST_TABLE                = 138
MENU_WL_PASSPOINT                      = 139
MENU_CELLULAR_INFO                     = 140
MENU_CELLULAR_INTERFACE                = 141
MENU_CELLULAR_INTERFACE_INTF           = 142
MENU_CELLULAR_APN                      = 143
MENU_CELLULAR_SMS                      = 144
MENU_OAM_LOID                          = 145
MENU_ST_QUEUE                          = 146
MENU_VOICE_EPTAPP                      = 147
MENU_OPENVS                            = 148
MENU_STUN                              = 149
MENU_MAP                               = 150
MENU_WL_MENU_RADIO                     = 151
MENU_WL_MENU_MEDIA                     = 152
MENU_WL_MENU_SSID                      = 153
MENU_WL_MENU_SECURITY                  = 154
MENU_WL_MENU_WPS                       = 155
MENU_WL_MENU_DEMO_ON_DFS               = 156
MENU_WL_MENU_DEMO_ON_WBD               = 157
MENU_MODSW_DBUS_REMOTE                 = 158
MENU_VOICE2_SETTINGS                   = 159
MENU_VOICE2_GLOBAL                     = 160
MENU_VOICE2_DIGITMAP                   = 161
MENU_VOICE2_SERVICE_PROVIDER           = 162
MENU_VOICE2_CALLMGT                    = 163
MENU_VOICE2_STATS                      = 164
MENU_VOICE2_DECT                       = 165
MENU_VOICE2_DEBUG                      = 166
MENU_MODSW_CONTAINER                   = 167
MENU_WL_AIRIQ_ENABLE                   = 168
MENU_TL_SETTINGS_PMD                   = 169
MENU_FLOWSTATS                         = 170
MENU_ETH_LAG                           = 171
MENU_TL_WAN_SELECT                     = 172
MENU_WL_IQOS                           = 173
MENU_MODSW_OPENPLAT                    = 174
MENU_BAS                               = 175
MENU_WL_MENU_DPP                       = 176
MENU_VPN_PPTPAC                        = 177
MENU_TL_SETTINGS_SMTC                  = 178
MENU_VXLAN                             = 179
MENU_VXLAN_TUNNEL                      = 180
MENU_APP_CONN                          = 181
MENU_STOMP                             = 182
MENU_USP                               = 183
MENU_AGENT                             = 184
MENU_CONTROLLER                        = 185
MENU_MTP                               = 186
MENU_VXLAN_STS                         = 187
MENU_SUBSCRIPTION                      = 188
MENU_CONTROLLER_TRUST                  = 189
MENU_ROLE                              = 190
MENU_ROLE_PERMISSION                   = 191
MENU_MQTT                              = 192
MENU_MQTT_CLIENT                       = 193
MENU_GRE                               = 194
MENU_GRE_TUNNEL                        = 195
MENU_GRE_STS                           = 196
MENU_CHALLENGE                         = 197
MENU_LICENSES                          = 198
MENU_BAS_CONFIGURATION                 = 199
MENU_BAS_APPLICATIONS                  = 200
MENU_VPN_L2TPNS                        = 201
MENU_VPN_PPTPNS                        = 202
MENU_DIAG_LPSELT                       = 203

var menuTitle = new Array();
menuTitle[MENU_DEVICE_INFO]                           = 'Device Info';
menuTitle[MENU_DEVICE_SUMMARY]                        = 'Summary';
menuTitle[MENU_DEVICE_WAN]                            = 'WAN';
menuTitle[MENU_STATISTICS]                            = 'Statistics';
menuTitle[MENU_ST_LAN]                                = 'LAN';
menuTitle[MENU_ST_ATM]                                = 'xTM';
menuTitle[MENU_ST_ADSL]                               = 'xDSL';
menuTitle[MENU_DEVICE_ROUTE]                          = 'Route';
menuTitle[MENU_RT_ARP]                                = 'ARP';
menuTitle[MENU_QUICK_SETUP]                           = 'Quick Setup';
menuTitle[MENU_ADVANCED_SETUP]                        = 'Advanced Setup';
menuTitle[MENU_DSL]                                   = 'DSL';
menuTitle[MENU_WAN]                                   = 'WAN Service';
menuTitle[MENU_LAN]                                   = 'LAN';
menuTitle[MENU_SC_NAT]                                = 'NAT';
menuTitle[MENU_SC_VIRTUAL_SERVER]                     = 'Virtual Servers';
menuTitle[MENU_SC_PORT_TRIGGER]                       = 'Port Triggering';
menuTitle[MENU_SC_DMZ_HOST]                           = 'DMZ Host';
menuTitle[MENU_SC_SECURITY]                           = 'Security';
menuTitle[MENU_SC_IP_FILTER]                          = 'IP Filtering';
menuTitle[MENU_SC_INCOMING]                           = 'Incoming';
menuTitle[MENU_SC_OUTGOING]                           = 'Outgoing';
menuTitle[MENU_MAC_FILTER]                            = 'MAC Filtering';
menuTitle[MENU_QOS]                                   = 'Quality of Service';
menuTitle[MENU_ROUTING]                               = 'Routing';
menuTitle[MENU_RT_STATIC_ROUTE]                       = 'Static Route';
menuTitle[MENU_RT_RIP]                                = 'RIP';
menuTitle[MENU_RT_DEFAULT_ROUTE]                      = 'Default Gateway';
menuTitle[MENU_DNS]                                   = 'DNS';
menuTitle[MENU_DIAGNOSTICS]                           = 'Diagnostics';
menuTitle[MENU_MANAGEMENT]                            = 'Management';
menuTitle[MENU_TL_SYSTEM_LOG]                         = 'System Log';
menuTitle[MENU_TL_SNMP]                               = 'SNMP Agent';
menuTitle[MENU_TL_UPDATE_SOFTWARE]                    = 'Update Software';
menuTitle[MENU_TL_SETTINGS]                           = 'Settings';
menuTitle[MENU_TL_SETTINGS_BACKUP]                    = 'Backup';
menuTitle[MENU_TL_SETTINGS_UPDATE]                    = 'Update';
menuTitle[MENU_TL_SETTINGS_DEFAULT]                   = 'Restore Default';
menuTitle[MENU_WIRELESS_SETTINGS]                     = 'Wireless';
menuTitle[MENU_WL_BASIC]                              = 'Basic';
menuTitle[MENU_WL_SECURITY]                           = 'Security';
menuTitle[MENU_WL_MAC_FILTERING]                      = 'MAC Filter';
menuTitle[MENU_WL_WDS]                                = 'Wireless Bridge';
menuTitle[MENU_WL_ADVANCED]                           = 'Advanced';
menuTitle[MENU_VOICE_SETTINGS]                        = 'Voice';
menuTitle[MENU_VOICE_SIP_BASIC]                       = 'SIP Basic Setting';
menuTitle[MENU_VOICE_SIP_ADVANCED]                    = 'SIP Advanced Setting';
menuTitle[MENU_VOICE_SIP_DEBUG]                       = 'SIP Debug Setting';
menuTitle[MENU_VOICE_STATS]                           = 'Statistics';
menuTitle[MENU_RESET_ROUTER]                          = 'Reboot';
menuTitle[MENU_ACC_CNTR]                              = 'Access Control';
menuTitle[MENU_ACC_CNTR_PASSWORD]                     = 'Passwords';
menuTitle[MENU_DNS_SETUP]                             = 'DNS Server';
menuTitle[MENU_DDNS]                                  = 'Dynamic DNS';
menuTitle[MENU_NTPD]                                  = 'Internet Time';
menuTitle[MENU_PARENTAL_CNTL]                         = 'Parental Control';
menuTitle[MENU_WL_STATION_LIST]                       = 'Station Info'
menuTitle[MENU_ALGS]                                  = 'ALG';
menuTitle[MENU_DHCPINFO]                              = 'DHCP';
menuTitle[MENU_INTF_GROUPING]                         = 'Interface Grouping';
menuTitle[MENU_IPP]                                   = 'Print Server';
menuTitle[MENU_WL_SES]                                = 'SecureEasySetup'; //SUPPORT_SES
menuTitle[MENU_SC_IPSEC]                              = 'IPSec';
menuTitle[MENU_CERT]                                  = 'Certificate';
menuTitle[MENU_CERT_LOCAL]                            = 'Local';
menuTitle[MENU_CERT_CA]                               = 'Trusted CA';
menuTitle[MENU_WL_QOS]                                = 'Quality of Service';
menuTitle[MENU_TR69C]                                 = 'TR-069 Client';
menuTitle[MENU_ST_VDSL]                               = 'VDSL';
menuTitle[MENU_QOS_CLASS]                             = 'QoS Classification';
menuTitle[MENU_QOS_QUEUE]                             = 'QoS Queue';
menuTitle[MENU_QOS_PORT_SHAPING]                      = 'QoS Port Shaping';
menuTitle[MENU_UPNP]                                  = 'UPnP';
menuTitle[MENU_LAN_PORTS]                             = 'LAN Ports';
menuTitle[MENU_URLFILTER]                             = 'Url Filter';
menuTitle[MENU_TOD]                                   = 'Time Restriction';
menuTitle[MENU_LAN6]                                  = 'IPv6 Autoconfig';
menuTitle[MENU_RT_STATIC_ROUTE6]                      = 'IPv6 Static Route';
menuTitle[MENU_DNSPROXY]                              = 'DNS Proxy';
menuTitle[MENU_POLICY_ROUTING]                        = 'Policy Routing';
menuTitle[MENU_LAYER2_INTERFACE]                      = 'Layer2 Interface';
menuTitle[MENU_DSL_ATM_INTERFACE]                     = 'ATM Interface';
menuTitle[MENU_DSL_PTM_INTERFACE]                     = 'PTM Interface';
menuTitle[MENU_ACC_CNTR_IPV6_ADDR]                    = 'IPv6 Addresses';
menuTitle[MENU_DIAGP8021AG]                           = 'Fault Management';
menuTitle[MENU_DIAGETHOAM]                            = 'Ethernet OAM';
menuTitle[MENU_SPDSVC]                                = 'Speed Service';
menuTitle[MENU_OMCI_CFG]                              = 'OMCI Configuration';
menuTitle[MENU_OMCI_GET_SET]                          = 'Get/Set/Reboot';
menuTitle[MENU_OMCI_CREATE]                           = 'Create';
menuTitle[MENU_OMCI_GET_NEXT]                         = 'Get Next';
menuTitle[MENU_OMCI_MACRO]                            = 'Macro';
menuTitle[MENU_OMCI_DOWNLOAD]                         = 'Download';
menuTitle[MENU_OMCI_SYSTEM]                           = 'System';
menuTitle[MENU_ETH_INTERFACE]                         = 'ETH Interface';
menuTitle[MENU_PWRMNGT]                               = 'Power Management';
menuTitle[MENU_VOICE_NTR]                             = 'NTR';
menuTitle[MENU_VOICE_DECT]                            = 'DECT';
menuTitle[MENU_DSL_BONDING]                           = 'DSL Bonding';
menuTitle[MENU_MULTICAST]                             = 'Multicast';
menuTitle[MENU_VPN]                                   = 'VPN';
menuTitle[MENU_VPN_L2TPAC]                            = 'L2TP Client';
menuTitle[MENU_VPN_L2TPNS]                            = 'L2TP Server';
menuTitle[MENU_STORAGESERVICE]                        = 'Storage Service';
menuTitle[MENU_STORAGE_INFO]                          = 'Storage Device Info';
menuTitle[MENU_STORAGE_USERACCOUNT]                   = 'User Accounts';
menuTitle[MENU_STANDBY]                               = 'Standby';
menuTitle[MENU_DLNA]                                  = 'DLNA';
menuTitle[MENU_WL_WAPI_AS]                            = 'WAPI AS Server';
menuTitle[MENU_TL_SECURITY_LOG]                       = 'Security Log';
menuTitle[MENU_AUTODETECTION]                         = 'Auto Detection';
menuTitle[MENU_GPONWAN_INTERFACE]                     = 'GPON Interface';
menuTitle[MENU_QOS_POLICER]                           = 'QoS Policer';
menuTitle[MENU_MODSW]                                 = 'BEEP';
menuTitle[MENU_MODSW_OPENPLAT]                        = 'Open Platform';
menuTitle[MENU_MODSW_EE]                              = 'Exec. Environment';
menuTitle[MENU_MODSW_DU]                              = 'Deployment Unit';
menuTitle[MENU_MODSW_EU]                              = 'Execution Unit';
menuTitle[MENU_EPONWAN_INTERFACE]                     = 'EPON Interface';
menuTitle[MENU_IP_TUNNEL]                             = 'IP Tunnel';
menuTitle[MENU_6IN4_TUNNEL]                           = 'IPv6inIPv4';
menuTitle[MENU_4IN6_TUNNEL]                           = 'IPv4inIPv6';
menuTitle[MENU_BMU]                                   = 'Batteries';
menuTitle[MENU_LAN_VLAN]                              = 'Lan VLAN Setting';
menuTitle[MENU_OPTICAL]                               = 'Optical';
menuTitle[MENU_WIFI_INTERFACE]                        = 'WIFI Interface';
menuTitle[MENU_QUEUE_CFG]                             = 'Queue Configuration';
menuTitle[MENU_WL_QUEUE]                              = 'Wlan Queue';
menuTitle[MENU_XMPP_CONN]                             = 'XMPP Connection';
menuTitle[MENU_UNUSED]                                = 'Unused';
menuTitle[MENU_CPU_MEM_GRAPH]                         = 'CPU & Memory';
menuTitle[MENU_FLOWSTATS]                             = 'Flow statistics';
menuTitle[MENU_WL_VISUALIZATION]                      = 'Wifi Insight';
menuTitle[MENU_WL_VISUALIZATION_SITESURVEY]           = 'Site Survey';
menuTitle[MENU_WL_VISUALIZATION_CONFIGURE]            = 'Configure';
menuTitle[MENU_WL_VISUALIZATION_METRICS]              = 'Metrics';
menuTitle[MENU_WL_VISUALIZATION_CHANNELSTAT]          = 'Channel Statistics';
menuTitle[MENU_VOICE_SIP_CCTK]                        = 'SIP CCTK Setting';
menuTitle[MENU_USB_HOSTS]                             = 'USB Hosts';
menuTitle[MENU_DPI]                                   = 'DPI';
menuTitle[MENU_DPI_GRAPH]                             = 'Statistic Charts';
menuTitle[MENU_DPI_APP_INST_TABLE]                    = 'Devices & Applications';
menuTitle[MENU_WL_PASSPOINT]                          = 'Wifi Passpoint';
menuTitle[MENU_CELLULAR_INFO]                         = 'Cellular';
menuTitle[MENU_CELLULAR_INTERFACE]                    = 'Cellular Interface';
menuTitle[MENU_CELLULAR_INTERFACE_INTF]               = 'Interface';
menuTitle[MENU_CELLULAR_APN]                          = 'Access Point';
menuTitle[MENU_CELLULAR_SMS]                          = 'SMS';
menuTitle[MENU_OAM_LOID]                              = 'LOID Authentication';
menuTitle[MENU_ST_QUEUE]                              = 'Queue';
menuTitle[MENU_VOICE_EPTAPP]                          = 'EPTAPP';
menuTitle[MENU_OPENVS]                                = 'OpenVSwitch';
menuTitle[MENU_STUN]                                  = 'STUN Client';
menuTitle[MENU_MAP]                                   = 'MAP';
menuTitle[MENU_WL_MENU_RADIO]                         = 'Radio';
menuTitle[MENU_WL_MENU_MEDIA]                         = 'Media';
menuTitle[MENU_WL_MENU_SSID]                          = 'SSID';
menuTitle[MENU_WL_MENU_SECURITY]                      = 'Security';
menuTitle[MENU_WL_MENU_WPS]                           = 'WPS';
menuTitle[MENU_WL_MENU_DEMO_ON_DFS]                   = 'ZeroDFS';
menuTitle[MENU_WL_MENU_DEMO_ON_WBD]                   = 'WBD';
menuTitle[MENU_MODSW_DBUS_REMOTE]                     = 'DBus Remote Setting';

menuTitle[MENU_VOICE2_SETTINGS]                       = 'Voice';
menuTitle[MENU_VOICE2_GLOBAL]                         = 'Global Settings';
menuTitle[MENU_VOICE2_DIGITMAP]                       = 'Voice Digit Map';
menuTitle[MENU_VOICE2_SERVICE_PROVIDER]               = 'Service Provider Settings';
menuTitle[MENU_VOICE2_CALLMGT]                        = 'Call Management';
menuTitle[MENU_VOICE2_STATS]                          = 'Statistics and Status';
menuTitle[MENU_VOICE2_DECT]                           = 'DECT Settings';
menuTitle[MENU_VOICE2_DEBUG]                          = 'Debug';

menuTitle[MENU_MODSW_CONTAINER]                       = 'Containers';
menuTitle[MENU_WL_AIRIQ_ENABLE]                       = 'AirIQ';

menuTitle[MENU_TL_SETTINGS_PMD]                       = 'PMD';
menuTitle[MENU_ETH_LAG]                               = 'ETH LAG';
menuTitle[MENU_TL_WAN_SELECT]                         = 'WAN Select';
menuTitle[MENU_WL_IQOS]                               = 'iQoS';

menuTitle[MENU_BAS]                                   = 'BAS';
menuTitle[MENU_WL_MENU_DPP]                           = 'DPP';

menuTitle[MENU_VPN_PPTPAC]                            = 'PPTP Client';
menuTitle[MENU_VPN_PPTPNS]                            = 'PPTP Server';

menuTitle[MENU_TL_SETTINGS_SMTC]                      = 'SMTC';
menuTitle[MENU_APP_CONN]                              = 'Application Connection';
menuTitle[MENU_STOMP]                                 = 'STOMP';
menuTitle[MENU_USP]                                   = 'USP';
menuTitle[MENU_AGENT]                                 = 'Agent';
menuTitle[MENU_CONTROLLER]                            = 'Controllers';
menuTitle[MENU_MTP]                                   = 'MTP';
menuTitle[MENU_SUBSCRIPTION]                          = 'Subscriptions';
menuTitle[MENU_CONTROLLER_TRUST]                      = 'Controller Trust';
menuTitle[MENU_ROLE]                                  = 'Roles';
menuTitle[MENU_ROLE_PERMISSION]                       = 'Permissions';
menuTitle[MENU_CHALLENGE]                             = 'Challenge';

menuTitle[MENU_VXLAN]                                 = 'VxLan';
menuTitle[MENU_VXLAN_TUNNEL]                          = 'VxLan Tunnel';
menuTitle[MENU_VXLAN_STS]                             = 'VxLan Stats';

menuTitle[MENU_MQTT]                                  = 'MQTT';
menuTitle[MENU_MQTT_CLIENT]                           = 'Client';

menuTitle[MENU_GRE]                                   = 'GRE';
menuTitle[MENU_GRE_TUNNEL]                            = 'GRE Tunnel';
menuTitle[MENU_GRE_STS]                               = 'GRE Stats';

menuTitle[MENU_LICENSES]                              = 'Licenses';
menuTitle[MENU_BAS_CONFIGURATION]                     = 'Configuration';
menuTitle[MENU_BAS_APPLICATIONS]                      = 'Applications';

menuTitle[MENU_DIAG_LPSELT]                           = 'LP-SELT';

function getMenuTitle(index) {
   return menuTitle[index];
}
