#ifndef __WLCSM_DM_NVRAM_MNGR_MAPPING_H__  
#define __WLCSM_DM_NVRAM_MNGR_MAPPING_H__ 


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file wlcsm_nvram_mngr_mapping.h 
 * \brief Automatically generated header file wlcsm_nvram_mngr_mapping.h
 */


#define MNGR_POS_RADIO (1)
#define MNGR_POS_SSID (2)
typedef enum {
 WLCSM_DT_STRING, /**< string type [char *] */
 WLCSM_DT_UINT,   /**< unsigned int  */
 WLCSM_DT_SINT32, /**< int */
 WLCSM_DT_UINT64,
 WLCSM_DT_SINT64,
 WLCSM_DT_BOOL,
 WLCSM_DT_BOOLREV, /**< bool reverese, the saved value in dm is reversed than in runtime value */
 WLCSM_DT_BASE64,
 WLCSM_DT_HEXBINARY,
 WLCSM_DT_DATETIME,
 WLCSM_DT_STR2INT, /**< DM saved value is string, but runtime is using integer,use mapper to convert */
 WLCSM_DT_INT2STR, /**< DM saved value is int, but runtime is string */
 WLCSM_DT_BOOL2STR,/**< DM saved value is bool, but runtime is string */
} WLCSM_DM_TYPE;
typedef struct {
char *nvram_name;
int pos;
char *mngr_name;
WLCSM_DM_TYPE data_type;
} WLCSM_NVRAM_MNGR_MAPPING;
#define MNGR_NVRAM_MLEN (118)
extern WLCSM_NVRAM_MNGR_MAPPING g_wlcsm_nvram_mngr_mapping[118];

#endif