#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1CA0)
#define runner_d_timer_scheduler_set		(0x1CA0)
#define runner_d_start_task_flow_cache_wakeup_request		(0xDF8)
#define runner_d_flow_cache_wakeup_request		(0xDF8)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x1A80)
#define runner_d_lan_dispatch_wakeup_request		(0x1A80)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_lan_normal_wakeup_request		(0x1A8)
#define runner_d_lan_normal_wakeup_request		(0x1A8)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1E1C)
#define runner_d_free_skb_index_wakeup_request		(0x1E1C)
#define runner_d_free_skb_index_tx_abs_done		(0x1E1C)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1F94)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1F94)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1408)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x147C)
#define runner_d_gpe_sop_push_replace_sram_64		(0x1490)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x14A4)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x14B8)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x152C)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x157C)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x15B8)
#define runner_d_gpe_replace_pointer_32_ddr		(0x1608)
#define runner_d_gpe_replace_pointer_32_sram		(0x162C)
#define runner_d_gpe_replace_pointer_64_sram		(0x1650)
#define runner_d_gpe_replace_16		(0x1674)
#define runner_d_gpe_replace_32		(0x16A8)
#define runner_d_gpe_replace_bits_16		(0x16CC)
#define runner_d_gpe_copy_add_16_cl		(0x16F8)
#define runner_d_gpe_copy_add_16_sram		(0x1704)
#define runner_d_gpe_copy_bits_16_cl		(0x174C)
#define runner_d_gpe_copy_bits_16_sram		(0x1758)
#define runner_d_gpe_insert_16		(0x17A0)
#define runner_d_gpe_delete_16		(0x1808)
#define runner_d_gpe_decrement_8		(0x1848)
#define runner_d_gpe_apply_icsum_16		(0x186C)
#define runner_d_gpe_apply_icsum_nz_16		(0x1890)
#define runner_d_gpe_compute_csum_16_cl		(0x18CC)
#define runner_d_gpe_compute_csum_16_sram		(0x18D8)
#define runner_d_gpe_buffer_copy_16_sram		(0x1918)
#define runner_d_gpe_buffer_copy_16_ddr		(0x1940)
#define runner_d_gpe_replace_add_packet_length_cl		(0x196C)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1D20)
#define runner_d_upstream_quasi_budget_allocate		(0x1DA0)
#define runner_d_schedule_free_skb_index		(0x1E00)

#endif
