/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_add_pbit_to_key        (0x3bec)
#define image_0_c_dhd_rx_complete_wakeup_request        (0x764)
#define image_0_c_dhd_tx_complete_wakeup_request        (0xbc0)
#define image_0_c_spu_response_wakeup_request        (0x5fd8)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_0_check_skip_cso        (0x3b8c)
#define image_0_ct_expect_natc_lookup        (0x3ca8)
#define image_0_ct_natc_lookup        (0x3c18)
#define image_0_debug_routine        (0x3b0)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dhd_send_entry_to_cpu_ring        (0x694)
#define image_0_dos_attack_handler        (0x3138)
#define image_0_drop_pkt_and_serial        (0x32e4)
#define image_0_dynamic_code_section        (0x8)
#define image_0_dynamic_code_section_proc0        (0x8)
#define image_0_dynamic_code_section_proc1        (0x78)
#define image_0_dynamic_code_section_proc2        (0xe8)
#define image_0_dynamic_code_section_proc3        (0x158)
#define image_0_dynamic_code_section_proc4        (0x1c8)
#define image_0_dynamic_code_section_proc5        (0x238)
#define image_0_dynamic_code_section_proc6        (0x2a8)
#define image_0_dynamic_code_section_proc7        (0x318)
#define image_0_flow_policer        (0x3438)
#define image_0_group_flow_lkp_and_fwd        (0x3e28)
#define image_0_ingress_filter_action_point_update        (0x3d34)
#define image_0_ingress_filters_handler        (0x3488)
#define image_0_initialization_task        (0x388)
#define image_0_is_iptv_capable        (0x3194)
#define image_0_mcast_flow_master_lookup        (0x3d80)
#define image_0_memcpy_abs_to_sbpm        (0x478)
#define image_0_parser_exception_handler        (0x2f54)
#define image_0_proccessing_loopback        (0x2ea0)
#define image_0_processing_policer_action        (0x5f68)
#define image_0_processing_wakeup_request        (0xe38)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0xac0)
#define image_0_rxcmpl_process_rx_packet        (0xb28)
#define image_0_spdsvc_natc_lookup        (0x31f0)
#define image_0_start_task_add_pbit_to_key        (0x3bec)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0x764)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0xbc0)
#define image_0_start_task_c_spu_response_wakeup_request        (0x5fd8)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_0_start_task_check_skip_cso        (0x3b8c)
#define image_0_start_task_ct_expect_natc_lookup        (0x3ca8)
#define image_0_start_task_ct_natc_lookup        (0x3c18)
#define image_0_start_task_debug_routine        (0x3b0)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0x694)
#define image_0_start_task_dos_attack_handler        (0x3138)
#define image_0_start_task_drop_pkt_and_serial        (0x32e4)
#define image_0_start_task_flow_policer        (0x3438)
#define image_0_start_task_group_flow_lkp_and_fwd        (0x3e28)
#define image_0_start_task_ingress_filter_action_point_update        (0x3d34)
#define image_0_start_task_ingress_filters_handler        (0x3488)
#define image_0_start_task_initialization_task        (0x388)
#define image_0_start_task_is_iptv_capable        (0x3194)
#define image_0_start_task_mcast_flow_master_lookup        (0x3d80)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_0_start_task_parser_exception_handler        (0x2f54)
#define image_0_start_task_proccessing_loopback        (0x2ea0)
#define image_0_start_task_processing_policer_action        (0x5f68)
#define image_0_start_task_processing_wakeup_request        (0xe38)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0xac0)
#define image_0_start_task_rxcmpl_process_rx_packet        (0xb28)
#define image_0_start_task_spdsvc_natc_lookup        (0x31f0)
#define image_0_start_task_xx_mirror_noinline        (0x37c0)
#define image_0_xx_mirror_noinline        (0x37c0)

#else

#define image_0_add_pbit_to_key        (0xefb)
#define image_0_c_dhd_rx_complete_wakeup_request        (0x1d9)
#define image_0_c_dhd_tx_complete_wakeup_request        (0x2f0)
#define image_0_c_spu_response_wakeup_request        (0x17f6)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_0_check_skip_cso        (0xee3)
#define image_0_ct_expect_natc_lookup        (0xf2a)
#define image_0_ct_natc_lookup        (0xf06)
#define image_0_debug_routine        (0xec)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dhd_send_entry_to_cpu_ring        (0x1a5)
#define image_0_dos_attack_handler        (0xc4e)
#define image_0_drop_pkt_and_serial        (0xcb9)
#define image_0_dynamic_code_section        (0x2)
#define image_0_dynamic_code_section_proc0        (0x2)
#define image_0_dynamic_code_section_proc1        (0x1e)
#define image_0_dynamic_code_section_proc2        (0x3a)
#define image_0_dynamic_code_section_proc3        (0x56)
#define image_0_dynamic_code_section_proc4        (0x72)
#define image_0_dynamic_code_section_proc5        (0x8e)
#define image_0_dynamic_code_section_proc6        (0xaa)
#define image_0_dynamic_code_section_proc7        (0xc6)
#define image_0_flow_policer        (0xd0e)
#define image_0_group_flow_lkp_and_fwd        (0xf8a)
#define image_0_ingress_filter_action_point_update        (0xf4d)
#define image_0_ingress_filters_handler        (0xd22)
#define image_0_initialization_task        (0xe2)
#define image_0_is_iptv_capable        (0xc65)
#define image_0_mcast_flow_master_lookup        (0xf60)
#define image_0_memcpy_abs_to_sbpm        (0x11e)
#define image_0_parser_exception_handler        (0xbd5)
#define image_0_proccessing_loopback        (0xba8)
#define image_0_processing_policer_action        (0x17da)
#define image_0_processing_wakeup_request        (0x38e)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0x2b0)
#define image_0_rxcmpl_process_rx_packet        (0x2ca)
#define image_0_spdsvc_natc_lookup        (0xc7c)
#define image_0_start_task_add_pbit_to_key        (0xefb)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0x1d9)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0x2f0)
#define image_0_start_task_c_spu_response_wakeup_request        (0x17f6)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_0_start_task_check_skip_cso        (0xee3)
#define image_0_start_task_ct_expect_natc_lookup        (0xf2a)
#define image_0_start_task_ct_natc_lookup        (0xf06)
#define image_0_start_task_debug_routine        (0xec)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0x1a5)
#define image_0_start_task_dos_attack_handler        (0xc4e)
#define image_0_start_task_drop_pkt_and_serial        (0xcb9)
#define image_0_start_task_flow_policer        (0xd0e)
#define image_0_start_task_group_flow_lkp_and_fwd        (0xf8a)
#define image_0_start_task_ingress_filter_action_point_update        (0xf4d)
#define image_0_start_task_ingress_filters_handler        (0xd22)
#define image_0_start_task_initialization_task        (0xe2)
#define image_0_start_task_is_iptv_capable        (0xc65)
#define image_0_start_task_mcast_flow_master_lookup        (0xf60)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_0_start_task_parser_exception_handler        (0xbd5)
#define image_0_start_task_proccessing_loopback        (0xba8)
#define image_0_start_task_processing_policer_action        (0x17da)
#define image_0_start_task_processing_wakeup_request        (0x38e)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0x2b0)
#define image_0_start_task_rxcmpl_process_rx_packet        (0x2ca)
#define image_0_start_task_spdsvc_natc_lookup        (0xc7c)
#define image_0_start_task_xx_mirror_noinline        (0xdf0)
#define image_0_xx_mirror_noinline        (0xdf0)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1___umulhisi3        (0x69a4)
#define image_1___umulsi3        (0x6964)
#define image_1_add_pbit_to_key        (0x34a4)
#define image_1_budget_allocator_tick        (0x5be0)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x6ac)
#define image_1_check_skip_cso        (0x3444)
#define image_1_ct_expect_natc_lookup        (0x3560)
#define image_1_ct_natc_lookup        (0x34d0)
#define image_1_debug_routine        (0x3b0)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dos_attack_handler        (0x29f0)
#define image_1_drop_pkt_and_serial        (0x2b9c)
#define image_1_dynamic_code_section        (0x8)
#define image_1_dynamic_code_section_proc0        (0x8)
#define image_1_dynamic_code_section_proc1        (0x78)
#define image_1_dynamic_code_section_proc2        (0xe8)
#define image_1_dynamic_code_section_proc3        (0x158)
#define image_1_dynamic_code_section_proc4        (0x1c8)
#define image_1_dynamic_code_section_proc5        (0x238)
#define image_1_dynamic_code_section_proc6        (0x2a8)
#define image_1_dynamic_code_section_proc7        (0x318)
#define image_1_flow_policer        (0x2cf0)
#define image_1_general_timer_wakeup_request        (0x5d24)
#define image_1_group_flow_lkp_and_fwd        (0x36e0)
#define image_1_ingress_filter_action_point_update        (0x35ec)
#define image_1_ingress_filters_handler        (0x2d40)
#define image_1_initialization_task        (0x388)
#define image_1_is_iptv_capable        (0x2a4c)
#define image_1_mcast_flow_master_lookup        (0x3638)
#define image_1_memcpy_abs_to_sbpm        (0x4cc)
#define image_1_parser_exception_handler        (0x280c)
#define image_1_pi2_deque_check        (0x5ae0)
#define image_1_pi2_deque_inc_drop_stats        (0x5a28)
#define image_1_pi2_probability_calc        (0x5964)
#define image_1_pi2_sq_timestamp        (0x5a90)
#define image_1_pi2_sq_timestamp_inject        (0x5e5c)
#define image_1_pi2_timer        (0x5898)
#define image_1_proccessing_loopback        (0x2758)
#define image_1_processing_policer_action        (0x5828)
#define image_1_processing_wakeup_request        (0x6e8)
#define image_1_spdsvc_natc_lookup        (0x2aa8)
#define image_1_sq_tx_task_wakeup_request        (0x5ed0)
#define image_1_start_task___umulhisi3        (0x69a4)
#define image_1_start_task___umulsi3        (0x6964)
#define image_1_start_task_add_pbit_to_key        (0x34a4)
#define image_1_start_task_budget_allocator_tick        (0x5be0)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x6ac)
#define image_1_start_task_check_skip_cso        (0x3444)
#define image_1_start_task_ct_expect_natc_lookup        (0x3560)
#define image_1_start_task_ct_natc_lookup        (0x34d0)
#define image_1_start_task_debug_routine        (0x3b0)
#define image_1_start_task_dos_attack_handler        (0x29f0)
#define image_1_start_task_drop_pkt_and_serial        (0x2b9c)
#define image_1_start_task_flow_policer        (0x2cf0)
#define image_1_start_task_general_timer_wakeup_request        (0x5d24)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x36e0)
#define image_1_start_task_ingress_filter_action_point_update        (0x35ec)
#define image_1_start_task_ingress_filters_handler        (0x2d40)
#define image_1_start_task_initialization_task        (0x388)
#define image_1_start_task_is_iptv_capable        (0x2a4c)
#define image_1_start_task_mcast_flow_master_lookup        (0x3638)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x4cc)
#define image_1_start_task_parser_exception_handler        (0x280c)
#define image_1_start_task_pi2_deque_check        (0x5ae0)
#define image_1_start_task_pi2_deque_inc_drop_stats        (0x5a28)
#define image_1_start_task_pi2_probability_calc        (0x5964)
#define image_1_start_task_pi2_sq_timestamp        (0x5a90)
#define image_1_start_task_pi2_sq_timestamp_inject        (0x5e5c)
#define image_1_start_task_pi2_timer        (0x5898)
#define image_1_start_task_proccessing_loopback        (0x2758)
#define image_1_start_task_processing_policer_action        (0x5828)
#define image_1_start_task_processing_wakeup_request        (0x6e8)
#define image_1_start_task_spdsvc_natc_lookup        (0x2aa8)
#define image_1_start_task_sq_tx_task_wakeup_request        (0x5ed0)
#define image_1_start_task_tm_tx_handle_rate_limit        (0x5d9c)
#define image_1_start_task_xx_mirror_noinline        (0x3078)
#define image_1_tm_tx_handle_rate_limit        (0x5d9c)
#define image_1_xx_mirror_noinline        (0x3078)

#else

#define image_1___umulhisi3        (0x1a69)
#define image_1___umulsi3        (0x1a59)
#define image_1_add_pbit_to_key        (0xd29)
#define image_1_budget_allocator_tick        (0x16f8)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x1ab)
#define image_1_check_skip_cso        (0xd11)
#define image_1_ct_expect_natc_lookup        (0xd58)
#define image_1_ct_natc_lookup        (0xd34)
#define image_1_debug_routine        (0xec)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dos_attack_handler        (0xa7c)
#define image_1_drop_pkt_and_serial        (0xae7)
#define image_1_dynamic_code_section        (0x2)
#define image_1_dynamic_code_section_proc0        (0x2)
#define image_1_dynamic_code_section_proc1        (0x1e)
#define image_1_dynamic_code_section_proc2        (0x3a)
#define image_1_dynamic_code_section_proc3        (0x56)
#define image_1_dynamic_code_section_proc4        (0x72)
#define image_1_dynamic_code_section_proc5        (0x8e)
#define image_1_dynamic_code_section_proc6        (0xaa)
#define image_1_dynamic_code_section_proc7        (0xc6)
#define image_1_flow_policer        (0xb3c)
#define image_1_general_timer_wakeup_request        (0x1749)
#define image_1_group_flow_lkp_and_fwd        (0xdb8)
#define image_1_ingress_filter_action_point_update        (0xd7b)
#define image_1_ingress_filters_handler        (0xb50)
#define image_1_initialization_task        (0xe2)
#define image_1_is_iptv_capable        (0xa93)
#define image_1_mcast_flow_master_lookup        (0xd8e)
#define image_1_memcpy_abs_to_sbpm        (0x133)
#define image_1_parser_exception_handler        (0xa03)
#define image_1_pi2_deque_check        (0x16b8)
#define image_1_pi2_deque_inc_drop_stats        (0x168a)
#define image_1_pi2_probability_calc        (0x1659)
#define image_1_pi2_sq_timestamp        (0x16a4)
#define image_1_pi2_sq_timestamp_inject        (0x1797)
#define image_1_pi2_timer        (0x1626)
#define image_1_proccessing_loopback        (0x9d6)
#define image_1_processing_policer_action        (0x160a)
#define image_1_processing_wakeup_request        (0x1ba)
#define image_1_spdsvc_natc_lookup        (0xaaa)
#define image_1_sq_tx_task_wakeup_request        (0x17b4)
#define image_1_start_task___umulhisi3        (0x1a69)
#define image_1_start_task___umulsi3        (0x1a59)
#define image_1_start_task_add_pbit_to_key        (0xd29)
#define image_1_start_task_budget_allocator_tick        (0x16f8)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x1ab)
#define image_1_start_task_check_skip_cso        (0xd11)
#define image_1_start_task_ct_expect_natc_lookup        (0xd58)
#define image_1_start_task_ct_natc_lookup        (0xd34)
#define image_1_start_task_debug_routine        (0xec)
#define image_1_start_task_dos_attack_handler        (0xa7c)
#define image_1_start_task_drop_pkt_and_serial        (0xae7)
#define image_1_start_task_flow_policer        (0xb3c)
#define image_1_start_task_general_timer_wakeup_request        (0x1749)
#define image_1_start_task_group_flow_lkp_and_fwd        (0xdb8)
#define image_1_start_task_ingress_filter_action_point_update        (0xd7b)
#define image_1_start_task_ingress_filters_handler        (0xb50)
#define image_1_start_task_initialization_task        (0xe2)
#define image_1_start_task_is_iptv_capable        (0xa93)
#define image_1_start_task_mcast_flow_master_lookup        (0xd8e)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x133)
#define image_1_start_task_parser_exception_handler        (0xa03)
#define image_1_start_task_pi2_deque_check        (0x16b8)
#define image_1_start_task_pi2_deque_inc_drop_stats        (0x168a)
#define image_1_start_task_pi2_probability_calc        (0x1659)
#define image_1_start_task_pi2_sq_timestamp        (0x16a4)
#define image_1_start_task_pi2_sq_timestamp_inject        (0x1797)
#define image_1_start_task_pi2_timer        (0x1626)
#define image_1_start_task_proccessing_loopback        (0x9d6)
#define image_1_start_task_processing_policer_action        (0x160a)
#define image_1_start_task_processing_wakeup_request        (0x1ba)
#define image_1_start_task_spdsvc_natc_lookup        (0xaaa)
#define image_1_start_task_sq_tx_task_wakeup_request        (0x17b4)
#define image_1_start_task_tm_tx_handle_rate_limit        (0x1767)
#define image_1_start_task_xx_mirror_noinline        (0xc1e)
#define image_1_tm_tx_handle_rate_limit        (0x1767)
#define image_1_xx_mirror_noinline        (0xc1e)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2___umulsi3        (0x6fc4)
#define image_2_add_pbit_to_key        (0x496c)
#define image_2_c_cpu_recycle_wakeup_request        (0x6dd0)
#define image_2_c_cpu_tx_wakeup_request        (0x854)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x818)
#define image_2_check_skip_cso        (0x490c)
#define image_2_cpu_recycle_int_coalescing        (0x6f28)
#define image_2_cpu_tx_send_pd_to_recycle        (0x1b2c)
#define image_2_cpu_tx_sync_tasks        (0x1b98)
#define image_2_ct_expect_natc_lookup        (0x4a28)
#define image_2_ct_natc_lookup        (0x4998)
#define image_2_debug_routine        (0x3b0)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dos_attack_handler        (0x3eb8)
#define image_2_drop_pkt_and_serial        (0x4064)
#define image_2_dynamic_code_section        (0x8)
#define image_2_dynamic_code_section_proc0        (0x8)
#define image_2_dynamic_code_section_proc1        (0x78)
#define image_2_dynamic_code_section_proc2        (0xe8)
#define image_2_dynamic_code_section_proc3        (0x158)
#define image_2_dynamic_code_section_proc4        (0x1c8)
#define image_2_dynamic_code_section_proc5        (0x238)
#define image_2_dynamic_code_section_proc6        (0x2a8)
#define image_2_dynamic_code_section_proc7        (0x318)
#define image_2_flow_policer        (0x41b8)
#define image_2_general_timer_wakeup_request        (0x6d58)
#define image_2_group_flow_lkp_and_fwd        (0x4ba8)
#define image_2_ingress_filter_action_point_update        (0x4ab4)
#define image_2_ingress_filters_handler        (0x4208)
#define image_2_initialization_task        (0x388)
#define image_2_is_iptv_capable        (0x3f14)
#define image_2_mcast_flow_master_lookup        (0x4b00)
#define image_2_memcpy_abs_to_fpm        (0x658)
#define image_2_memcpy_abs_to_sbpm        (0x478)
#define image_2_parser_exception_handler        (0x3cd4)
#define image_2_proccessing_loopback        (0x3c20)
#define image_2_processing_policer_action        (0x6ce8)
#define image_2_processing_wakeup_request        (0x1bb8)
#define image_2_spdsvc_natc_lookup        (0x3f70)
#define image_2_start_task___umulsi3        (0x6fc4)
#define image_2_start_task_add_pbit_to_key        (0x496c)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x6dd0)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x854)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x818)
#define image_2_start_task_check_skip_cso        (0x490c)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x6f28)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x1b2c)
#define image_2_start_task_cpu_tx_sync_tasks        (0x1b98)
#define image_2_start_task_ct_expect_natc_lookup        (0x4a28)
#define image_2_start_task_ct_natc_lookup        (0x4998)
#define image_2_start_task_debug_routine        (0x3b0)
#define image_2_start_task_dos_attack_handler        (0x3eb8)
#define image_2_start_task_drop_pkt_and_serial        (0x4064)
#define image_2_start_task_flow_policer        (0x41b8)
#define image_2_start_task_general_timer_wakeup_request        (0x6d58)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x4ba8)
#define image_2_start_task_ingress_filter_action_point_update        (0x4ab4)
#define image_2_start_task_ingress_filters_handler        (0x4208)
#define image_2_start_task_initialization_task        (0x388)
#define image_2_start_task_is_iptv_capable        (0x3f14)
#define image_2_start_task_mcast_flow_master_lookup        (0x4b00)
#define image_2_start_task_memcpy_abs_to_fpm        (0x658)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_2_start_task_parser_exception_handler        (0x3cd4)
#define image_2_start_task_proccessing_loopback        (0x3c20)
#define image_2_start_task_processing_policer_action        (0x6ce8)
#define image_2_start_task_processing_wakeup_request        (0x1bb8)
#define image_2_start_task_spdsvc_natc_lookup        (0x3f70)
#define image_2_start_task_xx_mirror_noinline        (0x4540)
#define image_2_xx_mirror_noinline        (0x4540)

#else

#define image_2___umulsi3        (0x1bf1)
#define image_2_add_pbit_to_key        (0x125b)
#define image_2_c_cpu_recycle_wakeup_request        (0x1b74)
#define image_2_c_cpu_tx_wakeup_request        (0x215)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x206)
#define image_2_check_skip_cso        (0x1243)
#define image_2_cpu_recycle_int_coalescing        (0x1bca)
#define image_2_cpu_tx_send_pd_to_recycle        (0x6cb)
#define image_2_cpu_tx_sync_tasks        (0x6e6)
#define image_2_ct_expect_natc_lookup        (0x128a)
#define image_2_ct_natc_lookup        (0x1266)
#define image_2_debug_routine        (0xec)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dos_attack_handler        (0xfae)
#define image_2_drop_pkt_and_serial        (0x1019)
#define image_2_dynamic_code_section        (0x2)
#define image_2_dynamic_code_section_proc0        (0x2)
#define image_2_dynamic_code_section_proc1        (0x1e)
#define image_2_dynamic_code_section_proc2        (0x3a)
#define image_2_dynamic_code_section_proc3        (0x56)
#define image_2_dynamic_code_section_proc4        (0x72)
#define image_2_dynamic_code_section_proc5        (0x8e)
#define image_2_dynamic_code_section_proc6        (0xaa)
#define image_2_dynamic_code_section_proc7        (0xc6)
#define image_2_flow_policer        (0x106e)
#define image_2_general_timer_wakeup_request        (0x1b56)
#define image_2_group_flow_lkp_and_fwd        (0x12ea)
#define image_2_ingress_filter_action_point_update        (0x12ad)
#define image_2_ingress_filters_handler        (0x1082)
#define image_2_initialization_task        (0xe2)
#define image_2_is_iptv_capable        (0xfc5)
#define image_2_mcast_flow_master_lookup        (0x12c0)
#define image_2_memcpy_abs_to_fpm        (0x196)
#define image_2_memcpy_abs_to_sbpm        (0x11e)
#define image_2_parser_exception_handler        (0xf35)
#define image_2_proccessing_loopback        (0xf08)
#define image_2_processing_policer_action        (0x1b3a)
#define image_2_processing_wakeup_request        (0x6ee)
#define image_2_spdsvc_natc_lookup        (0xfdc)
#define image_2_start_task___umulsi3        (0x1bf1)
#define image_2_start_task_add_pbit_to_key        (0x125b)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x1b74)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x215)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x206)
#define image_2_start_task_check_skip_cso        (0x1243)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x1bca)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x6cb)
#define image_2_start_task_cpu_tx_sync_tasks        (0x6e6)
#define image_2_start_task_ct_expect_natc_lookup        (0x128a)
#define image_2_start_task_ct_natc_lookup        (0x1266)
#define image_2_start_task_debug_routine        (0xec)
#define image_2_start_task_dos_attack_handler        (0xfae)
#define image_2_start_task_drop_pkt_and_serial        (0x1019)
#define image_2_start_task_flow_policer        (0x106e)
#define image_2_start_task_general_timer_wakeup_request        (0x1b56)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x12ea)
#define image_2_start_task_ingress_filter_action_point_update        (0x12ad)
#define image_2_start_task_ingress_filters_handler        (0x1082)
#define image_2_start_task_initialization_task        (0xe2)
#define image_2_start_task_is_iptv_capable        (0xfc5)
#define image_2_start_task_mcast_flow_master_lookup        (0x12c0)
#define image_2_start_task_memcpy_abs_to_fpm        (0x196)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_2_start_task_parser_exception_handler        (0xf35)
#define image_2_start_task_proccessing_loopback        (0xf08)
#define image_2_start_task_processing_policer_action        (0x1b3a)
#define image_2_start_task_processing_wakeup_request        (0x6ee)
#define image_2_start_task_spdsvc_natc_lookup        (0xfdc)
#define image_2_start_task_xx_mirror_noinline        (0x1150)
#define image_2_xx_mirror_noinline        (0x1150)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_add_pbit_to_key        (0x3448)
#define image_3_c_cpu_recycle_wakeup_request        (0x68c8)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x5cec)
#define image_3_c_cpu_rx_wakeup_request        (0x5834)
#define image_3_c_spdsvc_analyzer_wakeup_request        (0x6b28)
#define image_3_c_spu_request_wakeup_request        (0x7008)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_3_check_skip_cso        (0x33e8)
#define image_3_cpu_recycle_int_coalescing        (0x6a20)
#define image_3_cpu_rx_int_coalescing        (0x5c3c)
#define image_3_cpu_rx_meter_budget_allocator        (0x5c88)
#define image_3_ct_expect_natc_lookup        (0x3504)
#define image_3_ct_natc_lookup        (0x3474)
#define image_3_debug_routine        (0x3b0)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dos_attack_handler        (0x2994)
#define image_3_drop_pkt_and_serial        (0x2b40)
#define image_3_dynamic_code_section        (0x8)
#define image_3_dynamic_code_section_proc0        (0x8)
#define image_3_dynamic_code_section_proc1        (0x78)
#define image_3_dynamic_code_section_proc2        (0xe8)
#define image_3_dynamic_code_section_proc3        (0x158)
#define image_3_dynamic_code_section_proc4        (0x1c8)
#define image_3_dynamic_code_section_proc5        (0x238)
#define image_3_dynamic_code_section_proc6        (0x2a8)
#define image_3_dynamic_code_section_proc7        (0x318)
#define image_3_flow_policer        (0x2c94)
#define image_3_general_timer_wakeup_request        (0x6ab0)
#define image_3_get_pd_from_fifo        (0x6a4c)
#define image_3_group_flow_lkp_and_fwd        (0x3684)
#define image_3_ingress_filter_action_point_update        (0x3590)
#define image_3_ingress_filters_handler        (0x2ce4)
#define image_3_initialization_task        (0x388)
#define image_3_is_iptv_capable        (0x29f0)
#define image_3_mcast_flow_master_lookup        (0x35dc)
#define image_3_memcpy_abs_to_sbpm        (0x478)
#define image_3_packet_cso_hw_offload        (0x67f0)
#define image_3_parser_exception_handler        (0x27b0)
#define image_3_proccessing_loopback        (0x26fc)
#define image_3_processing_policer_action        (0x57c4)
#define image_3_processing_wakeup_request        (0x694)
#define image_3_spdsvc_natc_lookup        (0x2a4c)
#define image_3_spdt_brcm_spdsvc_rx_handler        (0x6ed8)
#define image_3_spdt_udp_basic_rx_handler        (0x6c54)
#define image_3_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x6f9c)
#define image_3_spdt_udp_iperf3_rx_handler        (0x6d00)
#define image_3_spdt_unsupported_proto_rx_handler        (0x6f40)
#define image_3_start_task_add_pbit_to_key        (0x3448)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x68c8)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x5cec)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x5834)
#define image_3_start_task_c_spdsvc_analyzer_wakeup_request        (0x6b28)
#define image_3_start_task_c_spu_request_wakeup_request        (0x7008)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_3_start_task_check_skip_cso        (0x33e8)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x6a20)
#define image_3_start_task_cpu_rx_int_coalescing        (0x5c3c)
#define image_3_start_task_cpu_rx_meter_budget_allocator        (0x5c88)
#define image_3_start_task_ct_expect_natc_lookup        (0x3504)
#define image_3_start_task_ct_natc_lookup        (0x3474)
#define image_3_start_task_debug_routine        (0x3b0)
#define image_3_start_task_dos_attack_handler        (0x2994)
#define image_3_start_task_drop_pkt_and_serial        (0x2b40)
#define image_3_start_task_flow_policer        (0x2c94)
#define image_3_start_task_general_timer_wakeup_request        (0x6ab0)
#define image_3_start_task_get_pd_from_fifo        (0x6a4c)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x3684)
#define image_3_start_task_ingress_filter_action_point_update        (0x3590)
#define image_3_start_task_ingress_filters_handler        (0x2ce4)
#define image_3_start_task_initialization_task        (0x388)
#define image_3_start_task_is_iptv_capable        (0x29f0)
#define image_3_start_task_mcast_flow_master_lookup        (0x35dc)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_3_start_task_packet_cso_hw_offload        (0x67f0)
#define image_3_start_task_parser_exception_handler        (0x27b0)
#define image_3_start_task_proccessing_loopback        (0x26fc)
#define image_3_start_task_processing_policer_action        (0x57c4)
#define image_3_start_task_processing_wakeup_request        (0x694)
#define image_3_start_task_spdsvc_natc_lookup        (0x2a4c)
#define image_3_start_task_spdt_brcm_spdsvc_rx_handler        (0x6ed8)
#define image_3_start_task_spdt_udp_basic_rx_handler        (0x6c54)
#define image_3_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x6f9c)
#define image_3_start_task_spdt_udp_iperf3_rx_handler        (0x6d00)
#define image_3_start_task_spdt_unsupported_proto_rx_handler        (0x6f40)
#define image_3_start_task_xx_mirror_noinline        (0x301c)
#define image_3_xx_mirror_noinline        (0x301c)

#else

#define image_3_add_pbit_to_key        (0xd12)
#define image_3_c_cpu_recycle_wakeup_request        (0x1a32)
#define image_3_c_cpu_rx_copy_wakeup_request        (0x173b)
#define image_3_c_cpu_rx_wakeup_request        (0x160d)
#define image_3_c_spdsvc_analyzer_wakeup_request        (0x1aca)
#define image_3_c_spu_request_wakeup_request        (0x1c02)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_3_check_skip_cso        (0xcfa)
#define image_3_cpu_recycle_int_coalescing        (0x1a88)
#define image_3_cpu_rx_int_coalescing        (0x170f)
#define image_3_cpu_rx_meter_budget_allocator        (0x1722)
#define image_3_ct_expect_natc_lookup        (0xd41)
#define image_3_ct_natc_lookup        (0xd1d)
#define image_3_debug_routine        (0xec)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dos_attack_handler        (0xa65)
#define image_3_drop_pkt_and_serial        (0xad0)
#define image_3_dynamic_code_section        (0x2)
#define image_3_dynamic_code_section_proc0        (0x2)
#define image_3_dynamic_code_section_proc1        (0x1e)
#define image_3_dynamic_code_section_proc2        (0x3a)
#define image_3_dynamic_code_section_proc3        (0x56)
#define image_3_dynamic_code_section_proc4        (0x72)
#define image_3_dynamic_code_section_proc5        (0x8e)
#define image_3_dynamic_code_section_proc6        (0xaa)
#define image_3_dynamic_code_section_proc7        (0xc6)
#define image_3_flow_policer        (0xb25)
#define image_3_general_timer_wakeup_request        (0x1aac)
#define image_3_get_pd_from_fifo        (0x1a93)
#define image_3_group_flow_lkp_and_fwd        (0xda1)
#define image_3_ingress_filter_action_point_update        (0xd64)
#define image_3_ingress_filters_handler        (0xb39)
#define image_3_initialization_task        (0xe2)
#define image_3_is_iptv_capable        (0xa7c)
#define image_3_mcast_flow_master_lookup        (0xd77)
#define image_3_memcpy_abs_to_sbpm        (0x11e)
#define image_3_packet_cso_hw_offload        (0x19fc)
#define image_3_parser_exception_handler        (0x9ec)
#define image_3_proccessing_loopback        (0x9bf)
#define image_3_processing_policer_action        (0x15f1)
#define image_3_processing_wakeup_request        (0x1a5)
#define image_3_spdsvc_natc_lookup        (0xa93)
#define image_3_spdt_brcm_spdsvc_rx_handler        (0x1bb6)
#define image_3_spdt_udp_basic_rx_handler        (0x1b15)
#define image_3_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x1be7)
#define image_3_spdt_udp_iperf3_rx_handler        (0x1b40)
#define image_3_spdt_unsupported_proto_rx_handler        (0x1bd0)
#define image_3_start_task_add_pbit_to_key        (0xd12)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x1a32)
#define image_3_start_task_c_cpu_rx_copy_wakeup_request        (0x173b)
#define image_3_start_task_c_cpu_rx_wakeup_request        (0x160d)
#define image_3_start_task_c_spdsvc_analyzer_wakeup_request        (0x1aca)
#define image_3_start_task_c_spu_request_wakeup_request        (0x1c02)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_3_start_task_check_skip_cso        (0xcfa)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x1a88)
#define image_3_start_task_cpu_rx_int_coalescing        (0x170f)
#define image_3_start_task_cpu_rx_meter_budget_allocator        (0x1722)
#define image_3_start_task_ct_expect_natc_lookup        (0xd41)
#define image_3_start_task_ct_natc_lookup        (0xd1d)
#define image_3_start_task_debug_routine        (0xec)
#define image_3_start_task_dos_attack_handler        (0xa65)
#define image_3_start_task_drop_pkt_and_serial        (0xad0)
#define image_3_start_task_flow_policer        (0xb25)
#define image_3_start_task_general_timer_wakeup_request        (0x1aac)
#define image_3_start_task_get_pd_from_fifo        (0x1a93)
#define image_3_start_task_group_flow_lkp_and_fwd        (0xda1)
#define image_3_start_task_ingress_filter_action_point_update        (0xd64)
#define image_3_start_task_ingress_filters_handler        (0xb39)
#define image_3_start_task_initialization_task        (0xe2)
#define image_3_start_task_is_iptv_capable        (0xa7c)
#define image_3_start_task_mcast_flow_master_lookup        (0xd77)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_3_start_task_packet_cso_hw_offload        (0x19fc)
#define image_3_start_task_parser_exception_handler        (0x9ec)
#define image_3_start_task_proccessing_loopback        (0x9bf)
#define image_3_start_task_processing_policer_action        (0x15f1)
#define image_3_start_task_processing_wakeup_request        (0x1a5)
#define image_3_start_task_spdsvc_natc_lookup        (0xa93)
#define image_3_start_task_spdt_brcm_spdsvc_rx_handler        (0x1bb6)
#define image_3_start_task_spdt_udp_basic_rx_handler        (0x1b15)
#define image_3_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x1be7)
#define image_3_start_task_spdt_udp_iperf3_rx_handler        (0x1b40)
#define image_3_start_task_spdt_unsupported_proto_rx_handler        (0x1bd0)
#define image_3_start_task_xx_mirror_noinline        (0xc07)
#define image_3_xx_mirror_noinline        (0xc07)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4___umulhisi3        (0x7b88)
#define image_4_add_pbit_to_key        (0x4700)
#define image_4_c_cpu_recycle_wakeup_request        (0x6b64)
#define image_4_c_cpu_tx_mcore_wakeup_request        (0x6ce8)
#define image_4_c_dhd_timer_wakeup_request        (0x924)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x9ac)
#define image_4_c_dhd_tx_post_wakeup_request        (0x9f0)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x818)
#define image_4_check_skip_cso        (0x46a0)
#define image_4_cpu_recycle_int_coalescing        (0x6cbc)
#define image_4_cpu_tx_send_pd_to_recycle        (0x7ab4)
#define image_4_ct_expect_natc_lookup        (0x47bc)
#define image_4_ct_natc_lookup        (0x472c)
#define image_4_debug_routine        (0x3b0)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dhd_send_entry_to_cpu_ring        (0x854)
#define image_4_dhd_tx_get_bq_index        (0x1784)
#define image_4_dhd_tx_post_drop_packet        (0x16a8)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x14e0)
#define image_4_dhd_tx_put_bq_index        (0x17f4)
#define image_4_dos_attack_handler        (0x3c4c)
#define image_4_drop_pkt_and_serial        (0x3df8)
#define image_4_dynamic_code_section        (0x8)
#define image_4_dynamic_code_section_proc0        (0x8)
#define image_4_dynamic_code_section_proc1        (0x78)
#define image_4_dynamic_code_section_proc2        (0xe8)
#define image_4_dynamic_code_section_proc3        (0x158)
#define image_4_dynamic_code_section_proc4        (0x1c8)
#define image_4_dynamic_code_section_proc5        (0x238)
#define image_4_dynamic_code_section_proc6        (0x2a8)
#define image_4_dynamic_code_section_proc7        (0x318)
#define image_4_flow_policer        (0x3f4c)
#define image_4_general_timer_wakeup_request        (0x6aec)
#define image_4_group_flow_lkp_and_fwd        (0x493c)
#define image_4_ingress_filter_action_point_update        (0x4848)
#define image_4_ingress_filters_handler        (0x3f9c)
#define image_4_initialization_task        (0x388)
#define image_4_is_iptv_capable        (0x3ca8)
#define image_4_mcast_flow_master_lookup        (0x4894)
#define image_4_memcpy_abs_to_fpm        (0x658)
#define image_4_memcpy_abs_to_sbpm        (0x478)
#define image_4_parser_exception_handler        (0x3a68)
#define image_4_proccessing_loopback        (0x39b4)
#define image_4_processing_policer_action        (0x6a7c)
#define image_4_processing_wakeup_request        (0x194c)
#define image_4_spdsvc_natc_lookup        (0x3d04)
#define image_4_start_task___umulhisi3        (0x7b88)
#define image_4_start_task_add_pbit_to_key        (0x4700)
#define image_4_start_task_c_cpu_recycle_wakeup_request        (0x6b64)
#define image_4_start_task_c_cpu_tx_mcore_wakeup_request        (0x6ce8)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x924)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x9ac)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x9f0)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x818)
#define image_4_start_task_check_skip_cso        (0x46a0)
#define image_4_start_task_cpu_recycle_int_coalescing        (0x6cbc)
#define image_4_start_task_cpu_tx_send_pd_to_recycle        (0x7ab4)
#define image_4_start_task_ct_expect_natc_lookup        (0x47bc)
#define image_4_start_task_ct_natc_lookup        (0x472c)
#define image_4_start_task_debug_routine        (0x3b0)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x854)
#define image_4_start_task_dhd_tx_get_bq_index        (0x1784)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x16a8)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x14e0)
#define image_4_start_task_dhd_tx_put_bq_index        (0x17f4)
#define image_4_start_task_dos_attack_handler        (0x3c4c)
#define image_4_start_task_drop_pkt_and_serial        (0x3df8)
#define image_4_start_task_flow_policer        (0x3f4c)
#define image_4_start_task_general_timer_wakeup_request        (0x6aec)
#define image_4_start_task_group_flow_lkp_and_fwd        (0x493c)
#define image_4_start_task_ingress_filter_action_point_update        (0x4848)
#define image_4_start_task_ingress_filters_handler        (0x3f9c)
#define image_4_start_task_initialization_task        (0x388)
#define image_4_start_task_is_iptv_capable        (0x3ca8)
#define image_4_start_task_mcast_flow_master_lookup        (0x4894)
#define image_4_start_task_memcpy_abs_to_fpm        (0x658)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_4_start_task_parser_exception_handler        (0x3a68)
#define image_4_start_task_proccessing_loopback        (0x39b4)
#define image_4_start_task_processing_policer_action        (0x6a7c)
#define image_4_start_task_processing_wakeup_request        (0x194c)
#define image_4_start_task_spdsvc_natc_lookup        (0x3d04)
#define image_4_start_task_tx_mirror        (0x185c)
#define image_4_start_task_xx_mirror_noinline        (0x42d4)
#define image_4_tx_mirror        (0x185c)
#define image_4_xx_mirror_noinline        (0x42d4)

#else

#define image_4___umulhisi3        (0x1ee2)
#define image_4_add_pbit_to_key        (0x11c0)
#define image_4_c_cpu_recycle_wakeup_request        (0x1ad9)
#define image_4_c_cpu_tx_mcore_wakeup_request        (0x1b3a)
#define image_4_c_dhd_timer_wakeup_request        (0x249)
#define image_4_c_dhd_tx_post_update_fifo_wakeup_request        (0x26b)
#define image_4_c_dhd_tx_post_wakeup_request        (0x27c)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x206)
#define image_4_check_skip_cso        (0x11a8)
#define image_4_cpu_recycle_int_coalescing        (0x1b2f)
#define image_4_cpu_tx_send_pd_to_recycle        (0x1ead)
#define image_4_ct_expect_natc_lookup        (0x11ef)
#define image_4_ct_natc_lookup        (0x11cb)
#define image_4_debug_routine        (0xec)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dhd_send_entry_to_cpu_ring        (0x215)
#define image_4_dhd_tx_get_bq_index        (0x5e1)
#define image_4_dhd_tx_post_drop_packet        (0x5aa)
#define image_4_dhd_tx_post_flow_ring_get_info        (0x538)
#define image_4_dhd_tx_put_bq_index        (0x5fd)
#define image_4_dos_attack_handler        (0xf13)
#define image_4_drop_pkt_and_serial        (0xf7e)
#define image_4_dynamic_code_section        (0x2)
#define image_4_dynamic_code_section_proc0        (0x2)
#define image_4_dynamic_code_section_proc1        (0x1e)
#define image_4_dynamic_code_section_proc2        (0x3a)
#define image_4_dynamic_code_section_proc3        (0x56)
#define image_4_dynamic_code_section_proc4        (0x72)
#define image_4_dynamic_code_section_proc5        (0x8e)
#define image_4_dynamic_code_section_proc6        (0xaa)
#define image_4_dynamic_code_section_proc7        (0xc6)
#define image_4_flow_policer        (0xfd3)
#define image_4_general_timer_wakeup_request        (0x1abb)
#define image_4_group_flow_lkp_and_fwd        (0x124f)
#define image_4_ingress_filter_action_point_update        (0x1212)
#define image_4_ingress_filters_handler        (0xfe7)
#define image_4_initialization_task        (0xe2)
#define image_4_is_iptv_capable        (0xf2a)
#define image_4_mcast_flow_master_lookup        (0x1225)
#define image_4_memcpy_abs_to_fpm        (0x196)
#define image_4_memcpy_abs_to_sbpm        (0x11e)
#define image_4_parser_exception_handler        (0xe9a)
#define image_4_proccessing_loopback        (0xe6d)
#define image_4_processing_policer_action        (0x1a9f)
#define image_4_processing_wakeup_request        (0x653)
#define image_4_spdsvc_natc_lookup        (0xf41)
#define image_4_start_task___umulhisi3        (0x1ee2)
#define image_4_start_task_add_pbit_to_key        (0x11c0)
#define image_4_start_task_c_cpu_recycle_wakeup_request        (0x1ad9)
#define image_4_start_task_c_cpu_tx_mcore_wakeup_request        (0x1b3a)
#define image_4_start_task_c_dhd_timer_wakeup_request        (0x249)
#define image_4_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x26b)
#define image_4_start_task_c_dhd_tx_post_wakeup_request        (0x27c)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x206)
#define image_4_start_task_check_skip_cso        (0x11a8)
#define image_4_start_task_cpu_recycle_int_coalescing        (0x1b2f)
#define image_4_start_task_cpu_tx_send_pd_to_recycle        (0x1ead)
#define image_4_start_task_ct_expect_natc_lookup        (0x11ef)
#define image_4_start_task_ct_natc_lookup        (0x11cb)
#define image_4_start_task_debug_routine        (0xec)
#define image_4_start_task_dhd_send_entry_to_cpu_ring        (0x215)
#define image_4_start_task_dhd_tx_get_bq_index        (0x5e1)
#define image_4_start_task_dhd_tx_post_drop_packet        (0x5aa)
#define image_4_start_task_dhd_tx_post_flow_ring_get_info        (0x538)
#define image_4_start_task_dhd_tx_put_bq_index        (0x5fd)
#define image_4_start_task_dos_attack_handler        (0xf13)
#define image_4_start_task_drop_pkt_and_serial        (0xf7e)
#define image_4_start_task_flow_policer        (0xfd3)
#define image_4_start_task_general_timer_wakeup_request        (0x1abb)
#define image_4_start_task_group_flow_lkp_and_fwd        (0x124f)
#define image_4_start_task_ingress_filter_action_point_update        (0x1212)
#define image_4_start_task_ingress_filters_handler        (0xfe7)
#define image_4_start_task_initialization_task        (0xe2)
#define image_4_start_task_is_iptv_capable        (0xf2a)
#define image_4_start_task_mcast_flow_master_lookup        (0x1225)
#define image_4_start_task_memcpy_abs_to_fpm        (0x196)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_4_start_task_parser_exception_handler        (0xe9a)
#define image_4_start_task_proccessing_loopback        (0xe6d)
#define image_4_start_task_processing_policer_action        (0x1a9f)
#define image_4_start_task_processing_wakeup_request        (0x653)
#define image_4_start_task_spdsvc_natc_lookup        (0xf41)
#define image_4_start_task_tx_mirror        (0x617)
#define image_4_start_task_xx_mirror_noinline        (0x10b5)
#define image_4_tx_mirror        (0x617)
#define image_4_xx_mirror_noinline        (0x10b5)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5___umulhisi3        (0x6b84)
#define image_5___umulsi3        (0x6b44)
#define image_5_add_pbit_to_key        (0x356c)
#define image_5_budget_allocator_tick        (0x5958)
#define image_5_buffer_cong_mgt_1st_wakeup_request        (0x308)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x77c)
#define image_5_check_skip_cso        (0x350c)
#define image_5_ct_expect_natc_lookup        (0x3628)
#define image_5_ct_natc_lookup        (0x3598)
#define image_5_debug_routine        (0x1f0)
#define image_5_debug_routine_handler        (0x4)
#define image_5_dos_attack_handler        (0x2ab8)
#define image_5_drop_pkt_and_serial        (0x2c64)
#define image_5_dynamic_code_section        (0x8)
#define image_5_dynamic_code_section_proc0        (0x8)
#define image_5_dynamic_code_section_proc1        (0x78)
#define image_5_dynamic_code_section_proc2        (0xe8)
#define image_5_dynamic_code_section_proc3        (0x158)
#define image_5_flow_policer        (0x2db8)
#define image_5_general_timer_wakeup_request        (0x68e0)
#define image_5_get_queue_delay        (0x6a88)
#define image_5_group_flow_lkp_and_fwd        (0x37a8)
#define image_5_handle_flush        (0x5d60)
#define image_5_ingress_filter_action_point_update        (0x36b4)
#define image_5_ingress_filters_handler        (0x2e08)
#define image_5_initialization_task        (0x1c8)
#define image_5_is_iptv_capable        (0x2b14)
#define image_5_mcast_flow_master_lookup        (0x3700)
#define image_5_memcpy_abs_to_sbpm        (0x59c)
#define image_5_parser_exception_handler        (0x28d4)
#define image_5_pi2_deque_check        (0x66c4)
#define image_5_pi2_deque_inc_drop_stats        (0x6adc)
#define image_5_pi2_get_queue_delay        (0x6958)
#define image_5_pi2_probability_calc        (0x69c4)
#define image_5_pi2_timer        (0x5a9c)
#define image_5_proccessing_loopback        (0x2820)
#define image_5_processing_policer_action        (0x58e8)
#define image_5_processing_wakeup_request        (0x7b8)
#define image_5_spdsvc_natc_lookup        (0x2b70)
#define image_5_start_task___umulhisi3        (0x6b84)
#define image_5_start_task___umulsi3        (0x6b44)
#define image_5_start_task_add_pbit_to_key        (0x356c)
#define image_5_start_task_budget_allocator_tick        (0x5958)
#define image_5_start_task_buffer_cong_mgt_1st_wakeup_request        (0x308)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x77c)
#define image_5_start_task_check_skip_cso        (0x350c)
#define image_5_start_task_ct_expect_natc_lookup        (0x3628)
#define image_5_start_task_ct_natc_lookup        (0x3598)
#define image_5_start_task_debug_routine        (0x1f0)
#define image_5_start_task_dos_attack_handler        (0x2ab8)
#define image_5_start_task_drop_pkt_and_serial        (0x2c64)
#define image_5_start_task_flow_policer        (0x2db8)
#define image_5_start_task_general_timer_wakeup_request        (0x68e0)
#define image_5_start_task_get_queue_delay        (0x6a88)
#define image_5_start_task_group_flow_lkp_and_fwd        (0x37a8)
#define image_5_start_task_handle_flush        (0x5d60)
#define image_5_start_task_ingress_filter_action_point_update        (0x36b4)
#define image_5_start_task_ingress_filters_handler        (0x2e08)
#define image_5_start_task_initialization_task        (0x1c8)
#define image_5_start_task_is_iptv_capable        (0x2b14)
#define image_5_start_task_mcast_flow_master_lookup        (0x3700)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x59c)
#define image_5_start_task_parser_exception_handler        (0x28d4)
#define image_5_start_task_pi2_deque_check        (0x66c4)
#define image_5_start_task_pi2_deque_inc_drop_stats        (0x6adc)
#define image_5_start_task_pi2_get_queue_delay        (0x6958)
#define image_5_start_task_pi2_probability_calc        (0x69c4)
#define image_5_start_task_pi2_timer        (0x5a9c)
#define image_5_start_task_proccessing_loopback        (0x2820)
#define image_5_start_task_processing_policer_action        (0x58e8)
#define image_5_start_task_processing_wakeup_request        (0x7b8)
#define image_5_start_task_spdsvc_natc_lookup        (0x2b70)
#define image_5_start_task_tm_tx_handle_rate_limit        (0x5b64)
#define image_5_start_task_tm_tx_mirroring_handle        (0x67c4)
#define image_5_start_task_tm_tx_task_wakeup_request        (0x5ecc)
#define image_5_start_task_tm_update_fifo_first_wakeup_request        (0x5c24)
#define image_5_start_task_tx_mirror        (0x67f0)
#define image_5_start_task_xx_mirror_noinline        (0x3140)
#define image_5_tm_tx_handle_rate_limit        (0x5b64)
#define image_5_tm_tx_mirroring_handle        (0x67c4)
#define image_5_tm_tx_task_wakeup_request        (0x5ecc)
#define image_5_tm_update_fifo_first_wakeup_request        (0x5c24)
#define image_5_tx_mirror        (0x67f0)
#define image_5_xx_mirror_noinline        (0x3140)

#else

#define image_5___umulhisi3        (0x1ae1)
#define image_5___umulsi3        (0x1ad1)
#define image_5_add_pbit_to_key        (0xd5b)
#define image_5_budget_allocator_tick        (0x1656)
#define image_5_buffer_cong_mgt_1st_wakeup_request        (0xc2)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x1df)
#define image_5_check_skip_cso        (0xd43)
#define image_5_ct_expect_natc_lookup        (0xd8a)
#define image_5_ct_natc_lookup        (0xd66)
#define image_5_debug_routine        (0x7c)
#define image_5_debug_routine_handler        (0x1)
#define image_5_dos_attack_handler        (0xaae)
#define image_5_drop_pkt_and_serial        (0xb19)
#define image_5_dynamic_code_section        (0x2)
#define image_5_dynamic_code_section_proc0        (0x2)
#define image_5_dynamic_code_section_proc1        (0x1e)
#define image_5_dynamic_code_section_proc2        (0x3a)
#define image_5_dynamic_code_section_proc3        (0x56)
#define image_5_flow_policer        (0xb6e)
#define image_5_general_timer_wakeup_request        (0x1a38)
#define image_5_get_queue_delay        (0x1aa2)
#define image_5_group_flow_lkp_and_fwd        (0xdea)
#define image_5_handle_flush        (0x1758)
#define image_5_ingress_filter_action_point_update        (0xdad)
#define image_5_ingress_filters_handler        (0xb82)
#define image_5_initialization_task        (0x72)
#define image_5_is_iptv_capable        (0xac5)
#define image_5_mcast_flow_master_lookup        (0xdc0)
#define image_5_memcpy_abs_to_sbpm        (0x167)
#define image_5_parser_exception_handler        (0xa35)
#define image_5_pi2_deque_check        (0x19b1)
#define image_5_pi2_deque_inc_drop_stats        (0x1ab7)
#define image_5_pi2_get_queue_delay        (0x1a56)
#define image_5_pi2_probability_calc        (0x1a71)
#define image_5_pi2_timer        (0x16a7)
#define image_5_proccessing_loopback        (0xa08)
#define image_5_processing_policer_action        (0x163a)
#define image_5_processing_wakeup_request        (0x1ee)
#define image_5_spdsvc_natc_lookup        (0xadc)
#define image_5_start_task___umulhisi3        (0x1ae1)
#define image_5_start_task___umulsi3        (0x1ad1)
#define image_5_start_task_add_pbit_to_key        (0xd5b)
#define image_5_start_task_budget_allocator_tick        (0x1656)
#define image_5_start_task_buffer_cong_mgt_1st_wakeup_request        (0xc2)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x1df)
#define image_5_start_task_check_skip_cso        (0xd43)
#define image_5_start_task_ct_expect_natc_lookup        (0xd8a)
#define image_5_start_task_ct_natc_lookup        (0xd66)
#define image_5_start_task_debug_routine        (0x7c)
#define image_5_start_task_dos_attack_handler        (0xaae)
#define image_5_start_task_drop_pkt_and_serial        (0xb19)
#define image_5_start_task_flow_policer        (0xb6e)
#define image_5_start_task_general_timer_wakeup_request        (0x1a38)
#define image_5_start_task_get_queue_delay        (0x1aa2)
#define image_5_start_task_group_flow_lkp_and_fwd        (0xdea)
#define image_5_start_task_handle_flush        (0x1758)
#define image_5_start_task_ingress_filter_action_point_update        (0xdad)
#define image_5_start_task_ingress_filters_handler        (0xb82)
#define image_5_start_task_initialization_task        (0x72)
#define image_5_start_task_is_iptv_capable        (0xac5)
#define image_5_start_task_mcast_flow_master_lookup        (0xdc0)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x167)
#define image_5_start_task_parser_exception_handler        (0xa35)
#define image_5_start_task_pi2_deque_check        (0x19b1)
#define image_5_start_task_pi2_deque_inc_drop_stats        (0x1ab7)
#define image_5_start_task_pi2_get_queue_delay        (0x1a56)
#define image_5_start_task_pi2_probability_calc        (0x1a71)
#define image_5_start_task_pi2_timer        (0x16a7)
#define image_5_start_task_proccessing_loopback        (0xa08)
#define image_5_start_task_processing_policer_action        (0x163a)
#define image_5_start_task_processing_wakeup_request        (0x1ee)
#define image_5_start_task_spdsvc_natc_lookup        (0xadc)
#define image_5_start_task_tm_tx_handle_rate_limit        (0x16d9)
#define image_5_start_task_tm_tx_mirroring_handle        (0x19f1)
#define image_5_start_task_tm_tx_task_wakeup_request        (0x17b3)
#define image_5_start_task_tm_update_fifo_first_wakeup_request        (0x1709)
#define image_5_start_task_tx_mirror        (0x19fc)
#define image_5_start_task_xx_mirror_noinline        (0xc50)
#define image_5_tm_tx_handle_rate_limit        (0x16d9)
#define image_5_tm_tx_mirroring_handle        (0x19f1)
#define image_5_tm_tx_task_wakeup_request        (0x17b3)
#define image_5_tm_update_fifo_first_wakeup_request        (0x1709)
#define image_5_tx_mirror        (0x19fc)
#define image_5_xx_mirror_noinline        (0xc50)

#endif


#endif

/* IMAGE 6 LABELS */
#ifndef IMAGE_6_CODE_ADDRESSES
#define IMAGE_6_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_6___umulhisi3        (0x3768)
#define image_6___umulsi3        (0x3728)
#define image_6_budget_allocator_tick        (0x1adc)
#define image_6_buffer_cong_mgt_1st_wakeup_request        (0x1848)
#define image_6_c_common_reprocessing_wakeup_request        (0x2ad4)
#define image_6_c_spdsvc_gen_wakeup_request        (0x2c60)
#define image_6_debug_routine        (0x74)
#define image_6_debug_routine_handler        (0x4)
#define image_6_general_timer_wakeup_request        (0x2a5c)
#define image_6_get_queue_delay        (0x320c)
#define image_6_handle_flush        (0x1ee4)
#define image_6_initialization_task        (0x8)
#define image_6_pi2_deque_check        (0x2840)
#define image_6_pi2_deque_inc_drop_stats        (0x3260)
#define image_6_pi2_get_queue_delay        (0x30dc)
#define image_6_pi2_probability_calc        (0x3148)
#define image_6_pi2_timer        (0x1c20)
#define image_6_start_task___umulhisi3        (0x3768)
#define image_6_start_task___umulsi3        (0x3728)
#define image_6_start_task_budget_allocator_tick        (0x1adc)
#define image_6_start_task_buffer_cong_mgt_1st_wakeup_request        (0x1848)
#define image_6_start_task_c_common_reprocessing_wakeup_request        (0x2ad4)
#define image_6_start_task_c_spdsvc_gen_wakeup_request        (0x2c60)
#define image_6_start_task_debug_routine        (0x74)
#define image_6_start_task_general_timer_wakeup_request        (0x2a5c)
#define image_6_start_task_get_queue_delay        (0x320c)
#define image_6_start_task_handle_flush        (0x1ee4)
#define image_6_start_task_initialization_task        (0x8)
#define image_6_start_task_pi2_deque_check        (0x2840)
#define image_6_start_task_pi2_deque_inc_drop_stats        (0x3260)
#define image_6_start_task_pi2_get_queue_delay        (0x30dc)
#define image_6_start_task_pi2_probability_calc        (0x3148)
#define image_6_start_task_pi2_timer        (0x1c20)
#define image_6_start_task_tcpspdtest_gen_wakeup_request        (0xae8)
#define image_6_start_task_tcpspdtest_wakeup_request        (0x2a8)
#define image_6_start_task_tm_tx_handle_rate_limit        (0x1ce8)
#define image_6_start_task_tm_tx_mirroring_handle        (0x2940)
#define image_6_start_task_tm_tx_task_wakeup_request        (0x2050)
#define image_6_start_task_tm_update_fifo_first_wakeup_request        (0x1da8)
#define image_6_start_task_tx_mirror        (0x296c)
#define image_6_tcpspdtest_gen_wakeup_request        (0xae8)
#define image_6_tcpspdtest_task_upload_init        (0xae8)
#define image_6_tcpspdtest_wakeup_request        (0x2a8)
#define image_6_tm_tx_handle_rate_limit        (0x1ce8)
#define image_6_tm_tx_mirroring_handle        (0x2940)
#define image_6_tm_tx_task_wakeup_request        (0x2050)
#define image_6_tm_update_fifo_first_wakeup_request        (0x1da8)
#define image_6_tx_mirror        (0x296c)

#else

#define image_6___umulhisi3        (0xdda)
#define image_6___umulsi3        (0xdca)
#define image_6_budget_allocator_tick        (0x6b7)
#define image_6_buffer_cong_mgt_1st_wakeup_request        (0x612)
#define image_6_c_common_reprocessing_wakeup_request        (0xab5)
#define image_6_c_spdsvc_gen_wakeup_request        (0xb18)
#define image_6_debug_routine        (0x1d)
#define image_6_debug_routine_handler        (0x1)
#define image_6_general_timer_wakeup_request        (0xa97)
#define image_6_get_queue_delay        (0xc83)
#define image_6_handle_flush        (0x7b9)
#define image_6_initialization_task        (0x2)
#define image_6_pi2_deque_check        (0xa10)
#define image_6_pi2_deque_inc_drop_stats        (0xc98)
#define image_6_pi2_get_queue_delay        (0xc37)
#define image_6_pi2_probability_calc        (0xc52)
#define image_6_pi2_timer        (0x708)
#define image_6_start_task___umulhisi3        (0xdda)
#define image_6_start_task___umulsi3        (0xdca)
#define image_6_start_task_budget_allocator_tick        (0x6b7)
#define image_6_start_task_buffer_cong_mgt_1st_wakeup_request        (0x612)
#define image_6_start_task_c_common_reprocessing_wakeup_request        (0xab5)
#define image_6_start_task_c_spdsvc_gen_wakeup_request        (0xb18)
#define image_6_start_task_debug_routine        (0x1d)
#define image_6_start_task_general_timer_wakeup_request        (0xa97)
#define image_6_start_task_get_queue_delay        (0xc83)
#define image_6_start_task_handle_flush        (0x7b9)
#define image_6_start_task_initialization_task        (0x2)
#define image_6_start_task_pi2_deque_check        (0xa10)
#define image_6_start_task_pi2_deque_inc_drop_stats        (0xc98)
#define image_6_start_task_pi2_get_queue_delay        (0xc37)
#define image_6_start_task_pi2_probability_calc        (0xc52)
#define image_6_start_task_pi2_timer        (0x708)
#define image_6_start_task_tcpspdtest_gen_wakeup_request        (0x2ba)
#define image_6_start_task_tcpspdtest_wakeup_request        (0xaa)
#define image_6_start_task_tm_tx_handle_rate_limit        (0x73a)
#define image_6_start_task_tm_tx_mirroring_handle        (0xa50)
#define image_6_start_task_tm_tx_task_wakeup_request        (0x814)
#define image_6_start_task_tm_update_fifo_first_wakeup_request        (0x76a)
#define image_6_start_task_tx_mirror        (0xa5b)
#define image_6_tcpspdtest_gen_wakeup_request        (0x2ba)
#define image_6_tcpspdtest_task_upload_init        (0x2ba)
#define image_6_tcpspdtest_wakeup_request        (0xaa)
#define image_6_tm_tx_handle_rate_limit        (0x73a)
#define image_6_tm_tx_mirroring_handle        (0xa50)
#define image_6_tm_tx_task_wakeup_request        (0x814)
#define image_6_tm_update_fifo_first_wakeup_request        (0x76a)
#define image_6_tx_mirror        (0xa5b)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND


#else


#endif


#endif

