/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_budget_allocator_1st_wakeup_request        (0x106c)
#define image_0_buffer_cong_mgt_1st_wakeup_request        (0xccc)
#define image_0_debug_routine        (0x84)
#define image_0_debug_routine_handler        (0x4)
#define image_0_ds_tx_task_wakeup_request        (0x694)
#define image_0_flush_task_1st_wakeup_request        (0x1610)
#define image_0_ghost_reporting_1st_wakeup_request        (0x1738)
#define image_0_initialization_task        (0x8)
#define image_0_pi2_calc_1st_wakeup_request        (0xf64)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x106c)
#define image_0_start_task_buffer_cong_mgt_1st_wakeup_request        (0xccc)
#define image_0_start_task_debug_routine        (0x84)
#define image_0_start_task_ds_tx_task_wakeup_request        (0x694)
#define image_0_start_task_flush_task_1st_wakeup_request        (0x1610)
#define image_0_start_task_ghost_reporting_1st_wakeup_request        (0x1738)
#define image_0_start_task_initialization_task        (0x8)
#define image_0_start_task_pi2_calc_1st_wakeup_request        (0xf64)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request        (0x4b8)
#define image_0_update_fifo_ds_read_1st_wakeup_request        (0x4b8)

#else

#define image_0_budget_allocator_1st_wakeup_request        (0x41b)
#define image_0_buffer_cong_mgt_1st_wakeup_request        (0x333)
#define image_0_debug_routine        (0x21)
#define image_0_debug_routine_handler        (0x1)
#define image_0_ds_tx_task_wakeup_request        (0x1a5)
#define image_0_flush_task_1st_wakeup_request        (0x584)
#define image_0_ghost_reporting_1st_wakeup_request        (0x5ce)
#define image_0_initialization_task        (0x2)
#define image_0_pi2_calc_1st_wakeup_request        (0x3d9)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x41b)
#define image_0_start_task_buffer_cong_mgt_1st_wakeup_request        (0x333)
#define image_0_start_task_debug_routine        (0x21)
#define image_0_start_task_ds_tx_task_wakeup_request        (0x1a5)
#define image_0_start_task_flush_task_1st_wakeup_request        (0x584)
#define image_0_start_task_ghost_reporting_1st_wakeup_request        (0x5ce)
#define image_0_start_task_initialization_task        (0x2)
#define image_0_start_task_pi2_calc_1st_wakeup_request        (0x3d9)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request        (0x12e)
#define image_0_update_fifo_ds_read_1st_wakeup_request        (0x12e)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_action_exception        (0x266c)
#define image_1_action_gpe        (0x2658)
#define image_1_common_reprocessing_wakeup_request        (0x6858)
#define image_1_cpu_recycle_wakeup_request        (0x49c8)
#define image_1_cpu_rx_copy_wakeup_request        (0x3710)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4948)
#define image_1_cpu_rx_wakeup_request        (0x45f4)
#define image_1_debug_routine        (0x3644)
#define image_1_debug_routine_handler        (0x4)
#define image_1_gpe_apply_icsum_16        (0x2a8c)
#define image_1_gpe_apply_icsum_nz_16        (0x2ab0)
#define image_1_gpe_buffer_copy_16_ddr        (0x2b64)
#define image_1_gpe_buffer_copy_16_sram        (0x2b38)
#define image_1_gpe_compute_csum_16_cl        (0x2aec)
#define image_1_gpe_compute_csum_16_sram        (0x2af8)
#define image_1_gpe_copy_add_16_cl        (0x2918)
#define image_1_gpe_copy_add_16_sram        (0x2924)
#define image_1_gpe_copy_bits_16_cl        (0x296c)
#define image_1_gpe_copy_bits_16_sram        (0x2978)
#define image_1_gpe_decrement_8        (0x2a68)
#define image_1_gpe_delete_16        (0x2a28)
#define image_1_gpe_insert_16        (0x29c0)
#define image_1_gpe_replace_16        (0x2894)
#define image_1_gpe_replace_32        (0x28c8)
#define image_1_gpe_replace_add_packet_length_cl        (0x2b94)
#define image_1_gpe_replace_bits_16        (0x28ec)
#define image_1_gpe_replace_pointer_32_sram        (0x284c)
#define image_1_gpe_replace_pointer_64_sram        (0x2870)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x272c)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x2770)
#define image_1_gpe_sop_pull_replace_sram_64        (0x27c0)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x27fc)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x26ac)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x26f0)
#define image_1_gpe_sop_push_replace_sram_64        (0x2704)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x2718)
#define image_1_initialization_task        (0x8)
#define image_1_interrupt_coalescing_1st_wakeup_request        (0x4b24)
#define image_1_processing_check_wlan_llcsnap        (0xa08)
#define image_1_processing_done        (0xbb4)
#define image_1_processing_wakeup_request        (0x78)
#define image_1_spdsvc_gen_wakeup_request        (0x620c)
#define image_1_start_task_common_reprocessing_wakeup_request        (0x6858)
#define image_1_start_task_cpu_recycle_wakeup_request        (0x49c8)
#define image_1_start_task_cpu_rx_copy_wakeup_request        (0x3710)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x4948)
#define image_1_start_task_cpu_rx_wakeup_request        (0x45f4)
#define image_1_start_task_debug_routine        (0x3644)
#define image_1_start_task_initialization_task        (0x8)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request        (0x4b24)
#define image_1_start_task_processing_wakeup_request        (0x78)
#define image_1_start_task_spdsvc_gen_wakeup_request        (0x620c)
#define image_1_tcam_cmd_dst_ip        (0x2e5c)
#define image_1_tcam_cmd_dst_ipv6_masked        (0x2eb8)
#define image_1_tcam_cmd_dst_mac        (0x2f50)
#define image_1_tcam_cmd_dst_port        (0x2f0c)
#define image_1_tcam_cmd_ethertype        (0x2c68)
#define image_1_tcam_cmd_gem_flow        (0x2d78)
#define image_1_tcam_cmd_generic_l2        (0x2f7c)
#define image_1_tcam_cmd_generic_l3        (0x2fb0)
#define image_1_tcam_cmd_generic_l4        (0x2fec)
#define image_1_tcam_cmd_ic_submit        (0x2bec)
#define image_1_tcam_cmd_ingress_port        (0x2d60)
#define image_1_tcam_cmd_inner_pbit        (0x2cc8)
#define image_1_tcam_cmd_inner_tpid        (0x2c50)
#define image_1_tcam_cmd_inner_vid        (0x2c98)
#define image_1_tcam_cmd_ip_protocol        (0x2cf8)
#define image_1_tcam_cmd_ipv6_label        (0x2d90)
#define image_1_tcam_cmd_l3_protocol        (0x2d10)
#define image_1_tcam_cmd_network_layer        (0x2d40)
#define image_1_tcam_cmd_outer_pbit        (0x2cb0)
#define image_1_tcam_cmd_outer_tpid        (0x2c38)
#define image_1_tcam_cmd_outer_vid        (0x2c80)
#define image_1_tcam_cmd_src_ip        (0x2dc4)
#define image_1_tcam_cmd_src_ipv6_masked        (0x2e20)
#define image_1_tcam_cmd_src_mac        (0x2f24)
#define image_1_tcam_cmd_src_port        (0x2ef4)
#define image_1_tcam_cmd_tos        (0x2d28)
#define image_1_tcam_cmd_vlan_num        (0x2ce0)

#else

#define image_1_action_exception        (0x99b)
#define image_1_action_gpe        (0x996)
#define image_1_common_reprocessing_wakeup_request        (0x1a16)
#define image_1_cpu_recycle_wakeup_request        (0x1272)
#define image_1_cpu_rx_copy_wakeup_request        (0xdc4)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x1252)
#define image_1_cpu_rx_wakeup_request        (0x117d)
#define image_1_debug_routine        (0xd91)
#define image_1_debug_routine_handler        (0x1)
#define image_1_gpe_apply_icsum_16        (0xaa3)
#define image_1_gpe_apply_icsum_nz_16        (0xaac)
#define image_1_gpe_buffer_copy_16_ddr        (0xad9)
#define image_1_gpe_buffer_copy_16_sram        (0xace)
#define image_1_gpe_compute_csum_16_cl        (0xabb)
#define image_1_gpe_compute_csum_16_sram        (0xabe)
#define image_1_gpe_copy_add_16_cl        (0xa46)
#define image_1_gpe_copy_add_16_sram        (0xa49)
#define image_1_gpe_copy_bits_16_cl        (0xa5b)
#define image_1_gpe_copy_bits_16_sram        (0xa5e)
#define image_1_gpe_decrement_8        (0xa9a)
#define image_1_gpe_delete_16        (0xa8a)
#define image_1_gpe_insert_16        (0xa70)
#define image_1_gpe_replace_16        (0xa25)
#define image_1_gpe_replace_32        (0xa32)
#define image_1_gpe_replace_add_packet_length_cl        (0xae5)
#define image_1_gpe_replace_bits_16        (0xa3b)
#define image_1_gpe_replace_pointer_32_sram        (0xa13)
#define image_1_gpe_replace_pointer_64_sram        (0xa1c)
#define image_1_gpe_sop_pull_replace_ddr_sram_32        (0x9cb)
#define image_1_gpe_sop_pull_replace_sram_32_64        (0x9dc)
#define image_1_gpe_sop_pull_replace_sram_64        (0x9f0)
#define image_1_gpe_sop_pull_replace_sram_64_32        (0x9ff)
#define image_1_gpe_sop_push_replace_ddr_sram_32        (0x9ab)
#define image_1_gpe_sop_push_replace_sram_32_64        (0x9bc)
#define image_1_gpe_sop_push_replace_sram_64        (0x9c1)
#define image_1_gpe_sop_push_replace_sram_64_32        (0x9c6)
#define image_1_initialization_task        (0x2)
#define image_1_interrupt_coalescing_1st_wakeup_request        (0x12c9)
#define image_1_processing_check_wlan_llcsnap        (0x282)
#define image_1_processing_done        (0x2ed)
#define image_1_processing_wakeup_request        (0x1e)
#define image_1_spdsvc_gen_wakeup_request        (0x1883)
#define image_1_start_task_common_reprocessing_wakeup_request        (0x1a16)
#define image_1_start_task_cpu_recycle_wakeup_request        (0x1272)
#define image_1_start_task_cpu_rx_copy_wakeup_request        (0xdc4)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x1252)
#define image_1_start_task_cpu_rx_wakeup_request        (0x117d)
#define image_1_start_task_debug_routine        (0xd91)
#define image_1_start_task_initialization_task        (0x2)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request        (0x12c9)
#define image_1_start_task_processing_wakeup_request        (0x1e)
#define image_1_start_task_spdsvc_gen_wakeup_request        (0x1883)
#define image_1_tcam_cmd_dst_ip        (0xb97)
#define image_1_tcam_cmd_dst_ipv6_masked        (0xbae)
#define image_1_tcam_cmd_dst_mac        (0xbd4)
#define image_1_tcam_cmd_dst_port        (0xbc3)
#define image_1_tcam_cmd_ethertype        (0xb1a)
#define image_1_tcam_cmd_gem_flow        (0xb5e)
#define image_1_tcam_cmd_generic_l2        (0xbdf)
#define image_1_tcam_cmd_generic_l3        (0xbec)
#define image_1_tcam_cmd_generic_l4        (0xbfb)
#define image_1_tcam_cmd_ic_submit        (0xafb)
#define image_1_tcam_cmd_ingress_port        (0xb58)
#define image_1_tcam_cmd_inner_pbit        (0xb32)
#define image_1_tcam_cmd_inner_tpid        (0xb14)
#define image_1_tcam_cmd_inner_vid        (0xb26)
#define image_1_tcam_cmd_ip_protocol        (0xb3e)
#define image_1_tcam_cmd_ipv6_label        (0xb64)
#define image_1_tcam_cmd_l3_protocol        (0xb44)
#define image_1_tcam_cmd_network_layer        (0xb50)
#define image_1_tcam_cmd_outer_pbit        (0xb2c)
#define image_1_tcam_cmd_outer_tpid        (0xb0e)
#define image_1_tcam_cmd_outer_vid        (0xb20)
#define image_1_tcam_cmd_src_ip        (0xb71)
#define image_1_tcam_cmd_src_ipv6_masked        (0xb88)
#define image_1_tcam_cmd_src_mac        (0xbc9)
#define image_1_tcam_cmd_src_port        (0xbbd)
#define image_1_tcam_cmd_tos        (0xb4a)
#define image_1_tcam_cmd_vlan_num        (0xb38)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_action_exception        (0x2778)
#define image_2_action_gpe        (0x2764)
#define image_2_budget_allocator_sq_1st_wakeup_request        (0x4ffc)
#define image_2_cpu_recycle_wakeup_request        (0x3e50)
#define image_2_cpu_tx_read_ring_indices        (0x3750)
#define image_2_cpu_tx_wakeup_request        (0x3750)
#define image_2_debug_routine        (0x78)
#define image_2_debug_routine_handler        (0x4)
#define image_2_flush_task_1st_wakeup_request        (0x4e9c)
#define image_2_gpe_apply_icsum_16        (0x2b98)
#define image_2_gpe_apply_icsum_nz_16        (0x2bbc)
#define image_2_gpe_buffer_copy_16_ddr        (0x2c70)
#define image_2_gpe_buffer_copy_16_sram        (0x2c44)
#define image_2_gpe_compute_csum_16_cl        (0x2bf8)
#define image_2_gpe_compute_csum_16_sram        (0x2c04)
#define image_2_gpe_copy_add_16_cl        (0x2a24)
#define image_2_gpe_copy_add_16_sram        (0x2a30)
#define image_2_gpe_copy_bits_16_cl        (0x2a78)
#define image_2_gpe_copy_bits_16_sram        (0x2a84)
#define image_2_gpe_decrement_8        (0x2b74)
#define image_2_gpe_delete_16        (0x2b34)
#define image_2_gpe_insert_16        (0x2acc)
#define image_2_gpe_replace_16        (0x29a0)
#define image_2_gpe_replace_32        (0x29d4)
#define image_2_gpe_replace_add_packet_length_cl        (0x2ca0)
#define image_2_gpe_replace_bits_16        (0x29f8)
#define image_2_gpe_replace_pointer_32_sram        (0x2958)
#define image_2_gpe_replace_pointer_64_sram        (0x297c)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0x2838)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0x287c)
#define image_2_gpe_sop_pull_replace_sram_64        (0x28cc)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0x2908)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x27b8)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x27fc)
#define image_2_gpe_sop_push_replace_sram_64        (0x2810)
#define image_2_gpe_sop_push_replace_sram_64_32        (0x2824)
#define image_2_initialization_task        (0x8)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0x3fac)
#define image_2_processing_check_wlan_llcsnap        (0xb14)
#define image_2_processing_done        (0xcc0)
#define image_2_processing_wakeup_request        (0x184)
#define image_2_scheduling_service_queues_call_scheduler_block        (0x4834)
#define image_2_service_queues_tx_task_wakeup_request        (0x4834)
#define image_2_service_queues_update_fifo_read_1st_wakeup_request        (0x4540)
#define image_2_start_task_budget_allocator_sq_1st_wakeup_request        (0x4ffc)
#define image_2_start_task_cpu_recycle_wakeup_request        (0x3e50)
#define image_2_start_task_cpu_tx_wakeup_request        (0x3750)
#define image_2_start_task_debug_routine        (0x78)
#define image_2_start_task_flush_task_1st_wakeup_request        (0x4e9c)
#define image_2_start_task_initialization_task        (0x8)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0x3fac)
#define image_2_start_task_processing_wakeup_request        (0x184)
#define image_2_start_task_service_queues_tx_task_wakeup_request        (0x4834)
#define image_2_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x4540)
#define image_2_tcam_cmd_dst_ip        (0x2f68)
#define image_2_tcam_cmd_dst_ipv6_masked        (0x2fc4)
#define image_2_tcam_cmd_dst_mac        (0x305c)
#define image_2_tcam_cmd_dst_port        (0x3018)
#define image_2_tcam_cmd_ethertype        (0x2d74)
#define image_2_tcam_cmd_gem_flow        (0x2e84)
#define image_2_tcam_cmd_generic_l2        (0x3088)
#define image_2_tcam_cmd_generic_l3        (0x30bc)
#define image_2_tcam_cmd_generic_l4        (0x30f8)
#define image_2_tcam_cmd_ic_submit        (0x2cf8)
#define image_2_tcam_cmd_ingress_port        (0x2e6c)
#define image_2_tcam_cmd_inner_pbit        (0x2dd4)
#define image_2_tcam_cmd_inner_tpid        (0x2d5c)
#define image_2_tcam_cmd_inner_vid        (0x2da4)
#define image_2_tcam_cmd_ip_protocol        (0x2e04)
#define image_2_tcam_cmd_ipv6_label        (0x2e9c)
#define image_2_tcam_cmd_l3_protocol        (0x2e1c)
#define image_2_tcam_cmd_network_layer        (0x2e4c)
#define image_2_tcam_cmd_outer_pbit        (0x2dbc)
#define image_2_tcam_cmd_outer_tpid        (0x2d44)
#define image_2_tcam_cmd_outer_vid        (0x2d8c)
#define image_2_tcam_cmd_src_ip        (0x2ed0)
#define image_2_tcam_cmd_src_ipv6_masked        (0x2f2c)
#define image_2_tcam_cmd_src_mac        (0x3030)
#define image_2_tcam_cmd_src_port        (0x3000)
#define image_2_tcam_cmd_tos        (0x2e34)
#define image_2_tcam_cmd_vlan_num        (0x2dec)

#else

#define image_2_action_exception        (0x9de)
#define image_2_action_gpe        (0x9d9)
#define image_2_budget_allocator_sq_1st_wakeup_request        (0x13ff)
#define image_2_cpu_recycle_wakeup_request        (0xf94)
#define image_2_cpu_tx_read_ring_indices        (0xdd4)
#define image_2_cpu_tx_wakeup_request        (0xdd4)
#define image_2_debug_routine        (0x1e)
#define image_2_debug_routine_handler        (0x1)
#define image_2_flush_task_1st_wakeup_request        (0x13a7)
#define image_2_gpe_apply_icsum_16        (0xae6)
#define image_2_gpe_apply_icsum_nz_16        (0xaef)
#define image_2_gpe_buffer_copy_16_ddr        (0xb1c)
#define image_2_gpe_buffer_copy_16_sram        (0xb11)
#define image_2_gpe_compute_csum_16_cl        (0xafe)
#define image_2_gpe_compute_csum_16_sram        (0xb01)
#define image_2_gpe_copy_add_16_cl        (0xa89)
#define image_2_gpe_copy_add_16_sram        (0xa8c)
#define image_2_gpe_copy_bits_16_cl        (0xa9e)
#define image_2_gpe_copy_bits_16_sram        (0xaa1)
#define image_2_gpe_decrement_8        (0xadd)
#define image_2_gpe_delete_16        (0xacd)
#define image_2_gpe_insert_16        (0xab3)
#define image_2_gpe_replace_16        (0xa68)
#define image_2_gpe_replace_32        (0xa75)
#define image_2_gpe_replace_add_packet_length_cl        (0xb28)
#define image_2_gpe_replace_bits_16        (0xa7e)
#define image_2_gpe_replace_pointer_32_sram        (0xa56)
#define image_2_gpe_replace_pointer_64_sram        (0xa5f)
#define image_2_gpe_sop_pull_replace_ddr_sram_32        (0xa0e)
#define image_2_gpe_sop_pull_replace_sram_32_64        (0xa1f)
#define image_2_gpe_sop_pull_replace_sram_64        (0xa33)
#define image_2_gpe_sop_pull_replace_sram_64_32        (0xa42)
#define image_2_gpe_sop_push_replace_ddr_sram_32        (0x9ee)
#define image_2_gpe_sop_push_replace_sram_32_64        (0x9ff)
#define image_2_gpe_sop_push_replace_sram_64        (0xa04)
#define image_2_gpe_sop_push_replace_sram_64_32        (0xa09)
#define image_2_initialization_task        (0x2)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0xfeb)
#define image_2_processing_check_wlan_llcsnap        (0x2c5)
#define image_2_processing_done        (0x330)
#define image_2_processing_wakeup_request        (0x61)
#define image_2_scheduling_service_queues_call_scheduler_block        (0x120d)
#define image_2_service_queues_tx_task_wakeup_request        (0x120d)
#define image_2_service_queues_update_fifo_read_1st_wakeup_request        (0x1150)
#define image_2_start_task_budget_allocator_sq_1st_wakeup_request        (0x13ff)
#define image_2_start_task_cpu_recycle_wakeup_request        (0xf94)
#define image_2_start_task_cpu_tx_wakeup_request        (0xdd4)
#define image_2_start_task_debug_routine        (0x1e)
#define image_2_start_task_flush_task_1st_wakeup_request        (0x13a7)
#define image_2_start_task_initialization_task        (0x2)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0xfeb)
#define image_2_start_task_processing_wakeup_request        (0x61)
#define image_2_start_task_service_queues_tx_task_wakeup_request        (0x120d)
#define image_2_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x1150)
#define image_2_tcam_cmd_dst_ip        (0xbda)
#define image_2_tcam_cmd_dst_ipv6_masked        (0xbf1)
#define image_2_tcam_cmd_dst_mac        (0xc17)
#define image_2_tcam_cmd_dst_port        (0xc06)
#define image_2_tcam_cmd_ethertype        (0xb5d)
#define image_2_tcam_cmd_gem_flow        (0xba1)
#define image_2_tcam_cmd_generic_l2        (0xc22)
#define image_2_tcam_cmd_generic_l3        (0xc2f)
#define image_2_tcam_cmd_generic_l4        (0xc3e)
#define image_2_tcam_cmd_ic_submit        (0xb3e)
#define image_2_tcam_cmd_ingress_port        (0xb9b)
#define image_2_tcam_cmd_inner_pbit        (0xb75)
#define image_2_tcam_cmd_inner_tpid        (0xb57)
#define image_2_tcam_cmd_inner_vid        (0xb69)
#define image_2_tcam_cmd_ip_protocol        (0xb81)
#define image_2_tcam_cmd_ipv6_label        (0xba7)
#define image_2_tcam_cmd_l3_protocol        (0xb87)
#define image_2_tcam_cmd_network_layer        (0xb93)
#define image_2_tcam_cmd_outer_pbit        (0xb6f)
#define image_2_tcam_cmd_outer_tpid        (0xb51)
#define image_2_tcam_cmd_outer_vid        (0xb63)
#define image_2_tcam_cmd_src_ip        (0xbb4)
#define image_2_tcam_cmd_src_ipv6_masked        (0xbcb)
#define image_2_tcam_cmd_src_mac        (0xc0c)
#define image_2_tcam_cmd_src_port        (0xc00)
#define image_2_tcam_cmd_tos        (0xb8d)
#define image_2_tcam_cmd_vlan_num        (0xb7b)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_budget_allocator_1st_wakeup_request        (0x1320)
#define image_3_buffer_cong_mgt_1st_wakeup_request        (0x18b8)
#define image_3_debug_routine        (0x84)
#define image_3_debug_routine_handler        (0x4)
#define image_3_epon_tx_task_wakeup_request        (0x101c)
#define image_3_epon_update_fifo_read_1st_wakeup_request        (0x2084)
#define image_3_flush_task_1st_wakeup_request        (0x1ba0)
#define image_3_gpon_control_wakeup_request        (0x150)
#define image_3_initialization_task        (0x8)
#define image_3_ovl_budget_allocator_1st_wakeup_request        (0x17f8)
#define image_3_pi2_calc_1st_wakeup_request        (0x5c8)
#define image_3_start_task_budget_allocator_1st_wakeup_request        (0x1320)
#define image_3_start_task_buffer_cong_mgt_1st_wakeup_request        (0x18b8)
#define image_3_start_task_debug_routine        (0x84)
#define image_3_start_task_epon_tx_task_wakeup_request        (0x101c)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request        (0x2084)
#define image_3_start_task_flush_task_1st_wakeup_request        (0x1ba0)
#define image_3_start_task_gpon_control_wakeup_request        (0x150)
#define image_3_start_task_initialization_task        (0x8)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request        (0x17f8)
#define image_3_start_task_pi2_calc_1st_wakeup_request        (0x5c8)
#define image_3_start_task_tx_task_1st_wakeup_request        (0x9fc)
#define image_3_start_task_update_fifo_us_read_1st_wakeup_request        (0x1d84)
#define image_3_start_task_wan_tx_ddr_read_1st_wakeup_request        (0x1b50)
#define image_3_start_task_wan_tx_psram_write_1st_wakeup_request        (0x1b78)
#define image_3_tx_task_1st_wakeup_request        (0x9fc)
#define image_3_update_fifo_us_read_1st_wakeup_request        (0x1d84)
#define image_3_wan_tx_ddr_read_1st_wakeup_request        (0x1b50)
#define image_3_wan_tx_psram_write_1st_wakeup_request        (0x1b78)

#else

#define image_3_budget_allocator_1st_wakeup_request        (0x4c8)
#define image_3_buffer_cong_mgt_1st_wakeup_request        (0x62e)
#define image_3_debug_routine        (0x21)
#define image_3_debug_routine_handler        (0x1)
#define image_3_epon_tx_task_wakeup_request        (0x407)
#define image_3_epon_update_fifo_read_1st_wakeup_request        (0x821)
#define image_3_flush_task_1st_wakeup_request        (0x6e8)
#define image_3_gpon_control_wakeup_request        (0x54)
#define image_3_initialization_task        (0x2)
#define image_3_ovl_budget_allocator_1st_wakeup_request        (0x5fe)
#define image_3_pi2_calc_1st_wakeup_request        (0x172)
#define image_3_start_task_budget_allocator_1st_wakeup_request        (0x4c8)
#define image_3_start_task_buffer_cong_mgt_1st_wakeup_request        (0x62e)
#define image_3_start_task_debug_routine        (0x21)
#define image_3_start_task_epon_tx_task_wakeup_request        (0x407)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request        (0x821)
#define image_3_start_task_flush_task_1st_wakeup_request        (0x6e8)
#define image_3_start_task_gpon_control_wakeup_request        (0x54)
#define image_3_start_task_initialization_task        (0x2)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request        (0x5fe)
#define image_3_start_task_pi2_calc_1st_wakeup_request        (0x172)
#define image_3_start_task_tx_task_1st_wakeup_request        (0x27f)
#define image_3_start_task_update_fifo_us_read_1st_wakeup_request        (0x761)
#define image_3_start_task_wan_tx_ddr_read_1st_wakeup_request        (0x6d4)
#define image_3_start_task_wan_tx_psram_write_1st_wakeup_request        (0x6de)
#define image_3_tx_task_1st_wakeup_request        (0x27f)
#define image_3_update_fifo_us_read_1st_wakeup_request        (0x761)
#define image_3_wan_tx_ddr_read_1st_wakeup_request        (0x6d4)
#define image_3_wan_tx_psram_write_1st_wakeup_request        (0x6de)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4_action_exception        (0x266c)
#define image_4_action_gpe        (0x2658)
#define image_4_debug_routine        (0x3644)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dhd_timer_1st_wakeup_request        (0x3ab8)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0x3b58)
#define image_4_dhd_tx_post_wakeup_request        (0x3bac)
#define image_4_gpe_apply_icsum_16        (0x2a8c)
#define image_4_gpe_apply_icsum_nz_16        (0x2ab0)
#define image_4_gpe_buffer_copy_16_ddr        (0x2b64)
#define image_4_gpe_buffer_copy_16_sram        (0x2b38)
#define image_4_gpe_compute_csum_16_cl        (0x2aec)
#define image_4_gpe_compute_csum_16_sram        (0x2af8)
#define image_4_gpe_copy_add_16_cl        (0x2918)
#define image_4_gpe_copy_add_16_sram        (0x2924)
#define image_4_gpe_copy_bits_16_cl        (0x296c)
#define image_4_gpe_copy_bits_16_sram        (0x2978)
#define image_4_gpe_decrement_8        (0x2a68)
#define image_4_gpe_delete_16        (0x2a28)
#define image_4_gpe_insert_16        (0x29c0)
#define image_4_gpe_replace_16        (0x2894)
#define image_4_gpe_replace_32        (0x28c8)
#define image_4_gpe_replace_add_packet_length_cl        (0x2b94)
#define image_4_gpe_replace_bits_16        (0x28ec)
#define image_4_gpe_replace_pointer_32_sram        (0x284c)
#define image_4_gpe_replace_pointer_64_sram        (0x2870)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x272c)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x2770)
#define image_4_gpe_sop_pull_replace_sram_64        (0x27c0)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x27fc)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x26ac)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x26f0)
#define image_4_gpe_sop_push_replace_sram_64        (0x2704)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x2718)
#define image_4_initialization_task        (0x8)
#define image_4_processing_check_wlan_llcsnap        (0xa08)
#define image_4_processing_done        (0xbb4)
#define image_4_processing_wakeup_request        (0x78)
#define image_4_start_task_debug_routine        (0x3644)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0x3ab8)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0x3b58)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0x3bac)
#define image_4_start_task_initialization_task        (0x8)
#define image_4_start_task_processing_wakeup_request        (0x78)
#define image_4_tcam_cmd_dst_ip        (0x2e5c)
#define image_4_tcam_cmd_dst_ipv6_masked        (0x2eb8)
#define image_4_tcam_cmd_dst_mac        (0x2f50)
#define image_4_tcam_cmd_dst_port        (0x2f0c)
#define image_4_tcam_cmd_ethertype        (0x2c68)
#define image_4_tcam_cmd_gem_flow        (0x2d78)
#define image_4_tcam_cmd_generic_l2        (0x2f7c)
#define image_4_tcam_cmd_generic_l3        (0x2fb0)
#define image_4_tcam_cmd_generic_l4        (0x2fec)
#define image_4_tcam_cmd_ic_submit        (0x2bec)
#define image_4_tcam_cmd_ingress_port        (0x2d60)
#define image_4_tcam_cmd_inner_pbit        (0x2cc8)
#define image_4_tcam_cmd_inner_tpid        (0x2c50)
#define image_4_tcam_cmd_inner_vid        (0x2c98)
#define image_4_tcam_cmd_ip_protocol        (0x2cf8)
#define image_4_tcam_cmd_ipv6_label        (0x2d90)
#define image_4_tcam_cmd_l3_protocol        (0x2d10)
#define image_4_tcam_cmd_network_layer        (0x2d40)
#define image_4_tcam_cmd_outer_pbit        (0x2cb0)
#define image_4_tcam_cmd_outer_tpid        (0x2c38)
#define image_4_tcam_cmd_outer_vid        (0x2c80)
#define image_4_tcam_cmd_src_ip        (0x2dc4)
#define image_4_tcam_cmd_src_ipv6_masked        (0x2e20)
#define image_4_tcam_cmd_src_mac        (0x2f24)
#define image_4_tcam_cmd_src_port        (0x2ef4)
#define image_4_tcam_cmd_tos        (0x2d28)
#define image_4_tcam_cmd_vlan_num        (0x2ce0)

#else

#define image_4_action_exception        (0x99b)
#define image_4_action_gpe        (0x996)
#define image_4_debug_routine        (0xd91)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dhd_timer_1st_wakeup_request        (0xeae)
#define image_4_dhd_tx_post_update_fifo_wakeup_request        (0xed6)
#define image_4_dhd_tx_post_wakeup_request        (0xeeb)
#define image_4_gpe_apply_icsum_16        (0xaa3)
#define image_4_gpe_apply_icsum_nz_16        (0xaac)
#define image_4_gpe_buffer_copy_16_ddr        (0xad9)
#define image_4_gpe_buffer_copy_16_sram        (0xace)
#define image_4_gpe_compute_csum_16_cl        (0xabb)
#define image_4_gpe_compute_csum_16_sram        (0xabe)
#define image_4_gpe_copy_add_16_cl        (0xa46)
#define image_4_gpe_copy_add_16_sram        (0xa49)
#define image_4_gpe_copy_bits_16_cl        (0xa5b)
#define image_4_gpe_copy_bits_16_sram        (0xa5e)
#define image_4_gpe_decrement_8        (0xa9a)
#define image_4_gpe_delete_16        (0xa8a)
#define image_4_gpe_insert_16        (0xa70)
#define image_4_gpe_replace_16        (0xa25)
#define image_4_gpe_replace_32        (0xa32)
#define image_4_gpe_replace_add_packet_length_cl        (0xae5)
#define image_4_gpe_replace_bits_16        (0xa3b)
#define image_4_gpe_replace_pointer_32_sram        (0xa13)
#define image_4_gpe_replace_pointer_64_sram        (0xa1c)
#define image_4_gpe_sop_pull_replace_ddr_sram_32        (0x9cb)
#define image_4_gpe_sop_pull_replace_sram_32_64        (0x9dc)
#define image_4_gpe_sop_pull_replace_sram_64        (0x9f0)
#define image_4_gpe_sop_pull_replace_sram_64_32        (0x9ff)
#define image_4_gpe_sop_push_replace_ddr_sram_32        (0x9ab)
#define image_4_gpe_sop_push_replace_sram_32_64        (0x9bc)
#define image_4_gpe_sop_push_replace_sram_64        (0x9c1)
#define image_4_gpe_sop_push_replace_sram_64_32        (0x9c6)
#define image_4_initialization_task        (0x2)
#define image_4_processing_check_wlan_llcsnap        (0x282)
#define image_4_processing_done        (0x2ed)
#define image_4_processing_wakeup_request        (0x1e)
#define image_4_start_task_debug_routine        (0xd91)
#define image_4_start_task_dhd_timer_1st_wakeup_request        (0xeae)
#define image_4_start_task_dhd_tx_post_update_fifo_wakeup_request        (0xed6)
#define image_4_start_task_dhd_tx_post_wakeup_request        (0xeeb)
#define image_4_start_task_initialization_task        (0x2)
#define image_4_start_task_processing_wakeup_request        (0x1e)
#define image_4_tcam_cmd_dst_ip        (0xb97)
#define image_4_tcam_cmd_dst_ipv6_masked        (0xbae)
#define image_4_tcam_cmd_dst_mac        (0xbd4)
#define image_4_tcam_cmd_dst_port        (0xbc3)
#define image_4_tcam_cmd_ethertype        (0xb1a)
#define image_4_tcam_cmd_gem_flow        (0xb5e)
#define image_4_tcam_cmd_generic_l2        (0xbdf)
#define image_4_tcam_cmd_generic_l3        (0xbec)
#define image_4_tcam_cmd_generic_l4        (0xbfb)
#define image_4_tcam_cmd_ic_submit        (0xafb)
#define image_4_tcam_cmd_ingress_port        (0xb58)
#define image_4_tcam_cmd_inner_pbit        (0xb32)
#define image_4_tcam_cmd_inner_tpid        (0xb14)
#define image_4_tcam_cmd_inner_vid        (0xb26)
#define image_4_tcam_cmd_ip_protocol        (0xb3e)
#define image_4_tcam_cmd_ipv6_label        (0xb64)
#define image_4_tcam_cmd_l3_protocol        (0xb44)
#define image_4_tcam_cmd_network_layer        (0xb50)
#define image_4_tcam_cmd_outer_pbit        (0xb2c)
#define image_4_tcam_cmd_outer_tpid        (0xb0e)
#define image_4_tcam_cmd_outer_vid        (0xb20)
#define image_4_tcam_cmd_src_ip        (0xb71)
#define image_4_tcam_cmd_src_ipv6_masked        (0xb88)
#define image_4_tcam_cmd_src_mac        (0xbc9)
#define image_4_tcam_cmd_src_port        (0xbbd)
#define image_4_tcam_cmd_tos        (0xb4a)
#define image_4_tcam_cmd_vlan_num        (0xb38)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5_action_exception        (0x266c)
#define image_5_action_gpe        (0x2658)
#define image_5_debug_routine        (0x3644)
#define image_5_debug_routine_handler        (0x4)
#define image_5_dhd_rx_complete_wakeup_request        (0x3b40)
#define image_5_dhd_tx_complete_wakeup_request        (0x37f0)
#define image_5_gpe_apply_icsum_16        (0x2a8c)
#define image_5_gpe_apply_icsum_nz_16        (0x2ab0)
#define image_5_gpe_buffer_copy_16_ddr        (0x2b64)
#define image_5_gpe_buffer_copy_16_sram        (0x2b38)
#define image_5_gpe_compute_csum_16_cl        (0x2aec)
#define image_5_gpe_compute_csum_16_sram        (0x2af8)
#define image_5_gpe_copy_add_16_cl        (0x2918)
#define image_5_gpe_copy_add_16_sram        (0x2924)
#define image_5_gpe_copy_bits_16_cl        (0x296c)
#define image_5_gpe_copy_bits_16_sram        (0x2978)
#define image_5_gpe_decrement_8        (0x2a68)
#define image_5_gpe_delete_16        (0x2a28)
#define image_5_gpe_insert_16        (0x29c0)
#define image_5_gpe_replace_16        (0x2894)
#define image_5_gpe_replace_32        (0x28c8)
#define image_5_gpe_replace_add_packet_length_cl        (0x2b94)
#define image_5_gpe_replace_bits_16        (0x28ec)
#define image_5_gpe_replace_pointer_32_sram        (0x284c)
#define image_5_gpe_replace_pointer_64_sram        (0x2870)
#define image_5_gpe_sop_pull_replace_ddr_sram_32        (0x272c)
#define image_5_gpe_sop_pull_replace_sram_32_64        (0x2770)
#define image_5_gpe_sop_pull_replace_sram_64        (0x27c0)
#define image_5_gpe_sop_pull_replace_sram_64_32        (0x27fc)
#define image_5_gpe_sop_push_replace_ddr_sram_32        (0x26ac)
#define image_5_gpe_sop_push_replace_sram_32_64        (0x26f0)
#define image_5_gpe_sop_push_replace_sram_64        (0x2704)
#define image_5_gpe_sop_push_replace_sram_64_32        (0x2718)
#define image_5_initialization_task        (0x8)
#define image_5_processing_check_wlan_llcsnap        (0xa08)
#define image_5_processing_done        (0xbb4)
#define image_5_processing_wakeup_request        (0x78)
#define image_5_start_task_debug_routine        (0x3644)
#define image_5_start_task_dhd_rx_complete_wakeup_request        (0x3b40)
#define image_5_start_task_dhd_tx_complete_wakeup_request        (0x37f0)
#define image_5_start_task_initialization_task        (0x8)
#define image_5_start_task_processing_wakeup_request        (0x78)
#define image_5_tcam_cmd_dst_ip        (0x2e5c)
#define image_5_tcam_cmd_dst_ipv6_masked        (0x2eb8)
#define image_5_tcam_cmd_dst_mac        (0x2f50)
#define image_5_tcam_cmd_dst_port        (0x2f0c)
#define image_5_tcam_cmd_ethertype        (0x2c68)
#define image_5_tcam_cmd_gem_flow        (0x2d78)
#define image_5_tcam_cmd_generic_l2        (0x2f7c)
#define image_5_tcam_cmd_generic_l3        (0x2fb0)
#define image_5_tcam_cmd_generic_l4        (0x2fec)
#define image_5_tcam_cmd_ic_submit        (0x2bec)
#define image_5_tcam_cmd_ingress_port        (0x2d60)
#define image_5_tcam_cmd_inner_pbit        (0x2cc8)
#define image_5_tcam_cmd_inner_tpid        (0x2c50)
#define image_5_tcam_cmd_inner_vid        (0x2c98)
#define image_5_tcam_cmd_ip_protocol        (0x2cf8)
#define image_5_tcam_cmd_ipv6_label        (0x2d90)
#define image_5_tcam_cmd_l3_protocol        (0x2d10)
#define image_5_tcam_cmd_network_layer        (0x2d40)
#define image_5_tcam_cmd_outer_pbit        (0x2cb0)
#define image_5_tcam_cmd_outer_tpid        (0x2c38)
#define image_5_tcam_cmd_outer_vid        (0x2c80)
#define image_5_tcam_cmd_src_ip        (0x2dc4)
#define image_5_tcam_cmd_src_ipv6_masked        (0x2e20)
#define image_5_tcam_cmd_src_mac        (0x2f24)
#define image_5_tcam_cmd_src_port        (0x2ef4)
#define image_5_tcam_cmd_tos        (0x2d28)
#define image_5_tcam_cmd_vlan_num        (0x2ce0)

#else

#define image_5_action_exception        (0x99b)
#define image_5_action_gpe        (0x996)
#define image_5_debug_routine        (0xd91)
#define image_5_debug_routine_handler        (0x1)
#define image_5_dhd_rx_complete_wakeup_request        (0xed0)
#define image_5_dhd_tx_complete_wakeup_request        (0xdfc)
#define image_5_gpe_apply_icsum_16        (0xaa3)
#define image_5_gpe_apply_icsum_nz_16        (0xaac)
#define image_5_gpe_buffer_copy_16_ddr        (0xad9)
#define image_5_gpe_buffer_copy_16_sram        (0xace)
#define image_5_gpe_compute_csum_16_cl        (0xabb)
#define image_5_gpe_compute_csum_16_sram        (0xabe)
#define image_5_gpe_copy_add_16_cl        (0xa46)
#define image_5_gpe_copy_add_16_sram        (0xa49)
#define image_5_gpe_copy_bits_16_cl        (0xa5b)
#define image_5_gpe_copy_bits_16_sram        (0xa5e)
#define image_5_gpe_decrement_8        (0xa9a)
#define image_5_gpe_delete_16        (0xa8a)
#define image_5_gpe_insert_16        (0xa70)
#define image_5_gpe_replace_16        (0xa25)
#define image_5_gpe_replace_32        (0xa32)
#define image_5_gpe_replace_add_packet_length_cl        (0xae5)
#define image_5_gpe_replace_bits_16        (0xa3b)
#define image_5_gpe_replace_pointer_32_sram        (0xa13)
#define image_5_gpe_replace_pointer_64_sram        (0xa1c)
#define image_5_gpe_sop_pull_replace_ddr_sram_32        (0x9cb)
#define image_5_gpe_sop_pull_replace_sram_32_64        (0x9dc)
#define image_5_gpe_sop_pull_replace_sram_64        (0x9f0)
#define image_5_gpe_sop_pull_replace_sram_64_32        (0x9ff)
#define image_5_gpe_sop_push_replace_ddr_sram_32        (0x9ab)
#define image_5_gpe_sop_push_replace_sram_32_64        (0x9bc)
#define image_5_gpe_sop_push_replace_sram_64        (0x9c1)
#define image_5_gpe_sop_push_replace_sram_64_32        (0x9c6)
#define image_5_initialization_task        (0x2)
#define image_5_processing_check_wlan_llcsnap        (0x282)
#define image_5_processing_done        (0x2ed)
#define image_5_processing_wakeup_request        (0x1e)
#define image_5_start_task_debug_routine        (0xd91)
#define image_5_start_task_dhd_rx_complete_wakeup_request        (0xed0)
#define image_5_start_task_dhd_tx_complete_wakeup_request        (0xdfc)
#define image_5_start_task_initialization_task        (0x2)
#define image_5_start_task_processing_wakeup_request        (0x1e)
#define image_5_tcam_cmd_dst_ip        (0xb97)
#define image_5_tcam_cmd_dst_ipv6_masked        (0xbae)
#define image_5_tcam_cmd_dst_mac        (0xbd4)
#define image_5_tcam_cmd_dst_port        (0xbc3)
#define image_5_tcam_cmd_ethertype        (0xb1a)
#define image_5_tcam_cmd_gem_flow        (0xb5e)
#define image_5_tcam_cmd_generic_l2        (0xbdf)
#define image_5_tcam_cmd_generic_l3        (0xbec)
#define image_5_tcam_cmd_generic_l4        (0xbfb)
#define image_5_tcam_cmd_ic_submit        (0xafb)
#define image_5_tcam_cmd_ingress_port        (0xb58)
#define image_5_tcam_cmd_inner_pbit        (0xb32)
#define image_5_tcam_cmd_inner_tpid        (0xb14)
#define image_5_tcam_cmd_inner_vid        (0xb26)
#define image_5_tcam_cmd_ip_protocol        (0xb3e)
#define image_5_tcam_cmd_ipv6_label        (0xb64)
#define image_5_tcam_cmd_l3_protocol        (0xb44)
#define image_5_tcam_cmd_network_layer        (0xb50)
#define image_5_tcam_cmd_outer_pbit        (0xb2c)
#define image_5_tcam_cmd_outer_tpid        (0xb0e)
#define image_5_tcam_cmd_outer_vid        (0xb20)
#define image_5_tcam_cmd_src_ip        (0xb71)
#define image_5_tcam_cmd_src_ipv6_masked        (0xb88)
#define image_5_tcam_cmd_src_mac        (0xbc9)
#define image_5_tcam_cmd_src_port        (0xbbd)
#define image_5_tcam_cmd_tos        (0xb4a)
#define image_5_tcam_cmd_vlan_num        (0xb38)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND

#define TCAM_CMD_DST_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2e5c, 0x2f68, INVALID_LABEL_ADDRESS, 0x2e5c, 0x2e5c}
#define TCAM_CMD_DST_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2eb8, 0x2fc4, INVALID_LABEL_ADDRESS, 0x2eb8, 0x2eb8}
#define TCAM_CMD_DST_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2f50, 0x305c, INVALID_LABEL_ADDRESS, 0x2f50, 0x2f50}
#define TCAM_CMD_DST_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2f0c, 0x3018, INVALID_LABEL_ADDRESS, 0x2f0c, 0x2f0c}
#define TCAM_CMD_ETHERTYPE_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2c68, 0x2d74, INVALID_LABEL_ADDRESS, 0x2c68, 0x2c68}
#define TCAM_CMD_GEM_FLOW_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2d78, 0x2e84, INVALID_LABEL_ADDRESS, 0x2d78, 0x2d78}
#define TCAM_CMD_GENERIC_L2_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2f7c, 0x3088, INVALID_LABEL_ADDRESS, 0x2f7c, 0x2f7c}
#define TCAM_CMD_GENERIC_L3_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2fb0, 0x30bc, INVALID_LABEL_ADDRESS, 0x2fb0, 0x2fb0}
#define TCAM_CMD_GENERIC_L4_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2fec, 0x30f8, INVALID_LABEL_ADDRESS, 0x2fec, 0x2fec}
#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2bec, 0x2cf8, INVALID_LABEL_ADDRESS, 0x2bec, 0x2bec}
#define TCAM_CMD_INGRESS_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2d60, 0x2e6c, INVALID_LABEL_ADDRESS, 0x2d60, 0x2d60}
#define TCAM_CMD_INNER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2cc8, 0x2dd4, INVALID_LABEL_ADDRESS, 0x2cc8, 0x2cc8}
#define TCAM_CMD_INNER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2c50, 0x2d5c, INVALID_LABEL_ADDRESS, 0x2c50, 0x2c50}
#define TCAM_CMD_INNER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2c98, 0x2da4, INVALID_LABEL_ADDRESS, 0x2c98, 0x2c98}
#define TCAM_CMD_IP_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2cf8, 0x2e04, INVALID_LABEL_ADDRESS, 0x2cf8, 0x2cf8}
#define TCAM_CMD_IPV6_LABEL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2d90, 0x2e9c, INVALID_LABEL_ADDRESS, 0x2d90, 0x2d90}
#define TCAM_CMD_L3_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2d10, 0x2e1c, INVALID_LABEL_ADDRESS, 0x2d10, 0x2d10}
#define TCAM_CMD_NETWORK_LAYER_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2d40, 0x2e4c, INVALID_LABEL_ADDRESS, 0x2d40, 0x2d40}
#define TCAM_CMD_OUTER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2cb0, 0x2dbc, INVALID_LABEL_ADDRESS, 0x2cb0, 0x2cb0}
#define TCAM_CMD_OUTER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2c38, 0x2d44, INVALID_LABEL_ADDRESS, 0x2c38, 0x2c38}
#define TCAM_CMD_OUTER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2c80, 0x2d8c, INVALID_LABEL_ADDRESS, 0x2c80, 0x2c80}
#define TCAM_CMD_SRC_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2dc4, 0x2ed0, INVALID_LABEL_ADDRESS, 0x2dc4, 0x2dc4}
#define TCAM_CMD_SRC_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2e20, 0x2f2c, INVALID_LABEL_ADDRESS, 0x2e20, 0x2e20}
#define TCAM_CMD_SRC_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2f24, 0x3030, INVALID_LABEL_ADDRESS, 0x2f24, 0x2f24}
#define TCAM_CMD_SRC_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2ef4, 0x3000, INVALID_LABEL_ADDRESS, 0x2ef4, 0x2ef4}
#define TCAM_CMD_TOS_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2d28, 0x2e34, INVALID_LABEL_ADDRESS, 0x2d28, 0x2d28}
#define TCAM_CMD_VLAN_NUM_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x2ce0, 0x2dec, INVALID_LABEL_ADDRESS, 0x2ce0, 0x2ce0}

#else

#define TCAM_CMD_DST_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb97, 0xbda, INVALID_LABEL_ADDRESS, 0xb97, 0xb97}
#define TCAM_CMD_DST_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbae, 0xbf1, INVALID_LABEL_ADDRESS, 0xbae, 0xbae}
#define TCAM_CMD_DST_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbd4, 0xc17, INVALID_LABEL_ADDRESS, 0xbd4, 0xbd4}
#define TCAM_CMD_DST_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbc3, 0xc06, INVALID_LABEL_ADDRESS, 0xbc3, 0xbc3}
#define TCAM_CMD_ETHERTYPE_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb1a, 0xb5d, INVALID_LABEL_ADDRESS, 0xb1a, 0xb1a}
#define TCAM_CMD_GEM_FLOW_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb5e, 0xba1, INVALID_LABEL_ADDRESS, 0xb5e, 0xb5e}
#define TCAM_CMD_GENERIC_L2_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbdf, 0xc22, INVALID_LABEL_ADDRESS, 0xbdf, 0xbdf}
#define TCAM_CMD_GENERIC_L3_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbec, 0xc2f, INVALID_LABEL_ADDRESS, 0xbec, 0xbec}
#define TCAM_CMD_GENERIC_L4_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbfb, 0xc3e, INVALID_LABEL_ADDRESS, 0xbfb, 0xbfb}
#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xafb, 0xb3e, INVALID_LABEL_ADDRESS, 0xafb, 0xafb}
#define TCAM_CMD_INGRESS_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb58, 0xb9b, INVALID_LABEL_ADDRESS, 0xb58, 0xb58}
#define TCAM_CMD_INNER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb32, 0xb75, INVALID_LABEL_ADDRESS, 0xb32, 0xb32}
#define TCAM_CMD_INNER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb14, 0xb57, INVALID_LABEL_ADDRESS, 0xb14, 0xb14}
#define TCAM_CMD_INNER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb26, 0xb69, INVALID_LABEL_ADDRESS, 0xb26, 0xb26}
#define TCAM_CMD_IP_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb3e, 0xb81, INVALID_LABEL_ADDRESS, 0xb3e, 0xb3e}
#define TCAM_CMD_IPV6_LABEL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb64, 0xba7, INVALID_LABEL_ADDRESS, 0xb64, 0xb64}
#define TCAM_CMD_L3_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb44, 0xb87, INVALID_LABEL_ADDRESS, 0xb44, 0xb44}
#define TCAM_CMD_NETWORK_LAYER_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb50, 0xb93, INVALID_LABEL_ADDRESS, 0xb50, 0xb50}
#define TCAM_CMD_OUTER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb2c, 0xb6f, INVALID_LABEL_ADDRESS, 0xb2c, 0xb2c}
#define TCAM_CMD_OUTER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb0e, 0xb51, INVALID_LABEL_ADDRESS, 0xb0e, 0xb0e}
#define TCAM_CMD_OUTER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb20, 0xb63, INVALID_LABEL_ADDRESS, 0xb20, 0xb20}
#define TCAM_CMD_SRC_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb71, 0xbb4, INVALID_LABEL_ADDRESS, 0xb71, 0xb71}
#define TCAM_CMD_SRC_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb88, 0xbcb, INVALID_LABEL_ADDRESS, 0xb88, 0xb88}
#define TCAM_CMD_SRC_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbc9, 0xc0c, INVALID_LABEL_ADDRESS, 0xbc9, 0xbc9}
#define TCAM_CMD_SRC_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xbbd, 0xc00, INVALID_LABEL_ADDRESS, 0xbbd, 0xbbd}
#define TCAM_CMD_TOS_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb4a, 0xb8d, INVALID_LABEL_ADDRESS, 0xb4a, 0xb4a}
#define TCAM_CMD_VLAN_NUM_ADDR_ARR {INVALID_LABEL_ADDRESS, 0xb38, 0xb7b, INVALID_LABEL_ADDRESS, 0xb38, 0xb38}

#endif


#endif

