/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_add_pbit_to_key        (0x3770)
#define image_0_c_dhd_rx_complete_wakeup_request        (0x3ec)
#define image_0_c_dhd_tx_complete_wakeup_request        (0x850)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_0_check_skip_cso        (0x3710)
#define image_0_debug_routine        (0x30)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_0_dos_attack_handler        (0x2c94)
#define image_0_drop_pkt_and_serial        (0x2e84)
#define image_0_dyn_code_func        (0x7c00)
#define image_0_flow_policer        (0x5950)
#define image_0_group_flow_lkp_and_fwd        (0x3890)
#define image_0_ingress_filter_action_point_update        (0x379c)
#define image_0_ingress_filters_handler        (0x3014)
#define image_0_initialization_task        (0x8)
#define image_0_is_iptv_capable        (0x2cf0)
#define image_0_mcast_flow_master_lookup        (0x37e8)
#define image_0_memcpy_abs_to_sbpm        (0xf8)
#define image_0_parser_exception_handler        (0x2ab0)
#define image_0_proccessing_loopback        (0x29f8)
#define image_0_processing_policer_action        (0x59a0)
#define image_0_processing_wakeup_request        (0xad8)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0x754)
#define image_0_rxcmpl_process_rx_packet        (0x7bc)
#define image_0_spdsvc_natc_lookup        (0x2d90)
#define image_0_start_task_add_pbit_to_key        (0x3770)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0x3ec)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0x850)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_0_start_task_check_skip_cso        (0x3710)
#define image_0_start_task_debug_routine        (0x30)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_0_start_task_dos_attack_handler        (0x2c94)
#define image_0_start_task_drop_pkt_and_serial        (0x2e84)
#define image_0_start_task_dyn_code_func        (0x7c00)
#define image_0_start_task_flow_policer        (0x5950)
#define image_0_start_task_group_flow_lkp_and_fwd        (0x3890)
#define image_0_start_task_ingress_filter_action_point_update        (0x379c)
#define image_0_start_task_ingress_filters_handler        (0x3014)
#define image_0_start_task_initialization_task        (0x8)
#define image_0_start_task_is_iptv_capable        (0x2cf0)
#define image_0_start_task_mcast_flow_master_lookup        (0x37e8)
#define image_0_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_0_start_task_parser_exception_handler        (0x2ab0)
#define image_0_start_task_proccessing_loopback        (0x29f8)
#define image_0_start_task_processing_policer_action        (0x59a0)
#define image_0_start_task_processing_wakeup_request        (0xad8)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0x754)
#define image_0_start_task_rxcmpl_process_rx_packet        (0x7bc)
#define image_0_start_task_spdsvc_natc_lookup        (0x2d90)
#define image_0_start_task_ts_1588_handler        (0x2fe0)
#define image_0_start_task_xx_mirror_noinline        (0x334c)
#define image_0_ts_1588_handler        (0x2fe0)
#define image_0_xx_mirror_noinline        (0x334c)

#else

#define image_0_add_pbit_to_key        (0xddc)
#define image_0_c_dhd_rx_complete_wakeup_request        (0xfb)
#define image_0_c_dhd_tx_complete_wakeup_request        (0x214)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_0_check_skip_cso        (0xdc4)
#define image_0_debug_routine        (0xc)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_0_dos_attack_handler        (0xb25)
#define image_0_drop_pkt_and_serial        (0xba1)
#define image_0_dyn_code_func        (0x1f00)
#define image_0_flow_policer        (0x1654)
#define image_0_group_flow_lkp_and_fwd        (0xe24)
#define image_0_ingress_filter_action_point_update        (0xde7)
#define image_0_ingress_filters_handler        (0xc05)
#define image_0_initialization_task        (0x2)
#define image_0_is_iptv_capable        (0xb3c)
#define image_0_mcast_flow_master_lookup        (0xdfa)
#define image_0_memcpy_abs_to_sbpm        (0x3e)
#define image_0_parser_exception_handler        (0xaac)
#define image_0_proccessing_loopback        (0xa7e)
#define image_0_processing_policer_action        (0x1668)
#define image_0_processing_wakeup_request        (0x2b6)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0x1d5)
#define image_0_rxcmpl_process_rx_packet        (0x1ef)
#define image_0_spdsvc_natc_lookup        (0xb64)
#define image_0_start_task_add_pbit_to_key        (0xddc)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0xfb)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0x214)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_0_start_task_check_skip_cso        (0xdc4)
#define image_0_start_task_debug_routine        (0xc)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_0_start_task_dos_attack_handler        (0xb25)
#define image_0_start_task_drop_pkt_and_serial        (0xba1)
#define image_0_start_task_dyn_code_func        (0x1f00)
#define image_0_start_task_flow_policer        (0x1654)
#define image_0_start_task_group_flow_lkp_and_fwd        (0xe24)
#define image_0_start_task_ingress_filter_action_point_update        (0xde7)
#define image_0_start_task_ingress_filters_handler        (0xc05)
#define image_0_start_task_initialization_task        (0x2)
#define image_0_start_task_is_iptv_capable        (0xb3c)
#define image_0_start_task_mcast_flow_master_lookup        (0xdfa)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_0_start_task_parser_exception_handler        (0xaac)
#define image_0_start_task_proccessing_loopback        (0xa7e)
#define image_0_start_task_processing_policer_action        (0x1668)
#define image_0_start_task_processing_wakeup_request        (0x2b6)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0x1d5)
#define image_0_start_task_rxcmpl_process_rx_packet        (0x1ef)
#define image_0_start_task_spdsvc_natc_lookup        (0xb64)
#define image_0_start_task_ts_1588_handler        (0xbf8)
#define image_0_start_task_xx_mirror_noinline        (0xcd3)
#define image_0_ts_1588_handler        (0xbf8)
#define image_0_xx_mirror_noinline        (0xcd3)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_add_pbit_to_key        (0x40cc)
#define image_1_c_cpu_recycle_wakeup_request        (0x6568)
#define image_1_c_cpu_rx_wakeup_request        (0x66f8)
#define image_1_c_dhd_timer_wakeup_request        (0x3ec)
#define image_1_c_dhd_tx_post_update_fifo_wakeup_request        (0x474)
#define image_1_c_dhd_tx_post_wakeup_request        (0x4b8)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_1_check_skip_cso        (0x406c)
#define image_1_cpu_recycle_int_coalescing        (0x66cc)
#define image_1_cpu_rx_int_coalescing        (0x7074)
#define image_1_cpu_rx_meter_budget_allocator        (0x70c0)
#define image_1_debug_routine        (0x30)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_1_dhd_tx_get_bq_index        (0x1320)
#define image_1_dhd_tx_post_drop_packet        (0x11f0)
#define image_1_dhd_tx_post_flow_ring_get_info        (0x102c)
#define image_1_dhd_tx_put_bq_index        (0x1390)
#define image_1_dos_attack_handler        (0x35f0)
#define image_1_drop_pkt_and_serial        (0x37e0)
#define image_1_dyn_code_func        (0x7c00)
#define image_1_flow_policer        (0x62b8)
#define image_1_general_timer_wakeup_request        (0x64f0)
#define image_1_get_pd_from_fifo        (0x71e0)
#define image_1_group_flow_lkp_and_fwd        (0x41ec)
#define image_1_ingress_filter_action_point_update        (0x40f8)
#define image_1_ingress_filters_handler        (0x3970)
#define image_1_initialization_task        (0x8)
#define image_1_is_iptv_capable        (0x364c)
#define image_1_mcast_flow_master_lookup        (0x4144)
#define image_1_memcpy_abs_to_sbpm        (0xf8)
#define image_1_packet_cso_hw_offload        (0x7124)
#define image_1_parser_exception_handler        (0x340c)
#define image_1_proccessing_loopback        (0x3354)
#define image_1_processing_policer_action        (0x6308)
#define image_1_processing_wakeup_request        (0x13f8)
#define image_1_spdsvc_natc_lookup        (0x36ec)
#define image_1_start_task_add_pbit_to_key        (0x40cc)
#define image_1_start_task_c_cpu_recycle_wakeup_request        (0x6568)
#define image_1_start_task_c_cpu_rx_wakeup_request        (0x66f8)
#define image_1_start_task_c_dhd_timer_wakeup_request        (0x3ec)
#define image_1_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x474)
#define image_1_start_task_c_dhd_tx_post_wakeup_request        (0x4b8)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_1_start_task_check_skip_cso        (0x406c)
#define image_1_start_task_cpu_recycle_int_coalescing        (0x66cc)
#define image_1_start_task_cpu_rx_int_coalescing        (0x7074)
#define image_1_start_task_cpu_rx_meter_budget_allocator        (0x70c0)
#define image_1_start_task_debug_routine        (0x30)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_1_start_task_dhd_tx_get_bq_index        (0x1320)
#define image_1_start_task_dhd_tx_post_drop_packet        (0x11f0)
#define image_1_start_task_dhd_tx_post_flow_ring_get_info        (0x102c)
#define image_1_start_task_dhd_tx_put_bq_index        (0x1390)
#define image_1_start_task_dos_attack_handler        (0x35f0)
#define image_1_start_task_drop_pkt_and_serial        (0x37e0)
#define image_1_start_task_dyn_code_func        (0x7c00)
#define image_1_start_task_flow_policer        (0x62b8)
#define image_1_start_task_general_timer_wakeup_request        (0x64f0)
#define image_1_start_task_get_pd_from_fifo        (0x71e0)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x41ec)
#define image_1_start_task_ingress_filter_action_point_update        (0x40f8)
#define image_1_start_task_ingress_filters_handler        (0x3970)
#define image_1_start_task_initialization_task        (0x8)
#define image_1_start_task_is_iptv_capable        (0x364c)
#define image_1_start_task_mcast_flow_master_lookup        (0x4144)
#define image_1_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_1_start_task_packet_cso_hw_offload        (0x7124)
#define image_1_start_task_parser_exception_handler        (0x340c)
#define image_1_start_task_proccessing_loopback        (0x3354)
#define image_1_start_task_processing_policer_action        (0x6308)
#define image_1_start_task_processing_wakeup_request        (0x13f8)
#define image_1_start_task_spdsvc_natc_lookup        (0x36ec)
#define image_1_start_task_ts_1588_handler        (0x393c)
#define image_1_start_task_tx_mirror        (0x6378)
#define image_1_start_task_xx_mirror_noinline        (0x3ca8)
#define image_1_ts_1588_handler        (0x393c)
#define image_1_tx_mirror        (0x6378)
#define image_1_xx_mirror_noinline        (0x3ca8)

#else

#define image_1_add_pbit_to_key        (0x1033)
#define image_1_c_cpu_recycle_wakeup_request        (0x195a)
#define image_1_c_cpu_rx_wakeup_request        (0x19be)
#define image_1_c_dhd_timer_wakeup_request        (0xfb)
#define image_1_c_dhd_tx_post_update_fifo_wakeup_request        (0x11d)
#define image_1_c_dhd_tx_post_wakeup_request        (0x12e)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_1_check_skip_cso        (0x101b)
#define image_1_cpu_recycle_int_coalescing        (0x19b3)
#define image_1_cpu_rx_int_coalescing        (0x1c1d)
#define image_1_cpu_rx_meter_budget_allocator        (0x1c30)
#define image_1_debug_routine        (0xc)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_1_dhd_tx_get_bq_index        (0x4c8)
#define image_1_dhd_tx_post_drop_packet        (0x47c)
#define image_1_dhd_tx_post_flow_ring_get_info        (0x40b)
#define image_1_dhd_tx_put_bq_index        (0x4e4)
#define image_1_dos_attack_handler        (0xd7c)
#define image_1_drop_pkt_and_serial        (0xdf8)
#define image_1_dyn_code_func        (0x1f00)
#define image_1_flow_policer        (0x18ae)
#define image_1_general_timer_wakeup_request        (0x193c)
#define image_1_get_pd_from_fifo        (0x1c78)
#define image_1_group_flow_lkp_and_fwd        (0x107b)
#define image_1_ingress_filter_action_point_update        (0x103e)
#define image_1_ingress_filters_handler        (0xe5c)
#define image_1_initialization_task        (0x2)
#define image_1_is_iptv_capable        (0xd93)
#define image_1_mcast_flow_master_lookup        (0x1051)
#define image_1_memcpy_abs_to_sbpm        (0x3e)
#define image_1_packet_cso_hw_offload        (0x1c49)
#define image_1_parser_exception_handler        (0xd03)
#define image_1_proccessing_loopback        (0xcd5)
#define image_1_processing_policer_action        (0x18c2)
#define image_1_processing_wakeup_request        (0x4fe)
#define image_1_spdsvc_natc_lookup        (0xdbb)
#define image_1_start_task_add_pbit_to_key        (0x1033)
#define image_1_start_task_c_cpu_recycle_wakeup_request        (0x195a)
#define image_1_start_task_c_cpu_rx_wakeup_request        (0x19be)
#define image_1_start_task_c_dhd_timer_wakeup_request        (0xfb)
#define image_1_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x11d)
#define image_1_start_task_c_dhd_tx_post_wakeup_request        (0x12e)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_1_start_task_check_skip_cso        (0x101b)
#define image_1_start_task_cpu_recycle_int_coalescing        (0x19b3)
#define image_1_start_task_cpu_rx_int_coalescing        (0x1c1d)
#define image_1_start_task_cpu_rx_meter_budget_allocator        (0x1c30)
#define image_1_start_task_debug_routine        (0xc)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_1_start_task_dhd_tx_get_bq_index        (0x4c8)
#define image_1_start_task_dhd_tx_post_drop_packet        (0x47c)
#define image_1_start_task_dhd_tx_post_flow_ring_get_info        (0x40b)
#define image_1_start_task_dhd_tx_put_bq_index        (0x4e4)
#define image_1_start_task_dos_attack_handler        (0xd7c)
#define image_1_start_task_drop_pkt_and_serial        (0xdf8)
#define image_1_start_task_dyn_code_func        (0x1f00)
#define image_1_start_task_flow_policer        (0x18ae)
#define image_1_start_task_general_timer_wakeup_request        (0x193c)
#define image_1_start_task_get_pd_from_fifo        (0x1c78)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x107b)
#define image_1_start_task_ingress_filter_action_point_update        (0x103e)
#define image_1_start_task_ingress_filters_handler        (0xe5c)
#define image_1_start_task_initialization_task        (0x2)
#define image_1_start_task_is_iptv_capable        (0xd93)
#define image_1_start_task_mcast_flow_master_lookup        (0x1051)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_1_start_task_packet_cso_hw_offload        (0x1c49)
#define image_1_start_task_parser_exception_handler        (0xd03)
#define image_1_start_task_proccessing_loopback        (0xcd5)
#define image_1_start_task_processing_policer_action        (0x18c2)
#define image_1_start_task_processing_wakeup_request        (0x4fe)
#define image_1_start_task_spdsvc_natc_lookup        (0xdbb)
#define image_1_start_task_ts_1588_handler        (0xe4f)
#define image_1_start_task_tx_mirror        (0x18de)
#define image_1_start_task_xx_mirror_noinline        (0xf2a)
#define image_1_ts_1588_handler        (0xe4f)
#define image_1_tx_mirror        (0x18de)
#define image_1_xx_mirror_noinline        (0xf2a)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2___umulsi3        (0x6acc)
#define image_2_add_pbit_to_key        (0x45a8)
#define image_2_c_cpu_recycle_wakeup_request        (0x68cc)
#define image_2_c_cpu_tx_wakeup_request        (0x4e0)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x4a4)
#define image_2_check_skip_cso        (0x4548)
#define image_2_cpu_recycle_int_coalescing        (0x6a30)
#define image_2_cpu_tx_send_pd_to_recycle        (0x17f0)
#define image_2_cpu_tx_sync_tasks        (0x18f4)
#define image_2_debug_routine        (0x30)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dos_attack_handler        (0x3acc)
#define image_2_drop_pkt_and_serial        (0x3cbc)
#define image_2_dyn_code_func        (0x7c00)
#define image_2_extension_header_prepend_required        (0x185c)
#define image_2_flow_policer        (0x6794)
#define image_2_general_timer_wakeup_request        (0x6854)
#define image_2_group_flow_lkp_and_fwd        (0x46c8)
#define image_2_ingress_filter_action_point_update        (0x45d4)
#define image_2_ingress_filters_handler        (0x3e4c)
#define image_2_initialization_task        (0x8)
#define image_2_is_iptv_capable        (0x3b28)
#define image_2_mcast_flow_master_lookup        (0x4620)
#define image_2_memcpy_abs_to_fpm        (0x2e0)
#define image_2_memcpy_abs_to_sbpm        (0xf8)
#define image_2_parser_exception_handler        (0x38e8)
#define image_2_prepend_fpm_extension_header        (0x1888)
#define image_2_proccessing_loopback        (0x3830)
#define image_2_processing_policer_action        (0x67e4)
#define image_2_processing_wakeup_request        (0x1914)
#define image_2_spdsvc_natc_lookup        (0x3bc8)
#define image_2_start_task___umulsi3        (0x6acc)
#define image_2_start_task_add_pbit_to_key        (0x45a8)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x68cc)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x4e0)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x4a4)
#define image_2_start_task_check_skip_cso        (0x4548)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x6a30)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x17f0)
#define image_2_start_task_cpu_tx_sync_tasks        (0x18f4)
#define image_2_start_task_debug_routine        (0x30)
#define image_2_start_task_dos_attack_handler        (0x3acc)
#define image_2_start_task_drop_pkt_and_serial        (0x3cbc)
#define image_2_start_task_dyn_code_func        (0x7c00)
#define image_2_start_task_extension_header_prepend_required        (0x185c)
#define image_2_start_task_flow_policer        (0x6794)
#define image_2_start_task_general_timer_wakeup_request        (0x6854)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x46c8)
#define image_2_start_task_ingress_filter_action_point_update        (0x45d4)
#define image_2_start_task_ingress_filters_handler        (0x3e4c)
#define image_2_start_task_initialization_task        (0x8)
#define image_2_start_task_is_iptv_capable        (0x3b28)
#define image_2_start_task_mcast_flow_master_lookup        (0x4620)
#define image_2_start_task_memcpy_abs_to_fpm        (0x2e0)
#define image_2_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_2_start_task_parser_exception_handler        (0x38e8)
#define image_2_start_task_prepend_fpm_extension_header        (0x1888)
#define image_2_start_task_proccessing_loopback        (0x3830)
#define image_2_start_task_processing_policer_action        (0x67e4)
#define image_2_start_task_processing_wakeup_request        (0x1914)
#define image_2_start_task_spdsvc_natc_lookup        (0x3bc8)
#define image_2_start_task_ts_1588_handler        (0x3e18)
#define image_2_start_task_xx_mirror_noinline        (0x4184)
#define image_2_ts_1588_handler        (0x3e18)
#define image_2_xx_mirror_noinline        (0x4184)

#else

#define image_2___umulsi3        (0x1ab3)
#define image_2_add_pbit_to_key        (0x116a)
#define image_2_c_cpu_recycle_wakeup_request        (0x1a33)
#define image_2_c_cpu_tx_wakeup_request        (0x138)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x129)
#define image_2_check_skip_cso        (0x1152)
#define image_2_cpu_recycle_int_coalescing        (0x1a8c)
#define image_2_cpu_tx_send_pd_to_recycle        (0x5fc)
#define image_2_cpu_tx_sync_tasks        (0x63d)
#define image_2_debug_routine        (0xc)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dos_attack_handler        (0xeb3)
#define image_2_drop_pkt_and_serial        (0xf2f)
#define image_2_dyn_code_func        (0x1f00)
#define image_2_extension_header_prepend_required        (0x617)
#define image_2_flow_policer        (0x19e5)
#define image_2_general_timer_wakeup_request        (0x1a15)
#define image_2_group_flow_lkp_and_fwd        (0x11b2)
#define image_2_ingress_filter_action_point_update        (0x1175)
#define image_2_ingress_filters_handler        (0xf93)
#define image_2_initialization_task        (0x2)
#define image_2_is_iptv_capable        (0xeca)
#define image_2_mcast_flow_master_lookup        (0x1188)
#define image_2_memcpy_abs_to_fpm        (0xb8)
#define image_2_memcpy_abs_to_sbpm        (0x3e)
#define image_2_parser_exception_handler        (0xe3a)
#define image_2_prepend_fpm_extension_header        (0x622)
#define image_2_proccessing_loopback        (0xe0c)
#define image_2_processing_policer_action        (0x19f9)
#define image_2_processing_wakeup_request        (0x645)
#define image_2_spdsvc_natc_lookup        (0xef2)
#define image_2_start_task___umulsi3        (0x1ab3)
#define image_2_start_task_add_pbit_to_key        (0x116a)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x1a33)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x138)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x129)
#define image_2_start_task_check_skip_cso        (0x1152)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x1a8c)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x5fc)
#define image_2_start_task_cpu_tx_sync_tasks        (0x63d)
#define image_2_start_task_debug_routine        (0xc)
#define image_2_start_task_dos_attack_handler        (0xeb3)
#define image_2_start_task_drop_pkt_and_serial        (0xf2f)
#define image_2_start_task_dyn_code_func        (0x1f00)
#define image_2_start_task_extension_header_prepend_required        (0x617)
#define image_2_start_task_flow_policer        (0x19e5)
#define image_2_start_task_general_timer_wakeup_request        (0x1a15)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x11b2)
#define image_2_start_task_ingress_filter_action_point_update        (0x1175)
#define image_2_start_task_ingress_filters_handler        (0xf93)
#define image_2_start_task_initialization_task        (0x2)
#define image_2_start_task_is_iptv_capable        (0xeca)
#define image_2_start_task_mcast_flow_master_lookup        (0x1188)
#define image_2_start_task_memcpy_abs_to_fpm        (0xb8)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_2_start_task_parser_exception_handler        (0xe3a)
#define image_2_start_task_prepend_fpm_extension_header        (0x622)
#define image_2_start_task_proccessing_loopback        (0xe0c)
#define image_2_start_task_processing_policer_action        (0x19f9)
#define image_2_start_task_processing_wakeup_request        (0x645)
#define image_2_start_task_spdsvc_natc_lookup        (0xef2)
#define image_2_start_task_ts_1588_handler        (0xf86)
#define image_2_start_task_xx_mirror_noinline        (0x1061)
#define image_2_ts_1588_handler        (0xf86)
#define image_2_xx_mirror_noinline        (0x1061)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3___umulsi3        (0x63a8)
#define image_3_add_pbit_to_key        (0x2fb8)
#define image_3_budget_allocator_tick        (0x58a8)
#define image_3_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x526c)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_3_check_skip_cso        (0x2f58)
#define image_3_debug_routine        (0x30)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dos_attack_handler        (0x24dc)
#define image_3_drop_pkt_and_serial        (0x26cc)
#define image_3_dualq_pi2_stats        (0x563c)
#define image_3_dyn_code_func        (0x7c00)
#define image_3_flow_policer        (0x51ac)
#define image_3_general_timer_wakeup_request        (0x59ec)
#define image_3_get_queue_delay        (0x55f8)
#define image_3_group_flow_lkp_and_fwd        (0x30d8)
#define image_3_ingress_filter_action_point_update        (0x2fe4)
#define image_3_ingress_filters_handler        (0x285c)
#define image_3_initialization_task        (0x8)
#define image_3_is_iptv_capable        (0x2538)
#define image_3_laqm_deque_check        (0x577c)
#define image_3_mcast_flow_master_lookup        (0x3030)
#define image_3_memcpy_abs_to_sbpm        (0xf8)
#define image_3_parser_exception_handler        (0x22f8)
#define image_3_pi2_deque_check        (0x56cc)
#define image_3_pi2_get_queue_delay        (0x548c)
#define image_3_pi2_probability_calc        (0x54f8)
#define image_3_pi2_timer        (0x53c0)
#define image_3_proccessing_loopback        (0x2240)
#define image_3_processing_policer_action        (0x51fc)
#define image_3_processing_wakeup_request        (0x31c)
#define image_3_spdsvc_natc_lookup        (0x25d8)
#define image_3_sq_tx_task_wakeup_request        (0x5b24)
#define image_3_start_task___umulsi3        (0x63a8)
#define image_3_start_task_add_pbit_to_key        (0x2fb8)
#define image_3_start_task_budget_allocator_tick        (0x58a8)
#define image_3_start_task_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x526c)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_3_start_task_check_skip_cso        (0x2f58)
#define image_3_start_task_debug_routine        (0x30)
#define image_3_start_task_dos_attack_handler        (0x24dc)
#define image_3_start_task_drop_pkt_and_serial        (0x26cc)
#define image_3_start_task_dualq_pi2_stats        (0x563c)
#define image_3_start_task_dyn_code_func        (0x7c00)
#define image_3_start_task_flow_policer        (0x51ac)
#define image_3_start_task_general_timer_wakeup_request        (0x59ec)
#define image_3_start_task_get_queue_delay        (0x55f8)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x30d8)
#define image_3_start_task_ingress_filter_action_point_update        (0x2fe4)
#define image_3_start_task_ingress_filters_handler        (0x285c)
#define image_3_start_task_initialization_task        (0x8)
#define image_3_start_task_is_iptv_capable        (0x2538)
#define image_3_start_task_laqm_deque_check        (0x577c)
#define image_3_start_task_mcast_flow_master_lookup        (0x3030)
#define image_3_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_3_start_task_parser_exception_handler        (0x22f8)
#define image_3_start_task_pi2_deque_check        (0x56cc)
#define image_3_start_task_pi2_get_queue_delay        (0x548c)
#define image_3_start_task_pi2_probability_calc        (0x54f8)
#define image_3_start_task_pi2_timer        (0x53c0)
#define image_3_start_task_proccessing_loopback        (0x2240)
#define image_3_start_task_processing_policer_action        (0x51fc)
#define image_3_start_task_processing_wakeup_request        (0x31c)
#define image_3_start_task_spdsvc_natc_lookup        (0x25d8)
#define image_3_start_task_sq_tx_task_wakeup_request        (0x5b24)
#define image_3_start_task_tm_tx_handle_rate_limit        (0x5a64)
#define image_3_start_task_ts_1588_handler        (0x2828)
#define image_3_start_task_xx_mirror_noinline        (0x2b94)
#define image_3_tm_tx_handle_rate_limit        (0x5a64)
#define image_3_ts_1588_handler        (0x2828)
#define image_3_xx_mirror_noinline        (0x2b94)

#else

#define image_3___umulsi3        (0x18ea)
#define image_3_add_pbit_to_key        (0xbee)
#define image_3_budget_allocator_tick        (0x162a)
#define image_3_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x149b)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_3_check_skip_cso        (0xbd6)
#define image_3_debug_routine        (0xc)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dos_attack_handler        (0x937)
#define image_3_drop_pkt_and_serial        (0x9b3)
#define image_3_dualq_pi2_stats        (0x158f)
#define image_3_dyn_code_func        (0x1f00)
#define image_3_flow_policer        (0x146b)
#define image_3_general_timer_wakeup_request        (0x167b)
#define image_3_get_queue_delay        (0x157e)
#define image_3_group_flow_lkp_and_fwd        (0xc36)
#define image_3_ingress_filter_action_point_update        (0xbf9)
#define image_3_ingress_filters_handler        (0xa17)
#define image_3_initialization_task        (0x2)
#define image_3_is_iptv_capable        (0x94e)
#define image_3_laqm_deque_check        (0x15df)
#define image_3_mcast_flow_master_lookup        (0xc0c)
#define image_3_memcpy_abs_to_sbpm        (0x3e)
#define image_3_parser_exception_handler        (0x8be)
#define image_3_pi2_deque_check        (0x15b3)
#define image_3_pi2_get_queue_delay        (0x1523)
#define image_3_pi2_probability_calc        (0x153e)
#define image_3_pi2_timer        (0x14f0)
#define image_3_proccessing_loopback        (0x890)
#define image_3_processing_policer_action        (0x147f)
#define image_3_processing_wakeup_request        (0xc7)
#define image_3_spdsvc_natc_lookup        (0x976)
#define image_3_sq_tx_task_wakeup_request        (0x16c9)
#define image_3_start_task___umulsi3        (0x18ea)
#define image_3_start_task_add_pbit_to_key        (0xbee)
#define image_3_start_task_budget_allocator_tick        (0x162a)
#define image_3_start_task_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x149b)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_3_start_task_check_skip_cso        (0xbd6)
#define image_3_start_task_debug_routine        (0xc)
#define image_3_start_task_dos_attack_handler        (0x937)
#define image_3_start_task_drop_pkt_and_serial        (0x9b3)
#define image_3_start_task_dualq_pi2_stats        (0x158f)
#define image_3_start_task_dyn_code_func        (0x1f00)
#define image_3_start_task_flow_policer        (0x146b)
#define image_3_start_task_general_timer_wakeup_request        (0x167b)
#define image_3_start_task_get_queue_delay        (0x157e)
#define image_3_start_task_group_flow_lkp_and_fwd        (0xc36)
#define image_3_start_task_ingress_filter_action_point_update        (0xbf9)
#define image_3_start_task_ingress_filters_handler        (0xa17)
#define image_3_start_task_initialization_task        (0x2)
#define image_3_start_task_is_iptv_capable        (0x94e)
#define image_3_start_task_laqm_deque_check        (0x15df)
#define image_3_start_task_mcast_flow_master_lookup        (0xc0c)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_3_start_task_parser_exception_handler        (0x8be)
#define image_3_start_task_pi2_deque_check        (0x15b3)
#define image_3_start_task_pi2_get_queue_delay        (0x1523)
#define image_3_start_task_pi2_probability_calc        (0x153e)
#define image_3_start_task_pi2_timer        (0x14f0)
#define image_3_start_task_proccessing_loopback        (0x890)
#define image_3_start_task_processing_policer_action        (0x147f)
#define image_3_start_task_processing_wakeup_request        (0xc7)
#define image_3_start_task_spdsvc_natc_lookup        (0x976)
#define image_3_start_task_sq_tx_task_wakeup_request        (0x16c9)
#define image_3_start_task_tm_tx_handle_rate_limit        (0x1699)
#define image_3_start_task_ts_1588_handler        (0xa0a)
#define image_3_start_task_xx_mirror_noinline        (0xae5)
#define image_3_tm_tx_handle_rate_limit        (0x1699)
#define image_3_ts_1588_handler        (0xa0a)
#define image_3_xx_mirror_noinline        (0xae5)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4___umulsi3        (0x17bc)
#define image_4_budget_allocator_tick        (0xf8)
#define image_4_debug_routine        (0x30)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dualq_pi2_stats        (0x13c0)
#define image_4_dyn_code_func        (0x8000)
#define image_4_general_timer_wakeup_request        (0x1198)
#define image_4_get_queue_delay        (0x137c)
#define image_4_ghost_reporting_wakeup_request        (0x1450)
#define image_4_handle_flush        (0x4fc)
#define image_4_initialization_task        (0x8)
#define image_4_laqm_deque_check        (0xe54)
#define image_4_pi2_deque_check        (0xda4)
#define image_4_pi2_get_queue_delay        (0x1210)
#define image_4_pi2_probability_calc        (0x127c)
#define image_4_pi2_timer        (0x23c)
#define image_4_start_task___umulsi3        (0x17bc)
#define image_4_start_task_budget_allocator_tick        (0xf8)
#define image_4_start_task_debug_routine        (0x30)
#define image_4_start_task_dualq_pi2_stats        (0x13c0)
#define image_4_start_task_dyn_code_func        (0x8000)
#define image_4_start_task_general_timer_wakeup_request        (0x1198)
#define image_4_start_task_get_queue_delay        (0x137c)
#define image_4_start_task_ghost_reporting_wakeup_request        (0x1450)
#define image_4_start_task_handle_flush        (0x4fc)
#define image_4_start_task_initialization_task        (0x8)
#define image_4_start_task_laqm_deque_check        (0xe54)
#define image_4_start_task_pi2_deque_check        (0xda4)
#define image_4_start_task_pi2_get_queue_delay        (0x1210)
#define image_4_start_task_pi2_probability_calc        (0x127c)
#define image_4_start_task_pi2_timer        (0x23c)
#define image_4_start_task_tm_tx_handle_rate_limit        (0x300)
#define image_4_start_task_tm_tx_mirroring_handle        (0xf80)
#define image_4_start_task_tm_tx_task_wakeup_request        (0x5fc)
#define image_4_start_task_tm_update_fifo_first_wakeup_request        (0x3c0)
#define image_4_start_task_tx_mirror        (0x1020)
#define image_4_tm_tx_handle_rate_limit        (0x300)
#define image_4_tm_tx_mirroring_handle        (0xf80)
#define image_4_tm_tx_task_wakeup_request        (0x5fc)
#define image_4_tm_update_fifo_first_wakeup_request        (0x3c0)
#define image_4_tx_mirror        (0x1020)

#else

#define image_4___umulsi3        (0x5ef)
#define image_4_budget_allocator_tick        (0x3e)
#define image_4_debug_routine        (0xc)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dualq_pi2_stats        (0x4f0)
#define image_4_dyn_code_func        (0x2000)
#define image_4_general_timer_wakeup_request        (0x466)
#define image_4_get_queue_delay        (0x4df)
#define image_4_ghost_reporting_wakeup_request        (0x514)
#define image_4_handle_flush        (0x13f)
#define image_4_initialization_task        (0x2)
#define image_4_laqm_deque_check        (0x395)
#define image_4_pi2_deque_check        (0x369)
#define image_4_pi2_get_queue_delay        (0x484)
#define image_4_pi2_probability_calc        (0x49f)
#define image_4_pi2_timer        (0x8f)
#define image_4_start_task___umulsi3        (0x5ef)
#define image_4_start_task_budget_allocator_tick        (0x3e)
#define image_4_start_task_debug_routine        (0xc)
#define image_4_start_task_dualq_pi2_stats        (0x4f0)
#define image_4_start_task_dyn_code_func        (0x2000)
#define image_4_start_task_general_timer_wakeup_request        (0x466)
#define image_4_start_task_get_queue_delay        (0x4df)
#define image_4_start_task_ghost_reporting_wakeup_request        (0x514)
#define image_4_start_task_handle_flush        (0x13f)
#define image_4_start_task_initialization_task        (0x2)
#define image_4_start_task_laqm_deque_check        (0x395)
#define image_4_start_task_pi2_deque_check        (0x369)
#define image_4_start_task_pi2_get_queue_delay        (0x484)
#define image_4_start_task_pi2_probability_calc        (0x49f)
#define image_4_start_task_pi2_timer        (0x8f)
#define image_4_start_task_tm_tx_handle_rate_limit        (0xc0)
#define image_4_start_task_tm_tx_mirroring_handle        (0x3e0)
#define image_4_start_task_tm_tx_task_wakeup_request        (0x17f)
#define image_4_start_task_tm_update_fifo_first_wakeup_request        (0xf0)
#define image_4_start_task_tx_mirror        (0x408)
#define image_4_tm_tx_handle_rate_limit        (0xc0)
#define image_4_tm_tx_mirroring_handle        (0x3e0)
#define image_4_tm_tx_task_wakeup_request        (0x17f)
#define image_4_tm_update_fifo_first_wakeup_request        (0xf0)
#define image_4_tx_mirror        (0x408)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5_add_pbit_to_key        (0x4714)
#define image_5_c_common_reprocessing_wakeup_request        (0x69c0)
#define image_5_c_spdsvc_gen_wakeup_request        (0x6b5c)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x1a44)
#define image_5_check_skip_cso        (0x46b4)
#define image_5_debug_routine        (0x30)
#define image_5_debug_routine_handler        (0x4)
#define image_5_dos_attack_handler        (0x3c38)
#define image_5_drop_pkt_and_serial        (0x3e28)
#define image_5_dyn_code_func        (0x7c00)
#define image_5_flow_policer        (0x6900)
#define image_5_group_flow_lkp_and_fwd        (0x4834)
#define image_5_ingress_filter_action_point_update        (0x4740)
#define image_5_ingress_filters_handler        (0x3fb8)
#define image_5_initialization_task        (0x8)
#define image_5_is_iptv_capable        (0x3c94)
#define image_5_mcast_flow_master_lookup        (0x478c)
#define image_5_memcpy_abs_to_sbpm        (0x185c)
#define image_5_parser_exception_handler        (0x3a54)
#define image_5_proccessing_loopback        (0x399c)
#define image_5_processing_policer_action        (0x6950)
#define image_5_processing_wakeup_request        (0x1a80)
#define image_5_spdsvc_natc_lookup        (0x3d34)
#define image_5_start_task_add_pbit_to_key        (0x4714)
#define image_5_start_task_c_common_reprocessing_wakeup_request        (0x69c0)
#define image_5_start_task_c_spdsvc_gen_wakeup_request        (0x6b5c)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x1a44)
#define image_5_start_task_check_skip_cso        (0x46b4)
#define image_5_start_task_debug_routine        (0x30)
#define image_5_start_task_dos_attack_handler        (0x3c38)
#define image_5_start_task_drop_pkt_and_serial        (0x3e28)
#define image_5_start_task_dyn_code_func        (0x7c00)
#define image_5_start_task_flow_policer        (0x6900)
#define image_5_start_task_group_flow_lkp_and_fwd        (0x4834)
#define image_5_start_task_ingress_filter_action_point_update        (0x4740)
#define image_5_start_task_ingress_filters_handler        (0x3fb8)
#define image_5_start_task_initialization_task        (0x8)
#define image_5_start_task_is_iptv_capable        (0x3c94)
#define image_5_start_task_mcast_flow_master_lookup        (0x478c)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x185c)
#define image_5_start_task_parser_exception_handler        (0x3a54)
#define image_5_start_task_proccessing_loopback        (0x399c)
#define image_5_start_task_processing_policer_action        (0x6950)
#define image_5_start_task_processing_wakeup_request        (0x1a80)
#define image_5_start_task_spdsvc_natc_lookup        (0x3d34)
#define image_5_start_task_tcpspdtest_gen_wakeup_request        (0xaf8)
#define image_5_start_task_tcpspdtest_wakeup_request        (0x2b0)
#define image_5_start_task_ts_1588_handler        (0x3f84)
#define image_5_start_task_xx_mirror_noinline        (0x42f0)
#define image_5_tcpspdtest_gen_wakeup_request        (0xaf8)
#define image_5_tcpspdtest_task_upload_init        (0xaf8)
#define image_5_tcpspdtest_wakeup_request        (0x2b0)
#define image_5_ts_1588_handler        (0x3f84)
#define image_5_xx_mirror_noinline        (0x42f0)

#else

#define image_5_add_pbit_to_key        (0x11c5)
#define image_5_c_common_reprocessing_wakeup_request        (0x1a70)
#define image_5_c_spdsvc_gen_wakeup_request        (0x1ad7)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x691)
#define image_5_check_skip_cso        (0x11ad)
#define image_5_debug_routine        (0xc)
#define image_5_debug_routine_handler        (0x1)
#define image_5_dos_attack_handler        (0xf0e)
#define image_5_drop_pkt_and_serial        (0xf8a)
#define image_5_dyn_code_func        (0x1f00)
#define image_5_flow_policer        (0x1a40)
#define image_5_group_flow_lkp_and_fwd        (0x120d)
#define image_5_ingress_filter_action_point_update        (0x11d0)
#define image_5_ingress_filters_handler        (0xfee)
#define image_5_initialization_task        (0x2)
#define image_5_is_iptv_capable        (0xf25)
#define image_5_mcast_flow_master_lookup        (0x11e3)
#define image_5_memcpy_abs_to_sbpm        (0x617)
#define image_5_parser_exception_handler        (0xe95)
#define image_5_proccessing_loopback        (0xe67)
#define image_5_processing_policer_action        (0x1a54)
#define image_5_processing_wakeup_request        (0x6a0)
#define image_5_spdsvc_natc_lookup        (0xf4d)
#define image_5_start_task_add_pbit_to_key        (0x11c5)
#define image_5_start_task_c_common_reprocessing_wakeup_request        (0x1a70)
#define image_5_start_task_c_spdsvc_gen_wakeup_request        (0x1ad7)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x691)
#define image_5_start_task_check_skip_cso        (0x11ad)
#define image_5_start_task_debug_routine        (0xc)
#define image_5_start_task_dos_attack_handler        (0xf0e)
#define image_5_start_task_drop_pkt_and_serial        (0xf8a)
#define image_5_start_task_dyn_code_func        (0x1f00)
#define image_5_start_task_flow_policer        (0x1a40)
#define image_5_start_task_group_flow_lkp_and_fwd        (0x120d)
#define image_5_start_task_ingress_filter_action_point_update        (0x11d0)
#define image_5_start_task_ingress_filters_handler        (0xfee)
#define image_5_start_task_initialization_task        (0x2)
#define image_5_start_task_is_iptv_capable        (0xf25)
#define image_5_start_task_mcast_flow_master_lookup        (0x11e3)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x617)
#define image_5_start_task_parser_exception_handler        (0xe95)
#define image_5_start_task_proccessing_loopback        (0xe67)
#define image_5_start_task_processing_policer_action        (0x1a54)
#define image_5_start_task_processing_wakeup_request        (0x6a0)
#define image_5_start_task_spdsvc_natc_lookup        (0xf4d)
#define image_5_start_task_tcpspdtest_gen_wakeup_request        (0x2be)
#define image_5_start_task_tcpspdtest_wakeup_request        (0xac)
#define image_5_start_task_ts_1588_handler        (0xfe1)
#define image_5_start_task_xx_mirror_noinline        (0x10bc)
#define image_5_tcpspdtest_gen_wakeup_request        (0x2be)
#define image_5_tcpspdtest_task_upload_init        (0x2be)
#define image_5_tcpspdtest_wakeup_request        (0xac)
#define image_5_ts_1588_handler        (0xfe1)
#define image_5_xx_mirror_noinline        (0x10bc)

#endif


#endif

/* IMAGE 6 LABELS */
#ifndef IMAGE_6_CODE_ADDRESSES
#define IMAGE_6_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_6___umulsi3        (0x23bc)
#define image_6_budget_allocator_tick        (0xc78)
#define image_6_c_spdsvc_analyzer_wakeup_request        (0x1eb4)
#define image_6_debug_routine        (0x30)
#define image_6_debug_routine_handler        (0x4)
#define image_6_direct_flow_wakeup_request        (0x2e0)
#define image_6_dualq_pi2_stats        (0xa0c)
#define image_6_dyn_code_func        (0x8000)
#define image_6_epon_tm_tx        (0x1ac4)
#define image_6_epon_tm_tx_credit_free        (0x1e04)
#define image_6_epon_tm_tx_task_wakeup_request        (0x1cf4)
#define image_6_epon_tm_update_fifo_first_wakeup_request        (0x1ca8)
#define image_6_general_timer_wakeup_request        (0x1e3c)
#define image_6_get_queue_delay        (0x9c8)
#define image_6_handle_flush        (0x10d4)
#define image_6_initialization_task        (0x8)
#define image_6_laqm_deque_check        (0xb4c)
#define image_6_memcpy_abs_to_sbpm        (0xf8)
#define image_6_pi2_deque_check        (0xa9c)
#define image_6_pi2_get_queue_delay        (0x85c)
#define image_6_pi2_probability_calc        (0x8c8)
#define image_6_pi2_timer        (0x798)
#define image_6_spdt_brcm_spdsvc_rx_handler        (0x227c)
#define image_6_spdt_udp_basic_rx_handler        (0x1fe8)
#define image_6_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x2350)
#define image_6_spdt_udp_iperf3_rx_handler        (0x209c)
#define image_6_spdt_unsupported_proto_rx_handler        (0x22ec)
#define image_6_start_task___umulsi3        (0x23bc)
#define image_6_start_task_budget_allocator_tick        (0xc78)
#define image_6_start_task_c_spdsvc_analyzer_wakeup_request        (0x1eb4)
#define image_6_start_task_debug_routine        (0x30)
#define image_6_start_task_direct_flow_wakeup_request        (0x2e0)
#define image_6_start_task_dualq_pi2_stats        (0xa0c)
#define image_6_start_task_dyn_code_func        (0x8000)
#define image_6_start_task_epon_tm_tx        (0x1ac4)
#define image_6_start_task_epon_tm_tx_credit_free        (0x1e04)
#define image_6_start_task_epon_tm_tx_task_wakeup_request        (0x1cf4)
#define image_6_start_task_epon_tm_update_fifo_first_wakeup_request        (0x1ca8)
#define image_6_start_task_general_timer_wakeup_request        (0x1e3c)
#define image_6_start_task_get_queue_delay        (0x9c8)
#define image_6_start_task_handle_flush        (0x10d4)
#define image_6_start_task_initialization_task        (0x8)
#define image_6_start_task_laqm_deque_check        (0xb4c)
#define image_6_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_6_start_task_pi2_deque_check        (0xa9c)
#define image_6_start_task_pi2_get_queue_delay        (0x85c)
#define image_6_start_task_pi2_probability_calc        (0x8c8)
#define image_6_start_task_pi2_timer        (0x798)
#define image_6_start_task_spdt_brcm_spdsvc_rx_handler        (0x227c)
#define image_6_start_task_spdt_udp_basic_rx_handler        (0x1fe8)
#define image_6_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x2350)
#define image_6_start_task_spdt_udp_iperf3_rx_handler        (0x209c)
#define image_6_start_task_spdt_unsupported_proto_rx_handler        (0x22ec)
#define image_6_start_task_tm_tx_dbg_stat_by_size        (0xeac)
#define image_6_start_task_tm_tx_dbg_stat_get_cntr_id        (0xe7c)
#define image_6_start_task_tm_tx_handle_rate_limit        (0xdbc)
#define image_6_start_task_tm_tx_mirroring_handle        (0x1a04)
#define image_6_start_task_tm_tx_task_wakeup_request        (0x11d4)
#define image_6_start_task_tm_update_fifo_first_wakeup_request        (0xf98)
#define image_6_start_task_tx_mirror        (0x1b30)
#define image_6_tm_tx_dbg_stat_by_size        (0xeac)
#define image_6_tm_tx_dbg_stat_get_cntr_id        (0xe7c)
#define image_6_tm_tx_handle_rate_limit        (0xdbc)
#define image_6_tm_tx_mirroring_handle        (0x1a04)
#define image_6_tm_tx_task_wakeup_request        (0x11d4)
#define image_6_tm_update_fifo_first_wakeup_request        (0xf98)
#define image_6_tx_mirror        (0x1b30)

#else

#define image_6___umulsi3        (0x8ef)
#define image_6_budget_allocator_tick        (0x31e)
#define image_6_c_spdsvc_analyzer_wakeup_request        (0x7ad)
#define image_6_debug_routine        (0xc)
#define image_6_debug_routine_handler        (0x1)
#define image_6_direct_flow_wakeup_request        (0xb8)
#define image_6_dualq_pi2_stats        (0x283)
#define image_6_dyn_code_func        (0x2000)
#define image_6_epon_tm_tx        (0x6b1)
#define image_6_epon_tm_tx_credit_free        (0x781)
#define image_6_epon_tm_tx_task_wakeup_request        (0x73d)
#define image_6_epon_tm_update_fifo_first_wakeup_request        (0x72a)
#define image_6_general_timer_wakeup_request        (0x78f)
#define image_6_get_queue_delay        (0x272)
#define image_6_handle_flush        (0x435)
#define image_6_initialization_task        (0x2)
#define image_6_laqm_deque_check        (0x2d3)
#define image_6_memcpy_abs_to_sbpm        (0x3e)
#define image_6_pi2_deque_check        (0x2a7)
#define image_6_pi2_get_queue_delay        (0x217)
#define image_6_pi2_probability_calc        (0x232)
#define image_6_pi2_timer        (0x1e6)
#define image_6_spdt_brcm_spdsvc_rx_handler        (0x89f)
#define image_6_spdt_udp_basic_rx_handler        (0x7fa)
#define image_6_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x8d4)
#define image_6_spdt_udp_iperf3_rx_handler        (0x827)
#define image_6_spdt_unsupported_proto_rx_handler        (0x8bb)
#define image_6_start_task___umulsi3        (0x8ef)
#define image_6_start_task_budget_allocator_tick        (0x31e)
#define image_6_start_task_c_spdsvc_analyzer_wakeup_request        (0x7ad)
#define image_6_start_task_debug_routine        (0xc)
#define image_6_start_task_direct_flow_wakeup_request        (0xb8)
#define image_6_start_task_dualq_pi2_stats        (0x283)
#define image_6_start_task_dyn_code_func        (0x2000)
#define image_6_start_task_epon_tm_tx        (0x6b1)
#define image_6_start_task_epon_tm_tx_credit_free        (0x781)
#define image_6_start_task_epon_tm_tx_task_wakeup_request        (0x73d)
#define image_6_start_task_epon_tm_update_fifo_first_wakeup_request        (0x72a)
#define image_6_start_task_general_timer_wakeup_request        (0x78f)
#define image_6_start_task_get_queue_delay        (0x272)
#define image_6_start_task_handle_flush        (0x435)
#define image_6_start_task_initialization_task        (0x2)
#define image_6_start_task_laqm_deque_check        (0x2d3)
#define image_6_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_6_start_task_pi2_deque_check        (0x2a7)
#define image_6_start_task_pi2_get_queue_delay        (0x217)
#define image_6_start_task_pi2_probability_calc        (0x232)
#define image_6_start_task_pi2_timer        (0x1e6)
#define image_6_start_task_spdt_brcm_spdsvc_rx_handler        (0x89f)
#define image_6_start_task_spdt_udp_basic_rx_handler        (0x7fa)
#define image_6_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x8d4)
#define image_6_start_task_spdt_udp_iperf3_rx_handler        (0x827)
#define image_6_start_task_spdt_unsupported_proto_rx_handler        (0x8bb)
#define image_6_start_task_tm_tx_dbg_stat_by_size        (0x3ab)
#define image_6_start_task_tm_tx_dbg_stat_get_cntr_id        (0x39f)
#define image_6_start_task_tm_tx_handle_rate_limit        (0x36f)
#define image_6_start_task_tm_tx_mirroring_handle        (0x681)
#define image_6_start_task_tm_tx_task_wakeup_request        (0x475)
#define image_6_start_task_tm_update_fifo_first_wakeup_request        (0x3e6)
#define image_6_start_task_tx_mirror        (0x6cc)
#define image_6_tm_tx_dbg_stat_by_size        (0x3ab)
#define image_6_tm_tx_dbg_stat_get_cntr_id        (0x39f)
#define image_6_tm_tx_handle_rate_limit        (0x36f)
#define image_6_tm_tx_mirroring_handle        (0x681)
#define image_6_tm_tx_task_wakeup_request        (0x475)
#define image_6_tm_update_fifo_first_wakeup_request        (0x3e6)
#define image_6_tx_mirror        (0x6cc)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND


#else


#endif


#endif

