/***********************************************************************
 *
 *
<:copyright-BRCM:2022:proprietary:standard

   Copyright (c) 2022 Broadcom
   All Rights Reserved

 This program is the proprietary software of Broadcom and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").  Except as set forth in
 an Authorized License, Broadcom grants no license (express or implied), right
 to use, or waiver of any kind with respect to the Software, and Broadcom
 expressly reserves all rights in and to the Software and all intellectual
 property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU HAVE
 NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY
 BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

 Except as expressly set forth in the Authorized License,

 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use
    all reasonable efforts to protect the confidentiality thereof, and to
    use this information only in connection with your use of Broadcom
    integrated circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
    RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND
    ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT,
    FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR
    COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE
    TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR
    PERFORMANCE OF THE SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR
    ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
    INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY
    WAY RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN
    IF BROADCOM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES;
    OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE
    SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE LIMITATIONS
    SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY
    LIMITED REMEDY.
:>
 *
 ************************************************************************/


#ifdef DMP_USPAGENT_1


#include "cms.h"
#include "bcm_ulog.h"
#include "cms_util.h"
#include "cms_core.h"
#include "rcl.h"
#include "rut_util.h"
#include "mdm.h"


/* This file contains RCLs for USPAgent Controller which is used by ACS
 * (CWMP) to configure USP (Device.LocalAgent.Controller)'s configuration.
 */


extern CmsRet replaceUSPAgentWithLocalAgent
   (const char *input, char *output, int outputLen);


static CmsRet addInstance
   (const MdmObjectId oid, const InstanceIdStack *uspIidStack, void *uspObj)
{
   CmsRet ret = CMSRET_SUCCESS;
   char buff[BUFLEN_64+1]={0};
   InstanceIdStack iidStack;

   /* Do not add new LocalAgent instance at boot up */
   if (mdmShmCtx->inMdmInit == TRUE)
   {
      return ret;
   }

   if (uspIidStack == NULL || uspObj == NULL)
   {
      return CMSRET_INVALID_ARGUMENTS;
   }

   INIT_INSTANCE_ID_STACK(&iidStack);

   switch (oid)
   {
      case MDMOID_USP_AGENT_CONTROLLER:
      {
         Dev2USPAgentControllerObject *obj = (Dev2USPAgentControllerObject *) uspObj;
         Dev2LocalagentControllerObject *localObj = NULL;

         /* add new instance of local agent controller */
         ret = cmsObj_addInstance(MDMOID_DEV2_LOCALAGENT_CONTROLLER, &iidStack);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Could not create new local agent controller, ret=%d", ret);
            return ret;
         }

         /* get the instance of local agent controller */
         ret = cmsObj_get(MDMOID_DEV2_LOCALAGENT_CONTROLLER, &iidStack, 0, (void **) &localObj);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Failed to get Dev2LocalagentControllerObject, ret=%d", ret);
            return ret;
         }

         /* At controller instance addition, the alias is autogenerated
          * already; and it's not supposed to be modified once set.
          * But uspAgent uses the alias field to remember which one it
          * created by adding "-cwmp" at the end of it. There is no
          * mechanism to pass in the alias at instance add at the moment.
          * If problem arises, a new proprietary parameter can be added
          * for the propose of mapping USPAgent with LocalAgent's
          * instance created by an ACS.
          */
         snprintf(buff, sizeof(buff), "%s-cwmp", localObj->alias);
         REPLACE_STRING_IF_NOT_EQUAL_FLAGS(obj->alias, buff,
                                           mdmLibCtx.allocFlags);

         /* free local agent controller */
         cmsObj_free((void **) &localObj);

         /* set usp agent controller */
         ret = cmsObj_set(obj, uspIidStack);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Failed to set Dev2USPAgentControllerObject, ret=%d", ret);
         }
      }
         break;

      case MDMOID_USP_AGENT_CONTROLLER_MTP:
      {
         UBOOL8 found = FALSE;
         Dev2USPAgentControllerMtpObject *mtpObj = (Dev2USPAgentControllerMtpObject *) uspObj;
         Dev2USPAgentControllerObject *cntrlObj = NULL;
         Dev2LocalagentControllerObject *localCntrlObj = NULL;
         Dev2LocalagentControllerMtpObject *localMtpObj = NULL;
         InstanceIdStack mtpIidStack = *uspIidStack;

         /* get Dev2USPAgentControllerObject parent of Dev2USPAgentControllerMtpObject */
         ret = cmsObj_getAncestor(MDMOID_USP_AGENT_CONTROLLER,
                                  MDMOID_USP_AGENT_CONTROLLER_MTP,
                                  &mtpIidStack,
                                  (void **)&cntrlObj);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Could not get usp agent controller, ret=%d", ret);
            return ret;
         }

         /* look for Dev2LocalagentControllerObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextFlags(MDMOID_DEV2_LOCALAGENT_CONTROLLER,
                                    &iidStack,
                                    OGF_NO_VALUE_UPDATE,
                                    (void **)&localCntrlObj) == CMSRET_SUCCESS)
         {
            if (strstr(cntrlObj->alias, localCntrlObj->alias) != NULL)
            {
               found = TRUE;
            }

            /* free local agent controller */
            cmsObj_free((void **) &localCntrlObj);
         }

         /* free usp agent controller */
         cmsObj_free((void **) &cntrlObj);

         if (found == FALSE)
         {
            cmsLog_error("Could not find parent of local agent controller mtp, ret=%d", ret);
            return CMSRET_OBJECT_NOT_FOUND;
         }

         /* add new instance of local agent controller MTP */
         ret = cmsObj_addInstance(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP, &iidStack);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Could not create new local agent controller mtp, ret=%d", ret);
            return ret;
         }

         /* get the instance of local agent controller MTP */
         ret = cmsObj_get(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP, &iidStack, 0, (void **) &localMtpObj);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Failed to get Dev2LocalagentControllerMtpObject, ret=%d", ret);
            return ret;
         }

         /* At MTP instance addition, the alias is autogenerated
          * already; and it's not supposed to be modified once set.
          * But uspAgent uses the alias field to remember which one it
          * created by adding "-cwmp" at the end of it. There is no
          * mechanism to pass in the alias at instance add at the moment.
          * If problem arises, a new proprietary parameter can be added
          * for the propose of mapping USPAgent with LocalAgent's
          * instance created by an ACS.
          */
         snprintf(buff, sizeof(buff), "%s-cwmp", localMtpObj->alias);
         REPLACE_STRING_IF_NOT_EQUAL_FLAGS(mtpObj->alias, buff,
                                           mdmLibCtx.allocFlags);

         /* free local agent controller MTP */
         cmsObj_free((void **) &localMtpObj);

         /* set usp agent controller MTP */
         ret = cmsObj_set(mtpObj, uspIidStack);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Failed to set Dev2USPAgentControllerMtpObject, ret=%d", ret);
         }
      }
         break;

      default:
         break;
   }

   return ret;
}


static CmsRet updateInstance
   (const MdmObjectId oid, const InstanceIdStack *uspIidStack, const void *uspObj)
{
   CmsRet ret = CMSRET_SUCCESS;
   UBOOL8 found = FALSE;
   InstanceIdStack iidStack;

   if (uspIidStack == NULL || uspObj == NULL)
   {
      return CMSRET_INVALID_ARGUMENTS;
   }

   INIT_INSTANCE_ID_STACK(&iidStack);

   switch (oid)
   {
      case MDMOID_USP_AGENT_CONTROLLER:
      {
         Dev2USPAgentControllerObject *obj = (Dev2USPAgentControllerObject *) uspObj;
         Dev2LocalagentControllerObject *localObj = NULL;
         char buf[BUFLEN_1024] = {0};

         /* look for Dev2LocalagentControllerObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextFlags(MDMOID_DEV2_LOCALAGENT_CONTROLLER,
                                    &iidStack,
                                    OGF_NO_VALUE_UPDATE,
                                    (void **)&localObj) == CMSRET_SUCCESS)
         {
            if (strstr(obj->alias, localObj->alias) != NULL)
            {
               found = TRUE;
               break;
            }

            /* free local agent controller that is not matched */
            cmsObj_free((void **) &localObj);
         }

         if (found == TRUE && localObj != NULL)
         {
            localObj->enable = obj->enable;
            localObj->periodicNotifInterval = obj->periodicNotifInterval;
            localObj->USPNotifRetryMinimumWaitInterval = obj->USPNotifRetryMinimumWaitInterval;
            localObj->USPNotifRetryIntervalMultiplier = obj->USPNotifRetryIntervalMultiplier;
            REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
               localObj->endpointID, obj->endpointID,
               mdmLibCtx.allocFlags);
            REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
               localObj->controllerCode, obj->controllerCode,
               mdmLibCtx.allocFlags);
            REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
               localObj->provisioningCode, obj->provisioningCode,
               mdmLibCtx.allocFlags);
            replaceUSPAgentWithLocalAgent(obj->assignedRole, buf, sizeof(buf)-1);
            REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
               localObj->assignedRole, buf,
               mdmLibCtx.allocFlags);
            REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
               localObj->credential, obj->credential,
               mdmLibCtx.allocFlags);
            REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
               localObj->periodicNotifTime, obj->periodicNotifTime,
               mdmLibCtx.allocFlags);

            /* set local agent controller */
            ret = cmsObj_set(localObj, &iidStack);
            if (ret != CMSRET_SUCCESS)
            {
               cmsLog_error("Failed to set Dev2LocalagentControllerObject, ret=%d", ret);
            }

            /* free local agent controller */
            cmsObj_free((void **) &localObj);
         }
      }
         break;

      case MDMOID_USP_AGENT_CONTROLLER_MTP:
      {
         Dev2USPAgentControllerMtpObject *mtpObj = (Dev2USPAgentControllerMtpObject *) uspObj;
         Dev2USPAgentControllerObject *cntrlObj = NULL;
         Dev2LocalagentControllerObject *localCntrlObj = NULL;
         Dev2LocalagentControllerMtpObject *localMtpObj = NULL;
         InstanceIdStack mtpIidStack = *uspIidStack;

         /* get Dev2USPAgentControllerObject parent of Dev2USPAgentControllerMtpObject */
         ret = cmsObj_getAncestor(MDMOID_USP_AGENT_CONTROLLER,
                                  MDMOID_USP_AGENT_CONTROLLER_MTP,
                                  &mtpIidStack,
                                  (void **)&cntrlObj);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Could not get usp agent controller, ret=%d", ret);
            return ret;
         }

         /* look for Dev2LocalagentControllerObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextFlags(MDMOID_DEV2_LOCALAGENT_CONTROLLER,
                                    &iidStack,
                                    OGF_NO_VALUE_UPDATE,
                                    (void **)&localCntrlObj) == CMSRET_SUCCESS)
         {
            if (strstr(cntrlObj->alias, localCntrlObj->alias) != NULL)
            {
               found = TRUE;
            }

            /* free local agent controller */
            cmsObj_free((void **) &localCntrlObj);
         }

         /* free usp agent controller */
         cmsObj_free((void **) &cntrlObj);

         if (found == FALSE)
         {
            cmsLog_error("Could not find parent of local agent controller mtp, ret=%d", ret);
            return CMSRET_OBJECT_NOT_FOUND;
         }

         found = FALSE;
         INIT_INSTANCE_ID_STACK(&mtpIidStack);

         /* look for Dev2LocalagentControllerMtpObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextInSubTree(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP,
                                        &iidStack, &mtpIidStack,
                                        (void **)&localMtpObj) == CMSRET_SUCCESS)
         {
            if (strstr(mtpObj->alias, localMtpObj->alias) != NULL)
            {
               found = TRUE;
               break;
            }

            /* free local agent controller MTP that is not matched */
            cmsObj_free((void **) &localMtpObj);
         }

         if (found == FALSE)
         {
            cmsLog_error("Could not find local agent controller mtp, ret=%d", ret);
            return CMSRET_OBJECT_NOT_FOUND;
         }

         localMtpObj->enable = mtpObj->enable;
         REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
            localMtpObj->protocol, mtpObj->protocol,
            mdmLibCtx.allocFlags);

         /* set local agent controller MTP */
         ret = cmsObj_set(localMtpObj, &mtpIidStack);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Failed to set Dev2LocalagentControllerMtpObject, ret=%d", ret);
         }

         /* free local agent controller MTP */
         cmsObj_free((void **) &localMtpObj);
      }
         break;

      case MDMOID_USP_AGENT_CONTROLLER_MTP_STOMP:
      case MDMOID_USP_AGENT_CONTROLLER_MTP_MQTT:
      case MDMOID_USP_AGENT_CONTROLLER_MTP_WEBSOCKET:
      {
         Dev2USPAgentControllerMtpObject *mtpObj = NULL;
         Dev2USPAgentControllerObject *cntrlObj = NULL;
         Dev2LocalagentControllerObject *localCntrlObj = NULL;
         Dev2LocalagentControllerMtpObject *localMtpObj = NULL;
         InstanceIdStack mtpIidStack = *uspIidStack;

         /* Dev2USPAgentControllerMtpStompObject has the same iidStack
          * with Dev2USPAgentControllerMtpObject */

         /* get Dev2USPAgentControllerObject parent of Dev2USPAgentControllerMtpObject */
         ret = cmsObj_getAncestor(MDMOID_USP_AGENT_CONTROLLER,
                                  MDMOID_USP_AGENT_CONTROLLER_MTP,
                                  &mtpIidStack,
                                  (void **)&cntrlObj);
         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Could not get usp agent controller, ret=%d", ret);
            return ret;
         }

         /* look for Dev2LocalagentControllerObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextFlags(MDMOID_DEV2_LOCALAGENT_CONTROLLER,
                                    &iidStack,
                                    OGF_NO_VALUE_UPDATE,
                                    (void **)&localCntrlObj) == CMSRET_SUCCESS)
         {
            if (strstr(cntrlObj->alias, localCntrlObj->alias) != NULL)
            {
               found = TRUE;
            }

            /* free local agent controller */
            cmsObj_free((void **) &localCntrlObj);
         }

         /* free usp agent controller */
         cmsObj_free((void **) &cntrlObj);

         if (found == FALSE)
         {
            cmsLog_error("Could not find parent of local agent controller mtp, ret=%d", ret);
            return CMSRET_OBJECT_NOT_FOUND;
         }

         mtpIidStack = *uspIidStack;
         /* get usp agent controller MTP */
         ret = cmsObj_get(MDMOID_USP_AGENT_CONTROLLER_MTP,
                          &mtpIidStack,
                          OGF_NO_VALUE_UPDATE,
                          (void **)&mtpObj);

         if (ret != CMSRET_SUCCESS || mtpObj == NULL)
         {
            cmsLog_error("Could not get usp agent controller mtp, ret=%d", ret);
            return ret;
         }

         found = FALSE;
         INIT_INSTANCE_ID_STACK(&mtpIidStack);

         /* look for Dev2LocalagentControllerMtpObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextInSubTree(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP,
                                        &iidStack, &mtpIidStack,
                                        (void **)&localMtpObj) == CMSRET_SUCCESS)
         {
            if (strstr(mtpObj->alias, localMtpObj->alias) != NULL)
            {
               found = TRUE;
            }

            /* free local agent controller MTP that is not matched */
            cmsObj_free((void **) &localMtpObj);
         }

         /* free usp agent controller mtp */
         cmsObj_free((void **) &mtpObj);

         if (found == FALSE)
         {
            cmsLog_error("Could not find local agent controller mtp, ret=%d", ret);
            return CMSRET_OBJECT_NOT_FOUND;
         }

         if (oid == MDMOID_USP_AGENT_CONTROLLER_MTP_STOMP)
         {
            Dev2USPAgentControllerMtpStompObject *stompObj =
               (Dev2USPAgentControllerMtpStompObject *) uspObj;
            Dev2LocalagentControllerMtpStompObject *localStompObj = NULL;

            /* Dev2LocalagentControllerMtpStompObject has the same iidStack
             * with Dev2LocalagentControllerMtpObject */

            /* get local agent controller MTP STOMP */
            ret = cmsObj_get(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP_STOMP,
                             &mtpIidStack,
                             OGF_NO_VALUE_UPDATE,
                             (void **)&localStompObj);

            if (ret == CMSRET_SUCCESS && localStompObj != NULL)
            {
               REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
                  localStompObj->reference, stompObj->reference,
                  mdmLibCtx.allocFlags);
               REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
                  localStompObj->destination, stompObj->destination,
                  mdmLibCtx.allocFlags);

               /* set local agent controller MTP STOMP */
               ret = cmsObj_set(localStompObj, &mtpIidStack);
               if (ret != CMSRET_SUCCESS)
               {
                  cmsLog_error("Failed to set Dev2LocalagentControllerMtpStompObject, ret=%d", ret);
               }

               /* free local agent controller MTP STOMP */
               cmsObj_free((void **) &localStompObj);
            }
            else
            {
               cmsLog_error("Failed to get Dev2LocalagentControllerMtpStompObject, ret=%d", ret);
            }
         }
         else if (oid == MDMOID_USP_AGENT_CONTROLLER_MTP_MQTT)
         {
            Dev2USPAgentControllerMtpMqttObject *mqttObj =
               (Dev2USPAgentControllerMtpMqttObject *) uspObj;
            Dev2LocalagentControllerMtpMqttObject *localMqttObj = NULL;

            /* Dev2LocalagentControllerMtpMqttObject has the same iidStack
             * with Dev2LocalagentControllerMtpObject */

            /* get local agent controller MTP MQTT */
            ret = cmsObj_get(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP_MQTT,
                             &mtpIidStack,
                             OGF_NO_VALUE_UPDATE,
                             (void **)&localMqttObj);

            if (ret == CMSRET_SUCCESS && localMqttObj != NULL)
            {
               REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
                  localMqttObj->reference, mqttObj->reference,
                  mdmLibCtx.allocFlags);
               REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
                  localMqttObj->topic, mqttObj->topic,
                  mdmLibCtx.allocFlags);
               localMqttObj->publishRetainResponse = mqttObj->publishRetainResponse;
               localMqttObj->publishRetainNotify = mqttObj->publishRetainNotify;

               /* set local agent controller MTP MQTT */
               ret = cmsObj_set(localMqttObj, &mtpIidStack);
               if (ret != CMSRET_SUCCESS)
               {
                  cmsLog_error("Failed to set Dev2LocalagentControllerMtpMqttObject, ret=%d", ret);
               }

               /* free local agent controller MTP MQTT */
               cmsObj_free((void **) &localMqttObj);
            }
            else
            {
               cmsLog_error("Failed to get Dev2LocalagentControllerMtpMqttObject, ret=%d", ret);
            }
         }
         else if (oid == MDMOID_USP_AGENT_CONTROLLER_MTP_WEBSOCKET)
         {
            Dev2USPAgentControllerMtpWebsocketObject *wsObj =
               (Dev2USPAgentControllerMtpWebsocketObject *) uspObj;
            Dev2LocalagentControllerMtpWebsocketObject *localWsObj = NULL;

            /* Dev2LocalagentControllerMtpWebsocketObject has the same iidStack
             * with Dev2LocalagentControllerMtpObject */

            /* get local agent controller MTP WEBSOCKET */
            ret = cmsObj_get(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP_WEBSOCKET,
                             &mtpIidStack,
                             OGF_NO_VALUE_UPDATE,
                             (void **)&localWsObj);

            if (ret == CMSRET_SUCCESS && localWsObj != NULL)
            {
               REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
                  localWsObj->host, wsObj->host,
                  mdmLibCtx.allocFlags);
               REPLACE_STRING_IF_NOT_EQUAL_FLAGS(
                  localWsObj->path, wsObj->path,
                  mdmLibCtx.allocFlags);
               localWsObj->port = wsObj->port;
               localWsObj->enableEncryption = wsObj->enableEncryption;
               localWsObj->keepAliveInterval = wsObj->keepAliveInterval;
               localWsObj->currentRetryCount = wsObj->currentRetryCount;
               localWsObj->sessionRetryMinimumWaitInterval = wsObj->sessionRetryMinimumWaitInterval;
               localWsObj->sessionRetryIntervalMultiplier = wsObj->sessionRetryIntervalMultiplier;

               /* set local agent controller MTP WEBSOCKET */
               ret = cmsObj_set(localWsObj, &mtpIidStack);
               if (ret != CMSRET_SUCCESS)
               {
                  cmsLog_error("Failed to set Dev2LocalagentControllerMtpWebsocketObject, ret=%d", ret);
               }

               /* free local agent controller MTP WEBSOCKET */
               cmsObj_free((void **) &localWsObj);
            }
            else
            {
               cmsLog_error("Failed to get Dev2LocalagentControllerMtpWebsocketObject, ret=%d", ret);
            }
         }
      }
         break;

      default:
         break;
   }

   if (found == FALSE)
   {
      ret = CMSRET_OBJECT_NOT_FOUND;
   }

   return ret;
}


static CmsRet deleteInstance
   (const MdmObjectId oid, const InstanceIdStack *uspIidStack, const char *alias)
{
   CmsRet ret = CMSRET_SUCCESS;
   InstanceIdStack iidStack;

   if (uspIidStack == NULL || alias == NULL)
   {
      return CMSRET_INVALID_ARGUMENTS;
   }

   INIT_INSTANCE_ID_STACK(&iidStack);

   switch (oid)
   {
      case MDMOID_USP_AGENT_CONTROLLER:
      {
         Dev2LocalagentControllerObject *localObj = NULL;
         UBOOL8 found = FALSE;

         /* look for Dev2LocalagentControllerObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextFlags(MDMOID_DEV2_LOCALAGENT_CONTROLLER,
                                    &iidStack,
                                    OGF_NO_VALUE_UPDATE,
                                    (void **)&localObj) == CMSRET_SUCCESS)
         {
            if (strstr(alias, localObj->alias) != NULL)
            {
               found = TRUE;
               ret = cmsObj_deleteInstance(MDMOID_DEV2_LOCALAGENT_CONTROLLER, &iidStack);
               if (ret != CMSRET_SUCCESS)
               {
                  cmsLog_error("Failed to delete Dev2LocalagentControllerObject, ret=%d", ret);
               }
            }

            /* free local agent controller */
            cmsObj_free((void **) &localObj);
         }

         if (found == FALSE)
         {
            cmsLog_error("Could not find local agent controller, ret=%d", ret);
            ret = CMSRET_OBJECT_NOT_FOUND;
         }
      }
         break;

      case MDMOID_USP_AGENT_CONTROLLER_MTP:
      {
         UBOOL8 found = FALSE;
         Dev2USPAgentControllerObject *cntrlObj = NULL;
         Dev2LocalagentControllerObject *localCntrlObj = NULL;
         Dev2LocalagentControllerMtpObject *localMtpObj = NULL;
         InstanceIdStack mtpIidStack = *uspIidStack;

         /* get Dev2USPAgentControllerObject parent of Dev2USPAgentControllerMtpObject */
         ret = cmsObj_getAncestor(MDMOID_USP_AGENT_CONTROLLER,
                                  MDMOID_USP_AGENT_CONTROLLER_MTP,
                                  &mtpIidStack,
                                  (void **)&cntrlObj);

         if (ret != CMSRET_SUCCESS)
         {
            cmsLog_error("Could not get usp agent controller, ret=%d", ret);
            return ret;
         }

         /* look for Dev2LocalagentControllerObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextFlags(MDMOID_DEV2_LOCALAGENT_CONTROLLER,
                                    &iidStack,
                                    OGF_NO_VALUE_UPDATE,
                                    (void **)&localCntrlObj) == CMSRET_SUCCESS)
         {
            if (strstr(cntrlObj->alias, localCntrlObj->alias) != NULL)
            {
               found = TRUE;
            }

            /* free local agent controller */
            cmsObj_free((void **) &localCntrlObj);
         }

         /* free usp agent controller */
         cmsObj_free((void **) &cntrlObj);

         if (found == FALSE)
         {
            cmsLog_error("Could not find parent of local agent controller mtp, ret=%d", ret);
            return CMSRET_OBJECT_NOT_FOUND;
         }

         found = FALSE;
         INIT_INSTANCE_ID_STACK(&mtpIidStack);

         /* look for Dev2LocalagentControllerMtpObject matching with alias */
         while (found == FALSE &&
                cmsObj_getNextInSubTree(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP,
                                        &iidStack, &mtpIidStack,
                                        (void **)&localMtpObj) == CMSRET_SUCCESS)
         {
            if (strstr(alias, localMtpObj->alias) != NULL)
            {
               found = TRUE;
               ret = cmsObj_deleteInstance(MDMOID_DEV2_LOCALAGENT_CONTROLLER_MTP, &mtpIidStack);
               if (ret != CMSRET_SUCCESS)
               {
                  cmsLog_error("Failed to delete Dev2LocalagentControllerMtpObject, ret=%d", ret);
               }
            }

            /* free local agent controller MTP */
            cmsObj_free((void **) &localMtpObj);
         }

         if (found == FALSE)
         {
            cmsLog_error("Could not find local agent controller mtp, ret=%d", ret);
            ret = CMSRET_OBJECT_NOT_FOUND;
         }
      }
         break;

      default:
         break;
   }

   return ret;
}


CmsRet rcl_dev2USPAgentControllerObject(_Dev2USPAgentControllerObject *newObj,
                                const _Dev2USPAgentControllerObject *currObj,
                                const InstanceIdStack *iidStack,
                                char **errorParam __attribute__((unused)),
                                CmsRet *errorCode __attribute__((unused)))
{
   CmsRet ret = CMSRET_SUCCESS;

   if (ADD_NEW(newObj, currObj))
   {
      ret = addInstance(MDMOID_USP_AGENT_CONTROLLER, iidStack, newObj);

      if (ret == CMSRET_SUCCESS)
      {
         rutUtil_modifyNumCwmpControllerEntry_dev2(iidStack, 1);
      }
   }
   else if (newObj && currObj)
   {
      if (currObj->alias != NULL)
      {
         ret = updateInstance(MDMOID_USP_AGENT_CONTROLLER, iidStack, newObj);
      }
   }
   else if (DELETE_EXISTING(newObj, currObj))
   {
      ret = deleteInstance(MDMOID_USP_AGENT_CONTROLLER, iidStack, currObj->alias);

      if (ret == CMSRET_SUCCESS)
      {
         rutUtil_modifyNumCwmpControllerEntry_dev2(iidStack, -1);
      }
   }

   return ret;
}


CmsRet rcl_dev2USPAgentControllerMtpObject(_Dev2USPAgentControllerMtpObject *newObj,
                                const _Dev2USPAgentControllerMtpObject *currObj,
                                const InstanceIdStack *iidStack,
                                char **errorParam __attribute__((unused)),
                                CmsRet *errorCode __attribute__((unused)))
{
   CmsRet ret = CMSRET_SUCCESS;

   if (ADD_NEW(newObj, currObj))
   {
      ret = addInstance(MDMOID_USP_AGENT_CONTROLLER_MTP, iidStack, newObj);

      if (ret == CMSRET_SUCCESS)
      {
         rutUtil_modifyNumCwmpControllerMtpEntry_dev2(iidStack, 1);
      }
   }
   else if (newObj && currObj)
   {
      if (currObj->alias != NULL)
      {
         ret = updateInstance(MDMOID_USP_AGENT_CONTROLLER_MTP, iidStack, newObj);
      }
   }
   else if (DELETE_EXISTING(newObj, currObj))
   {
      ret = deleteInstance(MDMOID_USP_AGENT_CONTROLLER_MTP, iidStack, currObj->alias);

      if (ret == CMSRET_SUCCESS)
      {
         rutUtil_modifyNumCwmpControllerMtpEntry_dev2(iidStack, -1);
      }
   }

   return ret;
}


CmsRet rcl_dev2USPAgentControllerMtpStompObject(_Dev2USPAgentControllerMtpStompObject *newObj __attribute__((unused)),
                                const _Dev2USPAgentControllerMtpStompObject *currObj __attribute__((unused)),
                                const InstanceIdStack *iidStack __attribute__((unused)),
                                char **errorParam __attribute__((unused)),
                                CmsRet *errorCode __attribute__((unused)))
{
   CmsRet ret = CMSRET_SUCCESS;

   if (newObj && currObj)
   {
      ret = updateInstance(MDMOID_USP_AGENT_CONTROLLER_MTP_STOMP, iidStack, newObj);
   }

   return ret;
}


CmsRet rcl_dev2USPAgentControllerMtpWebsocketObject(_Dev2USPAgentControllerMtpWebsocketObject *newObj,
                     const _Dev2USPAgentControllerMtpWebsocketObject *currObj,
                     const InstanceIdStack *iidStack,
                     char **errorParam __attribute__((unused)),
                     CmsRet *errorCode __attribute__((unused)))
{
   CmsRet ret = CMSRET_SUCCESS;

   if (newObj && currObj)
   {
      ret = updateInstance(MDMOID_USP_AGENT_CONTROLLER_MTP_WEBSOCKET, iidStack, newObj);
   }

   return ret;
}


CmsRet rcl_dev2USPAgentControllerMtpMqttObject(_Dev2USPAgentControllerMtpMqttObject *newObj __attribute__((unused)),
                                const _Dev2USPAgentControllerMtpMqttObject *currObj __attribute__((unused)),
                                const InstanceIdStack *iidStack __attribute__((unused)),
                                char **errorParam __attribute__((unused)),
                                CmsRet *errorCode __attribute__((unused)))
{
   CmsRet ret = CMSRET_SUCCESS;

   if (newObj && currObj)
   {
      ret = updateInstance(MDMOID_USP_AGENT_CONTROLLER_MTP_MQTT, iidStack, newObj);
   }

   return ret;
}


#endif /* DMP_USPAGENT_1 */
