
 
#define SUPPORT_DM_PURE181 1
 
#define DMP_DEVICE2_BASELINE_1 1
 
#define DMP_DEVICE2_X_BROADCOM_COM_BASELINE_1 1
 
#define DMP_DEVICE2_BASELINE_2 1
 
#define DMP_DEVICE2_BASELINE_3 1
 
#define DMP_DEVICE2_DEVICEINFO_1 1
 
#define DMP_DEVICE2_GATEWAYINFO_1 1
 
#define DMP_DEVICE2_FIRMWARE_1 1
 
#define DMP_DEVICE2_IPINTERFACE_1 1
 
#define DMP_DEVICE2_IPINTERFACE_2 1
 
#define DMP_DEVICE2_ETHERNETLINK_1 1
 
#define DMP_DEVICE2_ETHERNETINTERFACE_1 1
 
#define DMP_DEVICE2_VLANTERMINATION_1 1
 
#define DMP_X_BROADCOM_COM_CABLEDIAGNOSTICS_1 1
 
#define DMP_DEVICE2_PPPINTERFACE_1 1
 
#define DMP_DEVICE2_PPPINTERFACE_2 1
 
#define DMP_DEVICE2_IPPING_1 1
 
#define DMP_DEVICE2_TRACEROUTE_1 1
 
#define DMP_DEVICE2_ROUTING_1 1
 
#define DMP_DEVICE2_ROUTING_2 1
 
#define DMP_DEVICE2_DUSTATECHNGCOMPLPOLICY_1 1
 
#define DMP_DEVICE2_BRIDGE_1 1
 
#define DMP_DEVICE2_VLANBRIDGE_1 1
 
#define DMP_DEVICE2_BRIDGEFILTER_1 1
 
#define DMP_DEVICE2_ROUTING_1 1
 
#define DMP_DEVICE2_ROUTING_2 1
 
#define DMP_DEVICE2_NAT_1 1
 
#define DMP_DEVICE2_PROCESSORS_1 1
 
#define DMP_DEVICE2_HOSTS_1 1
 
#define DMP_DEVICE2_HOSTS_2 1
 
#define DMP_DEVICE2_DHCPV4SERVERCLIENTINFO_1 1
 
#define DMP_X_BROADCOM_COM_DEBUG_1 1
 
#define DMP_X_BROADCOM_COM_SECURITY_1 1
 
#define DMP_DEVICE2_DEVICEASSOCIATION_1 1
 
#define DMP_X_BROADCOM_COM_BASELINE_1 1
 
#define DMP_DEVICE2_SIMPLEFIREWALL_1 1
 
#define DMP_DEVICE2_ADVANCEDFIREWALL_1 1
 
#define DMP_DEVICE2_MEMORYSTATUS_1 1
 
#define DMP_DEVICE2_PROCESSSTATUS_1 1
 
#define SUPPORT_ETHWAN 1
 
#define SUPPORT_TMCTL 1
 
#define SUPPORT_ARCHERCTL 1
 
#define DMP_X_BROADCOM_COM_L2TPAC_1 1
 
#define DMP_X_BROADCOM_COM_L2TPAC_2 1
 
#define DMP_X_BROADCOM_COM_PPTPAC_2 1
 
#define DMP_DEVICE2_VXLANBASIC_1 1
 
#define DMP_DEVICE2_VXLANADV_1 1
 
#define SUPPORT_VXLAN_TUNNEL_TR181 1
 
#define SUPPORT_GRE_TUNNEL 1
 
#define DMP_DEVICE2_GREBASIC_1 1
 
#define DMP_DEVICE2_GREADV_1 1
 
#define SUPPORT_GRE_TUNNEL_TR181 1
 
#define SUPPORT_IPSEC 1
 
#define DMP_DEVICE2_IPSEC_1 1
 
#define SUPPORT_IPV6 1
 
#define DMP_X_BROADCOM_COM_DEV2_IPV6_1 1
 
#define DMP_DEVICE2_DSLITE_1 1
 
#define DMP_DEVICE2_DSLITE_2 1
 
#define DMP_DEVICE2_IPV6RD_1 1
 
#define DMP_DEVICE2_IPV6INTERFACE_1 1
 
#define DMP_DEVICE2_IPV6ROUTING_1 1
 
#define DMP_DEVICE2_DHCPV6CLIENT_1 1
 
#define DMP_DEVICE2_DHCPV6CLIENTSERVERIDENTITY_1 1
 
#define DMP_DEVICE2_DHCPV6SERVER_1 1
 
#define DMP_DEVICE2_DHCPV6SERVERADV_1 1
 
#define DMP_DEVICE2_DHCPV6SERVERCLIENTINFO_1 1
 
#define DMP_DEVICE2_NEIGHBORDISCOVERY_1 1
 
#define DMP_DEVICE2_ROUTERADVERTISEMENT_1 1
 
#define DMP_DEVICE2_MAPBASIC_1 1
 
#define DMP_DEVICE2_MAPADV_1 1
 
#define SUPPORT_MAP 1
 
#define DMP_DEVICE2_IPLAYERCAPACITYTEST_1 1
 
#define SUPPORT_CPU_MEMORY_WEB_PAGE 1
 
#define SUPPORT_JQPLOT 1
 
#define SUPPORT_WEB_SOCKETS 1
 
#define SUPPORT_LICENSE_UPLOAD 1
 
#define SUPPORT_HTTPD 1
 
#define SUPPORT_HTTPD_BASIC_SSL 1
 
#define SUPPORT_CLI_CMD 1
 
#define CLI_CMD_EDIT 1
 
#define SUPPORT_TELNETD 1
 
#define SUPPORT_SSHD 1
 
#define SUPPORT_FTPD 1
 
#define SUPPORT_EBTABLES 1
 
#define SUPPORT_TOD 1
 
#define DMP_X_BROADCOM_COM_ACCESSTIMERESTRICTION_1 1
 
#define SUPPORT_URLFILTER 1
 
#define SUPPORT_POLICYROUTING 1
 
#define SUPPORT_UPNP 1
 
#define DMP_X_BROADCOM_COM_UPNP_1 1
 
#define SUPPORT_DDNSD 1
 
#define DMP_X_BROADCOM_COM_DYNAMICDNS_1 1
 
#define SUPPORT_DNSMASQ 1
 
#define DMP_X_BROADCOM_COM_DNSPROXY_1 1
 
#define SUPPORT_IPP 1
 
#define DMP_X_BROADCOM_COM_IPPRINTING_1 1
 
#define DMP_X_BROADCOM_COM_DLNA_1 1
 
#define SUPPORT_BLOGCTL 1
 
#define SUPPORT_FCCTL 1
 
#define SUPPORT_NTPD 1
 
#define DMP_DEVICE2_TIME_1 1
 
#define SUPPORT_UDHCP 1
 
#define DMP_DEVICE2_DHCPV4_1 1
 
#define DMP_DEVICE2_DHCPV4CLIENT_1 1
 
#define DMP_DEVICE2_DHCPV4SERVER_1 1
 
#define DHCP_SERVER_DEFAULT 1
 
#define SUPPORT_ETHSWCTL 1
 
#define SUPPORT_PWRMNGT 1
 
#define DMP_X_BROADCOM_COM_PWRMNGT_1 1
 
#define SUPPORT_DDR_SELF_REFRESH_PWRSAVE 1
 
#define SUPPORT_ETH_PWRSAVE 1
 
#define SUPPORT_ENERGY_EFFICIENT_ETHERNET 1
 
#define SUPPORT_STORAGESERVICE 1
 
#define DMP_STORAGESERVICE_1 1
 
#define SUPPORT_NTFS_3G 1
 
#define SUPPORT_SAMBA 1
 
#define DMP_X_BROADCOM_COM_MCAST_1 1
 
#define DMP_X_BROADCOM_COM_IGMPSNOOP_1 1
 
#define DMP_X_BROADCOM_COM_MLDSNOOP_1 1
 
#define SUPPORT_IGMP 1
 
#define DMP_X_BROADCOM_COM_IGMP_1 1
 
#define SUPPORT_MLD 1
 
#define DMP_X_BROADCOM_COM_MLD_1 1
 
#define SUPPORT_NF_NAT 1
 
#define SUPPORT_NF_FIREWALL 1
 
#define SUPPORT_PPTP 1
 
#define SUPPORT_SIP 1
 
#define SUPPORT_NF_MANGLE 1
 
#define SUPPORT_CONNTRACK_TOOLS 1
 
#define SUPPORT_INTF_GROUPING 1
 
#define SUPPORT_PORT_MAP 1
 
#define SUPPORT_WANVLANMUX 1
 
#define DMP_DEVICE2_VLANTERMINATION_1 1
 
#define SUPPORT_VLANCTL 1
 
#define SUPPORT_VLANSUBIF 1
 
#define SUPPORT_LANVLAN 1
 
#define DMP_DEVICE2_VLANTERMINATION_1 1
 
#define SUPPORT_CMS_ALLOW_REAL_HW_SWITCHING 1
 
#define DMP_DEVICE2_ETHLAG_1 1
 
#define SUPPORT_QOS 1
 
#define DMP_DEVICE2_QOS_1 1
 
#define DMP_DEVICE2_QOS_2 1
 
#define DMP_DEVICE2_QOSSTATS_1 1
 
#define DMP_X_BROADCOM_COM_DEVICE2_QOS_1 1
 
#define SUPPORT_RATE_LIMIT 1
 
#define SUPPORT_DEBUG_TOOLS 1
 
#define SUPPORT_CERT 1
 
#define DMP_X_BROADCOM_COM_DIGITALCERTIFICATES_1 1
 
#define DMP_DEVICE2_CERTIFICATES_1 1
 
#define SUPPORT_RIP 1
 
#define COMPRESSED_CONFIG_FILE 1
 
#define CMS_CONFIG_COMPAT 1
 
#define CMS_CONFIG_IGNORE_UNRECOGNIZED 1
 
#define DMP_DEVICE2_WIFIRADIO_1 1
 
#define DMP_DEVICE2_WIFISSID_1 1
 
#define DMP_DEVICE2_WIFIACCESSPOINT_1 1

 

// original CMS_DMP_FLAGS= -DSUPPORT_DM_PURE181 -DDMP_DEVICE2_BASELINE_1 -DDMP_DEVICE2_X_BROADCOM_COM_BASELINE_1 -DDMP_DEVICE2_BASELINE_2 -DDMP_DEVICE2_BASELINE_3 -DDMP_DEVICE2_DEVICEINFO_1 -DDMP_DEVICE2_GATEWAYINFO_1 -DDMP_DEVICE2_FIRMWARE_1 -DDMP_DEVICE2_IPINTERFACE_1 -DDMP_DEVICE2_IPINTERFACE_2 -DDMP_DEVICE2_ETHERNETLINK_1 -DDMP_DEVICE2_ETHERNETINTERFACE_1 -DDMP_DEVICE2_VLANTERMINATION_1 -DDMP_X_BROADCOM_COM_CABLEDIAGNOSTICS_1 -DDMP_DEVICE2_PPPINTERFACE_1 -DDMP_DEVICE2_PPPINTERFACE_2 -DDMP_DEVICE2_IPPING_1 -DDMP_DEVICE2_TRACEROUTE_1 -DDMP_DEVICE2_ROUTING_1 -DDMP_DEVICE2_ROUTING_2 -DDMP_DEVICE2_DUSTATECHNGCOMPLPOLICY_1 -DDMP_DEVICE2_BRIDGE_1 -DDMP_DEVICE2_VLANBRIDGE_1 -DDMP_DEVICE2_BRIDGEFILTER_1 -DDMP_DEVICE2_ROUTING_1 -DDMP_DEVICE2_ROUTING_2 -DDMP_DEVICE2_NAT_1 -DDMP_DEVICE2_PROCESSORS_1 -DDMP_DEVICE2_HOSTS_1 -DDMP_DEVICE2_HOSTS_2 -DDMP_DEVICE2_DHCPV4SERVERCLIENTINFO_1 -DDMP_X_BROADCOM_COM_DEBUG_1 -DDMP_X_BROADCOM_COM_SECURITY_1 -DDMP_DEVICE2_DEVICEASSOCIATION_1 -DDMP_X_BROADCOM_COM_BASELINE_1 -DDMP_DEVICE2_SIMPLEFIREWALL_1 -DDMP_DEVICE2_ADVANCEDFIREWALL_1 -DDMP_DEVICE2_MEMORYSTATUS_1 -DDMP_DEVICE2_PROCESSSTATUS_1 -DSUPPORT_ETHWAN -DSUPPORT_TMCTL -DSUPPORT_ARCHERCTL -DDMP_X_BROADCOM_COM_L2TPAC_1 -DDMP_X_BROADCOM_COM_L2TPAC_2 -DDMP_X_BROADCOM_COM_PPTPAC_2 -DDMP_DEVICE2_VXLANBASIC_1 -DDMP_DEVICE2_VXLANADV_1 -DSUPPORT_VXLAN_TUNNEL_TR181 -DSUPPORT_GRE_TUNNEL -DDMP_DEVICE2_GREBASIC_1 -DDMP_DEVICE2_GREADV_1 -DSUPPORT_GRE_TUNNEL_TR181 -DSUPPORT_IPSEC -DDMP_DEVICE2_IPSEC_1 -DSUPPORT_IPV6 -DDMP_X_BROADCOM_COM_DEV2_IPV6_1 -DDMP_DEVICE2_DSLITE_1 -DDMP_DEVICE2_DSLITE_2 -DDMP_DEVICE2_IPV6RD_1 -DDMP_DEVICE2_IPV6INTERFACE_1 -DDMP_DEVICE2_IPV6ROUTING_1 -DDMP_DEVICE2_DHCPV6CLIENT_1 -DDMP_DEVICE2_DHCPV6CLIENTSERVERIDENTITY_1 -DDMP_DEVICE2_DHCPV6SERVER_1 -DDMP_DEVICE2_DHCPV6SERVERADV_1 -DDMP_DEVICE2_DHCPV6SERVERCLIENTINFO_1 -DDMP_DEVICE2_NEIGHBORDISCOVERY_1 -DDMP_DEVICE2_ROUTERADVERTISEMENT_1 -DDMP_DEVICE2_MAPBASIC_1 -DDMP_DEVICE2_MAPADV_1 -DSUPPORT_MAP -DDMP_DEVICE2_IPLAYERCAPACITYTEST_1 -DSUPPORT_CPU_MEMORY_WEB_PAGE -DSUPPORT_JQPLOT -DSUPPORT_WEB_SOCKETS -DSUPPORT_LICENSE_UPLOAD -DSUPPORT_HTTPD -DSUPPORT_HTTPD_BASIC_SSL -DSUPPORT_CLI_CMD -DCLI_CMD_EDIT -DSUPPORT_TELNETD -DSUPPORT_SSHD -DSUPPORT_FTPD -DSUPPORT_EBTABLES -DSUPPORT_TOD -DDMP_X_BROADCOM_COM_ACCESSTIMERESTRICTION_1 -DSUPPORT_URLFILTER -DSUPPORT_POLICYROUTING -DSUPPORT_UPNP -DDMP_X_BROADCOM_COM_UPNP_1 -DSUPPORT_DDNSD -DDMP_X_BROADCOM_COM_DYNAMICDNS_1 -DSUPPORT_DNSMASQ -DDMP_X_BROADCOM_COM_DNSPROXY_1 -DSUPPORT_IPP -DDMP_X_BROADCOM_COM_IPPRINTING_1 -DDMP_X_BROADCOM_COM_DLNA_1 -DSUPPORT_BLOGCTL -DSUPPORT_FCCTL -DSUPPORT_NTPD -DDMP_DEVICE2_TIME_1 -DSUPPORT_UDHCP -DDMP_DEVICE2_DHCPV4_1 -DDMP_DEVICE2_DHCPV4CLIENT_1 -DDMP_DEVICE2_DHCPV4SERVER_1 -DDHCP_SERVER_DEFAULT -DSUPPORT_ETHSWCTL -DSUPPORT_PWRMNGT -DDMP_X_BROADCOM_COM_PWRMNGT_1 -DSUPPORT_DDR_SELF_REFRESH_PWRSAVE -DSUPPORT_ETH_PWRSAVE -DSUPPORT_ENERGY_EFFICIENT_ETHERNET -DSUPPORT_STORAGESERVICE -DDMP_STORAGESERVICE_1 -DSUPPORT_NTFS_3G -DSUPPORT_SAMBA -DDMP_X_BROADCOM_COM_MCAST_1 -DDMP_X_BROADCOM_COM_IGMPSNOOP_1 -DDMP_X_BROADCOM_COM_MLDSNOOP_1 -DSUPPORT_IGMP -DDMP_X_BROADCOM_COM_IGMP_1 -DSUPPORT_MLD -DDMP_X_BROADCOM_COM_MLD_1 -DSUPPORT_NF_NAT -DSUPPORT_NF_FIREWALL -DSUPPORT_PPTP -DSUPPORT_SIP -DSUPPORT_NF_MANGLE -DSUPPORT_CONNTRACK_TOOLS -DSUPPORT_INTF_GROUPING -DSUPPORT_PORT_MAP -DSUPPORT_WANVLANMUX -DDMP_DEVICE2_VLANTERMINATION_1 -DSUPPORT_VLANCTL -DSUPPORT_VLANSUBIF -DSUPPORT_LANVLAN -DDMP_DEVICE2_VLANTERMINATION_1 -DSUPPORT_CMS_ALLOW_REAL_HW_SWITCHING -DDMP_DEVICE2_ETHLAG_1 -DSUPPORT_QOS -DDMP_DEVICE2_QOS_1 -DDMP_DEVICE2_QOS_2 -DDMP_DEVICE2_QOSSTATS_1 -DDMP_X_BROADCOM_COM_DEVICE2_QOS_1 -DSUPPORT_RATE_LIMIT -DSUPPORT_DEBUG_TOOLS -DSUPPORT_CERT -DDMP_X_BROADCOM_COM_DIGITALCERTIFICATES_1 -DDMP_DEVICE2_CERTIFICATES_1 -DSUPPORT_RIP -DCOMPRESSED_CONFIG_FILE -DCMS_CONFIG_COMPAT -DCMS_CONFIG_IGNORE_UNRECOGNIZED -DDMP_DEVICE2_WIFIRADIO_1 -DDMP_DEVICE2_WIFISSID_1 -DDMP_DEVICE2_WIFIACCESSPOINT_1

