/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_add_pbit_to_key        (0x3844)
#define image_0_c_dhd_rx_complete_wakeup_request        (0x3ec)
#define image_0_c_dhd_tx_complete_wakeup_request        (0x850)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_0_check_skip_cso        (0x37e4)
#define image_0_debug_routine        (0x30)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_0_dos_attack_handler        (0x2d68)
#define image_0_drop_pkt_and_serial        (0x2f58)
#define image_0_dyn_code_func        (0x7c00)
#define image_0_flow_policer        (0x5ae8)
#define image_0_group_flow_lkp_and_fwd        (0x3964)
#define image_0_ingress_filter_action_point_update        (0x3870)
#define image_0_ingress_filters_handler        (0x30e8)
#define image_0_initialization_task        (0x8)
#define image_0_is_iptv_capable        (0x2dc4)
#define image_0_mcast_flow_master_lookup        (0x38bc)
#define image_0_memcpy_abs_to_sbpm        (0xf8)
#define image_0_parser_exception_handler        (0x2b84)
#define image_0_proccessing_loopback        (0x2acc)
#define image_0_processing_policer_action        (0x5b38)
#define image_0_processing_wakeup_request        (0xafc)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0x754)
#define image_0_rxcmpl_process_rx_packet        (0x7bc)
#define image_0_spdsvc_natc_lookup        (0x2e64)
#define image_0_start_task_add_pbit_to_key        (0x3844)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0x3ec)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0x850)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_0_start_task_check_skip_cso        (0x37e4)
#define image_0_start_task_debug_routine        (0x30)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_0_start_task_dos_attack_handler        (0x2d68)
#define image_0_start_task_drop_pkt_and_serial        (0x2f58)
#define image_0_start_task_dyn_code_func        (0x7c00)
#define image_0_start_task_flow_policer        (0x5ae8)
#define image_0_start_task_group_flow_lkp_and_fwd        (0x3964)
#define image_0_start_task_ingress_filter_action_point_update        (0x3870)
#define image_0_start_task_ingress_filters_handler        (0x30e8)
#define image_0_start_task_initialization_task        (0x8)
#define image_0_start_task_is_iptv_capable        (0x2dc4)
#define image_0_start_task_mcast_flow_master_lookup        (0x38bc)
#define image_0_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_0_start_task_parser_exception_handler        (0x2b84)
#define image_0_start_task_proccessing_loopback        (0x2acc)
#define image_0_start_task_processing_policer_action        (0x5b38)
#define image_0_start_task_processing_wakeup_request        (0xafc)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0x754)
#define image_0_start_task_rxcmpl_process_rx_packet        (0x7bc)
#define image_0_start_task_spdsvc_natc_lookup        (0x2e64)
#define image_0_start_task_ts_1588_handler        (0x30b4)
#define image_0_start_task_xx_mirror_noinline        (0x3420)
#define image_0_ts_1588_handler        (0x30b4)
#define image_0_xx_mirror_noinline        (0x3420)

#else

#define image_0_add_pbit_to_key        (0xe11)
#define image_0_c_dhd_rx_complete_wakeup_request        (0xfb)
#define image_0_c_dhd_tx_complete_wakeup_request        (0x214)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_0_check_skip_cso        (0xdf9)
#define image_0_debug_routine        (0xc)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_0_dos_attack_handler        (0xb5a)
#define image_0_drop_pkt_and_serial        (0xbd6)
#define image_0_dyn_code_func        (0x1f00)
#define image_0_flow_policer        (0x16ba)
#define image_0_group_flow_lkp_and_fwd        (0xe59)
#define image_0_ingress_filter_action_point_update        (0xe1c)
#define image_0_ingress_filters_handler        (0xc3a)
#define image_0_initialization_task        (0x2)
#define image_0_is_iptv_capable        (0xb71)
#define image_0_mcast_flow_master_lookup        (0xe2f)
#define image_0_memcpy_abs_to_sbpm        (0x3e)
#define image_0_parser_exception_handler        (0xae1)
#define image_0_proccessing_loopback        (0xab3)
#define image_0_processing_policer_action        (0x16ce)
#define image_0_processing_wakeup_request        (0x2bf)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0x1d5)
#define image_0_rxcmpl_process_rx_packet        (0x1ef)
#define image_0_spdsvc_natc_lookup        (0xb99)
#define image_0_start_task_add_pbit_to_key        (0xe11)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0xfb)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0x214)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_0_start_task_check_skip_cso        (0xdf9)
#define image_0_start_task_debug_routine        (0xc)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_0_start_task_dos_attack_handler        (0xb5a)
#define image_0_start_task_drop_pkt_and_serial        (0xbd6)
#define image_0_start_task_dyn_code_func        (0x1f00)
#define image_0_start_task_flow_policer        (0x16ba)
#define image_0_start_task_group_flow_lkp_and_fwd        (0xe59)
#define image_0_start_task_ingress_filter_action_point_update        (0xe1c)
#define image_0_start_task_ingress_filters_handler        (0xc3a)
#define image_0_start_task_initialization_task        (0x2)
#define image_0_start_task_is_iptv_capable        (0xb71)
#define image_0_start_task_mcast_flow_master_lookup        (0xe2f)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_0_start_task_parser_exception_handler        (0xae1)
#define image_0_start_task_proccessing_loopback        (0xab3)
#define image_0_start_task_processing_policer_action        (0x16ce)
#define image_0_start_task_processing_wakeup_request        (0x2bf)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0x1d5)
#define image_0_start_task_rxcmpl_process_rx_packet        (0x1ef)
#define image_0_start_task_spdsvc_natc_lookup        (0xb99)
#define image_0_start_task_ts_1588_handler        (0xc2d)
#define image_0_start_task_xx_mirror_noinline        (0xd08)
#define image_0_ts_1588_handler        (0xc2d)
#define image_0_xx_mirror_noinline        (0xd08)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_add_pbit_to_key        (0x41a0)
#define image_1_c_dhd_timer_wakeup_request        (0x3ec)
#define image_1_c_dhd_tx_post_update_fifo_wakeup_request        (0x474)
#define image_1_c_dhd_tx_post_wakeup_request        (0x4b8)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_1_check_skip_cso        (0x4140)
#define image_1_debug_routine        (0x30)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_1_dhd_tx_get_bq_index        (0x1384)
#define image_1_dhd_tx_post_drop_packet        (0x1238)
#define image_1_dhd_tx_post_flow_ring_get_info        (0x1074)
#define image_1_dhd_tx_put_bq_index        (0x13f4)
#define image_1_dos_attack_handler        (0x36c4)
#define image_1_drop_pkt_and_serial        (0x38b4)
#define image_1_dyn_code_func        (0x7c00)
#define image_1_flow_policer        (0x6444)
#define image_1_group_flow_lkp_and_fwd        (0x42c0)
#define image_1_ingress_filter_action_point_update        (0x41cc)
#define image_1_ingress_filters_handler        (0x3a44)
#define image_1_initialization_task        (0x8)
#define image_1_is_iptv_capable        (0x3720)
#define image_1_mcast_flow_master_lookup        (0x4218)
#define image_1_memcpy_abs_to_sbpm        (0xf8)
#define image_1_parser_exception_handler        (0x34e0)
#define image_1_proccessing_loopback        (0x3428)
#define image_1_processing_policer_action        (0x6494)
#define image_1_processing_wakeup_request        (0x145c)
#define image_1_spdsvc_natc_lookup        (0x37c0)
#define image_1_start_task_add_pbit_to_key        (0x41a0)
#define image_1_start_task_c_dhd_timer_wakeup_request        (0x3ec)
#define image_1_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x474)
#define image_1_start_task_c_dhd_tx_post_wakeup_request        (0x4b8)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_1_start_task_check_skip_cso        (0x4140)
#define image_1_start_task_debug_routine        (0x30)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0x31c)
#define image_1_start_task_dhd_tx_get_bq_index        (0x1384)
#define image_1_start_task_dhd_tx_post_drop_packet        (0x1238)
#define image_1_start_task_dhd_tx_post_flow_ring_get_info        (0x1074)
#define image_1_start_task_dhd_tx_put_bq_index        (0x13f4)
#define image_1_start_task_dos_attack_handler        (0x36c4)
#define image_1_start_task_drop_pkt_and_serial        (0x38b4)
#define image_1_start_task_dyn_code_func        (0x7c00)
#define image_1_start_task_flow_policer        (0x6444)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x42c0)
#define image_1_start_task_ingress_filter_action_point_update        (0x41cc)
#define image_1_start_task_ingress_filters_handler        (0x3a44)
#define image_1_start_task_initialization_task        (0x8)
#define image_1_start_task_is_iptv_capable        (0x3720)
#define image_1_start_task_mcast_flow_master_lookup        (0x4218)
#define image_1_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_1_start_task_parser_exception_handler        (0x34e0)
#define image_1_start_task_proccessing_loopback        (0x3428)
#define image_1_start_task_processing_policer_action        (0x6494)
#define image_1_start_task_processing_wakeup_request        (0x145c)
#define image_1_start_task_spdsvc_natc_lookup        (0x37c0)
#define image_1_start_task_ts_1588_handler        (0x3a10)
#define image_1_start_task_tx_mirror        (0x6504)
#define image_1_start_task_xx_mirror_noinline        (0x3d7c)
#define image_1_ts_1588_handler        (0x3a10)
#define image_1_tx_mirror        (0x6504)
#define image_1_xx_mirror_noinline        (0x3d7c)

#else

#define image_1_add_pbit_to_key        (0x1068)
#define image_1_c_dhd_timer_wakeup_request        (0xfb)
#define image_1_c_dhd_tx_post_update_fifo_wakeup_request        (0x11d)
#define image_1_c_dhd_tx_post_wakeup_request        (0x12e)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_1_check_skip_cso        (0x1050)
#define image_1_debug_routine        (0xc)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_1_dhd_tx_get_bq_index        (0x4e1)
#define image_1_dhd_tx_post_drop_packet        (0x48e)
#define image_1_dhd_tx_post_flow_ring_get_info        (0x41d)
#define image_1_dhd_tx_put_bq_index        (0x4fd)
#define image_1_dos_attack_handler        (0xdb1)
#define image_1_drop_pkt_and_serial        (0xe2d)
#define image_1_dyn_code_func        (0x1f00)
#define image_1_flow_policer        (0x1911)
#define image_1_group_flow_lkp_and_fwd        (0x10b0)
#define image_1_ingress_filter_action_point_update        (0x1073)
#define image_1_ingress_filters_handler        (0xe91)
#define image_1_initialization_task        (0x2)
#define image_1_is_iptv_capable        (0xdc8)
#define image_1_mcast_flow_master_lookup        (0x1086)
#define image_1_memcpy_abs_to_sbpm        (0x3e)
#define image_1_parser_exception_handler        (0xd38)
#define image_1_proccessing_loopback        (0xd0a)
#define image_1_processing_policer_action        (0x1925)
#define image_1_processing_wakeup_request        (0x517)
#define image_1_spdsvc_natc_lookup        (0xdf0)
#define image_1_start_task_add_pbit_to_key        (0x1068)
#define image_1_start_task_c_dhd_timer_wakeup_request        (0xfb)
#define image_1_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x11d)
#define image_1_start_task_c_dhd_tx_post_wakeup_request        (0x12e)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_1_start_task_check_skip_cso        (0x1050)
#define image_1_start_task_debug_routine        (0xc)
#define image_1_start_task_dhd_send_entry_to_cpu_ring        (0xc7)
#define image_1_start_task_dhd_tx_get_bq_index        (0x4e1)
#define image_1_start_task_dhd_tx_post_drop_packet        (0x48e)
#define image_1_start_task_dhd_tx_post_flow_ring_get_info        (0x41d)
#define image_1_start_task_dhd_tx_put_bq_index        (0x4fd)
#define image_1_start_task_dos_attack_handler        (0xdb1)
#define image_1_start_task_drop_pkt_and_serial        (0xe2d)
#define image_1_start_task_dyn_code_func        (0x1f00)
#define image_1_start_task_flow_policer        (0x1911)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x10b0)
#define image_1_start_task_ingress_filter_action_point_update        (0x1073)
#define image_1_start_task_ingress_filters_handler        (0xe91)
#define image_1_start_task_initialization_task        (0x2)
#define image_1_start_task_is_iptv_capable        (0xdc8)
#define image_1_start_task_mcast_flow_master_lookup        (0x1086)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_1_start_task_parser_exception_handler        (0xd38)
#define image_1_start_task_proccessing_loopback        (0xd0a)
#define image_1_start_task_processing_policer_action        (0x1925)
#define image_1_start_task_processing_wakeup_request        (0x517)
#define image_1_start_task_spdsvc_natc_lookup        (0xdf0)
#define image_1_start_task_ts_1588_handler        (0xe84)
#define image_1_start_task_tx_mirror        (0x1941)
#define image_1_start_task_xx_mirror_noinline        (0xf5f)
#define image_1_ts_1588_handler        (0xe84)
#define image_1_tx_mirror        (0x1941)
#define image_1_xx_mirror_noinline        (0xf5f)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_add_pbit_to_key        (0x3060)
#define image_2_c_cpu_recycle_wakeup_request        (0x5434)
#define image_2_c_cpu_rx_wakeup_request        (0x55c4)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_2_check_skip_cso        (0x3000)
#define image_2_cpu_recycle_int_coalescing        (0x5598)
#define image_2_cpu_rx_int_coalescing        (0x5f5c)
#define image_2_cpu_rx_meter_budget_allocator        (0x5fa8)
#define image_2_debug_routine        (0x30)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dos_attack_handler        (0x2584)
#define image_2_drop_pkt_and_serial        (0x2774)
#define image_2_dyn_code_func        (0x7c00)
#define image_2_flow_policer        (0x5304)
#define image_2_general_timer_wakeup_request        (0x53c4)
#define image_2_get_pd_from_fifo        (0x60c8)
#define image_2_group_flow_lkp_and_fwd        (0x3180)
#define image_2_ingress_filter_action_point_update        (0x308c)
#define image_2_ingress_filters_handler        (0x2904)
#define image_2_initialization_task        (0x8)
#define image_2_is_iptv_capable        (0x25e0)
#define image_2_mcast_flow_master_lookup        (0x30d8)
#define image_2_memcpy_abs_to_sbpm        (0xf8)
#define image_2_packet_cso_hw_offload        (0x600c)
#define image_2_parser_exception_handler        (0x23a0)
#define image_2_proccessing_loopback        (0x22e8)
#define image_2_processing_policer_action        (0x5354)
#define image_2_processing_wakeup_request        (0x31c)
#define image_2_spdsvc_natc_lookup        (0x2680)
#define image_2_start_task_add_pbit_to_key        (0x3060)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x5434)
#define image_2_start_task_c_cpu_rx_wakeup_request        (0x55c4)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_2_start_task_check_skip_cso        (0x3000)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x5598)
#define image_2_start_task_cpu_rx_int_coalescing        (0x5f5c)
#define image_2_start_task_cpu_rx_meter_budget_allocator        (0x5fa8)
#define image_2_start_task_debug_routine        (0x30)
#define image_2_start_task_dos_attack_handler        (0x2584)
#define image_2_start_task_drop_pkt_and_serial        (0x2774)
#define image_2_start_task_dyn_code_func        (0x7c00)
#define image_2_start_task_flow_policer        (0x5304)
#define image_2_start_task_general_timer_wakeup_request        (0x53c4)
#define image_2_start_task_get_pd_from_fifo        (0x60c8)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x3180)
#define image_2_start_task_ingress_filter_action_point_update        (0x308c)
#define image_2_start_task_ingress_filters_handler        (0x2904)
#define image_2_start_task_initialization_task        (0x8)
#define image_2_start_task_is_iptv_capable        (0x25e0)
#define image_2_start_task_mcast_flow_master_lookup        (0x30d8)
#define image_2_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_2_start_task_packet_cso_hw_offload        (0x600c)
#define image_2_start_task_parser_exception_handler        (0x23a0)
#define image_2_start_task_proccessing_loopback        (0x22e8)
#define image_2_start_task_processing_policer_action        (0x5354)
#define image_2_start_task_processing_wakeup_request        (0x31c)
#define image_2_start_task_spdsvc_natc_lookup        (0x2680)
#define image_2_start_task_ts_1588_handler        (0x28d0)
#define image_2_start_task_xx_mirror_noinline        (0x2c3c)
#define image_2_ts_1588_handler        (0x28d0)
#define image_2_xx_mirror_noinline        (0x2c3c)

#else

#define image_2_add_pbit_to_key        (0xc18)
#define image_2_c_cpu_recycle_wakeup_request        (0x150d)
#define image_2_c_cpu_rx_wakeup_request        (0x1571)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_2_check_skip_cso        (0xc00)
#define image_2_cpu_recycle_int_coalescing        (0x1566)
#define image_2_cpu_rx_int_coalescing        (0x17d7)
#define image_2_cpu_rx_meter_budget_allocator        (0x17ea)
#define image_2_debug_routine        (0xc)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dos_attack_handler        (0x961)
#define image_2_drop_pkt_and_serial        (0x9dd)
#define image_2_dyn_code_func        (0x1f00)
#define image_2_flow_policer        (0x14c1)
#define image_2_general_timer_wakeup_request        (0x14f1)
#define image_2_get_pd_from_fifo        (0x1832)
#define image_2_group_flow_lkp_and_fwd        (0xc60)
#define image_2_ingress_filter_action_point_update        (0xc23)
#define image_2_ingress_filters_handler        (0xa41)
#define image_2_initialization_task        (0x2)
#define image_2_is_iptv_capable        (0x978)
#define image_2_mcast_flow_master_lookup        (0xc36)
#define image_2_memcpy_abs_to_sbpm        (0x3e)
#define image_2_packet_cso_hw_offload        (0x1803)
#define image_2_parser_exception_handler        (0x8e8)
#define image_2_proccessing_loopback        (0x8ba)
#define image_2_processing_policer_action        (0x14d5)
#define image_2_processing_wakeup_request        (0xc7)
#define image_2_spdsvc_natc_lookup        (0x9a0)
#define image_2_start_task_add_pbit_to_key        (0xc18)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x150d)
#define image_2_start_task_c_cpu_rx_wakeup_request        (0x1571)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_2_start_task_check_skip_cso        (0xc00)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x1566)
#define image_2_start_task_cpu_rx_int_coalescing        (0x17d7)
#define image_2_start_task_cpu_rx_meter_budget_allocator        (0x17ea)
#define image_2_start_task_debug_routine        (0xc)
#define image_2_start_task_dos_attack_handler        (0x961)
#define image_2_start_task_drop_pkt_and_serial        (0x9dd)
#define image_2_start_task_dyn_code_func        (0x1f00)
#define image_2_start_task_flow_policer        (0x14c1)
#define image_2_start_task_general_timer_wakeup_request        (0x14f1)
#define image_2_start_task_get_pd_from_fifo        (0x1832)
#define image_2_start_task_group_flow_lkp_and_fwd        (0xc60)
#define image_2_start_task_ingress_filter_action_point_update        (0xc23)
#define image_2_start_task_ingress_filters_handler        (0xa41)
#define image_2_start_task_initialization_task        (0x2)
#define image_2_start_task_is_iptv_capable        (0x978)
#define image_2_start_task_mcast_flow_master_lookup        (0xc36)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_2_start_task_packet_cso_hw_offload        (0x1803)
#define image_2_start_task_parser_exception_handler        (0x8e8)
#define image_2_start_task_proccessing_loopback        (0x8ba)
#define image_2_start_task_processing_policer_action        (0x14d5)
#define image_2_start_task_processing_wakeup_request        (0xc7)
#define image_2_start_task_spdsvc_natc_lookup        (0x9a0)
#define image_2_start_task_ts_1588_handler        (0xa34)
#define image_2_start_task_xx_mirror_noinline        (0xb0f)
#define image_2_ts_1588_handler        (0xa34)
#define image_2_xx_mirror_noinline        (0xb0f)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3___umulsi3        (0x6cac)
#define image_3_add_pbit_to_key        (0x46d0)
#define image_3_c_cpu_recycle_wakeup_request        (0x6aac)
#define image_3_c_cpu_tx_wakeup_request        (0x4e0)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x4a4)
#define image_3_check_skip_cso        (0x4670)
#define image_3_cpu_recycle_int_coalescing        (0x6c10)
#define image_3_cpu_tx_send_pd_to_recycle        (0x1868)
#define image_3_cpu_tx_sync_tasks        (0x196c)
#define image_3_debug_routine        (0x30)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dos_attack_handler        (0x3bf4)
#define image_3_drop_pkt_and_serial        (0x3de4)
#define image_3_dyn_code_func        (0x7c00)
#define image_3_extension_header_prepend_required        (0x18d4)
#define image_3_flow_policer        (0x6974)
#define image_3_general_timer_wakeup_request        (0x6a34)
#define image_3_group_flow_lkp_and_fwd        (0x47f0)
#define image_3_ingress_filter_action_point_update        (0x46fc)
#define image_3_ingress_filters_handler        (0x3f74)
#define image_3_initialization_task        (0x8)
#define image_3_is_iptv_capable        (0x3c50)
#define image_3_mcast_flow_master_lookup        (0x4748)
#define image_3_memcpy_abs_to_fpm        (0x2e0)
#define image_3_memcpy_abs_to_sbpm        (0xf8)
#define image_3_parser_exception_handler        (0x3a10)
#define image_3_prepend_fpm_extension_header        (0x1900)
#define image_3_proccessing_loopback        (0x3958)
#define image_3_processing_policer_action        (0x69c4)
#define image_3_processing_wakeup_request        (0x198c)
#define image_3_spdsvc_natc_lookup        (0x3cf0)
#define image_3_start_task___umulsi3        (0x6cac)
#define image_3_start_task_add_pbit_to_key        (0x46d0)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x6aac)
#define image_3_start_task_c_cpu_tx_wakeup_request        (0x4e0)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x4a4)
#define image_3_start_task_check_skip_cso        (0x4670)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x6c10)
#define image_3_start_task_cpu_tx_send_pd_to_recycle        (0x1868)
#define image_3_start_task_cpu_tx_sync_tasks        (0x196c)
#define image_3_start_task_debug_routine        (0x30)
#define image_3_start_task_dos_attack_handler        (0x3bf4)
#define image_3_start_task_drop_pkt_and_serial        (0x3de4)
#define image_3_start_task_dyn_code_func        (0x7c00)
#define image_3_start_task_extension_header_prepend_required        (0x18d4)
#define image_3_start_task_flow_policer        (0x6974)
#define image_3_start_task_general_timer_wakeup_request        (0x6a34)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x47f0)
#define image_3_start_task_ingress_filter_action_point_update        (0x46fc)
#define image_3_start_task_ingress_filters_handler        (0x3f74)
#define image_3_start_task_initialization_task        (0x8)
#define image_3_start_task_is_iptv_capable        (0x3c50)
#define image_3_start_task_mcast_flow_master_lookup        (0x4748)
#define image_3_start_task_memcpy_abs_to_fpm        (0x2e0)
#define image_3_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_3_start_task_parser_exception_handler        (0x3a10)
#define image_3_start_task_prepend_fpm_extension_header        (0x1900)
#define image_3_start_task_proccessing_loopback        (0x3958)
#define image_3_start_task_processing_policer_action        (0x69c4)
#define image_3_start_task_processing_wakeup_request        (0x198c)
#define image_3_start_task_spdsvc_natc_lookup        (0x3cf0)
#define image_3_start_task_ts_1588_handler        (0x3f40)
#define image_3_start_task_xx_mirror_noinline        (0x42ac)
#define image_3_ts_1588_handler        (0x3f40)
#define image_3_xx_mirror_noinline        (0x42ac)

#else

#define image_3___umulsi3        (0x1b2b)
#define image_3_add_pbit_to_key        (0x11b4)
#define image_3_c_cpu_recycle_wakeup_request        (0x1aab)
#define image_3_c_cpu_tx_wakeup_request        (0x138)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x129)
#define image_3_check_skip_cso        (0x119c)
#define image_3_cpu_recycle_int_coalescing        (0x1b04)
#define image_3_cpu_tx_send_pd_to_recycle        (0x61a)
#define image_3_cpu_tx_sync_tasks        (0x65b)
#define image_3_debug_routine        (0xc)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dos_attack_handler        (0xefd)
#define image_3_drop_pkt_and_serial        (0xf79)
#define image_3_dyn_code_func        (0x1f00)
#define image_3_extension_header_prepend_required        (0x635)
#define image_3_flow_policer        (0x1a5d)
#define image_3_general_timer_wakeup_request        (0x1a8d)
#define image_3_group_flow_lkp_and_fwd        (0x11fc)
#define image_3_ingress_filter_action_point_update        (0x11bf)
#define image_3_ingress_filters_handler        (0xfdd)
#define image_3_initialization_task        (0x2)
#define image_3_is_iptv_capable        (0xf14)
#define image_3_mcast_flow_master_lookup        (0x11d2)
#define image_3_memcpy_abs_to_fpm        (0xb8)
#define image_3_memcpy_abs_to_sbpm        (0x3e)
#define image_3_parser_exception_handler        (0xe84)
#define image_3_prepend_fpm_extension_header        (0x640)
#define image_3_proccessing_loopback        (0xe56)
#define image_3_processing_policer_action        (0x1a71)
#define image_3_processing_wakeup_request        (0x663)
#define image_3_spdsvc_natc_lookup        (0xf3c)
#define image_3_start_task___umulsi3        (0x1b2b)
#define image_3_start_task_add_pbit_to_key        (0x11b4)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x1aab)
#define image_3_start_task_c_cpu_tx_wakeup_request        (0x138)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x129)
#define image_3_start_task_check_skip_cso        (0x119c)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x1b04)
#define image_3_start_task_cpu_tx_send_pd_to_recycle        (0x61a)
#define image_3_start_task_cpu_tx_sync_tasks        (0x65b)
#define image_3_start_task_debug_routine        (0xc)
#define image_3_start_task_dos_attack_handler        (0xefd)
#define image_3_start_task_drop_pkt_and_serial        (0xf79)
#define image_3_start_task_dyn_code_func        (0x1f00)
#define image_3_start_task_extension_header_prepend_required        (0x635)
#define image_3_start_task_flow_policer        (0x1a5d)
#define image_3_start_task_general_timer_wakeup_request        (0x1a8d)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x11fc)
#define image_3_start_task_ingress_filter_action_point_update        (0x11bf)
#define image_3_start_task_ingress_filters_handler        (0xfdd)
#define image_3_start_task_initialization_task        (0x2)
#define image_3_start_task_is_iptv_capable        (0xf14)
#define image_3_start_task_mcast_flow_master_lookup        (0x11d2)
#define image_3_start_task_memcpy_abs_to_fpm        (0xb8)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_3_start_task_parser_exception_handler        (0xe84)
#define image_3_start_task_prepend_fpm_extension_header        (0x640)
#define image_3_start_task_proccessing_loopback        (0xe56)
#define image_3_start_task_processing_policer_action        (0x1a71)
#define image_3_start_task_processing_wakeup_request        (0x663)
#define image_3_start_task_spdsvc_natc_lookup        (0xf3c)
#define image_3_start_task_ts_1588_handler        (0xfd0)
#define image_3_start_task_xx_mirror_noinline        (0x10ab)
#define image_3_ts_1588_handler        (0xfd0)
#define image_3_xx_mirror_noinline        (0x10ab)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4___umulsi3        (0x6e5c)
#define image_4_add_pbit_to_key        (0x3068)
#define image_4_budget_allocator_tick        (0x6360)
#define image_4_c_spu_request_wakeup_request        (0x53d4)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_4_check_skip_cso        (0x3008)
#define image_4_debug_routine        (0x30)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dos_attack_handler        (0x258c)
#define image_4_drop_pkt_and_serial        (0x277c)
#define image_4_dualq_pi2_stats        (0x60f4)
#define image_4_dyn_code_func        (0x7c00)
#define image_4_flow_policer        (0x5314)
#define image_4_general_timer_wakeup_request        (0x64a4)
#define image_4_get_queue_delay        (0x60b0)
#define image_4_group_flow_lkp_and_fwd        (0x3188)
#define image_4_ingress_filter_action_point_update        (0x3094)
#define image_4_ingress_filters_handler        (0x290c)
#define image_4_initialization_task        (0x8)
#define image_4_is_iptv_capable        (0x25e8)
#define image_4_laqm_deque_check        (0x6234)
#define image_4_mcast_flow_master_lookup        (0x30e0)
#define image_4_memcpy_abs_to_sbpm        (0xf8)
#define image_4_parser_exception_handler        (0x23a8)
#define image_4_pi2_deque_check        (0x6184)
#define image_4_pi2_get_queue_delay        (0x5f44)
#define image_4_pi2_probability_calc        (0x5fb0)
#define image_4_pi2_timer        (0x5e78)
#define image_4_proccessing_loopback        (0x22f0)
#define image_4_processing_policer_action        (0x5364)
#define image_4_processing_wakeup_request        (0x31c)
#define image_4_spdsvc_natc_lookup        (0x2688)
#define image_4_sq_tx_task_wakeup_request        (0x65dc)
#define image_4_start_task___umulsi3        (0x6e5c)
#define image_4_start_task_add_pbit_to_key        (0x3068)
#define image_4_start_task_budget_allocator_tick        (0x6360)
#define image_4_start_task_c_spu_request_wakeup_request        (0x53d4)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_4_start_task_check_skip_cso        (0x3008)
#define image_4_start_task_debug_routine        (0x30)
#define image_4_start_task_dos_attack_handler        (0x258c)
#define image_4_start_task_drop_pkt_and_serial        (0x277c)
#define image_4_start_task_dualq_pi2_stats        (0x60f4)
#define image_4_start_task_dyn_code_func        (0x7c00)
#define image_4_start_task_flow_policer        (0x5314)
#define image_4_start_task_general_timer_wakeup_request        (0x64a4)
#define image_4_start_task_get_queue_delay        (0x60b0)
#define image_4_start_task_group_flow_lkp_and_fwd        (0x3188)
#define image_4_start_task_ingress_filter_action_point_update        (0x3094)
#define image_4_start_task_ingress_filters_handler        (0x290c)
#define image_4_start_task_initialization_task        (0x8)
#define image_4_start_task_is_iptv_capable        (0x25e8)
#define image_4_start_task_laqm_deque_check        (0x6234)
#define image_4_start_task_mcast_flow_master_lookup        (0x30e0)
#define image_4_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_4_start_task_parser_exception_handler        (0x23a8)
#define image_4_start_task_pi2_deque_check        (0x6184)
#define image_4_start_task_pi2_get_queue_delay        (0x5f44)
#define image_4_start_task_pi2_probability_calc        (0x5fb0)
#define image_4_start_task_pi2_timer        (0x5e78)
#define image_4_start_task_proccessing_loopback        (0x22f0)
#define image_4_start_task_processing_policer_action        (0x5364)
#define image_4_start_task_processing_wakeup_request        (0x31c)
#define image_4_start_task_spdsvc_natc_lookup        (0x2688)
#define image_4_start_task_sq_tx_task_wakeup_request        (0x65dc)
#define image_4_start_task_tm_tx_handle_rate_limit        (0x651c)
#define image_4_start_task_ts_1588_handler        (0x28d8)
#define image_4_start_task_xx_mirror_noinline        (0x2c44)
#define image_4_tm_tx_handle_rate_limit        (0x651c)
#define image_4_ts_1588_handler        (0x28d8)
#define image_4_xx_mirror_noinline        (0x2c44)

#else

#define image_4___umulsi3        (0x1b97)
#define image_4_add_pbit_to_key        (0xc1a)
#define image_4_budget_allocator_tick        (0x18d8)
#define image_4_c_spu_request_wakeup_request        (0x14f5)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_4_check_skip_cso        (0xc02)
#define image_4_debug_routine        (0xc)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dos_attack_handler        (0x963)
#define image_4_drop_pkt_and_serial        (0x9df)
#define image_4_dualq_pi2_stats        (0x183d)
#define image_4_dyn_code_func        (0x1f00)
#define image_4_flow_policer        (0x14c5)
#define image_4_general_timer_wakeup_request        (0x1929)
#define image_4_get_queue_delay        (0x182c)
#define image_4_group_flow_lkp_and_fwd        (0xc62)
#define image_4_ingress_filter_action_point_update        (0xc25)
#define image_4_ingress_filters_handler        (0xa43)
#define image_4_initialization_task        (0x2)
#define image_4_is_iptv_capable        (0x97a)
#define image_4_laqm_deque_check        (0x188d)
#define image_4_mcast_flow_master_lookup        (0xc38)
#define image_4_memcpy_abs_to_sbpm        (0x3e)
#define image_4_parser_exception_handler        (0x8ea)
#define image_4_pi2_deque_check        (0x1861)
#define image_4_pi2_get_queue_delay        (0x17d1)
#define image_4_pi2_probability_calc        (0x17ec)
#define image_4_pi2_timer        (0x179e)
#define image_4_proccessing_loopback        (0x8bc)
#define image_4_processing_policer_action        (0x14d9)
#define image_4_processing_wakeup_request        (0xc7)
#define image_4_spdsvc_natc_lookup        (0x9a2)
#define image_4_sq_tx_task_wakeup_request        (0x1977)
#define image_4_start_task___umulsi3        (0x1b97)
#define image_4_start_task_add_pbit_to_key        (0xc1a)
#define image_4_start_task_budget_allocator_tick        (0x18d8)
#define image_4_start_task_c_spu_request_wakeup_request        (0x14f5)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_4_start_task_check_skip_cso        (0xc02)
#define image_4_start_task_debug_routine        (0xc)
#define image_4_start_task_dos_attack_handler        (0x963)
#define image_4_start_task_drop_pkt_and_serial        (0x9df)
#define image_4_start_task_dualq_pi2_stats        (0x183d)
#define image_4_start_task_dyn_code_func        (0x1f00)
#define image_4_start_task_flow_policer        (0x14c5)
#define image_4_start_task_general_timer_wakeup_request        (0x1929)
#define image_4_start_task_get_queue_delay        (0x182c)
#define image_4_start_task_group_flow_lkp_and_fwd        (0xc62)
#define image_4_start_task_ingress_filter_action_point_update        (0xc25)
#define image_4_start_task_ingress_filters_handler        (0xa43)
#define image_4_start_task_initialization_task        (0x2)
#define image_4_start_task_is_iptv_capable        (0x97a)
#define image_4_start_task_laqm_deque_check        (0x188d)
#define image_4_start_task_mcast_flow_master_lookup        (0xc38)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_4_start_task_parser_exception_handler        (0x8ea)
#define image_4_start_task_pi2_deque_check        (0x1861)
#define image_4_start_task_pi2_get_queue_delay        (0x17d1)
#define image_4_start_task_pi2_probability_calc        (0x17ec)
#define image_4_start_task_pi2_timer        (0x179e)
#define image_4_start_task_proccessing_loopback        (0x8bc)
#define image_4_start_task_processing_policer_action        (0x14d9)
#define image_4_start_task_processing_wakeup_request        (0xc7)
#define image_4_start_task_spdsvc_natc_lookup        (0x9a2)
#define image_4_start_task_sq_tx_task_wakeup_request        (0x1977)
#define image_4_start_task_tm_tx_handle_rate_limit        (0x1947)
#define image_4_start_task_ts_1588_handler        (0xa36)
#define image_4_start_task_xx_mirror_noinline        (0xb11)
#define image_4_tm_tx_handle_rate_limit        (0x1947)
#define image_4_ts_1588_handler        (0xa36)
#define image_4_xx_mirror_noinline        (0xb11)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5_add_pbit_to_key        (0x47c4)
#define image_5_c_common_reprocessing_wakeup_request        (0x6b28)
#define image_5_c_spdsvc_gen_wakeup_request        (0x6cc4)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x1a44)
#define image_5_check_skip_cso        (0x4764)
#define image_5_debug_routine        (0x30)
#define image_5_debug_routine_handler        (0x4)
#define image_5_dos_attack_handler        (0x3ce8)
#define image_5_drop_pkt_and_serial        (0x3ed8)
#define image_5_dyn_code_func        (0x7c00)
#define image_5_flow_policer        (0x6a68)
#define image_5_group_flow_lkp_and_fwd        (0x48e4)
#define image_5_ingress_filter_action_point_update        (0x47f0)
#define image_5_ingress_filters_handler        (0x4068)
#define image_5_initialization_task        (0x8)
#define image_5_is_iptv_capable        (0x3d44)
#define image_5_mcast_flow_master_lookup        (0x483c)
#define image_5_memcpy_abs_to_sbpm        (0x185c)
#define image_5_parser_exception_handler        (0x3b04)
#define image_5_proccessing_loopback        (0x3a4c)
#define image_5_processing_policer_action        (0x6ab8)
#define image_5_processing_wakeup_request        (0x1a80)
#define image_5_spdsvc_natc_lookup        (0x3de4)
#define image_5_start_task_add_pbit_to_key        (0x47c4)
#define image_5_start_task_c_common_reprocessing_wakeup_request        (0x6b28)
#define image_5_start_task_c_spdsvc_gen_wakeup_request        (0x6cc4)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x1a44)
#define image_5_start_task_check_skip_cso        (0x4764)
#define image_5_start_task_debug_routine        (0x30)
#define image_5_start_task_dos_attack_handler        (0x3ce8)
#define image_5_start_task_drop_pkt_and_serial        (0x3ed8)
#define image_5_start_task_dyn_code_func        (0x7c00)
#define image_5_start_task_flow_policer        (0x6a68)
#define image_5_start_task_group_flow_lkp_and_fwd        (0x48e4)
#define image_5_start_task_ingress_filter_action_point_update        (0x47f0)
#define image_5_start_task_ingress_filters_handler        (0x4068)
#define image_5_start_task_initialization_task        (0x8)
#define image_5_start_task_is_iptv_capable        (0x3d44)
#define image_5_start_task_mcast_flow_master_lookup        (0x483c)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x185c)
#define image_5_start_task_parser_exception_handler        (0x3b04)
#define image_5_start_task_proccessing_loopback        (0x3a4c)
#define image_5_start_task_processing_policer_action        (0x6ab8)
#define image_5_start_task_processing_wakeup_request        (0x1a80)
#define image_5_start_task_spdsvc_natc_lookup        (0x3de4)
#define image_5_start_task_tcpspdtest_gen_wakeup_request        (0xaf8)
#define image_5_start_task_tcpspdtest_wakeup_request        (0x2b0)
#define image_5_start_task_ts_1588_handler        (0x4034)
#define image_5_start_task_xx_mirror_noinline        (0x43a0)
#define image_5_tcpspdtest_gen_wakeup_request        (0xaf8)
#define image_5_tcpspdtest_task_upload_init        (0xaf8)
#define image_5_tcpspdtest_wakeup_request        (0x2b0)
#define image_5_ts_1588_handler        (0x4034)
#define image_5_xx_mirror_noinline        (0x43a0)

#else

#define image_5_add_pbit_to_key        (0x11f1)
#define image_5_c_common_reprocessing_wakeup_request        (0x1aca)
#define image_5_c_spdsvc_gen_wakeup_request        (0x1b31)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x691)
#define image_5_check_skip_cso        (0x11d9)
#define image_5_debug_routine        (0xc)
#define image_5_debug_routine_handler        (0x1)
#define image_5_dos_attack_handler        (0xf3a)
#define image_5_drop_pkt_and_serial        (0xfb6)
#define image_5_dyn_code_func        (0x1f00)
#define image_5_flow_policer        (0x1a9a)
#define image_5_group_flow_lkp_and_fwd        (0x1239)
#define image_5_ingress_filter_action_point_update        (0x11fc)
#define image_5_ingress_filters_handler        (0x101a)
#define image_5_initialization_task        (0x2)
#define image_5_is_iptv_capable        (0xf51)
#define image_5_mcast_flow_master_lookup        (0x120f)
#define image_5_memcpy_abs_to_sbpm        (0x617)
#define image_5_parser_exception_handler        (0xec1)
#define image_5_proccessing_loopback        (0xe93)
#define image_5_processing_policer_action        (0x1aae)
#define image_5_processing_wakeup_request        (0x6a0)
#define image_5_spdsvc_natc_lookup        (0xf79)
#define image_5_start_task_add_pbit_to_key        (0x11f1)
#define image_5_start_task_c_common_reprocessing_wakeup_request        (0x1aca)
#define image_5_start_task_c_spdsvc_gen_wakeup_request        (0x1b31)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x691)
#define image_5_start_task_check_skip_cso        (0x11d9)
#define image_5_start_task_debug_routine        (0xc)
#define image_5_start_task_dos_attack_handler        (0xf3a)
#define image_5_start_task_drop_pkt_and_serial        (0xfb6)
#define image_5_start_task_dyn_code_func        (0x1f00)
#define image_5_start_task_flow_policer        (0x1a9a)
#define image_5_start_task_group_flow_lkp_and_fwd        (0x1239)
#define image_5_start_task_ingress_filter_action_point_update        (0x11fc)
#define image_5_start_task_ingress_filters_handler        (0x101a)
#define image_5_start_task_initialization_task        (0x2)
#define image_5_start_task_is_iptv_capable        (0xf51)
#define image_5_start_task_mcast_flow_master_lookup        (0x120f)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x617)
#define image_5_start_task_parser_exception_handler        (0xec1)
#define image_5_start_task_proccessing_loopback        (0xe93)
#define image_5_start_task_processing_policer_action        (0x1aae)
#define image_5_start_task_processing_wakeup_request        (0x6a0)
#define image_5_start_task_spdsvc_natc_lookup        (0xf79)
#define image_5_start_task_tcpspdtest_gen_wakeup_request        (0x2be)
#define image_5_start_task_tcpspdtest_wakeup_request        (0xac)
#define image_5_start_task_ts_1588_handler        (0x100d)
#define image_5_start_task_xx_mirror_noinline        (0x10e8)
#define image_5_tcpspdtest_gen_wakeup_request        (0x2be)
#define image_5_tcpspdtest_task_upload_init        (0x2be)
#define image_5_tcpspdtest_wakeup_request        (0xac)
#define image_5_ts_1588_handler        (0x100d)
#define image_5_xx_mirror_noinline        (0x10e8)

#endif


#endif

/* IMAGE 6 LABELS */
#ifndef IMAGE_6_CODE_ADDRESSES
#define IMAGE_6_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_6_add_pbit_to_key        (0x3040)
#define image_6_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_6_check_skip_cso        (0x2fe0)
#define image_6_debug_routine        (0x30)
#define image_6_debug_routine_handler        (0x4)
#define image_6_dos_attack_handler        (0x2564)
#define image_6_drop_pkt_and_serial        (0x2754)
#define image_6_dyn_code_func        (0x7c00)
#define image_6_flow_policer        (0x52d8)
#define image_6_group_flow_lkp_and_fwd        (0x3160)
#define image_6_ingress_filter_action_point_update        (0x306c)
#define image_6_ingress_filters_handler        (0x28e4)
#define image_6_initialization_task        (0x8)
#define image_6_is_iptv_capable        (0x25c0)
#define image_6_mcast_flow_master_lookup        (0x30b8)
#define image_6_memcpy_abs_to_sbpm        (0xf8)
#define image_6_parser_exception_handler        (0x2380)
#define image_6_proccessing_loopback        (0x22c8)
#define image_6_processing_policer_action        (0x5328)
#define image_6_processing_wakeup_request        (0x31c)
#define image_6_spdsvc_natc_lookup        (0x2660)
#define image_6_start_task_add_pbit_to_key        (0x3040)
#define image_6_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_6_start_task_check_skip_cso        (0x2fe0)
#define image_6_start_task_debug_routine        (0x30)
#define image_6_start_task_dos_attack_handler        (0x2564)
#define image_6_start_task_drop_pkt_and_serial        (0x2754)
#define image_6_start_task_dyn_code_func        (0x7c00)
#define image_6_start_task_flow_policer        (0x52d8)
#define image_6_start_task_group_flow_lkp_and_fwd        (0x3160)
#define image_6_start_task_ingress_filter_action_point_update        (0x306c)
#define image_6_start_task_ingress_filters_handler        (0x28e4)
#define image_6_start_task_initialization_task        (0x8)
#define image_6_start_task_is_iptv_capable        (0x25c0)
#define image_6_start_task_mcast_flow_master_lookup        (0x30b8)
#define image_6_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_6_start_task_parser_exception_handler        (0x2380)
#define image_6_start_task_proccessing_loopback        (0x22c8)
#define image_6_start_task_processing_policer_action        (0x5328)
#define image_6_start_task_processing_wakeup_request        (0x31c)
#define image_6_start_task_spdsvc_natc_lookup        (0x2660)
#define image_6_start_task_ts_1588_handler        (0x28b0)
#define image_6_start_task_xx_mirror_noinline        (0x2c1c)
#define image_6_ts_1588_handler        (0x28b0)
#define image_6_xx_mirror_noinline        (0x2c1c)

#else

#define image_6_add_pbit_to_key        (0xc10)
#define image_6_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_6_check_skip_cso        (0xbf8)
#define image_6_debug_routine        (0xc)
#define image_6_debug_routine_handler        (0x1)
#define image_6_dos_attack_handler        (0x959)
#define image_6_drop_pkt_and_serial        (0x9d5)
#define image_6_dyn_code_func        (0x1f00)
#define image_6_flow_policer        (0x14b6)
#define image_6_group_flow_lkp_and_fwd        (0xc58)
#define image_6_ingress_filter_action_point_update        (0xc1b)
#define image_6_ingress_filters_handler        (0xa39)
#define image_6_initialization_task        (0x2)
#define image_6_is_iptv_capable        (0x970)
#define image_6_mcast_flow_master_lookup        (0xc2e)
#define image_6_memcpy_abs_to_sbpm        (0x3e)
#define image_6_parser_exception_handler        (0x8e0)
#define image_6_proccessing_loopback        (0x8b2)
#define image_6_processing_policer_action        (0x14ca)
#define image_6_processing_wakeup_request        (0xc7)
#define image_6_spdsvc_natc_lookup        (0x998)
#define image_6_start_task_add_pbit_to_key        (0xc10)
#define image_6_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_6_start_task_check_skip_cso        (0xbf8)
#define image_6_start_task_debug_routine        (0xc)
#define image_6_start_task_dos_attack_handler        (0x959)
#define image_6_start_task_drop_pkt_and_serial        (0x9d5)
#define image_6_start_task_dyn_code_func        (0x1f00)
#define image_6_start_task_flow_policer        (0x14b6)
#define image_6_start_task_group_flow_lkp_and_fwd        (0xc58)
#define image_6_start_task_ingress_filter_action_point_update        (0xc1b)
#define image_6_start_task_ingress_filters_handler        (0xa39)
#define image_6_start_task_initialization_task        (0x2)
#define image_6_start_task_is_iptv_capable        (0x970)
#define image_6_start_task_mcast_flow_master_lookup        (0xc2e)
#define image_6_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_6_start_task_parser_exception_handler        (0x8e0)
#define image_6_start_task_proccessing_loopback        (0x8b2)
#define image_6_start_task_processing_policer_action        (0x14ca)
#define image_6_start_task_processing_wakeup_request        (0xc7)
#define image_6_start_task_spdsvc_natc_lookup        (0x998)
#define image_6_start_task_ts_1588_handler        (0xa2c)
#define image_6_start_task_xx_mirror_noinline        (0xb07)
#define image_6_ts_1588_handler        (0xa2c)
#define image_6_xx_mirror_noinline        (0xb07)

#endif


#endif

/* IMAGE 7 LABELS */
#ifndef IMAGE_7_CODE_ADDRESSES
#define IMAGE_7_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_7_add_pbit_to_key        (0x3040)
#define image_7_c_spdsvc_analyzer_wakeup_request        (0x5398)
#define image_7_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_7_check_skip_cso        (0x2fe0)
#define image_7_debug_routine        (0x30)
#define image_7_debug_routine_handler        (0x4)
#define image_7_dos_attack_handler        (0x2564)
#define image_7_drop_pkt_and_serial        (0x2754)
#define image_7_dyn_code_func        (0x7c00)
#define image_7_flow_policer        (0x52d8)
#define image_7_group_flow_lkp_and_fwd        (0x3160)
#define image_7_ingress_filter_action_point_update        (0x306c)
#define image_7_ingress_filters_handler        (0x28e4)
#define image_7_initialization_task        (0x8)
#define image_7_is_iptv_capable        (0x25c0)
#define image_7_mcast_flow_master_lookup        (0x30b8)
#define image_7_memcpy_abs_to_sbpm        (0xf8)
#define image_7_parser_exception_handler        (0x2380)
#define image_7_proccessing_loopback        (0x22c8)
#define image_7_processing_policer_action        (0x5328)
#define image_7_processing_wakeup_request        (0x31c)
#define image_7_spdsvc_natc_lookup        (0x2660)
#define image_7_spdt_brcm_spdsvc_rx_handler        (0x5764)
#define image_7_spdt_udp_basic_rx_handler        (0x54d0)
#define image_7_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x5838)
#define image_7_spdt_udp_iperf3_rx_handler        (0x5584)
#define image_7_spdt_unsupported_proto_rx_handler        (0x57d4)
#define image_7_start_task_add_pbit_to_key        (0x3040)
#define image_7_start_task_c_spdsvc_analyzer_wakeup_request        (0x5398)
#define image_7_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_7_start_task_check_skip_cso        (0x2fe0)
#define image_7_start_task_debug_routine        (0x30)
#define image_7_start_task_dos_attack_handler        (0x2564)
#define image_7_start_task_drop_pkt_and_serial        (0x2754)
#define image_7_start_task_dyn_code_func        (0x7c00)
#define image_7_start_task_flow_policer        (0x52d8)
#define image_7_start_task_group_flow_lkp_and_fwd        (0x3160)
#define image_7_start_task_ingress_filter_action_point_update        (0x306c)
#define image_7_start_task_ingress_filters_handler        (0x28e4)
#define image_7_start_task_initialization_task        (0x8)
#define image_7_start_task_is_iptv_capable        (0x25c0)
#define image_7_start_task_mcast_flow_master_lookup        (0x30b8)
#define image_7_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_7_start_task_parser_exception_handler        (0x2380)
#define image_7_start_task_proccessing_loopback        (0x22c8)
#define image_7_start_task_processing_policer_action        (0x5328)
#define image_7_start_task_processing_wakeup_request        (0x31c)
#define image_7_start_task_spdsvc_natc_lookup        (0x2660)
#define image_7_start_task_spdt_brcm_spdsvc_rx_handler        (0x5764)
#define image_7_start_task_spdt_udp_basic_rx_handler        (0x54d0)
#define image_7_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x5838)
#define image_7_start_task_spdt_udp_iperf3_rx_handler        (0x5584)
#define image_7_start_task_spdt_unsupported_proto_rx_handler        (0x57d4)
#define image_7_start_task_ts_1588_handler        (0x28b0)
#define image_7_start_task_xx_mirror_noinline        (0x2c1c)
#define image_7_ts_1588_handler        (0x28b0)
#define image_7_xx_mirror_noinline        (0x2c1c)

#else

#define image_7_add_pbit_to_key        (0xc10)
#define image_7_c_spdsvc_analyzer_wakeup_request        (0x14e6)
#define image_7_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_7_check_skip_cso        (0xbf8)
#define image_7_debug_routine        (0xc)
#define image_7_debug_routine_handler        (0x1)
#define image_7_dos_attack_handler        (0x959)
#define image_7_drop_pkt_and_serial        (0x9d5)
#define image_7_dyn_code_func        (0x1f00)
#define image_7_flow_policer        (0x14b6)
#define image_7_group_flow_lkp_and_fwd        (0xc58)
#define image_7_ingress_filter_action_point_update        (0xc1b)
#define image_7_ingress_filters_handler        (0xa39)
#define image_7_initialization_task        (0x2)
#define image_7_is_iptv_capable        (0x970)
#define image_7_mcast_flow_master_lookup        (0xc2e)
#define image_7_memcpy_abs_to_sbpm        (0x3e)
#define image_7_parser_exception_handler        (0x8e0)
#define image_7_proccessing_loopback        (0x8b2)
#define image_7_processing_policer_action        (0x14ca)
#define image_7_processing_wakeup_request        (0xc7)
#define image_7_spdsvc_natc_lookup        (0x998)
#define image_7_spdt_brcm_spdsvc_rx_handler        (0x15d9)
#define image_7_spdt_udp_basic_rx_handler        (0x1534)
#define image_7_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x160e)
#define image_7_spdt_udp_iperf3_rx_handler        (0x1561)
#define image_7_spdt_unsupported_proto_rx_handler        (0x15f5)
#define image_7_start_task_add_pbit_to_key        (0xc10)
#define image_7_start_task_c_spdsvc_analyzer_wakeup_request        (0x14e6)
#define image_7_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_7_start_task_check_skip_cso        (0xbf8)
#define image_7_start_task_debug_routine        (0xc)
#define image_7_start_task_dos_attack_handler        (0x959)
#define image_7_start_task_drop_pkt_and_serial        (0x9d5)
#define image_7_start_task_dyn_code_func        (0x1f00)
#define image_7_start_task_flow_policer        (0x14b6)
#define image_7_start_task_group_flow_lkp_and_fwd        (0xc58)
#define image_7_start_task_ingress_filter_action_point_update        (0xc1b)
#define image_7_start_task_ingress_filters_handler        (0xa39)
#define image_7_start_task_initialization_task        (0x2)
#define image_7_start_task_is_iptv_capable        (0x970)
#define image_7_start_task_mcast_flow_master_lookup        (0xc2e)
#define image_7_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_7_start_task_parser_exception_handler        (0x8e0)
#define image_7_start_task_proccessing_loopback        (0x8b2)
#define image_7_start_task_processing_policer_action        (0x14ca)
#define image_7_start_task_processing_wakeup_request        (0xc7)
#define image_7_start_task_spdsvc_natc_lookup        (0x998)
#define image_7_start_task_spdt_brcm_spdsvc_rx_handler        (0x15d9)
#define image_7_start_task_spdt_udp_basic_rx_handler        (0x1534)
#define image_7_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x160e)
#define image_7_start_task_spdt_udp_iperf3_rx_handler        (0x1561)
#define image_7_start_task_spdt_unsupported_proto_rx_handler        (0x15f5)
#define image_7_start_task_ts_1588_handler        (0xa2c)
#define image_7_start_task_xx_mirror_noinline        (0xb07)
#define image_7_ts_1588_handler        (0xa2c)
#define image_7_xx_mirror_noinline        (0xb07)

#endif


#endif

/* IMAGE 8 LABELS */
#ifndef IMAGE_8_CODE_ADDRESSES
#define IMAGE_8_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_8_add_pbit_to_key        (0x3060)
#define image_8_c_spu_response_wakeup_request        (0x53c4)
#define image_8_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_8_check_skip_cso        (0x3000)
#define image_8_debug_routine        (0x30)
#define image_8_debug_routine_handler        (0x4)
#define image_8_dos_attack_handler        (0x2584)
#define image_8_drop_pkt_and_serial        (0x2774)
#define image_8_dyn_code_func        (0x7c00)
#define image_8_flow_policer        (0x5304)
#define image_8_group_flow_lkp_and_fwd        (0x3180)
#define image_8_ingress_filter_action_point_update        (0x308c)
#define image_8_ingress_filters_handler        (0x2904)
#define image_8_initialization_task        (0x8)
#define image_8_is_iptv_capable        (0x25e0)
#define image_8_mcast_flow_master_lookup        (0x30d8)
#define image_8_memcpy_abs_to_sbpm        (0xf8)
#define image_8_parser_exception_handler        (0x23a0)
#define image_8_proccessing_loopback        (0x22e8)
#define image_8_processing_policer_action        (0x5354)
#define image_8_processing_wakeup_request        (0x31c)
#define image_8_spdsvc_natc_lookup        (0x2680)
#define image_8_start_task_add_pbit_to_key        (0x3060)
#define image_8_start_task_c_spu_response_wakeup_request        (0x53c4)
#define image_8_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_8_start_task_check_skip_cso        (0x3000)
#define image_8_start_task_debug_routine        (0x30)
#define image_8_start_task_dos_attack_handler        (0x2584)
#define image_8_start_task_drop_pkt_and_serial        (0x2774)
#define image_8_start_task_dyn_code_func        (0x7c00)
#define image_8_start_task_flow_policer        (0x5304)
#define image_8_start_task_group_flow_lkp_and_fwd        (0x3180)
#define image_8_start_task_ingress_filter_action_point_update        (0x308c)
#define image_8_start_task_ingress_filters_handler        (0x2904)
#define image_8_start_task_initialization_task        (0x8)
#define image_8_start_task_is_iptv_capable        (0x25e0)
#define image_8_start_task_mcast_flow_master_lookup        (0x30d8)
#define image_8_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_8_start_task_parser_exception_handler        (0x23a0)
#define image_8_start_task_proccessing_loopback        (0x22e8)
#define image_8_start_task_processing_policer_action        (0x5354)
#define image_8_start_task_processing_wakeup_request        (0x31c)
#define image_8_start_task_spdsvc_natc_lookup        (0x2680)
#define image_8_start_task_ts_1588_handler        (0x28d0)
#define image_8_start_task_xx_mirror_noinline        (0x2c3c)
#define image_8_ts_1588_handler        (0x28d0)
#define image_8_xx_mirror_noinline        (0x2c3c)

#else

#define image_8_add_pbit_to_key        (0xc18)
#define image_8_c_spu_response_wakeup_request        (0x14f1)
#define image_8_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_8_check_skip_cso        (0xc00)
#define image_8_debug_routine        (0xc)
#define image_8_debug_routine_handler        (0x1)
#define image_8_dos_attack_handler        (0x961)
#define image_8_drop_pkt_and_serial        (0x9dd)
#define image_8_dyn_code_func        (0x1f00)
#define image_8_flow_policer        (0x14c1)
#define image_8_group_flow_lkp_and_fwd        (0xc60)
#define image_8_ingress_filter_action_point_update        (0xc23)
#define image_8_ingress_filters_handler        (0xa41)
#define image_8_initialization_task        (0x2)
#define image_8_is_iptv_capable        (0x978)
#define image_8_mcast_flow_master_lookup        (0xc36)
#define image_8_memcpy_abs_to_sbpm        (0x3e)
#define image_8_parser_exception_handler        (0x8e8)
#define image_8_proccessing_loopback        (0x8ba)
#define image_8_processing_policer_action        (0x14d5)
#define image_8_processing_wakeup_request        (0xc7)
#define image_8_spdsvc_natc_lookup        (0x9a0)
#define image_8_start_task_add_pbit_to_key        (0xc18)
#define image_8_start_task_c_spu_response_wakeup_request        (0x14f1)
#define image_8_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_8_start_task_check_skip_cso        (0xc00)
#define image_8_start_task_debug_routine        (0xc)
#define image_8_start_task_dos_attack_handler        (0x961)
#define image_8_start_task_drop_pkt_and_serial        (0x9dd)
#define image_8_start_task_dyn_code_func        (0x1f00)
#define image_8_start_task_flow_policer        (0x14c1)
#define image_8_start_task_group_flow_lkp_and_fwd        (0xc60)
#define image_8_start_task_ingress_filter_action_point_update        (0xc23)
#define image_8_start_task_ingress_filters_handler        (0xa41)
#define image_8_start_task_initialization_task        (0x2)
#define image_8_start_task_is_iptv_capable        (0x978)
#define image_8_start_task_mcast_flow_master_lookup        (0xc36)
#define image_8_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_8_start_task_parser_exception_handler        (0x8e8)
#define image_8_start_task_proccessing_loopback        (0x8ba)
#define image_8_start_task_processing_policer_action        (0x14d5)
#define image_8_start_task_processing_wakeup_request        (0xc7)
#define image_8_start_task_spdsvc_natc_lookup        (0x9a0)
#define image_8_start_task_ts_1588_handler        (0xa34)
#define image_8_start_task_xx_mirror_noinline        (0xb0f)
#define image_8_ts_1588_handler        (0xa34)
#define image_8_xx_mirror_noinline        (0xb0f)

#endif


#endif

/* IMAGE 9 LABELS */
#ifndef IMAGE_9_CODE_ADDRESSES
#define IMAGE_9_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_9___umulsi3        (0x66ec)
#define image_9_add_pbit_to_key        (0x3060)
#define image_9_budget_allocator_tick        (0x58a8)
#define image_9_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_9_check_skip_cso        (0x3000)
#define image_9_debug_routine        (0x30)
#define image_9_debug_routine_handler        (0x4)
#define image_9_dos_attack_handler        (0x2584)
#define image_9_drop_pkt_and_serial        (0x2774)
#define image_9_dualq_pi2_stats        (0x563c)
#define image_9_dyn_code_func        (0x7c00)
#define image_9_flow_policer        (0x5304)
#define image_9_general_timer_wakeup_request        (0x6674)
#define image_9_get_queue_delay        (0x55f8)
#define image_9_group_flow_lkp_and_fwd        (0x3180)
#define image_9_handle_flush        (0x5be8)
#define image_9_ingress_filter_action_point_update        (0x308c)
#define image_9_ingress_filters_handler        (0x2904)
#define image_9_initialization_task        (0x8)
#define image_9_is_iptv_capable        (0x25e0)
#define image_9_laqm_deque_check        (0x577c)
#define image_9_mcast_flow_master_lookup        (0x30d8)
#define image_9_memcpy_abs_to_sbpm        (0xf8)
#define image_9_parser_exception_handler        (0x23a0)
#define image_9_pi2_deque_check        (0x56cc)
#define image_9_pi2_get_queue_delay        (0x548c)
#define image_9_pi2_probability_calc        (0x54f8)
#define image_9_pi2_timer        (0x53c4)
#define image_9_proccessing_loopback        (0x22e8)
#define image_9_processing_policer_action        (0x5354)
#define image_9_processing_wakeup_request        (0x31c)
#define image_9_spdsvc_natc_lookup        (0x2680)
#define image_9_start_task___umulsi3        (0x66ec)
#define image_9_start_task_add_pbit_to_key        (0x3060)
#define image_9_start_task_budget_allocator_tick        (0x58a8)
#define image_9_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_9_start_task_check_skip_cso        (0x3000)
#define image_9_start_task_debug_routine        (0x30)
#define image_9_start_task_dos_attack_handler        (0x2584)
#define image_9_start_task_drop_pkt_and_serial        (0x2774)
#define image_9_start_task_dualq_pi2_stats        (0x563c)
#define image_9_start_task_dyn_code_func        (0x7c00)
#define image_9_start_task_flow_policer        (0x5304)
#define image_9_start_task_general_timer_wakeup_request        (0x6674)
#define image_9_start_task_get_queue_delay        (0x55f8)
#define image_9_start_task_group_flow_lkp_and_fwd        (0x3180)
#define image_9_start_task_handle_flush        (0x5be8)
#define image_9_start_task_ingress_filter_action_point_update        (0x308c)
#define image_9_start_task_ingress_filters_handler        (0x2904)
#define image_9_start_task_initialization_task        (0x8)
#define image_9_start_task_is_iptv_capable        (0x25e0)
#define image_9_start_task_laqm_deque_check        (0x577c)
#define image_9_start_task_mcast_flow_master_lookup        (0x30d8)
#define image_9_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_9_start_task_parser_exception_handler        (0x23a0)
#define image_9_start_task_pi2_deque_check        (0x56cc)
#define image_9_start_task_pi2_get_queue_delay        (0x548c)
#define image_9_start_task_pi2_probability_calc        (0x54f8)
#define image_9_start_task_pi2_timer        (0x53c4)
#define image_9_start_task_proccessing_loopback        (0x22e8)
#define image_9_start_task_processing_policer_action        (0x5354)
#define image_9_start_task_processing_wakeup_request        (0x31c)
#define image_9_start_task_spdsvc_natc_lookup        (0x2680)
#define image_9_start_task_tm_tx_handle_rate_limit        (0x59ec)
#define image_9_start_task_tm_tx_mirroring_handle        (0x645c)
#define image_9_start_task_tm_tx_task_wakeup_request        (0x5ce8)
#define image_9_start_task_tm_update_fifo_first_wakeup_request        (0x5aac)
#define image_9_start_task_ts_1588_handler        (0x28d0)
#define image_9_start_task_tx_mirror        (0x64fc)
#define image_9_start_task_xx_mirror_noinline        (0x2c3c)
#define image_9_tm_tx_handle_rate_limit        (0x59ec)
#define image_9_tm_tx_mirroring_handle        (0x645c)
#define image_9_tm_tx_task_wakeup_request        (0x5ce8)
#define image_9_tm_update_fifo_first_wakeup_request        (0x5aac)
#define image_9_ts_1588_handler        (0x28d0)
#define image_9_tx_mirror        (0x64fc)
#define image_9_xx_mirror_noinline        (0x2c3c)

#else

#define image_9___umulsi3        (0x19bb)
#define image_9_add_pbit_to_key        (0xc18)
#define image_9_budget_allocator_tick        (0x162a)
#define image_9_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_9_check_skip_cso        (0xc00)
#define image_9_debug_routine        (0xc)
#define image_9_debug_routine_handler        (0x1)
#define image_9_dos_attack_handler        (0x961)
#define image_9_drop_pkt_and_serial        (0x9dd)
#define image_9_dualq_pi2_stats        (0x158f)
#define image_9_dyn_code_func        (0x1f00)
#define image_9_flow_policer        (0x14c1)
#define image_9_general_timer_wakeup_request        (0x199d)
#define image_9_get_queue_delay        (0x157e)
#define image_9_group_flow_lkp_and_fwd        (0xc60)
#define image_9_handle_flush        (0x16fa)
#define image_9_ingress_filter_action_point_update        (0xc23)
#define image_9_ingress_filters_handler        (0xa41)
#define image_9_initialization_task        (0x2)
#define image_9_is_iptv_capable        (0x978)
#define image_9_laqm_deque_check        (0x15df)
#define image_9_mcast_flow_master_lookup        (0xc36)
#define image_9_memcpy_abs_to_sbpm        (0x3e)
#define image_9_parser_exception_handler        (0x8e8)
#define image_9_pi2_deque_check        (0x15b3)
#define image_9_pi2_get_queue_delay        (0x1523)
#define image_9_pi2_probability_calc        (0x153e)
#define image_9_pi2_timer        (0x14f1)
#define image_9_proccessing_loopback        (0x8ba)
#define image_9_processing_policer_action        (0x14d5)
#define image_9_processing_wakeup_request        (0xc7)
#define image_9_spdsvc_natc_lookup        (0x9a0)
#define image_9_start_task___umulsi3        (0x19bb)
#define image_9_start_task_add_pbit_to_key        (0xc18)
#define image_9_start_task_budget_allocator_tick        (0x162a)
#define image_9_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_9_start_task_check_skip_cso        (0xc00)
#define image_9_start_task_debug_routine        (0xc)
#define image_9_start_task_dos_attack_handler        (0x961)
#define image_9_start_task_drop_pkt_and_serial        (0x9dd)
#define image_9_start_task_dualq_pi2_stats        (0x158f)
#define image_9_start_task_dyn_code_func        (0x1f00)
#define image_9_start_task_flow_policer        (0x14c1)
#define image_9_start_task_general_timer_wakeup_request        (0x199d)
#define image_9_start_task_get_queue_delay        (0x157e)
#define image_9_start_task_group_flow_lkp_and_fwd        (0xc60)
#define image_9_start_task_handle_flush        (0x16fa)
#define image_9_start_task_ingress_filter_action_point_update        (0xc23)
#define image_9_start_task_ingress_filters_handler        (0xa41)
#define image_9_start_task_initialization_task        (0x2)
#define image_9_start_task_is_iptv_capable        (0x978)
#define image_9_start_task_laqm_deque_check        (0x15df)
#define image_9_start_task_mcast_flow_master_lookup        (0xc36)
#define image_9_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_9_start_task_parser_exception_handler        (0x8e8)
#define image_9_start_task_pi2_deque_check        (0x15b3)
#define image_9_start_task_pi2_get_queue_delay        (0x1523)
#define image_9_start_task_pi2_probability_calc        (0x153e)
#define image_9_start_task_pi2_timer        (0x14f1)
#define image_9_start_task_proccessing_loopback        (0x8ba)
#define image_9_start_task_processing_policer_action        (0x14d5)
#define image_9_start_task_processing_wakeup_request        (0xc7)
#define image_9_start_task_spdsvc_natc_lookup        (0x9a0)
#define image_9_start_task_tm_tx_handle_rate_limit        (0x167b)
#define image_9_start_task_tm_tx_mirroring_handle        (0x1917)
#define image_9_start_task_tm_tx_task_wakeup_request        (0x173a)
#define image_9_start_task_tm_update_fifo_first_wakeup_request        (0x16ab)
#define image_9_start_task_ts_1588_handler        (0xa34)
#define image_9_start_task_tx_mirror        (0x193f)
#define image_9_start_task_xx_mirror_noinline        (0xb0f)
#define image_9_tm_tx_handle_rate_limit        (0x167b)
#define image_9_tm_tx_mirroring_handle        (0x1917)
#define image_9_tm_tx_task_wakeup_request        (0x173a)
#define image_9_tm_update_fifo_first_wakeup_request        (0x16ab)
#define image_9_ts_1588_handler        (0xa34)
#define image_9_tx_mirror        (0x193f)
#define image_9_xx_mirror_noinline        (0xb0f)

#endif


#endif

/* IMAGE 10 LABELS */
#ifndef IMAGE_10_CODE_ADDRESSES
#define IMAGE_10_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_10___umulsi3        (0x66ec)
#define image_10_add_pbit_to_key        (0x3060)
#define image_10_budget_allocator_tick        (0x58a8)
#define image_10_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_10_check_skip_cso        (0x3000)
#define image_10_debug_routine        (0x30)
#define image_10_debug_routine_handler        (0x4)
#define image_10_dos_attack_handler        (0x2584)
#define image_10_drop_pkt_and_serial        (0x2774)
#define image_10_dualq_pi2_stats        (0x563c)
#define image_10_dyn_code_func        (0x7c00)
#define image_10_flow_policer        (0x5304)
#define image_10_general_timer_wakeup_request        (0x6674)
#define image_10_get_queue_delay        (0x55f8)
#define image_10_group_flow_lkp_and_fwd        (0x3180)
#define image_10_handle_flush        (0x5be8)
#define image_10_ingress_filter_action_point_update        (0x308c)
#define image_10_ingress_filters_handler        (0x2904)
#define image_10_initialization_task        (0x8)
#define image_10_is_iptv_capable        (0x25e0)
#define image_10_laqm_deque_check        (0x577c)
#define image_10_mcast_flow_master_lookup        (0x30d8)
#define image_10_memcpy_abs_to_sbpm        (0xf8)
#define image_10_parser_exception_handler        (0x23a0)
#define image_10_pi2_deque_check        (0x56cc)
#define image_10_pi2_get_queue_delay        (0x548c)
#define image_10_pi2_probability_calc        (0x54f8)
#define image_10_pi2_timer        (0x53c4)
#define image_10_proccessing_loopback        (0x22e8)
#define image_10_processing_policer_action        (0x5354)
#define image_10_processing_wakeup_request        (0x31c)
#define image_10_spdsvc_natc_lookup        (0x2680)
#define image_10_start_task___umulsi3        (0x66ec)
#define image_10_start_task_add_pbit_to_key        (0x3060)
#define image_10_start_task_budget_allocator_tick        (0x58a8)
#define image_10_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_10_start_task_check_skip_cso        (0x3000)
#define image_10_start_task_debug_routine        (0x30)
#define image_10_start_task_dos_attack_handler        (0x2584)
#define image_10_start_task_drop_pkt_and_serial        (0x2774)
#define image_10_start_task_dualq_pi2_stats        (0x563c)
#define image_10_start_task_dyn_code_func        (0x7c00)
#define image_10_start_task_flow_policer        (0x5304)
#define image_10_start_task_general_timer_wakeup_request        (0x6674)
#define image_10_start_task_get_queue_delay        (0x55f8)
#define image_10_start_task_group_flow_lkp_and_fwd        (0x3180)
#define image_10_start_task_handle_flush        (0x5be8)
#define image_10_start_task_ingress_filter_action_point_update        (0x308c)
#define image_10_start_task_ingress_filters_handler        (0x2904)
#define image_10_start_task_initialization_task        (0x8)
#define image_10_start_task_is_iptv_capable        (0x25e0)
#define image_10_start_task_laqm_deque_check        (0x577c)
#define image_10_start_task_mcast_flow_master_lookup        (0x30d8)
#define image_10_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_10_start_task_parser_exception_handler        (0x23a0)
#define image_10_start_task_pi2_deque_check        (0x56cc)
#define image_10_start_task_pi2_get_queue_delay        (0x548c)
#define image_10_start_task_pi2_probability_calc        (0x54f8)
#define image_10_start_task_pi2_timer        (0x53c4)
#define image_10_start_task_proccessing_loopback        (0x22e8)
#define image_10_start_task_processing_policer_action        (0x5354)
#define image_10_start_task_processing_wakeup_request        (0x31c)
#define image_10_start_task_spdsvc_natc_lookup        (0x2680)
#define image_10_start_task_tm_tx_handle_rate_limit        (0x59ec)
#define image_10_start_task_tm_tx_mirroring_handle        (0x645c)
#define image_10_start_task_tm_tx_task_wakeup_request        (0x5ce8)
#define image_10_start_task_tm_update_fifo_first_wakeup_request        (0x5aac)
#define image_10_start_task_ts_1588_handler        (0x28d0)
#define image_10_start_task_tx_mirror        (0x64fc)
#define image_10_start_task_xx_mirror_noinline        (0x2c3c)
#define image_10_tm_tx_handle_rate_limit        (0x59ec)
#define image_10_tm_tx_mirroring_handle        (0x645c)
#define image_10_tm_tx_task_wakeup_request        (0x5ce8)
#define image_10_tm_update_fifo_first_wakeup_request        (0x5aac)
#define image_10_ts_1588_handler        (0x28d0)
#define image_10_tx_mirror        (0x64fc)
#define image_10_xx_mirror_noinline        (0x2c3c)

#else

#define image_10___umulsi3        (0x19bb)
#define image_10_add_pbit_to_key        (0xc18)
#define image_10_budget_allocator_tick        (0x162a)
#define image_10_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_10_check_skip_cso        (0xc00)
#define image_10_debug_routine        (0xc)
#define image_10_debug_routine_handler        (0x1)
#define image_10_dos_attack_handler        (0x961)
#define image_10_drop_pkt_and_serial        (0x9dd)
#define image_10_dualq_pi2_stats        (0x158f)
#define image_10_dyn_code_func        (0x1f00)
#define image_10_flow_policer        (0x14c1)
#define image_10_general_timer_wakeup_request        (0x199d)
#define image_10_get_queue_delay        (0x157e)
#define image_10_group_flow_lkp_and_fwd        (0xc60)
#define image_10_handle_flush        (0x16fa)
#define image_10_ingress_filter_action_point_update        (0xc23)
#define image_10_ingress_filters_handler        (0xa41)
#define image_10_initialization_task        (0x2)
#define image_10_is_iptv_capable        (0x978)
#define image_10_laqm_deque_check        (0x15df)
#define image_10_mcast_flow_master_lookup        (0xc36)
#define image_10_memcpy_abs_to_sbpm        (0x3e)
#define image_10_parser_exception_handler        (0x8e8)
#define image_10_pi2_deque_check        (0x15b3)
#define image_10_pi2_get_queue_delay        (0x1523)
#define image_10_pi2_probability_calc        (0x153e)
#define image_10_pi2_timer        (0x14f1)
#define image_10_proccessing_loopback        (0x8ba)
#define image_10_processing_policer_action        (0x14d5)
#define image_10_processing_wakeup_request        (0xc7)
#define image_10_spdsvc_natc_lookup        (0x9a0)
#define image_10_start_task___umulsi3        (0x19bb)
#define image_10_start_task_add_pbit_to_key        (0xc18)
#define image_10_start_task_budget_allocator_tick        (0x162a)
#define image_10_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_10_start_task_check_skip_cso        (0xc00)
#define image_10_start_task_debug_routine        (0xc)
#define image_10_start_task_dos_attack_handler        (0x961)
#define image_10_start_task_drop_pkt_and_serial        (0x9dd)
#define image_10_start_task_dualq_pi2_stats        (0x158f)
#define image_10_start_task_dyn_code_func        (0x1f00)
#define image_10_start_task_flow_policer        (0x14c1)
#define image_10_start_task_general_timer_wakeup_request        (0x199d)
#define image_10_start_task_get_queue_delay        (0x157e)
#define image_10_start_task_group_flow_lkp_and_fwd        (0xc60)
#define image_10_start_task_handle_flush        (0x16fa)
#define image_10_start_task_ingress_filter_action_point_update        (0xc23)
#define image_10_start_task_ingress_filters_handler        (0xa41)
#define image_10_start_task_initialization_task        (0x2)
#define image_10_start_task_is_iptv_capable        (0x978)
#define image_10_start_task_laqm_deque_check        (0x15df)
#define image_10_start_task_mcast_flow_master_lookup        (0xc36)
#define image_10_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_10_start_task_parser_exception_handler        (0x8e8)
#define image_10_start_task_pi2_deque_check        (0x15b3)
#define image_10_start_task_pi2_get_queue_delay        (0x1523)
#define image_10_start_task_pi2_probability_calc        (0x153e)
#define image_10_start_task_pi2_timer        (0x14f1)
#define image_10_start_task_proccessing_loopback        (0x8ba)
#define image_10_start_task_processing_policer_action        (0x14d5)
#define image_10_start_task_processing_wakeup_request        (0xc7)
#define image_10_start_task_spdsvc_natc_lookup        (0x9a0)
#define image_10_start_task_tm_tx_handle_rate_limit        (0x167b)
#define image_10_start_task_tm_tx_mirroring_handle        (0x1917)
#define image_10_start_task_tm_tx_task_wakeup_request        (0x173a)
#define image_10_start_task_tm_update_fifo_first_wakeup_request        (0x16ab)
#define image_10_start_task_ts_1588_handler        (0xa34)
#define image_10_start_task_tx_mirror        (0x193f)
#define image_10_start_task_xx_mirror_noinline        (0xb0f)
#define image_10_tm_tx_handle_rate_limit        (0x167b)
#define image_10_tm_tx_mirroring_handle        (0x1917)
#define image_10_tm_tx_task_wakeup_request        (0x173a)
#define image_10_tm_update_fifo_first_wakeup_request        (0x16ab)
#define image_10_ts_1588_handler        (0xa34)
#define image_10_tx_mirror        (0x193f)
#define image_10_xx_mirror_noinline        (0xb0f)

#endif


#endif

/* IMAGE 11 LABELS */
#ifndef IMAGE_11_CODE_ADDRESSES
#define IMAGE_11_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_11___umulsi3        (0x6a58)
#define image_11_add_pbit_to_key        (0x3060)
#define image_11_budget_allocator_tick        (0x5c14)
#define image_11_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_11_check_skip_cso        (0x3000)
#define image_11_debug_routine        (0x30)
#define image_11_debug_routine_handler        (0x4)
#define image_11_dos_attack_handler        (0x2584)
#define image_11_drop_pkt_and_serial        (0x2774)
#define image_11_dualq_pi2_stats        (0x59a8)
#define image_11_dyn_code_func        (0x7c00)
#define image_11_flow_policer        (0x5304)
#define image_11_general_timer_wakeup_request        (0x69e0)
#define image_11_get_queue_delay        (0x5964)
#define image_11_ghost_reporting_wakeup_request        (0x53c4)
#define image_11_group_flow_lkp_and_fwd        (0x3180)
#define image_11_handle_flush        (0x5f54)
#define image_11_ingress_filter_action_point_update        (0x308c)
#define image_11_ingress_filters_handler        (0x2904)
#define image_11_initialization_task        (0x8)
#define image_11_is_iptv_capable        (0x25e0)
#define image_11_laqm_deque_check        (0x5ae8)
#define image_11_mcast_flow_master_lookup        (0x30d8)
#define image_11_memcpy_abs_to_sbpm        (0xf8)
#define image_11_parser_exception_handler        (0x23a0)
#define image_11_pi2_deque_check        (0x5a38)
#define image_11_pi2_get_queue_delay        (0x57f8)
#define image_11_pi2_probability_calc        (0x5864)
#define image_11_pi2_timer        (0x5730)
#define image_11_proccessing_loopback        (0x22e8)
#define image_11_processing_policer_action        (0x5354)
#define image_11_processing_wakeup_request        (0x31c)
#define image_11_spdsvc_natc_lookup        (0x2680)
#define image_11_start_task___umulsi3        (0x6a58)
#define image_11_start_task_add_pbit_to_key        (0x3060)
#define image_11_start_task_budget_allocator_tick        (0x5c14)
#define image_11_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2e0)
#define image_11_start_task_check_skip_cso        (0x3000)
#define image_11_start_task_debug_routine        (0x30)
#define image_11_start_task_dos_attack_handler        (0x2584)
#define image_11_start_task_drop_pkt_and_serial        (0x2774)
#define image_11_start_task_dualq_pi2_stats        (0x59a8)
#define image_11_start_task_dyn_code_func        (0x7c00)
#define image_11_start_task_flow_policer        (0x5304)
#define image_11_start_task_general_timer_wakeup_request        (0x69e0)
#define image_11_start_task_get_queue_delay        (0x5964)
#define image_11_start_task_ghost_reporting_wakeup_request        (0x53c4)
#define image_11_start_task_group_flow_lkp_and_fwd        (0x3180)
#define image_11_start_task_handle_flush        (0x5f54)
#define image_11_start_task_ingress_filter_action_point_update        (0x308c)
#define image_11_start_task_ingress_filters_handler        (0x2904)
#define image_11_start_task_initialization_task        (0x8)
#define image_11_start_task_is_iptv_capable        (0x25e0)
#define image_11_start_task_laqm_deque_check        (0x5ae8)
#define image_11_start_task_mcast_flow_master_lookup        (0x30d8)
#define image_11_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_11_start_task_parser_exception_handler        (0x23a0)
#define image_11_start_task_pi2_deque_check        (0x5a38)
#define image_11_start_task_pi2_get_queue_delay        (0x57f8)
#define image_11_start_task_pi2_probability_calc        (0x5864)
#define image_11_start_task_pi2_timer        (0x5730)
#define image_11_start_task_proccessing_loopback        (0x22e8)
#define image_11_start_task_processing_policer_action        (0x5354)
#define image_11_start_task_processing_wakeup_request        (0x31c)
#define image_11_start_task_spdsvc_natc_lookup        (0x2680)
#define image_11_start_task_tm_tx_handle_rate_limit        (0x5d58)
#define image_11_start_task_tm_tx_mirroring_handle        (0x67c8)
#define image_11_start_task_tm_tx_task_wakeup_request        (0x6054)
#define image_11_start_task_tm_update_fifo_first_wakeup_request        (0x5e18)
#define image_11_start_task_ts_1588_handler        (0x28d0)
#define image_11_start_task_tx_mirror        (0x6868)
#define image_11_start_task_xx_mirror_noinline        (0x2c3c)
#define image_11_tm_tx_handle_rate_limit        (0x5d58)
#define image_11_tm_tx_mirroring_handle        (0x67c8)
#define image_11_tm_tx_task_wakeup_request        (0x6054)
#define image_11_tm_update_fifo_first_wakeup_request        (0x5e18)
#define image_11_ts_1588_handler        (0x28d0)
#define image_11_tx_mirror        (0x6868)
#define image_11_xx_mirror_noinline        (0x2c3c)

#else

#define image_11___umulsi3        (0x1a96)
#define image_11_add_pbit_to_key        (0xc18)
#define image_11_budget_allocator_tick        (0x1705)
#define image_11_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_11_check_skip_cso        (0xc00)
#define image_11_debug_routine        (0xc)
#define image_11_debug_routine_handler        (0x1)
#define image_11_dos_attack_handler        (0x961)
#define image_11_drop_pkt_and_serial        (0x9dd)
#define image_11_dualq_pi2_stats        (0x166a)
#define image_11_dyn_code_func        (0x1f00)
#define image_11_flow_policer        (0x14c1)
#define image_11_general_timer_wakeup_request        (0x1a78)
#define image_11_get_queue_delay        (0x1659)
#define image_11_ghost_reporting_wakeup_request        (0x14f1)
#define image_11_group_flow_lkp_and_fwd        (0xc60)
#define image_11_handle_flush        (0x17d5)
#define image_11_ingress_filter_action_point_update        (0xc23)
#define image_11_ingress_filters_handler        (0xa41)
#define image_11_initialization_task        (0x2)
#define image_11_is_iptv_capable        (0x978)
#define image_11_laqm_deque_check        (0x16ba)
#define image_11_mcast_flow_master_lookup        (0xc36)
#define image_11_memcpy_abs_to_sbpm        (0x3e)
#define image_11_parser_exception_handler        (0x8e8)
#define image_11_pi2_deque_check        (0x168e)
#define image_11_pi2_get_queue_delay        (0x15fe)
#define image_11_pi2_probability_calc        (0x1619)
#define image_11_pi2_timer        (0x15cc)
#define image_11_proccessing_loopback        (0x8ba)
#define image_11_processing_policer_action        (0x14d5)
#define image_11_processing_wakeup_request        (0xc7)
#define image_11_spdsvc_natc_lookup        (0x9a0)
#define image_11_start_task___umulsi3        (0x1a96)
#define image_11_start_task_add_pbit_to_key        (0xc18)
#define image_11_start_task_budget_allocator_tick        (0x1705)
#define image_11_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb8)
#define image_11_start_task_check_skip_cso        (0xc00)
#define image_11_start_task_debug_routine        (0xc)
#define image_11_start_task_dos_attack_handler        (0x961)
#define image_11_start_task_drop_pkt_and_serial        (0x9dd)
#define image_11_start_task_dualq_pi2_stats        (0x166a)
#define image_11_start_task_dyn_code_func        (0x1f00)
#define image_11_start_task_flow_policer        (0x14c1)
#define image_11_start_task_general_timer_wakeup_request        (0x1a78)
#define image_11_start_task_get_queue_delay        (0x1659)
#define image_11_start_task_ghost_reporting_wakeup_request        (0x14f1)
#define image_11_start_task_group_flow_lkp_and_fwd        (0xc60)
#define image_11_start_task_handle_flush        (0x17d5)
#define image_11_start_task_ingress_filter_action_point_update        (0xc23)
#define image_11_start_task_ingress_filters_handler        (0xa41)
#define image_11_start_task_initialization_task        (0x2)
#define image_11_start_task_is_iptv_capable        (0x978)
#define image_11_start_task_laqm_deque_check        (0x16ba)
#define image_11_start_task_mcast_flow_master_lookup        (0xc36)
#define image_11_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_11_start_task_parser_exception_handler        (0x8e8)
#define image_11_start_task_pi2_deque_check        (0x168e)
#define image_11_start_task_pi2_get_queue_delay        (0x15fe)
#define image_11_start_task_pi2_probability_calc        (0x1619)
#define image_11_start_task_pi2_timer        (0x15cc)
#define image_11_start_task_proccessing_loopback        (0x8ba)
#define image_11_start_task_processing_policer_action        (0x14d5)
#define image_11_start_task_processing_wakeup_request        (0xc7)
#define image_11_start_task_spdsvc_natc_lookup        (0x9a0)
#define image_11_start_task_tm_tx_handle_rate_limit        (0x1756)
#define image_11_start_task_tm_tx_mirroring_handle        (0x19f2)
#define image_11_start_task_tm_tx_task_wakeup_request        (0x1815)
#define image_11_start_task_tm_update_fifo_first_wakeup_request        (0x1786)
#define image_11_start_task_ts_1588_handler        (0xa34)
#define image_11_start_task_tx_mirror        (0x1a1a)
#define image_11_start_task_xx_mirror_noinline        (0xb0f)
#define image_11_tm_tx_handle_rate_limit        (0x1756)
#define image_11_tm_tx_mirroring_handle        (0x19f2)
#define image_11_tm_tx_task_wakeup_request        (0x1815)
#define image_11_tm_update_fifo_first_wakeup_request        (0x1786)
#define image_11_ts_1588_handler        (0xa34)
#define image_11_tx_mirror        (0x1a1a)
#define image_11_xx_mirror_noinline        (0xb0f)

#endif


#endif

/* IMAGE 12 LABELS */
#ifndef IMAGE_12_CODE_ADDRESSES
#define IMAGE_12_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_12___umulsi3        (0x1fd8)
#define image_12_budget_allocator_tick        (0xc78)
#define image_12_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x1e84)
#define image_12_debug_routine        (0x30)
#define image_12_debug_routine_handler        (0x4)
#define image_12_direct_flow_wakeup_request        (0x2e0)
#define image_12_dualq_pi2_stats        (0xa0c)
#define image_12_dyn_code_func        (0x8000)
#define image_12_epon_tm_tx        (0x1a94)
#define image_12_epon_tm_tx_credit_free        (0x1dd4)
#define image_12_epon_tm_tx_task_wakeup_request        (0x1cc4)
#define image_12_epon_tm_update_fifo_first_wakeup_request        (0x1c78)
#define image_12_general_timer_wakeup_request        (0x1e0c)
#define image_12_get_queue_delay        (0x9c8)
#define image_12_handle_flush        (0x10d4)
#define image_12_initialization_task        (0x8)
#define image_12_laqm_deque_check        (0xb4c)
#define image_12_memcpy_abs_to_sbpm        (0xf8)
#define image_12_pi2_deque_check        (0xa9c)
#define image_12_pi2_get_queue_delay        (0x85c)
#define image_12_pi2_probability_calc        (0x8c8)
#define image_12_pi2_timer        (0x798)
#define image_12_start_task___umulsi3        (0x1fd8)
#define image_12_start_task_budget_allocator_tick        (0xc78)
#define image_12_start_task_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x1e84)
#define image_12_start_task_debug_routine        (0x30)
#define image_12_start_task_direct_flow_wakeup_request        (0x2e0)
#define image_12_start_task_dualq_pi2_stats        (0xa0c)
#define image_12_start_task_dyn_code_func        (0x8000)
#define image_12_start_task_epon_tm_tx        (0x1a94)
#define image_12_start_task_epon_tm_tx_credit_free        (0x1dd4)
#define image_12_start_task_epon_tm_tx_task_wakeup_request        (0x1cc4)
#define image_12_start_task_epon_tm_update_fifo_first_wakeup_request        (0x1c78)
#define image_12_start_task_general_timer_wakeup_request        (0x1e0c)
#define image_12_start_task_get_queue_delay        (0x9c8)
#define image_12_start_task_handle_flush        (0x10d4)
#define image_12_start_task_initialization_task        (0x8)
#define image_12_start_task_laqm_deque_check        (0xb4c)
#define image_12_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_12_start_task_pi2_deque_check        (0xa9c)
#define image_12_start_task_pi2_get_queue_delay        (0x85c)
#define image_12_start_task_pi2_probability_calc        (0x8c8)
#define image_12_start_task_pi2_timer        (0x798)
#define image_12_start_task_tm_tx_dbg_stat_by_size        (0xeac)
#define image_12_start_task_tm_tx_dbg_stat_get_cntr_id        (0xe7c)
#define image_12_start_task_tm_tx_handle_rate_limit        (0xdbc)
#define image_12_start_task_tm_tx_mirroring_handle        (0x19d4)
#define image_12_start_task_tm_tx_task_wakeup_request        (0x11d4)
#define image_12_start_task_tm_update_fifo_first_wakeup_request        (0xf98)
#define image_12_start_task_tx_mirror        (0x1b00)
#define image_12_tm_tx_dbg_stat_by_size        (0xeac)
#define image_12_tm_tx_dbg_stat_get_cntr_id        (0xe7c)
#define image_12_tm_tx_handle_rate_limit        (0xdbc)
#define image_12_tm_tx_mirroring_handle        (0x19d4)
#define image_12_tm_tx_task_wakeup_request        (0x11d4)
#define image_12_tm_update_fifo_first_wakeup_request        (0xf98)
#define image_12_tx_mirror        (0x1b00)

#else

#define image_12___umulsi3        (0x7f6)
#define image_12_budget_allocator_tick        (0x31e)
#define image_12_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x7a1)
#define image_12_debug_routine        (0xc)
#define image_12_debug_routine_handler        (0x1)
#define image_12_direct_flow_wakeup_request        (0xb8)
#define image_12_dualq_pi2_stats        (0x283)
#define image_12_dyn_code_func        (0x2000)
#define image_12_epon_tm_tx        (0x6a5)
#define image_12_epon_tm_tx_credit_free        (0x775)
#define image_12_epon_tm_tx_task_wakeup_request        (0x731)
#define image_12_epon_tm_update_fifo_first_wakeup_request        (0x71e)
#define image_12_general_timer_wakeup_request        (0x783)
#define image_12_get_queue_delay        (0x272)
#define image_12_handle_flush        (0x435)
#define image_12_initialization_task        (0x2)
#define image_12_laqm_deque_check        (0x2d3)
#define image_12_memcpy_abs_to_sbpm        (0x3e)
#define image_12_pi2_deque_check        (0x2a7)
#define image_12_pi2_get_queue_delay        (0x217)
#define image_12_pi2_probability_calc        (0x232)
#define image_12_pi2_timer        (0x1e6)
#define image_12_start_task___umulsi3        (0x7f6)
#define image_12_start_task_budget_allocator_tick        (0x31e)
#define image_12_start_task_c_cpu_fpm_rings_and_bufmng_refill_wakeup_request        (0x7a1)
#define image_12_start_task_debug_routine        (0xc)
#define image_12_start_task_direct_flow_wakeup_request        (0xb8)
#define image_12_start_task_dualq_pi2_stats        (0x283)
#define image_12_start_task_dyn_code_func        (0x2000)
#define image_12_start_task_epon_tm_tx        (0x6a5)
#define image_12_start_task_epon_tm_tx_credit_free        (0x775)
#define image_12_start_task_epon_tm_tx_task_wakeup_request        (0x731)
#define image_12_start_task_epon_tm_update_fifo_first_wakeup_request        (0x71e)
#define image_12_start_task_general_timer_wakeup_request        (0x783)
#define image_12_start_task_get_queue_delay        (0x272)
#define image_12_start_task_handle_flush        (0x435)
#define image_12_start_task_initialization_task        (0x2)
#define image_12_start_task_laqm_deque_check        (0x2d3)
#define image_12_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_12_start_task_pi2_deque_check        (0x2a7)
#define image_12_start_task_pi2_get_queue_delay        (0x217)
#define image_12_start_task_pi2_probability_calc        (0x232)
#define image_12_start_task_pi2_timer        (0x1e6)
#define image_12_start_task_tm_tx_dbg_stat_by_size        (0x3ab)
#define image_12_start_task_tm_tx_dbg_stat_get_cntr_id        (0x39f)
#define image_12_start_task_tm_tx_handle_rate_limit        (0x36f)
#define image_12_start_task_tm_tx_mirroring_handle        (0x675)
#define image_12_start_task_tm_tx_task_wakeup_request        (0x475)
#define image_12_start_task_tm_update_fifo_first_wakeup_request        (0x3e6)
#define image_12_start_task_tx_mirror        (0x6c0)
#define image_12_tm_tx_dbg_stat_by_size        (0x3ab)
#define image_12_tm_tx_dbg_stat_get_cntr_id        (0x39f)
#define image_12_tm_tx_handle_rate_limit        (0x36f)
#define image_12_tm_tx_mirroring_handle        (0x675)
#define image_12_tm_tx_task_wakeup_request        (0x475)
#define image_12_tm_update_fifo_first_wakeup_request        (0x3e6)
#define image_12_tx_mirror        (0x6c0)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND


#else


#endif


#endif

