/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard

    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:

       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.

    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.

:>
*/



/* This is an automated file. Do not edit its contents. */


#include "packing.h"
#include "rdd.h"
#include "ru_types.h"

#include "rdd_data_structures_auto.h"

/* >>>RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_AQM_ENABLE_TABLE_ADDRESS_ARR */
uint32_t RDD_AQM_ENABLE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x820,
	0xde0,
	0xda0,
};
/* <<<RDD_AQM_ENABLE_TABLE_ADDRESS_ARR */


/* >>>RDD_AQM_SQ_TABLE_ADDRESS_ARR */
uint32_t RDD_AQM_SQ_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x840,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_AQM_SQ_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x880,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_AQM_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_AQM_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x900,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_AQM_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_DS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xa00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_DS_TM_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xb80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xc00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DIRECT_FLOW_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_FLOW_PD_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xe10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_FLOW_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */
uint32_t RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xe20,
	0xfa0,
	0xee0,
};
/* <<<RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xe40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_US_BUFFER_CONG_MGT_CFG_ADDRESS_ARR */
uint32_t RDD_US_BUFFER_CONG_MGT_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xe80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_BUFFER_CONG_MGT_CFG_ADDRESS_ARR */


/* >>>RDD_MUTEX_TABLE_ADDRESS_ARR */
uint32_t RDD_MUTEX_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xec4,
	0x29fc,
	0x25b4,
};
/* <<<RDD_MUTEX_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_WAN_0_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_WAN_0_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xec8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_WAN_0_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xed0,
	0x2790,
	0xed0,
};
/* <<<RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_FLOW_CNTR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xee0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0xf00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1e08,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1e10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */


/* >>>RDD_BUFFER_CONG_DQM_NOT_EMPTY_ADDRESS_ARR */
uint32_t RDD_BUFFER_CONG_DQM_NOT_EMPTY_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1e20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUFFER_CONG_DQM_NOT_EMPTY_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1e40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_BUFFER_CONG_MGT_CFG_ADDRESS_ARR */
uint32_t RDD_DS_BUFFER_CONG_MGT_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_BUFFER_CONG_MGT_CFG_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1ec4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_DEBUG_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_DEBUG_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1ec8,
	0x2988,
	0x2390,
};
/* <<<RDD_DEBUG_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_WAKE_UP_DATA_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1ef8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_US_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x1f00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */
uint32_t RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2410,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2490,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_CPU_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_FLOW_EPON_CONTROL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_DIRECT_FLOW_EPON_CONTROL_SCRATCH_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x24a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_FLOW_EPON_CONTROL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_AQM_NUM_QUEUES_ADDRESS_ARR */
uint32_t RDD_AQM_NUM_QUEUES_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x24b6,
	0x2d74,
	0x26f4,
};
/* <<<RDD_AQM_NUM_QUEUES_ADDRESS_ARR */


/* >>>RDD_NULL_BUFFER_ADDRESS_ARR */
uint32_t RDD_NULL_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x24b8,
	0x2a88,
	0x2588,
};
/* <<<RDD_NULL_BUFFER_ADDRESS_ARR */


/* >>>RDD_BUFFER_CONG_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_BUFFER_CONG_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x24c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUFFER_CONG_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2500,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x25a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_ONE_VALUE_ADDRESS_ARR */
uint32_t RDD_ONE_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x25b4,
	0x2cec,
	0x25ec,
};
/* <<<RDD_ONE_VALUE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x25b8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_TM_PI2_PROBABILITY_CALC_DESCRIPTOR_ADDRESS_ARR */
uint32_t RDD_TM_PI2_PROBABILITY_CALC_DESCRIPTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x25c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_PI2_PROBABILITY_CALC_DESCRIPTOR_ADDRESS_ARR */


/* >>>RDD_DIRECT_FLOW_PAUSE_QUANTA_ADDRESS_ARR */
uint32_t RDD_DIRECT_FLOW_PAUSE_QUANTA_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x25fa,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_FLOW_PAUSE_QUANTA_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_WAN_0_FIFO_BYTES_USED_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_WAN_0_FIFO_BYTES_USED_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x25fc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_WAN_0_FIFO_BYTES_USED_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2600,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */
uint32_t RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2720,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27b4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_US_TM_WAN_0_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_WAN_0_BB_DESTINATION_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27b6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_WAN_0_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_MIRRORING_SCRATCH_ADDRESS_ARR */
uint32_t RDD_MIRRORING_SCRATCH_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27b8,
	INVALID_TABLE_ADDRESS,
	0x26f8,
};
/* <<<RDD_MIRRORING_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR */
uint32_t RDD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27ec,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_PON_TM_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR */
uint32_t RDD_PON_TM_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27ee,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PON_TM_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x27f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_REGISTERS_BUFFER_ADDRESS_ARR */
uint32_t RDD_REGISTERS_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2a08,
	0x3148,
	0x2860,
};
/* <<<RDD_REGISTERS_BUFFER_ADDRESS_ARR */


/* >>>RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2a88,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2a90,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2aa0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_TASK_IDX_ADDRESS_ARR */
uint32_t RDD_TASK_IDX_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2ab4,
	0x2ffc,
	0x28f4,
};
/* <<<RDD_TASK_IDX_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2ab8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2abe,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_US_TM_WAN_0_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_WAN_0_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2ac0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_WAN_0_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2ae8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FLUSH_CFG_FW_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2af0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FLUSH_CFG_FW_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_FLOW_RX_MIRRORING_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_DIRECT_FLOW_RX_MIRRORING_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_FLOW_RX_MIRRORING_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2b88,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2b90,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */


/* >>>RDD_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2ba0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bb4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR */


/* >>>RDD_DIRECT_FLOW_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */
uint32_t RDD_DIRECT_FLOW_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bb6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_FLOW_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */


/* >>>RDD_US_TM_TX_PAUSE_NACK_ADDRESS_ARR */
uint32_t RDD_US_TM_TX_PAUSE_NACK_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bb7,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TX_PAUSE_NACK_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_WAKEUP_CMD_US_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_WAKEUP_CMD_US_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bb8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_WAKEUP_CMD_US_ADDRESS_ARR */


/* >>>RDD_BBH_TX_US_WAN_0_FIFO_BYTES_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_BBH_TX_US_WAN_0_FIFO_BYTES_THRESHOLD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bbc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_US_WAN_0_FIFO_BYTES_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bbe,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_TM_VLAN_STATS_ENABLE_ADDRESS_ARR */
uint32_t RDD_TM_VLAN_STATS_ENABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bbf,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_VLAN_STATS_ENABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_WAKEUP_CMD_US_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_WAKEUP_CMD_US_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2be8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_WAKEUP_CMD_US_ADDRESS_ARR */


/* >>>RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bec,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bee,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2bf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_AQM_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_AQM_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_AQM_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_PON_TM_VPORT_TO_RL_OVERHEAD_TABLE_ADDRESS_ARR */
uint32_t RDD_PON_TM_VPORT_TO_RL_OVERHEAD_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f04,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PON_TM_VPORT_TO_RL_OVERHEAD_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_EXCEPTION_ADDRESS_ARR */
uint32_t RDD_TX_EXCEPTION_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f05,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_EXCEPTION_ADDRESS_ARR */


/* >>>RDD_CORE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_CORE_ID_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f06,
	0x2ded,
	0x29af,
};
/* <<<RDD_CORE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f07,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_WAKEUP_CMD_DS_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_WAKEUP_CMD_DS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f08,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_WAKEUP_CMD_DS_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f0c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f0e,
	0x2fe2,
	0x29fe,
};
/* <<<RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FLUSH_CFG_CURRENT_TABLE_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f34,
	0x31dc,
	0x2a5c,
};
/* <<<RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f36,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f37,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f38,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */


/* >>>RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */
uint32_t RDD_SRAM_DUMMY_STORE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f3a,
	0x31ec,
	0x2a5f,
};
/* <<<RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */


/* >>>RDD_MAC_TYPE_ADDRESS_ARR */
uint32_t RDD_MAC_TYPE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f3b,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MAC_TYPE_ADDRESS_ARR */


/* >>>RDD_WAN_0_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_WAN_0_BBH_TX_FIFO_SIZE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f3c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WAN_0_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_BACKUP_BBH_INGRESS_COUNTERS_TABLE_ADDRESS_ARR */
uint32_t RDD_BACKUP_BBH_INGRESS_COUNTERS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f3d,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BACKUP_BBH_INGRESS_COUNTERS_TABLE_ADDRESS_ARR */


/* >>>RDD_BACKUP_BBH_EGRESS_COUNTERS_TABLE_ADDRESS_ARR */
uint32_t RDD_BACKUP_BBH_EGRESS_COUNTERS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f3e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BACKUP_BBH_EGRESS_COUNTERS_TABLE_ADDRESS_ARR */


/* >>>RDD_DEBUG_PRINT_CORE_LOCK_ADDRESS_ARR */
uint32_t RDD_DEBUG_PRINT_CORE_LOCK_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f3f,
	0x31fe,
	0x2a6f,
};
/* <<<RDD_DEBUG_PRINT_CORE_LOCK_ADDRESS_ARR */


/* >>>RDD_HOST_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR */
uint32_t RDD_HOST_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f40,
	0x2ec0,
	0x29c0,
};
/* <<<RDD_HOST_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f68,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f6a,
	0x323d,
	0x2a7e,
};
/* <<<RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */


/* >>>RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_ETH_TM_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR */
uint32_t RDD_ETH_TM_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2f80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_ETH_TM_TX_TRUNCATE_MIRRORING_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2fa8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FLUSH_CFG_ENABLE_TABLE_ADDRESS_ARR */


/* >>>RDD_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2fb0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_TM_ACTION_PTR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2fc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x2ff0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR */


/* >>>RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */
uint32_t RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3000,
	0x2400,
	0x800,
};
/* <<<RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */


/* >>>RDD_US_TM_TX_QUEUE_DROP_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TX_QUEUE_DROP_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3200,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TX_QUEUE_DROP_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_TX_QUEUE_DROP_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TX_QUEUE_DROP_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3408,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TX_QUEUE_DROP_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3610,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR */


/* >>>RDD_QUEUE_TO_REPORT_BIT_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_TO_REPORT_BIT_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3620,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_QUEUE_TO_REPORT_BIT_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3640,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3660,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_FLOW_PAUSE_DEBUG_ADDRESS_ARR */
uint32_t RDD_DIRECT_FLOW_PAUSE_DEBUG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3670,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_FLOW_PAUSE_DEBUG_ADDRESS_ARR */


/* >>>RDD_DS_TM_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3680,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_AQM_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_AQM_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x36a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_AQM_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x36c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x36e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x36f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3700,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_TX_OCTETS_COUNTERS_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TX_OCTETS_COUNTERS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3788,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TX_OCTETS_COUNTERS_TABLE_ADDRESS_ARR */


/* >>>RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x37d0,
	0x31f0,
	0x2a70,
};
/* <<<RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x37e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x37f0,
	0x3230,
	0x2af0,
};
/* <<<RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3900,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3990,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x39a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_CODEL_DROP_DESCRIPTOR_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x39b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x39c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_FPM_GLOBAL_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x39e0,
	0x32a0,
	0x2be0,
};
/* <<<RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_SQ_TX_QUEUE_DROP_TABLE_ADDRESS_ARR */
uint32_t RDD_SQ_TX_QUEUE_DROP_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3aa0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SQ_TX_QUEUE_DROP_TABLE_ADDRESS_ARR */


/* >>>RDD_DEBUG_PRINT_TABLE_ADDRESS_ARR */
uint32_t RDD_DEBUG_PRINT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3ae0,
	0x3460,
	0x2ca0,
};
/* <<<RDD_DEBUG_PRINT_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3af0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_AQM_QUEUE_TIMER_TABLE_ADDRESS_ARR */


/* >>>RDD_NATC_TBL_CFG_ADDRESS_ARR */
uint32_t RDD_NATC_TBL_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3b00,
	0x3100,
	0x2b00,
};
/* <<<RDD_NATC_TBL_CFG_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3b48,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */


/* >>>RDD_FW_ERROR_VECTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_FW_ERROR_VECTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3b60,
	0x34e0,
	0x2d20,
};
/* <<<RDD_FW_ERROR_VECTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_CNTR_STASH_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_CNTR_STASH_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3b70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_CNTR_STASH_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_RL_OVERHEAD_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_RL_OVERHEAD_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3b80,
	0x3480,
	0x2c40,
};
/* <<<RDD_VPORT_TO_RL_OVERHEAD_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_CNTR_STASH_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_CNTR_STASH_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3ba0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_CNTR_STASH_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3c40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_SCT_FILTER_ADDRESS_ARR */
uint32_t RDD_SCT_FILTER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	0x3ffc,
	0x3ffc,
	0x3ffc,
};
/* <<<RDD_SCT_FILTER_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x0,
	0x400,
};
/* <<<RDD_RX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_PROCESSING_GROUP_PARAMS_GEN4_TABLE_ADDRESS_ARR */
uint32_t RDD_PROCESSING_GROUP_PARAMS_GEN4_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x280,
	0x680,
};
/* <<<RDD_PROCESSING_GROUP_PARAMS_GEN4_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x300,
	0x700,
};
/* <<<RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x400,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x600,
	0xc00,
};
/* <<<RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_METER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x700,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_STREAM_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_STREAM_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x800,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_STREAM_TABLE_ADDRESS_ARR */


/* >>>RDD_UDPSPDT_STREAM_RX_STAT_TABLE_ADDRESS_ARR */
uint32_t RDD_UDPSPDT_STREAM_RX_STAT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0xe00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UDPSPDT_STREAM_RX_STAT_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNEL_TABLE_ADDRESS_ARR */
uint32_t RDD_TUNNEL_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0xec0,
	0xb40,
};
/* <<<RDD_TUNNEL_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0xf00,
	0xd00,
};
/* <<<RDD_VPORT_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */
uint32_t RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0xfc0,
	0xdc0,
};
/* <<<RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_DS_PACKET_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x1000,
	0x1000,
};
/* <<<RDD_DS_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_PKTGEN_TX_STREAM_TABLE_ADDRESS_ARR */
uint32_t RDD_PKTGEN_TX_STREAM_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2000,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_TX_STREAM_TABLE_ADDRESS_ARR */


/* >>>RDD_FLOODING_HEADER_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_FLOODING_HEADER_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2220,
	0xfa0,
};
/* <<<RDD_FLOODING_HEADER_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2240,
	0xfc0,
};
/* <<<RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_CACHE_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_CACHE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2280,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_CACHE_TABLE_ADDRESS_ARR */


/* >>>RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2300,
	0x2100,
};
/* <<<RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x23a0,
	0x21a0,
};
/* <<<RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNEL_DST_IP_LKP_TABLE_ADDRESS_ARR */
uint32_t RDD_TUNNEL_DST_IP_LKP_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x23c0,
	0x21c0,
};
/* <<<RDD_TUNNEL_DST_IP_LKP_TABLE_ADDRESS_ARR */


/* >>>RDD_UDPSPDT_STREAM_TX_STAT_TABLE_ADDRESS_ARR */
uint32_t RDD_UDPSPDT_STREAM_TX_STAT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2600,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UDPSPDT_STREAM_TX_STAT_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_FLOW_IDX_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_FLOW_IDX_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x26a0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_FLOW_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x26c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_FLOW_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2700,
	0x2300,
};
/* <<<RDD_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x27a0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x27c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2800,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2890,
	0x2590,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x28a0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x28c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */


/* >>>RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2900,
	0x2500,
};
/* <<<RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_MCAST_FPM_TOKENS_READ_FLAG_ADDRESS_ARR */
uint32_t RDD_MCAST_FPM_TOKENS_READ_FLAG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x29b8,
	0xbf8,
};
/* <<<RDD_MCAST_FPM_TOKENS_READ_FLAG_ADDRESS_ARR */


/* >>>RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x29c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2a00,
	0x2600,
};
/* <<<RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2a90,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2aa0,
	0x25a0,
};
/* <<<RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_NO_SBPM_HDRS_CNTR_ADDRESS_ARR */
uint32_t RDD_PKTGEN_NO_SBPM_HDRS_CNTR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2ab4,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_NO_SBPM_HDRS_CNTR_ADDRESS_ARR */


/* >>>RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR */
uint32_t RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2ab8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR */


/* >>>RDD_TR471_SPDSVC_RX_PKT_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_TR471_SPDSVC_RX_PKT_ID_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2ac0,
	0x23c0,
};
/* <<<RDD_TR471_SPDSVC_RX_PKT_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_INT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_INT_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2af0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_INT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2b00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2b80,
	0xb80,
};
/* <<<RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2bf8,
	0x25b8,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2c00,
	0x2700,
};
/* <<<RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */


/* >>>RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */
uint32_t RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2c80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2cf0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_UDPSPDT_TX_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_UDPSPDT_TX_PARAMS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2d00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UDPSPDT_TX_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2d60,
	0x26e0,
};
/* <<<RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_LOOPBACK_WAN_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_LOOPBACK_WAN_FLOW_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2d76,
	0x29ac,
};
/* <<<RDD_LOOPBACK_WAN_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_FORCE_DSCP_ADDRESS_ARR */
uint32_t RDD_FORCE_DSCP_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2d77,
	0x29ad,
};
/* <<<RDD_FORCE_DSCP_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2d78,
	0x26d8,
};
/* <<<RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_MAX_PKT_LEN_TABLE_ADDRESS_ARR */
uint32_t RDD_MAX_PKT_LEN_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2d80,
	0x2780,
};
/* <<<RDD_MAX_PKT_LEN_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2dc0,
	0x27c0,
};
/* <<<RDD_RX_MIRRORING_TABLE_ADDRESS_ARR */


/* >>>RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2de8,
	0x28f8,
};
/* <<<RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_SPDSVC_TCPSPDTEST_COMMON_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_TCPSPDTEST_COMMON_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2dee,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_TCPSPDTEST_COMMON_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDTEST_NUM_OF_RX_FLOWS_ADDRESS_ARR */
uint32_t RDD_SPDTEST_NUM_OF_RX_FLOWS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2def,
	0x29fc,
};
/* <<<RDD_SPDTEST_NUM_OF_RX_FLOWS_ADDRESS_ARR */


/* >>>RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2df0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2e00,
	0x2900,
};
/* <<<RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDTEST_GEN_PARAM_ADDRESS_ARR */
uint32_t RDD_SPDTEST_GEN_PARAM_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2e50,
	0x25f0,
};
/* <<<RDD_SPDTEST_GEN_PARAM_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_ENGINE_GLOBAL_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_ENGINE_GLOBAL_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2e60,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_ENGINE_GLOBAL_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2e74,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_INGRESS_PACKET_BASED_MAPPING_ADDRESS_ARR */
uint32_t RDD_INGRESS_PACKET_BASED_MAPPING_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2e78,
	0x29a8,
};
/* <<<RDD_INGRESS_PACKET_BASED_MAPPING_ADDRESS_ARR */


/* >>>RDD_PKTGEN_BAD_GET_NEXT_ADDRESS_ARR */
uint32_t RDD_PKTGEN_BAD_GET_NEXT_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2e7c,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_BAD_GET_NEXT_ADDRESS_ARR */


/* >>>RDD_COMMON_REPROCESSING_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_COMMON_REPROCESSING_PD_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2e80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMMON_REPROCESSING_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2ee8,
	0x29e8,
};
/* <<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2ef0,
	0x27f0,
};
/* <<<RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2f00,
	0x2a00,
};
/* <<<RDD_EMAC_FLOW_CTRL_ADDRESS_ARR */


/* >>>RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2f50,
	0x2970,
};
/* <<<RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2f60,
	0x29b0,
};
/* <<<RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2f70,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_MAX_UT_PKTS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_MAX_UT_PKTS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2f7c,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_MAX_UT_PKTS_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SBPM_HDR_BNS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SBPM_HDR_BNS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2f80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SBPM_HDR_BNS_ADDRESS_ARR */


/* >>>RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2fc0,
	0x2ac0,
};
/* <<<RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_UT_TRIGGER_ADDRESS_ARR */
uint32_t RDD_PKTGEN_UT_TRIGGER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2fe4,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_UT_TRIGGER_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2fe8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x2ff0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_CURR_SBPM_HDR_PTR_ADDRESS_ARR */
uint32_t RDD_PKTGEN_CURR_SBPM_HDR_PTR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31c8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_CURR_SBPM_HDR_PTR_ADDRESS_ARR */


/* >>>RDD_COMMON_REPROCESSING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_COMMON_REPROCESSING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31d0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMMON_REPROCESSING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_ECN_IPV6_REMARK_TABLE_ADDRESS_ARR */
uint32_t RDD_ECN_IPV6_REMARK_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31de,
	0x29fd,
};
/* <<<RDD_ECN_IPV6_REMARK_TABLE_ADDRESS_ARR */


/* >>>RDD_MULTI_FLOW_FLAG_TABLE_ADDRESS_ARR */
uint32_t RDD_MULTI_FLOW_FLAG_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31df,
	0x2a5e,
};
/* <<<RDD_MULTI_FLOW_FLAG_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31e0,
	0x2a60,
};
/* <<<RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */
uint32_t RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31ed,
	0x2a6c,
};
/* <<<RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */


/* >>>RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR */
uint32_t RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31ee,
	0x2a6d,
};
/* <<<RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_CACHE_OFFSET_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_CACHE_OFFSET_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31ef,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_CACHE_OFFSET_ADDRESS_ARR */


/* >>>RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */
uint32_t RDD_CPU_REDIRECT_MODE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31fc,
	0x2a6e,
};
/* <<<RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */


/* >>>RDD_CSO_DISABLE_ADDRESS_ARR */
uint32_t RDD_CSO_DISABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31fd,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CSO_DISABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x31ff,
	0x2a7c,
};
/* <<<RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_DEFAULT_VLAN_VID_TABLE_ADDRESS_ARR */
uint32_t RDD_DEFAULT_VLAN_VID_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3200,
	0x2980,
};
/* <<<RDD_DEFAULT_VLAN_VID_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_NUM_OF_AVAIL_SBPM_HDRS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_NUM_OF_AVAIL_SBPM_HDRS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3228,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_NUM_OF_AVAIL_SBPM_HDRS_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x323c,
	0x2a7d,
};
/* <<<RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */


/* >>>RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3240,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_BCM_SPDSVC_STREAM_RX_TS_TABLE_ADDRESS_ARR */
uint32_t RDD_BCM_SPDSVC_STREAM_RX_TS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3260,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BCM_SPDSVC_STREAM_RX_TS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3270,
	0x2c30,
};
/* <<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3280,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SBPM_END_PTR_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SBPM_END_PTR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x32b8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SBPM_END_PTR_ADDRESS_ARR */


/* >>>RDD_COMMON_REPROCESSING_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_COMMON_REPROCESSING_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x32c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMMON_REPROCESSING_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x32e0,
	0x2c58,
};
/* <<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x32f0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_PD_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3300,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_TC_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_TC_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3320,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_TC_ADDRESS_ARR */


/* >>>RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_TC_TO_CPU_RXQ_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3360,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x33a0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_PD_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_PD_SCRATCH_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x33e0,
	0x2c70,
};
/* <<<RDD_CPU_RECYCLE_PD_SCRATCH_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SBPM_EXTS_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SBPM_EXTS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x33e8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SBPM_EXTS_ADDRESS_ARR */


/* >>>RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */
uint32_t RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x33f8,
	0x2ae8,
};
/* <<<RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */


/* >>>RDD_PKTGEN_SESSION_DATA_ADDRESS_ARR */
uint32_t RDD_PKTGEN_SESSION_DATA_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3400,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_SESSION_DATA_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3420,
	0x2ba0,
};
/* <<<RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_PKTGEN_BBMSG_REPLY_SCRATCH_ADDRESS_ARR */
uint32_t RDD_PKTGEN_BBMSG_REPLY_SCRATCH_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3450,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_BBMSG_REPLY_SCRATCH_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_CFG_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3458,
	0x2b48,
};
/* <<<RDD_NAT_CACHE_CFG_ADDRESS_ARR */


/* >>>RDD_GDX_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_GDX_PARAMS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3470,
	0x2cb0,
};
/* <<<RDD_GDX_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CFG_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3498,
	0x2bf8,
};
/* <<<RDD_IPTV_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNEL_HEADER_PSRAM_BUFFER_ADDRESS_ARR */
uint32_t RDD_TUNNEL_HEADER_PSRAM_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34a0,
	0x2ce0,
};
/* <<<RDD_TUNNEL_HEADER_PSRAM_BUFFER_ADDRESS_ARR */


/* >>>RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */
uint32_t RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34a8,
	0x2c68,
};
/* <<<RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34b0,
	0x2cf0,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34b8,
	0x2cd8,
};
/* <<<RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */


/* >>>RDD_VPORT_PBIT_TO_DISCARD_PRIO_VECTOR_ADDRESS_ARR */
uint32_t RDD_VPORT_PBIT_TO_DISCARD_PRIO_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34c0,
	0x2cc0,
};
/* <<<RDD_VPORT_PBIT_TO_DISCARD_PRIO_VECTOR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34d8,
	0x2ce8,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34e8,
	0x2cf8,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_NEXT_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_NEXT_PTR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34f0,
	0x2dd0,
};
/* <<<RDD_CPU_RECYCLE_NEXT_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x34f8,
	0x2d68,
};
/* <<<RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */


/* >>>RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3500,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3518,
	0x2d78,
};
/* <<<RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */


/* >>>RDD_MULTICAST_KEY_MASK_ADDRESS_ARR */
uint32_t RDD_MULTICAST_KEY_MASK_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3520,
	0x2d60,
};
/* <<<RDD_MULTICAST_KEY_MASK_ADDRESS_ARR */


/* >>>RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_TOS_MASK_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3528,
	0x2da8,
};
/* <<<RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */


/* >>>RDD_PKTGEN_FPM_UG_MGMT_ADDRESS_ARR */
uint32_t RDD_PKTGEN_FPM_UG_MGMT_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3540,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_FPM_UG_MGMT_ADDRESS_ARR */


/* >>>RDD_BITS_CALC_MASKS_TABLE_ADDRESS_ARR */
uint32_t RDD_BITS_CALC_MASKS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3580,
	0x2dc0,
};
/* <<<RDD_BITS_CALC_MASKS_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x35c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */


/* >>>RDD_PKTGEN_TX_STREAM_SCRATCH_TABLE_ADDRESS_ARR */
uint32_t RDD_PKTGEN_TX_STREAM_SCRATCH_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	0x3600,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PKTGEN_TX_STREAM_SCRATCH_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
};
/* <<<RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_CBS_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_CBS_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa00,
};
/* <<<RDD_FW_POLICER_CBS_ADDRESS_ARR */


/* >>>RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe00,
};
/* <<<RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_TIMER_COMMON_CTR_REP_ADDRESS_ARR */
uint32_t RDD_TIMER_COMMON_CTR_REP_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xec8,
};
/* <<<RDD_TIMER_COMMON_CTR_REP_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_BUDGET_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_BUDGET_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf00,
};
/* <<<RDD_FW_POLICER_BUDGET_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2000,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2200,
};
/* <<<RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22c0,
};
/* <<<RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */


/* >>>RDD_BUFFER_ALLOC_REPLY_ADDRESS_ARR */
uint32_t RDD_BUFFER_ALLOC_REPLY_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23f0,
};
/* <<<RDD_BUFFER_ALLOC_REPLY_ADDRESS_ARR */


/* >>>RDD_DHD_AUX_INFO_CACHE_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_AUX_INFO_CACHE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2400,
};
/* <<<RDD_DHD_AUX_INFO_CACHE_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25c0,
};
/* <<<RDD_DHD_CODEL_BIAS_SLOPE_TABLE_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_BUDGET_REMAINDER_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_BUDGET_REMAINDER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2688,
};
/* <<<RDD_FW_POLICER_BUDGET_REMAINDER_ADDRESS_ARR */


/* >>>RDD_TIMER_COMMON_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_TIMER_COMMON_TIMER_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x26f6,
};
/* <<<RDD_TIMER_COMMON_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27e8,
};
/* <<<RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2800,
};
/* <<<RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_HW_CFG_ADDRESS_ARR */
uint32_t RDD_DHD_HW_CFG_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x28e0,
};
/* <<<RDD_DHD_HW_CFG_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x28fd,
};
/* <<<RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR */


/* >>>RDD_SPDSVC_WLAN_TXPOST_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_WLAN_TXPOST_PARAMS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x28fe,
};
/* <<<RDD_SPDSVC_WLAN_TXPOST_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2950,
};
/* <<<RDD_CPU_TX_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_VLAN_STATS_ENABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_VLAN_STATS_ENABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29ae,
};
/* <<<RDD_CPU_TX_VLAN_STATS_ENABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29f0,
};
/* <<<RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a50,
};
/* <<<RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a80,
};
/* <<<RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RING_INDICES_VALUES_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RING_INDICES_VALUES_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2aa8,
};
/* <<<RDD_CPU_TX_RING_INDICES_VALUES_TABLE_ADDRESS_ARR */


/* >>>RDD_FW_POLICER_VECTOR_ADDRESS_ARR */
uint32_t RDD_FW_POLICER_VECTOR_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ab0,
};
/* <<<RDD_FW_POLICER_VECTOR_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b50,
};
/* <<<RDD_DHD_RX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b60,
};
/* <<<RDD_DHD_TX_COMPLETE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b70,
};
/* <<<RDD_DHD_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
};
/* <<<RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_WLAN_GEN_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_WLAN_GEN_PARAMS_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bd0,
};
/* <<<RDD_SPDSVC_WLAN_GEN_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c00,
};
/* <<<RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_BUDGET_REMAINDER_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_BUDGET_REMAINDER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c78,
};
/* <<<RDD_EMAC_FLOW_CTRL_BUDGET_REMAINDER_ADDRESS_ARR */


/* >>>RDD_RING_CPU_TX_DESCRIPTOR_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_RING_CPU_TX_DESCRIPTOR_DATA_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c80,
};
/* <<<RDD_RING_CPU_TX_DESCRIPTOR_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d00,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d28,
};
/* <<<RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d30,
};
/* <<<RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d38,
};
/* <<<RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d40,
};
/* <<<RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d58,
};
/* <<<RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d70,
};
/* <<<RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d80,
};
/* <<<RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2da0,
};
/* <<<RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_INT_ID_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_INT_ID_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2db0,
};
/* <<<RDD_DHD_CPU_INT_ID_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e00,
};
/* <<<RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e40,
};
/* <<<RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e80,
};
/* <<<RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_REPLY_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ec0,
};
/* <<<RDD_DHD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_DHD_L2_HEADER_ADDRESS_ARR */
uint32_t RDD_DHD_L2_HEADER_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f00,
};
/* <<<RDD_DHD_L2_HEADER_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SYNC_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SYNC_FIFO_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f80,
};
/* <<<RDD_CPU_TX_SYNC_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_TX_POST_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_TX_POST_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
};
/* <<<RDD_DHD_CPU_TX_POST_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[NUM_OF_RUNNER_CORES] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3080,
};
/* <<<RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */

