/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_add_pbit_to_key        (0x3af4)
#define image_0_c_cpu_recycle_wakeup_request        (0x6e94)
#define image_0_c_cpu_rx_copy_wakeup_request        (0x62cc)
#define image_0_c_cpu_rx_wakeup_request        (0x5de4)
#define image_0_c_dhd_rx_complete_wakeup_request        (0x764)
#define image_0_c_dhd_tx_complete_wakeup_request        (0xbe0)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_0_check_skip_cso        (0x3a94)
#define image_0_cpu_recycle_int_coalescing        (0x6fec)
#define image_0_cpu_rx_int_coalescing        (0x6228)
#define image_0_cpu_rx_meter_budget_allocator        (0x6274)
#define image_0_debug_routine        (0x3b0)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dhd_send_entry_to_cpu_ring        (0x694)
#define image_0_dos_attack_handler        (0x3010)
#define image_0_drop_pkt_and_serial        (0x3208)
#define image_0_dynamic_code_section        (0x8)
#define image_0_dynamic_code_section_proc0        (0x8)
#define image_0_dynamic_code_section_proc1        (0x78)
#define image_0_dynamic_code_section_proc2        (0xe8)
#define image_0_dynamic_code_section_proc3        (0x158)
#define image_0_dynamic_code_section_proc4        (0x1c8)
#define image_0_dynamic_code_section_proc5        (0x238)
#define image_0_dynamic_code_section_proc6        (0x2a8)
#define image_0_dynamic_code_section_proc7        (0x318)
#define image_0_flow_policer        (0x5cac)
#define image_0_general_timer_wakeup_request        (0x5d6c)
#define image_0_get_pd_from_fifo        (0x7018)
#define image_0_group_flow_lkp_and_fwd        (0x3c14)
#define image_0_ingress_filter_action_point_update        (0x3b20)
#define image_0_ingress_filters_handler        (0x3390)
#define image_0_initialization_task        (0x388)
#define image_0_is_iptv_capable        (0x306c)
#define image_0_mcast_flow_master_lookup        (0x3b6c)
#define image_0_memcpy_abs_to_sbpm        (0x478)
#define image_0_packet_cso_rnr_calc        (0x6d00)
#define image_0_parser_exception_handler        (0x2e2c)
#define image_0_proccessing_loopback        (0x2d78)
#define image_0_processing_policer_action        (0x5cfc)
#define image_0_processing_wakeup_request        (0xe54)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0xacc)
#define image_0_rxcmpl_process_rx_packet        (0xb34)
#define image_0_spdsvc_natc_lookup        (0x310c)
#define image_0_start_task_add_pbit_to_key        (0x3af4)
#define image_0_start_task_c_cpu_recycle_wakeup_request        (0x6e94)
#define image_0_start_task_c_cpu_rx_copy_wakeup_request        (0x62cc)
#define image_0_start_task_c_cpu_rx_wakeup_request        (0x5de4)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0x764)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0xbe0)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_0_start_task_check_skip_cso        (0x3a94)
#define image_0_start_task_cpu_recycle_int_coalescing        (0x6fec)
#define image_0_start_task_cpu_rx_int_coalescing        (0x6228)
#define image_0_start_task_cpu_rx_meter_budget_allocator        (0x6274)
#define image_0_start_task_debug_routine        (0x3b0)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0x694)
#define image_0_start_task_dos_attack_handler        (0x3010)
#define image_0_start_task_drop_pkt_and_serial        (0x3208)
#define image_0_start_task_flow_policer        (0x5cac)
#define image_0_start_task_general_timer_wakeup_request        (0x5d6c)
#define image_0_start_task_get_pd_from_fifo        (0x7018)
#define image_0_start_task_group_flow_lkp_and_fwd        (0x3c14)
#define image_0_start_task_ingress_filter_action_point_update        (0x3b20)
#define image_0_start_task_ingress_filters_handler        (0x3390)
#define image_0_start_task_initialization_task        (0x388)
#define image_0_start_task_is_iptv_capable        (0x306c)
#define image_0_start_task_mcast_flow_master_lookup        (0x3b6c)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_0_start_task_packet_cso_rnr_calc        (0x6d00)
#define image_0_start_task_parser_exception_handler        (0x2e2c)
#define image_0_start_task_proccessing_loopback        (0x2d78)
#define image_0_start_task_processing_policer_action        (0x5cfc)
#define image_0_start_task_processing_wakeup_request        (0xe54)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0xacc)
#define image_0_start_task_rxcmpl_process_rx_packet        (0xb34)
#define image_0_start_task_spdsvc_natc_lookup        (0x310c)
#define image_0_start_task_ts_1588_handler        (0x335c)
#define image_0_start_task_xx_mirror_noinline        (0x36c8)
#define image_0_ts_1588_handler        (0x335c)
#define image_0_xx_mirror_noinline        (0x36c8)

#else

#define image_0_add_pbit_to_key        (0xebd)
#define image_0_c_cpu_recycle_wakeup_request        (0x1ba5)
#define image_0_c_cpu_rx_copy_wakeup_request        (0x18b3)
#define image_0_c_cpu_rx_wakeup_request        (0x1779)
#define image_0_c_dhd_rx_complete_wakeup_request        (0x1d9)
#define image_0_c_dhd_tx_complete_wakeup_request        (0x2f8)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_0_check_skip_cso        (0xea5)
#define image_0_cpu_recycle_int_coalescing        (0x1bfb)
#define image_0_cpu_rx_int_coalescing        (0x188a)
#define image_0_cpu_rx_meter_budget_allocator        (0x189d)
#define image_0_debug_routine        (0xec)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dhd_send_entry_to_cpu_ring        (0x1a5)
#define image_0_dos_attack_handler        (0xc04)
#define image_0_drop_pkt_and_serial        (0xc82)
#define image_0_dynamic_code_section        (0x2)
#define image_0_dynamic_code_section_proc0        (0x2)
#define image_0_dynamic_code_section_proc1        (0x1e)
#define image_0_dynamic_code_section_proc2        (0x3a)
#define image_0_dynamic_code_section_proc3        (0x56)
#define image_0_dynamic_code_section_proc4        (0x72)
#define image_0_dynamic_code_section_proc5        (0x8e)
#define image_0_dynamic_code_section_proc6        (0xaa)
#define image_0_dynamic_code_section_proc7        (0xc6)
#define image_0_flow_policer        (0x172b)
#define image_0_general_timer_wakeup_request        (0x175b)
#define image_0_get_pd_from_fifo        (0x1c06)
#define image_0_group_flow_lkp_and_fwd        (0xf05)
#define image_0_ingress_filter_action_point_update        (0xec8)
#define image_0_ingress_filters_handler        (0xce4)
#define image_0_initialization_task        (0xe2)
#define image_0_is_iptv_capable        (0xc1b)
#define image_0_mcast_flow_master_lookup        (0xedb)
#define image_0_memcpy_abs_to_sbpm        (0x11e)
#define image_0_packet_cso_rnr_calc        (0x1b40)
#define image_0_parser_exception_handler        (0xb8b)
#define image_0_proccessing_loopback        (0xb5e)
#define image_0_processing_policer_action        (0x173f)
#define image_0_processing_wakeup_request        (0x395)
#define image_0_rx_cmpl_send_doorbell_activate_idma        (0x2b3)
#define image_0_rxcmpl_process_rx_packet        (0x2cd)
#define image_0_spdsvc_natc_lookup        (0xc43)
#define image_0_start_task_add_pbit_to_key        (0xebd)
#define image_0_start_task_c_cpu_recycle_wakeup_request        (0x1ba5)
#define image_0_start_task_c_cpu_rx_copy_wakeup_request        (0x18b3)
#define image_0_start_task_c_cpu_rx_wakeup_request        (0x1779)
#define image_0_start_task_c_dhd_rx_complete_wakeup_request        (0x1d9)
#define image_0_start_task_c_dhd_tx_complete_wakeup_request        (0x2f8)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_0_start_task_check_skip_cso        (0xea5)
#define image_0_start_task_cpu_recycle_int_coalescing        (0x1bfb)
#define image_0_start_task_cpu_rx_int_coalescing        (0x188a)
#define image_0_start_task_cpu_rx_meter_budget_allocator        (0x189d)
#define image_0_start_task_debug_routine        (0xec)
#define image_0_start_task_dhd_send_entry_to_cpu_ring        (0x1a5)
#define image_0_start_task_dos_attack_handler        (0xc04)
#define image_0_start_task_drop_pkt_and_serial        (0xc82)
#define image_0_start_task_flow_policer        (0x172b)
#define image_0_start_task_general_timer_wakeup_request        (0x175b)
#define image_0_start_task_get_pd_from_fifo        (0x1c06)
#define image_0_start_task_group_flow_lkp_and_fwd        (0xf05)
#define image_0_start_task_ingress_filter_action_point_update        (0xec8)
#define image_0_start_task_ingress_filters_handler        (0xce4)
#define image_0_start_task_initialization_task        (0xe2)
#define image_0_start_task_is_iptv_capable        (0xc1b)
#define image_0_start_task_mcast_flow_master_lookup        (0xedb)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_0_start_task_packet_cso_rnr_calc        (0x1b40)
#define image_0_start_task_parser_exception_handler        (0xb8b)
#define image_0_start_task_proccessing_loopback        (0xb5e)
#define image_0_start_task_processing_policer_action        (0x173f)
#define image_0_start_task_processing_wakeup_request        (0x395)
#define image_0_start_task_rx_cmpl_send_doorbell_activate_idma        (0x2b3)
#define image_0_start_task_rxcmpl_process_rx_packet        (0x2cd)
#define image_0_start_task_spdsvc_natc_lookup        (0xc43)
#define image_0_start_task_ts_1588_handler        (0xcd7)
#define image_0_start_task_xx_mirror_noinline        (0xdb2)
#define image_0_ts_1588_handler        (0xcd7)
#define image_0_xx_mirror_noinline        (0xdb2)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_add_pbit_to_key        (0x4a98)
#define image_1_c_common_reprocessing_wakeup_request        (0x6d10)
#define image_1_c_spdsvc_analyzer_wakeup_request        (0x7318)
#define image_1_c_spdsvc_gen_wakeup_request        (0x6e9c)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x1db4)
#define image_1_check_skip_cso        (0x4a38)
#define image_1_debug_routine        (0x3b0)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dos_attack_handler        (0x3fb4)
#define image_1_drop_pkt_and_serial        (0x41ac)
#define image_1_dynamic_code_section        (0x8)
#define image_1_dynamic_code_section_proc0        (0x8)
#define image_1_dynamic_code_section_proc1        (0x78)
#define image_1_dynamic_code_section_proc2        (0xe8)
#define image_1_dynamic_code_section_proc3        (0x158)
#define image_1_dynamic_code_section_proc4        (0x1c8)
#define image_1_dynamic_code_section_proc5        (0x238)
#define image_1_dynamic_code_section_proc6        (0x2a8)
#define image_1_dynamic_code_section_proc7        (0x318)
#define image_1_flow_policer        (0x6c50)
#define image_1_group_flow_lkp_and_fwd        (0x4bb8)
#define image_1_ingress_filter_action_point_update        (0x4ac4)
#define image_1_ingress_filters_handler        (0x4334)
#define image_1_initialization_task        (0x388)
#define image_1_is_iptv_capable        (0x4010)
#define image_1_mcast_flow_master_lookup        (0x4b10)
#define image_1_memcpy_abs_to_sbpm        (0x1bd4)
#define image_1_parser_exception_handler        (0x3dd0)
#define image_1_proccessing_loopback        (0x3d1c)
#define image_1_processing_policer_action        (0x6ca0)
#define image_1_processing_wakeup_request        (0x1df0)
#define image_1_spdsvc_natc_lookup        (0x40b0)
#define image_1_spdt_brcm_spdsvc_rx_handler        (0x76c8)
#define image_1_spdt_udp_basic_rx_handler        (0x7444)
#define image_1_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x778c)
#define image_1_spdt_udp_iperf3_rx_handler        (0x74f0)
#define image_1_spdt_unsupported_proto_rx_handler        (0x7730)
#define image_1_start_task_add_pbit_to_key        (0x4a98)
#define image_1_start_task_c_common_reprocessing_wakeup_request        (0x6d10)
#define image_1_start_task_c_spdsvc_analyzer_wakeup_request        (0x7318)
#define image_1_start_task_c_spdsvc_gen_wakeup_request        (0x6e9c)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x1db4)
#define image_1_start_task_check_skip_cso        (0x4a38)
#define image_1_start_task_debug_routine        (0x3b0)
#define image_1_start_task_dos_attack_handler        (0x3fb4)
#define image_1_start_task_drop_pkt_and_serial        (0x41ac)
#define image_1_start_task_flow_policer        (0x6c50)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x4bb8)
#define image_1_start_task_ingress_filter_action_point_update        (0x4ac4)
#define image_1_start_task_ingress_filters_handler        (0x4334)
#define image_1_start_task_initialization_task        (0x388)
#define image_1_start_task_is_iptv_capable        (0x4010)
#define image_1_start_task_mcast_flow_master_lookup        (0x4b10)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x1bd4)
#define image_1_start_task_parser_exception_handler        (0x3dd0)
#define image_1_start_task_proccessing_loopback        (0x3d1c)
#define image_1_start_task_processing_policer_action        (0x6ca0)
#define image_1_start_task_processing_wakeup_request        (0x1df0)
#define image_1_start_task_spdsvc_natc_lookup        (0x40b0)
#define image_1_start_task_spdt_brcm_spdsvc_rx_handler        (0x76c8)
#define image_1_start_task_spdt_udp_basic_rx_handler        (0x7444)
#define image_1_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x778c)
#define image_1_start_task_spdt_udp_iperf3_rx_handler        (0x74f0)
#define image_1_start_task_spdt_unsupported_proto_rx_handler        (0x7730)
#define image_1_start_task_tcpspdtest_gen_wakeup_request        (0xd08)
#define image_1_start_task_tcpspdtest_wakeup_request        (0x4c8)
#define image_1_start_task_ts_1588_handler        (0x4300)
#define image_1_start_task_xx_mirror_noinline        (0x466c)
#define image_1_tcpspdtest_gen_wakeup_request        (0xd08)
#define image_1_tcpspdtest_task_upload_init        (0xd08)
#define image_1_tcpspdtest_wakeup_request        (0x4c8)
#define image_1_ts_1588_handler        (0x4300)
#define image_1_xx_mirror_noinline        (0x466c)

#else

#define image_1_add_pbit_to_key        (0x12a6)
#define image_1_c_common_reprocessing_wakeup_request        (0x1b44)
#define image_1_c_spdsvc_analyzer_wakeup_request        (0x1cc6)
#define image_1_c_spdsvc_gen_wakeup_request        (0x1ba7)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x76d)
#define image_1_check_skip_cso        (0x128e)
#define image_1_debug_routine        (0xec)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dos_attack_handler        (0xfed)
#define image_1_drop_pkt_and_serial        (0x106b)
#define image_1_dynamic_code_section        (0x2)
#define image_1_dynamic_code_section_proc0        (0x2)
#define image_1_dynamic_code_section_proc1        (0x1e)
#define image_1_dynamic_code_section_proc2        (0x3a)
#define image_1_dynamic_code_section_proc3        (0x56)
#define image_1_dynamic_code_section_proc4        (0x72)
#define image_1_dynamic_code_section_proc5        (0x8e)
#define image_1_dynamic_code_section_proc6        (0xaa)
#define image_1_dynamic_code_section_proc7        (0xc6)
#define image_1_flow_policer        (0x1b14)
#define image_1_group_flow_lkp_and_fwd        (0x12ee)
#define image_1_ingress_filter_action_point_update        (0x12b1)
#define image_1_ingress_filters_handler        (0x10cd)
#define image_1_initialization_task        (0xe2)
#define image_1_is_iptv_capable        (0x1004)
#define image_1_mcast_flow_master_lookup        (0x12c4)
#define image_1_memcpy_abs_to_sbpm        (0x6f5)
#define image_1_parser_exception_handler        (0xf74)
#define image_1_proccessing_loopback        (0xf47)
#define image_1_processing_policer_action        (0x1b28)
#define image_1_processing_wakeup_request        (0x77c)
#define image_1_spdsvc_natc_lookup        (0x102c)
#define image_1_spdt_brcm_spdsvc_rx_handler        (0x1db2)
#define image_1_spdt_udp_basic_rx_handler        (0x1d11)
#define image_1_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x1de3)
#define image_1_spdt_udp_iperf3_rx_handler        (0x1d3c)
#define image_1_spdt_unsupported_proto_rx_handler        (0x1dcc)
#define image_1_start_task_add_pbit_to_key        (0x12a6)
#define image_1_start_task_c_common_reprocessing_wakeup_request        (0x1b44)
#define image_1_start_task_c_spdsvc_analyzer_wakeup_request        (0x1cc6)
#define image_1_start_task_c_spdsvc_gen_wakeup_request        (0x1ba7)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x76d)
#define image_1_start_task_check_skip_cso        (0x128e)
#define image_1_start_task_debug_routine        (0xec)
#define image_1_start_task_dos_attack_handler        (0xfed)
#define image_1_start_task_drop_pkt_and_serial        (0x106b)
#define image_1_start_task_flow_policer        (0x1b14)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x12ee)
#define image_1_start_task_ingress_filter_action_point_update        (0x12b1)
#define image_1_start_task_ingress_filters_handler        (0x10cd)
#define image_1_start_task_initialization_task        (0xe2)
#define image_1_start_task_is_iptv_capable        (0x1004)
#define image_1_start_task_mcast_flow_master_lookup        (0x12c4)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x6f5)
#define image_1_start_task_parser_exception_handler        (0xf74)
#define image_1_start_task_proccessing_loopback        (0xf47)
#define image_1_start_task_processing_policer_action        (0x1b28)
#define image_1_start_task_processing_wakeup_request        (0x77c)
#define image_1_start_task_spdsvc_natc_lookup        (0x102c)
#define image_1_start_task_spdt_brcm_spdsvc_rx_handler        (0x1db2)
#define image_1_start_task_spdt_udp_basic_rx_handler        (0x1d11)
#define image_1_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x1de3)
#define image_1_start_task_spdt_udp_iperf3_rx_handler        (0x1d3c)
#define image_1_start_task_spdt_unsupported_proto_rx_handler        (0x1dcc)
#define image_1_start_task_tcpspdtest_gen_wakeup_request        (0x342)
#define image_1_start_task_tcpspdtest_wakeup_request        (0x132)
#define image_1_start_task_ts_1588_handler        (0x10c0)
#define image_1_start_task_xx_mirror_noinline        (0x119b)
#define image_1_tcpspdtest_gen_wakeup_request        (0x342)
#define image_1_tcpspdtest_task_upload_init        (0x342)
#define image_1_tcpspdtest_wakeup_request        (0x132)
#define image_1_ts_1588_handler        (0x10c0)
#define image_1_xx_mirror_noinline        (0x119b)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2___umulhisi3        (0x7c58)
#define image_2___umulsi3        (0x7c18)
#define image_2_add_pbit_to_key        (0x46d4)
#define image_2_budget_allocator_tick        (0x6e20)
#define image_2_c_cpu_recycle_wakeup_request        (0x6954)
#define image_2_c_cpu_tx_wakeup_request        (0x854)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x818)
#define image_2_check_skip_cso        (0x4674)
#define image_2_cpu_recycle_int_coalescing        (0x6aac)
#define image_2_cpu_tx_send_pd_to_recycle        (0x1998)
#define image_2_cpu_tx_sync_tasks        (0x1a04)
#define image_2_debug_routine        (0x3b0)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dos_attack_handler        (0x3bf0)
#define image_2_drop_pkt_and_serial        (0x3de8)
#define image_2_dynamic_code_section        (0x8)
#define image_2_dynamic_code_section_proc0        (0x8)
#define image_2_dynamic_code_section_proc1        (0x78)
#define image_2_dynamic_code_section_proc2        (0xe8)
#define image_2_dynamic_code_section_proc3        (0x158)
#define image_2_dynamic_code_section_proc4        (0x1c8)
#define image_2_dynamic_code_section_proc5        (0x238)
#define image_2_dynamic_code_section_proc6        (0x2a8)
#define image_2_dynamic_code_section_proc7        (0x318)
#define image_2_flow_policer        (0x6894)
#define image_2_general_timer_wakeup_request        (0x6f64)
#define image_2_group_flow_lkp_and_fwd        (0x47f4)
#define image_2_ingress_filter_action_point_update        (0x4700)
#define image_2_ingress_filters_handler        (0x3f70)
#define image_2_initialization_task        (0x388)
#define image_2_is_iptv_capable        (0x3c4c)
#define image_2_mcast_flow_master_lookup        (0x474c)
#define image_2_memcpy_abs_to_fpm        (0x658)
#define image_2_memcpy_abs_to_sbpm        (0x478)
#define image_2_parser_exception_handler        (0x3a0c)
#define image_2_pi2_deque_check        (0x6d20)
#define image_2_pi2_deque_inc_drop_stats        (0x6c68)
#define image_2_pi2_probability_calc        (0x6ba4)
#define image_2_pi2_sq_timestamp        (0x6cd0)
#define image_2_pi2_sq_timestamp_inject        (0x709c)
#define image_2_pi2_timer        (0x6ad8)
#define image_2_proccessing_loopback        (0x3958)
#define image_2_processing_policer_action        (0x68e4)
#define image_2_processing_wakeup_request        (0x1a24)
#define image_2_spdsvc_natc_lookup        (0x3cec)
#define image_2_sq_tx_task_wakeup_request        (0x7110)
#define image_2_start_task___umulhisi3        (0x7c58)
#define image_2_start_task___umulsi3        (0x7c18)
#define image_2_start_task_add_pbit_to_key        (0x46d4)
#define image_2_start_task_budget_allocator_tick        (0x6e20)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x6954)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x854)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x818)
#define image_2_start_task_check_skip_cso        (0x4674)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x6aac)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x1998)
#define image_2_start_task_cpu_tx_sync_tasks        (0x1a04)
#define image_2_start_task_debug_routine        (0x3b0)
#define image_2_start_task_dos_attack_handler        (0x3bf0)
#define image_2_start_task_drop_pkt_and_serial        (0x3de8)
#define image_2_start_task_flow_policer        (0x6894)
#define image_2_start_task_general_timer_wakeup_request        (0x6f64)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x47f4)
#define image_2_start_task_ingress_filter_action_point_update        (0x4700)
#define image_2_start_task_ingress_filters_handler        (0x3f70)
#define image_2_start_task_initialization_task        (0x388)
#define image_2_start_task_is_iptv_capable        (0x3c4c)
#define image_2_start_task_mcast_flow_master_lookup        (0x474c)
#define image_2_start_task_memcpy_abs_to_fpm        (0x658)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_2_start_task_parser_exception_handler        (0x3a0c)
#define image_2_start_task_pi2_deque_check        (0x6d20)
#define image_2_start_task_pi2_deque_inc_drop_stats        (0x6c68)
#define image_2_start_task_pi2_probability_calc        (0x6ba4)
#define image_2_start_task_pi2_sq_timestamp        (0x6cd0)
#define image_2_start_task_pi2_sq_timestamp_inject        (0x709c)
#define image_2_start_task_pi2_timer        (0x6ad8)
#define image_2_start_task_proccessing_loopback        (0x3958)
#define image_2_start_task_processing_policer_action        (0x68e4)
#define image_2_start_task_processing_wakeup_request        (0x1a24)
#define image_2_start_task_spdsvc_natc_lookup        (0x3cec)
#define image_2_start_task_sq_tx_task_wakeup_request        (0x7110)
#define image_2_start_task_tm_tx_handle_rate_limit        (0x6fdc)
#define image_2_start_task_ts_1588_handler        (0x3f3c)
#define image_2_start_task_xx_mirror_noinline        (0x42a8)
#define image_2_tm_tx_handle_rate_limit        (0x6fdc)
#define image_2_ts_1588_handler        (0x3f3c)
#define image_2_xx_mirror_noinline        (0x42a8)

#else

#define image_2___umulhisi3        (0x1f16)
#define image_2___umulsi3        (0x1f06)
#define image_2_add_pbit_to_key        (0x11b5)
#define image_2_budget_allocator_tick        (0x1b88)
#define image_2_c_cpu_recycle_wakeup_request        (0x1a55)
#define image_2_c_cpu_tx_wakeup_request        (0x215)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x206)
#define image_2_check_skip_cso        (0x119d)
#define image_2_cpu_recycle_int_coalescing        (0x1aab)
#define image_2_cpu_tx_send_pd_to_recycle        (0x666)
#define image_2_cpu_tx_sync_tasks        (0x681)
#define image_2_debug_routine        (0xec)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dos_attack_handler        (0xefc)
#define image_2_drop_pkt_and_serial        (0xf7a)
#define image_2_dynamic_code_section        (0x2)
#define image_2_dynamic_code_section_proc0        (0x2)
#define image_2_dynamic_code_section_proc1        (0x1e)
#define image_2_dynamic_code_section_proc2        (0x3a)
#define image_2_dynamic_code_section_proc3        (0x56)
#define image_2_dynamic_code_section_proc4        (0x72)
#define image_2_dynamic_code_section_proc5        (0x8e)
#define image_2_dynamic_code_section_proc6        (0xaa)
#define image_2_dynamic_code_section_proc7        (0xc6)
#define image_2_flow_policer        (0x1a25)
#define image_2_general_timer_wakeup_request        (0x1bd9)
#define image_2_group_flow_lkp_and_fwd        (0x11fd)
#define image_2_ingress_filter_action_point_update        (0x11c0)
#define image_2_ingress_filters_handler        (0xfdc)
#define image_2_initialization_task        (0xe2)
#define image_2_is_iptv_capable        (0xf13)
#define image_2_mcast_flow_master_lookup        (0x11d3)
#define image_2_memcpy_abs_to_fpm        (0x196)
#define image_2_memcpy_abs_to_sbpm        (0x11e)
#define image_2_parser_exception_handler        (0xe83)
#define image_2_pi2_deque_check        (0x1b48)
#define image_2_pi2_deque_inc_drop_stats        (0x1b1a)
#define image_2_pi2_probability_calc        (0x1ae9)
#define image_2_pi2_sq_timestamp        (0x1b34)
#define image_2_pi2_sq_timestamp_inject        (0x1c27)
#define image_2_pi2_timer        (0x1ab6)
#define image_2_proccessing_loopback        (0xe56)
#define image_2_processing_policer_action        (0x1a39)
#define image_2_processing_wakeup_request        (0x689)
#define image_2_spdsvc_natc_lookup        (0xf3b)
#define image_2_sq_tx_task_wakeup_request        (0x1c44)
#define image_2_start_task___umulhisi3        (0x1f16)
#define image_2_start_task___umulsi3        (0x1f06)
#define image_2_start_task_add_pbit_to_key        (0x11b5)
#define image_2_start_task_budget_allocator_tick        (0x1b88)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x1a55)
#define image_2_start_task_c_cpu_tx_wakeup_request        (0x215)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x206)
#define image_2_start_task_check_skip_cso        (0x119d)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x1aab)
#define image_2_start_task_cpu_tx_send_pd_to_recycle        (0x666)
#define image_2_start_task_cpu_tx_sync_tasks        (0x681)
#define image_2_start_task_debug_routine        (0xec)
#define image_2_start_task_dos_attack_handler        (0xefc)
#define image_2_start_task_drop_pkt_and_serial        (0xf7a)
#define image_2_start_task_flow_policer        (0x1a25)
#define image_2_start_task_general_timer_wakeup_request        (0x1bd9)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x11fd)
#define image_2_start_task_ingress_filter_action_point_update        (0x11c0)
#define image_2_start_task_ingress_filters_handler        (0xfdc)
#define image_2_start_task_initialization_task        (0xe2)
#define image_2_start_task_is_iptv_capable        (0xf13)
#define image_2_start_task_mcast_flow_master_lookup        (0x11d3)
#define image_2_start_task_memcpy_abs_to_fpm        (0x196)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_2_start_task_parser_exception_handler        (0xe83)
#define image_2_start_task_pi2_deque_check        (0x1b48)
#define image_2_start_task_pi2_deque_inc_drop_stats        (0x1b1a)
#define image_2_start_task_pi2_probability_calc        (0x1ae9)
#define image_2_start_task_pi2_sq_timestamp        (0x1b34)
#define image_2_start_task_pi2_sq_timestamp_inject        (0x1c27)
#define image_2_start_task_pi2_timer        (0x1ab6)
#define image_2_start_task_proccessing_loopback        (0xe56)
#define image_2_start_task_processing_policer_action        (0x1a39)
#define image_2_start_task_processing_wakeup_request        (0x689)
#define image_2_start_task_spdsvc_natc_lookup        (0xf3b)
#define image_2_start_task_sq_tx_task_wakeup_request        (0x1c44)
#define image_2_start_task_tm_tx_handle_rate_limit        (0x1bf7)
#define image_2_start_task_ts_1588_handler        (0xfcf)
#define image_2_start_task_xx_mirror_noinline        (0x10aa)
#define image_2_tm_tx_handle_rate_limit        (0x1bf7)
#define image_2_ts_1588_handler        (0xfcf)
#define image_2_xx_mirror_noinline        (0x10aa)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_add_pbit_to_key        (0x411c)
#define image_3_c_dhd_timer_wakeup_request        (0x764)
#define image_3_c_dhd_tx_post_update_fifo_wakeup_request        (0x7ec)
#define image_3_c_dhd_tx_post_wakeup_request        (0x830)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_3_check_skip_cso        (0x40bc)
#define image_3_debug_routine        (0x3b0)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dhd_send_entry_to_cpu_ring        (0x694)
#define image_3_dhd_tx_get_bq_index        (0x139c)
#define image_3_dhd_tx_post_drop_packet        (0x12c0)
#define image_3_dhd_tx_post_flow_ring_get_info        (0x10fc)
#define image_3_dhd_tx_put_bq_index        (0x140c)
#define image_3_dos_attack_handler        (0x3638)
#define image_3_drop_pkt_and_serial        (0x3830)
#define image_3_dynamic_code_section        (0x8)
#define image_3_dynamic_code_section_proc0        (0x8)
#define image_3_dynamic_code_section_proc1        (0x78)
#define image_3_dynamic_code_section_proc2        (0xe8)
#define image_3_dynamic_code_section_proc3        (0x158)
#define image_3_dynamic_code_section_proc4        (0x1c8)
#define image_3_dynamic_code_section_proc5        (0x238)
#define image_3_dynamic_code_section_proc6        (0x2a8)
#define image_3_dynamic_code_section_proc7        (0x318)
#define image_3_flow_policer        (0x62d4)
#define image_3_group_flow_lkp_and_fwd        (0x423c)
#define image_3_ingress_filter_action_point_update        (0x4148)
#define image_3_ingress_filters_handler        (0x39b8)
#define image_3_initialization_task        (0x388)
#define image_3_is_iptv_capable        (0x3694)
#define image_3_mcast_flow_master_lookup        (0x4194)
#define image_3_memcpy_abs_to_sbpm        (0x478)
#define image_3_parser_exception_handler        (0x3454)
#define image_3_proccessing_loopback        (0x33a0)
#define image_3_processing_policer_action        (0x6324)
#define image_3_processing_wakeup_request        (0x1474)
#define image_3_spdsvc_natc_lookup        (0x3734)
#define image_3_start_task_add_pbit_to_key        (0x411c)
#define image_3_start_task_c_dhd_timer_wakeup_request        (0x764)
#define image_3_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x7ec)
#define image_3_start_task_c_dhd_tx_post_wakeup_request        (0x830)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x658)
#define image_3_start_task_check_skip_cso        (0x40bc)
#define image_3_start_task_debug_routine        (0x3b0)
#define image_3_start_task_dhd_send_entry_to_cpu_ring        (0x694)
#define image_3_start_task_dhd_tx_get_bq_index        (0x139c)
#define image_3_start_task_dhd_tx_post_drop_packet        (0x12c0)
#define image_3_start_task_dhd_tx_post_flow_ring_get_info        (0x10fc)
#define image_3_start_task_dhd_tx_put_bq_index        (0x140c)
#define image_3_start_task_dos_attack_handler        (0x3638)
#define image_3_start_task_drop_pkt_and_serial        (0x3830)
#define image_3_start_task_flow_policer        (0x62d4)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x423c)
#define image_3_start_task_ingress_filter_action_point_update        (0x4148)
#define image_3_start_task_ingress_filters_handler        (0x39b8)
#define image_3_start_task_initialization_task        (0x388)
#define image_3_start_task_is_iptv_capable        (0x3694)
#define image_3_start_task_mcast_flow_master_lookup        (0x4194)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x478)
#define image_3_start_task_parser_exception_handler        (0x3454)
#define image_3_start_task_proccessing_loopback        (0x33a0)
#define image_3_start_task_processing_policer_action        (0x6324)
#define image_3_start_task_processing_wakeup_request        (0x1474)
#define image_3_start_task_spdsvc_natc_lookup        (0x3734)
#define image_3_start_task_ts_1588_handler        (0x3984)
#define image_3_start_task_tx_mirror        (0x6394)
#define image_3_start_task_xx_mirror_noinline        (0x3cf0)
#define image_3_ts_1588_handler        (0x3984)
#define image_3_tx_mirror        (0x6394)
#define image_3_xx_mirror_noinline        (0x3cf0)

#else

#define image_3_add_pbit_to_key        (0x1047)
#define image_3_c_dhd_timer_wakeup_request        (0x1d9)
#define image_3_c_dhd_tx_post_update_fifo_wakeup_request        (0x1fb)
#define image_3_c_dhd_tx_post_wakeup_request        (0x20c)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_3_check_skip_cso        (0x102f)
#define image_3_debug_routine        (0xec)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dhd_send_entry_to_cpu_ring        (0x1a5)
#define image_3_dhd_tx_get_bq_index        (0x4e7)
#define image_3_dhd_tx_post_drop_packet        (0x4b0)
#define image_3_dhd_tx_post_flow_ring_get_info        (0x43f)
#define image_3_dhd_tx_put_bq_index        (0x503)
#define image_3_dos_attack_handler        (0xd8e)
#define image_3_drop_pkt_and_serial        (0xe0c)
#define image_3_dynamic_code_section        (0x2)
#define image_3_dynamic_code_section_proc0        (0x2)
#define image_3_dynamic_code_section_proc1        (0x1e)
#define image_3_dynamic_code_section_proc2        (0x3a)
#define image_3_dynamic_code_section_proc3        (0x56)
#define image_3_dynamic_code_section_proc4        (0x72)
#define image_3_dynamic_code_section_proc5        (0x8e)
#define image_3_dynamic_code_section_proc6        (0xaa)
#define image_3_dynamic_code_section_proc7        (0xc6)
#define image_3_flow_policer        (0x18b5)
#define image_3_group_flow_lkp_and_fwd        (0x108f)
#define image_3_ingress_filter_action_point_update        (0x1052)
#define image_3_ingress_filters_handler        (0xe6e)
#define image_3_initialization_task        (0xe2)
#define image_3_is_iptv_capable        (0xda5)
#define image_3_mcast_flow_master_lookup        (0x1065)
#define image_3_memcpy_abs_to_sbpm        (0x11e)
#define image_3_parser_exception_handler        (0xd15)
#define image_3_proccessing_loopback        (0xce8)
#define image_3_processing_policer_action        (0x18c9)
#define image_3_processing_wakeup_request        (0x51d)
#define image_3_spdsvc_natc_lookup        (0xdcd)
#define image_3_start_task_add_pbit_to_key        (0x1047)
#define image_3_start_task_c_dhd_timer_wakeup_request        (0x1d9)
#define image_3_start_task_c_dhd_tx_post_update_fifo_wakeup_request        (0x1fb)
#define image_3_start_task_c_dhd_tx_post_wakeup_request        (0x20c)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x196)
#define image_3_start_task_check_skip_cso        (0x102f)
#define image_3_start_task_debug_routine        (0xec)
#define image_3_start_task_dhd_send_entry_to_cpu_ring        (0x1a5)
#define image_3_start_task_dhd_tx_get_bq_index        (0x4e7)
#define image_3_start_task_dhd_tx_post_drop_packet        (0x4b0)
#define image_3_start_task_dhd_tx_post_flow_ring_get_info        (0x43f)
#define image_3_start_task_dhd_tx_put_bq_index        (0x503)
#define image_3_start_task_dos_attack_handler        (0xd8e)
#define image_3_start_task_drop_pkt_and_serial        (0xe0c)
#define image_3_start_task_flow_policer        (0x18b5)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x108f)
#define image_3_start_task_ingress_filter_action_point_update        (0x1052)
#define image_3_start_task_ingress_filters_handler        (0xe6e)
#define image_3_start_task_initialization_task        (0xe2)
#define image_3_start_task_is_iptv_capable        (0xda5)
#define image_3_start_task_mcast_flow_master_lookup        (0x1065)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x11e)
#define image_3_start_task_parser_exception_handler        (0xd15)
#define image_3_start_task_proccessing_loopback        (0xce8)
#define image_3_start_task_processing_policer_action        (0x18c9)
#define image_3_start_task_processing_wakeup_request        (0x51d)
#define image_3_start_task_spdsvc_natc_lookup        (0xdcd)
#define image_3_start_task_ts_1588_handler        (0xe61)
#define image_3_start_task_tx_mirror        (0x18e5)
#define image_3_start_task_xx_mirror_noinline        (0xf3c)
#define image_3_ts_1588_handler        (0xe61)
#define image_3_tx_mirror        (0x18e5)
#define image_3_xx_mirror_noinline        (0xf3c)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4___umulhisi3        (0x695c)
#define image_4___umulsi3        (0x691c)
#define image_4_add_pbit_to_key        (0x317c)
#define image_4_budget_allocator_tick        (0x5b14)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x498)
#define image_4_check_skip_cso        (0x311c)
#define image_4_debug_routine        (0x1f0)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dos_attack_handler        (0x2698)
#define image_4_drop_pkt_and_serial        (0x2890)
#define image_4_dynamic_code_section        (0x8)
#define image_4_dynamic_code_section_proc0        (0x8)
#define image_4_dynamic_code_section_proc1        (0x78)
#define image_4_dynamic_code_section_proc2        (0xe8)
#define image_4_dynamic_code_section_proc3        (0x158)
#define image_4_flow_policer        (0x5334)
#define image_4_general_timer_wakeup_request        (0x68a4)
#define image_4_get_queue_delay        (0x5958)
#define image_4_ghost_reporting_wakeup_request        (0x53f4)
#define image_4_group_flow_lkp_and_fwd        (0x329c)
#define image_4_handle_flush        (0x5e54)
#define image_4_ingress_filter_action_point_update        (0x31a8)
#define image_4_ingress_filters_handler        (0x2a18)
#define image_4_initialization_task        (0x1c8)
#define image_4_is_iptv_capable        (0x26f4)
#define image_4_mcast_flow_master_lookup        (0x31f4)
#define image_4_memcpy_abs_to_sbpm        (0x2b8)
#define image_4_parser_exception_handler        (0x24b4)
#define image_4_pi2_deque_check        (0x5a14)
#define image_4_pi2_deque_inc_drop_stats        (0x59ac)
#define image_4_pi2_get_queue_delay        (0x5828)
#define image_4_pi2_probability_calc        (0x5894)
#define image_4_pi2_timer        (0x5760)
#define image_4_proccessing_loopback        (0x2400)
#define image_4_processing_policer_action        (0x5384)
#define image_4_processing_wakeup_request        (0x4d4)
#define image_4_spdsvc_natc_lookup        (0x2794)
#define image_4_start_task___umulhisi3        (0x695c)
#define image_4_start_task___umulsi3        (0x691c)
#define image_4_start_task_add_pbit_to_key        (0x317c)
#define image_4_start_task_budget_allocator_tick        (0x5b14)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x498)
#define image_4_start_task_check_skip_cso        (0x311c)
#define image_4_start_task_debug_routine        (0x1f0)
#define image_4_start_task_dos_attack_handler        (0x2698)
#define image_4_start_task_drop_pkt_and_serial        (0x2890)
#define image_4_start_task_flow_policer        (0x5334)
#define image_4_start_task_general_timer_wakeup_request        (0x68a4)
#define image_4_start_task_get_queue_delay        (0x5958)
#define image_4_start_task_ghost_reporting_wakeup_request        (0x53f4)
#define image_4_start_task_group_flow_lkp_and_fwd        (0x329c)
#define image_4_start_task_handle_flush        (0x5e54)
#define image_4_start_task_ingress_filter_action_point_update        (0x31a8)
#define image_4_start_task_ingress_filters_handler        (0x2a18)
#define image_4_start_task_initialization_task        (0x1c8)
#define image_4_start_task_is_iptv_capable        (0x26f4)
#define image_4_start_task_mcast_flow_master_lookup        (0x31f4)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x2b8)
#define image_4_start_task_parser_exception_handler        (0x24b4)
#define image_4_start_task_pi2_deque_check        (0x5a14)
#define image_4_start_task_pi2_deque_inc_drop_stats        (0x59ac)
#define image_4_start_task_pi2_get_queue_delay        (0x5828)
#define image_4_start_task_pi2_probability_calc        (0x5894)
#define image_4_start_task_pi2_timer        (0x5760)
#define image_4_start_task_proccessing_loopback        (0x2400)
#define image_4_start_task_processing_policer_action        (0x5384)
#define image_4_start_task_processing_wakeup_request        (0x4d4)
#define image_4_start_task_spdsvc_natc_lookup        (0x2794)
#define image_4_start_task_tm_tx_handle_rate_limit        (0x5c58)
#define image_4_start_task_tm_tx_mirroring_handle        (0x6788)
#define image_4_start_task_tm_tx_task_wakeup_request        (0x5fc0)
#define image_4_start_task_tm_update_fifo_first_wakeup_request        (0x5d18)
#define image_4_start_task_ts_1588_handler        (0x29e4)
#define image_4_start_task_tx_mirror        (0x67b4)
#define image_4_start_task_xx_mirror_noinline        (0x2d50)
#define image_4_tm_tx_handle_rate_limit        (0x5c58)
#define image_4_tm_tx_mirroring_handle        (0x6788)
#define image_4_tm_tx_task_wakeup_request        (0x5fc0)
#define image_4_tm_update_fifo_first_wakeup_request        (0x5d18)
#define image_4_ts_1588_handler        (0x29e4)
#define image_4_tx_mirror        (0x67b4)
#define image_4_xx_mirror_noinline        (0x2d50)

#else

#define image_4___umulhisi3        (0x1a57)
#define image_4___umulsi3        (0x1a47)
#define image_4_add_pbit_to_key        (0xc5f)
#define image_4_budget_allocator_tick        (0x16c5)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x126)
#define image_4_check_skip_cso        (0xc47)
#define image_4_debug_routine        (0x7c)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dos_attack_handler        (0x9a6)
#define image_4_drop_pkt_and_serial        (0xa24)
#define image_4_dynamic_code_section        (0x2)
#define image_4_dynamic_code_section_proc0        (0x2)
#define image_4_dynamic_code_section_proc1        (0x1e)
#define image_4_dynamic_code_section_proc2        (0x3a)
#define image_4_dynamic_code_section_proc3        (0x56)
#define image_4_flow_policer        (0x14cd)
#define image_4_general_timer_wakeup_request        (0x1a29)
#define image_4_get_queue_delay        (0x1656)
#define image_4_ghost_reporting_wakeup_request        (0x14fd)
#define image_4_group_flow_lkp_and_fwd        (0xca7)
#define image_4_handle_flush        (0x1795)
#define image_4_ingress_filter_action_point_update        (0xc6a)
#define image_4_ingress_filters_handler        (0xa86)
#define image_4_initialization_task        (0x72)
#define image_4_is_iptv_capable        (0x9bd)
#define image_4_mcast_flow_master_lookup        (0xc7d)
#define image_4_memcpy_abs_to_sbpm        (0xae)
#define image_4_parser_exception_handler        (0x92d)
#define image_4_pi2_deque_check        (0x1685)
#define image_4_pi2_deque_inc_drop_stats        (0x166b)
#define image_4_pi2_get_queue_delay        (0x160a)
#define image_4_pi2_probability_calc        (0x1625)
#define image_4_pi2_timer        (0x15d8)
#define image_4_proccessing_loopback        (0x900)
#define image_4_processing_policer_action        (0x14e1)
#define image_4_processing_wakeup_request        (0x135)
#define image_4_spdsvc_natc_lookup        (0x9e5)
#define image_4_start_task___umulhisi3        (0x1a57)
#define image_4_start_task___umulsi3        (0x1a47)
#define image_4_start_task_add_pbit_to_key        (0xc5f)
#define image_4_start_task_budget_allocator_tick        (0x16c5)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x126)
#define image_4_start_task_check_skip_cso        (0xc47)
#define image_4_start_task_debug_routine        (0x7c)
#define image_4_start_task_dos_attack_handler        (0x9a6)
#define image_4_start_task_drop_pkt_and_serial        (0xa24)
#define image_4_start_task_flow_policer        (0x14cd)
#define image_4_start_task_general_timer_wakeup_request        (0x1a29)
#define image_4_start_task_get_queue_delay        (0x1656)
#define image_4_start_task_ghost_reporting_wakeup_request        (0x14fd)
#define image_4_start_task_group_flow_lkp_and_fwd        (0xca7)
#define image_4_start_task_handle_flush        (0x1795)
#define image_4_start_task_ingress_filter_action_point_update        (0xc6a)
#define image_4_start_task_ingress_filters_handler        (0xa86)
#define image_4_start_task_initialization_task        (0x72)
#define image_4_start_task_is_iptv_capable        (0x9bd)
#define image_4_start_task_mcast_flow_master_lookup        (0xc7d)
#define image_4_start_task_memcpy_abs_to_sbpm        (0xae)
#define image_4_start_task_parser_exception_handler        (0x92d)
#define image_4_start_task_pi2_deque_check        (0x1685)
#define image_4_start_task_pi2_deque_inc_drop_stats        (0x166b)
#define image_4_start_task_pi2_get_queue_delay        (0x160a)
#define image_4_start_task_pi2_probability_calc        (0x1625)
#define image_4_start_task_pi2_timer        (0x15d8)
#define image_4_start_task_proccessing_loopback        (0x900)
#define image_4_start_task_processing_policer_action        (0x14e1)
#define image_4_start_task_processing_wakeup_request        (0x135)
#define image_4_start_task_spdsvc_natc_lookup        (0x9e5)
#define image_4_start_task_tm_tx_handle_rate_limit        (0x1716)
#define image_4_start_task_tm_tx_mirroring_handle        (0x19e2)
#define image_4_start_task_tm_tx_task_wakeup_request        (0x17f0)
#define image_4_start_task_tm_update_fifo_first_wakeup_request        (0x1746)
#define image_4_start_task_ts_1588_handler        (0xa79)
#define image_4_start_task_tx_mirror        (0x19ed)
#define image_4_start_task_xx_mirror_noinline        (0xb54)
#define image_4_tm_tx_handle_rate_limit        (0x1716)
#define image_4_tm_tx_mirroring_handle        (0x19e2)
#define image_4_tm_tx_task_wakeup_request        (0x17f0)
#define image_4_tm_update_fifo_first_wakeup_request        (0x1746)
#define image_4_ts_1588_handler        (0xa79)
#define image_4_tx_mirror        (0x19ed)
#define image_4_xx_mirror_noinline        (0xb54)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5___umulhisi3        (0x1d48)
#define image_5___umulsi3        (0x1d08)
#define image_5_budget_allocator_tick        (0x1b1c)
#define image_5_debug_routine        (0x30)
#define image_5_debug_routine_handler        (0x4)
#define image_5_direct_flow_wakeup_request        (0x2d8)
#define image_5_epon_tm_tx        (0x1820)
#define image_5_epon_tm_tx_credit_free        (0x1adc)
#define image_5_epon_tm_tx_task_wakeup_request        (0x19c8)
#define image_5_epon_tm_update_fifo_first_wakeup_request        (0x197c)
#define image_5_general_timer_wakeup_request        (0x1c60)
#define image_5_get_queue_delay        (0x990)
#define image_5_handle_flush        (0xc88)
#define image_5_initialization_task        (0x8)
#define image_5_memcpy_abs_to_sbpm        (0xf8)
#define image_5_pi2_deque_check        (0xa4c)
#define image_5_pi2_deque_inc_drop_stats        (0x9e4)
#define image_5_pi2_get_queue_delay        (0x860)
#define image_5_pi2_probability_calc        (0x8cc)
#define image_5_pi2_timer        (0x79c)
#define image_5_start_task___umulhisi3        (0x1d48)
#define image_5_start_task___umulsi3        (0x1d08)
#define image_5_start_task_budget_allocator_tick        (0x1b1c)
#define image_5_start_task_debug_routine        (0x30)
#define image_5_start_task_direct_flow_wakeup_request        (0x2d8)
#define image_5_start_task_epon_tm_tx        (0x1820)
#define image_5_start_task_epon_tm_tx_credit_free        (0x1adc)
#define image_5_start_task_epon_tm_tx_task_wakeup_request        (0x19c8)
#define image_5_start_task_epon_tm_update_fifo_first_wakeup_request        (0x197c)
#define image_5_start_task_general_timer_wakeup_request        (0x1c60)
#define image_5_start_task_get_queue_delay        (0x990)
#define image_5_start_task_handle_flush        (0xc88)
#define image_5_start_task_initialization_task        (0x8)
#define image_5_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_5_start_task_pi2_deque_check        (0xa4c)
#define image_5_start_task_pi2_deque_inc_drop_stats        (0x9e4)
#define image_5_start_task_pi2_get_queue_delay        (0x860)
#define image_5_start_task_pi2_probability_calc        (0x8cc)
#define image_5_start_task_pi2_timer        (0x79c)
#define image_5_start_task_tm_tx_dbg_stat_by_size        (0x1734)
#define image_5_start_task_tm_tx_dbg_stat_get_cntr_id        (0x1cd8)
#define image_5_start_task_tm_tx_handle_rate_limit        (0x1648)
#define image_5_start_task_tm_tx_mirroring_handle        (0x1708)
#define image_5_start_task_tm_tx_task_wakeup_request        (0xdf4)
#define image_5_start_task_tm_update_fifo_first_wakeup_request        (0xb4c)
#define image_5_start_task_tx_mirror        (0x188c)
#define image_5_tm_tx_dbg_stat_by_size        (0x1734)
#define image_5_tm_tx_dbg_stat_get_cntr_id        (0x1cd8)
#define image_5_tm_tx_handle_rate_limit        (0x1648)
#define image_5_tm_tx_mirroring_handle        (0x1708)
#define image_5_tm_tx_task_wakeup_request        (0xdf4)
#define image_5_tm_update_fifo_first_wakeup_request        (0xb4c)
#define image_5_tx_mirror        (0x188c)

#else

#define image_5___umulhisi3        (0x752)
#define image_5___umulsi3        (0x742)
#define image_5_budget_allocator_tick        (0x6c7)
#define image_5_debug_routine        (0xc)
#define image_5_debug_routine_handler        (0x1)
#define image_5_direct_flow_wakeup_request        (0xb6)
#define image_5_epon_tm_tx        (0x608)
#define image_5_epon_tm_tx_credit_free        (0x6b7)
#define image_5_epon_tm_tx_task_wakeup_request        (0x672)
#define image_5_epon_tm_update_fifo_first_wakeup_request        (0x65f)
#define image_5_general_timer_wakeup_request        (0x718)
#define image_5_get_queue_delay        (0x264)
#define image_5_handle_flush        (0x322)
#define image_5_initialization_task        (0x2)
#define image_5_memcpy_abs_to_sbpm        (0x3e)
#define image_5_pi2_deque_check        (0x293)
#define image_5_pi2_deque_inc_drop_stats        (0x279)
#define image_5_pi2_get_queue_delay        (0x218)
#define image_5_pi2_probability_calc        (0x233)
#define image_5_pi2_timer        (0x1e7)
#define image_5_start_task___umulhisi3        (0x752)
#define image_5_start_task___umulsi3        (0x742)
#define image_5_start_task_budget_allocator_tick        (0x6c7)
#define image_5_start_task_debug_routine        (0xc)
#define image_5_start_task_direct_flow_wakeup_request        (0xb6)
#define image_5_start_task_epon_tm_tx        (0x608)
#define image_5_start_task_epon_tm_tx_credit_free        (0x6b7)
#define image_5_start_task_epon_tm_tx_task_wakeup_request        (0x672)
#define image_5_start_task_epon_tm_update_fifo_first_wakeup_request        (0x65f)
#define image_5_start_task_general_timer_wakeup_request        (0x718)
#define image_5_start_task_get_queue_delay        (0x264)
#define image_5_start_task_handle_flush        (0x322)
#define image_5_start_task_initialization_task        (0x2)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_5_start_task_pi2_deque_check        (0x293)
#define image_5_start_task_pi2_deque_inc_drop_stats        (0x279)
#define image_5_start_task_pi2_get_queue_delay        (0x218)
#define image_5_start_task_pi2_probability_calc        (0x233)
#define image_5_start_task_pi2_timer        (0x1e7)
#define image_5_start_task_tm_tx_dbg_stat_by_size        (0x5cd)
#define image_5_start_task_tm_tx_dbg_stat_get_cntr_id        (0x736)
#define image_5_start_task_tm_tx_handle_rate_limit        (0x592)
#define image_5_start_task_tm_tx_mirroring_handle        (0x5c2)
#define image_5_start_task_tm_tx_task_wakeup_request        (0x37d)
#define image_5_start_task_tm_update_fifo_first_wakeup_request        (0x2d3)
#define image_5_start_task_tx_mirror        (0x623)
#define image_5_tm_tx_dbg_stat_by_size        (0x5cd)
#define image_5_tm_tx_dbg_stat_get_cntr_id        (0x736)
#define image_5_tm_tx_handle_rate_limit        (0x592)
#define image_5_tm_tx_mirroring_handle        (0x5c2)
#define image_5_tm_tx_task_wakeup_request        (0x37d)
#define image_5_tm_update_fifo_first_wakeup_request        (0x2d3)
#define image_5_tx_mirror        (0x623)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND


#else


#endif


#endif

