OBJS := bcm_ipc_api.o

CFLAGS += -Werror -Wfatal-errors


$(LIB): $(OBJS)
	$(CC) -shared $(BCM_LD_FLAGS) -Wl,--whole-archive,-soname,$(notdir $@) -o $@ $(OBJS) -Wl,--no-whole-archive


binaryonly_prepare:
	-cp $(LIB) $(mdir)/$(SAVED)
	-$(MAKE) -f $(name) clean
	rm -f $(mdir)/*.c $(mdir)/*.h $(mdir)/Makefile.fullsrc


# Generate and use dependencies.
CFLAGS += -MD
-include $(OBJS:%.o=%.d)
