/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_0_add_pbit_to_key        (0x29a4)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_0_check_skip_cso        (0x2944)
#define image_0_debug_routine        (0x30)
#define image_0_debug_routine_handler        (0x4)
#define image_0_dos_attack_handler        (0x1f08)
#define image_0_drop_pkt_and_serial        (0x20f8)
#define image_0_dyn_code_func        (0x7c00)
#define image_0_flow_policer        (0x485c)
#define image_0_group_flow_lkp_and_fwd        (0x2ac4)
#define image_0_ingress_filter_action_point_update        (0x29d0)
#define image_0_ingress_filters_handler        (0x2270)
#define image_0_initialization_task        (0x8)
#define image_0_is_iptv_capable        (0x1f64)
#define image_0_mcast_flow_master_lookup        (0x2a1c)
#define image_0_memcpy_abs_to_sbpm        (0xf8)
#define image_0_parser_exception_handler        (0x1d24)
#define image_0_proccessing_loopback        (0x1c6c)
#define image_0_processing_policer_action        (0x48ac)
#define image_0_processing_wakeup_request        (0x314)
#define image_0_spdsvc_natc_lookup        (0x2004)
#define image_0_start_task_add_pbit_to_key        (0x29a4)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_0_start_task_check_skip_cso        (0x2944)
#define image_0_start_task_debug_routine        (0x30)
#define image_0_start_task_dos_attack_handler        (0x1f08)
#define image_0_start_task_drop_pkt_and_serial        (0x20f8)
#define image_0_start_task_dyn_code_func        (0x7c00)
#define image_0_start_task_flow_policer        (0x485c)
#define image_0_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_0_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_0_start_task_ingress_filters_handler        (0x2270)
#define image_0_start_task_initialization_task        (0x8)
#define image_0_start_task_is_iptv_capable        (0x1f64)
#define image_0_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_0_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_0_start_task_parser_exception_handler        (0x1d24)
#define image_0_start_task_proccessing_loopback        (0x1c6c)
#define image_0_start_task_processing_policer_action        (0x48ac)
#define image_0_start_task_processing_wakeup_request        (0x314)
#define image_0_start_task_spdsvc_natc_lookup        (0x2004)
#define image_0_start_task_ts_1588_handler        (0x223c)
#define image_0_start_task_xx_mirror_noinline        (0x25a8)
#define image_0_ts_1588_handler        (0x223c)
#define image_0_xx_mirror_noinline        (0x25a8)

#else

#define image_0_add_pbit_to_key        (0xa69)
#define image_0_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_0_check_skip_cso        (0xa51)
#define image_0_debug_routine        (0xc)
#define image_0_debug_routine_handler        (0x1)
#define image_0_dos_attack_handler        (0x7c2)
#define image_0_drop_pkt_and_serial        (0x83e)
#define image_0_dyn_code_func        (0x1f00)
#define image_0_flow_policer        (0x1217)
#define image_0_group_flow_lkp_and_fwd        (0xab1)
#define image_0_ingress_filter_action_point_update        (0xa74)
#define image_0_ingress_filters_handler        (0x89c)
#define image_0_initialization_task        (0x2)
#define image_0_is_iptv_capable        (0x7d9)
#define image_0_mcast_flow_master_lookup        (0xa87)
#define image_0_memcpy_abs_to_sbpm        (0x3e)
#define image_0_parser_exception_handler        (0x749)
#define image_0_proccessing_loopback        (0x71b)
#define image_0_processing_policer_action        (0x122b)
#define image_0_processing_wakeup_request        (0xc5)
#define image_0_spdsvc_natc_lookup        (0x801)
#define image_0_start_task_add_pbit_to_key        (0xa69)
#define image_0_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_0_start_task_check_skip_cso        (0xa51)
#define image_0_start_task_debug_routine        (0xc)
#define image_0_start_task_dos_attack_handler        (0x7c2)
#define image_0_start_task_drop_pkt_and_serial        (0x83e)
#define image_0_start_task_dyn_code_func        (0x1f00)
#define image_0_start_task_flow_policer        (0x1217)
#define image_0_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_0_start_task_ingress_filter_action_point_update        (0xa74)
#define image_0_start_task_ingress_filters_handler        (0x89c)
#define image_0_start_task_initialization_task        (0x2)
#define image_0_start_task_is_iptv_capable        (0x7d9)
#define image_0_start_task_mcast_flow_master_lookup        (0xa87)
#define image_0_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_0_start_task_parser_exception_handler        (0x749)
#define image_0_start_task_proccessing_loopback        (0x71b)
#define image_0_start_task_processing_policer_action        (0x122b)
#define image_0_start_task_processing_wakeup_request        (0xc5)
#define image_0_start_task_spdsvc_natc_lookup        (0x801)
#define image_0_start_task_ts_1588_handler        (0x88f)
#define image_0_start_task_xx_mirror_noinline        (0x96a)
#define image_0_ts_1588_handler        (0x88f)
#define image_0_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_1_add_pbit_to_key        (0x29a4)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_1_check_skip_cso        (0x2944)
#define image_1_debug_routine        (0x30)
#define image_1_debug_routine_handler        (0x4)
#define image_1_dos_attack_handler        (0x1f08)
#define image_1_drop_pkt_and_serial        (0x20f8)
#define image_1_dyn_code_func        (0x7c00)
#define image_1_flow_policer        (0x485c)
#define image_1_group_flow_lkp_and_fwd        (0x2ac4)
#define image_1_ingress_filter_action_point_update        (0x29d0)
#define image_1_ingress_filters_handler        (0x2270)
#define image_1_initialization_task        (0x8)
#define image_1_is_iptv_capable        (0x1f64)
#define image_1_mcast_flow_master_lookup        (0x2a1c)
#define image_1_memcpy_abs_to_sbpm        (0xf8)
#define image_1_parser_exception_handler        (0x1d24)
#define image_1_proccessing_loopback        (0x1c6c)
#define image_1_processing_policer_action        (0x48ac)
#define image_1_processing_wakeup_request        (0x314)
#define image_1_spdsvc_natc_lookup        (0x2004)
#define image_1_start_task_add_pbit_to_key        (0x29a4)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_1_start_task_check_skip_cso        (0x2944)
#define image_1_start_task_debug_routine        (0x30)
#define image_1_start_task_dos_attack_handler        (0x1f08)
#define image_1_start_task_drop_pkt_and_serial        (0x20f8)
#define image_1_start_task_dyn_code_func        (0x7c00)
#define image_1_start_task_flow_policer        (0x485c)
#define image_1_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_1_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_1_start_task_ingress_filters_handler        (0x2270)
#define image_1_start_task_initialization_task        (0x8)
#define image_1_start_task_is_iptv_capable        (0x1f64)
#define image_1_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_1_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_1_start_task_parser_exception_handler        (0x1d24)
#define image_1_start_task_proccessing_loopback        (0x1c6c)
#define image_1_start_task_processing_policer_action        (0x48ac)
#define image_1_start_task_processing_wakeup_request        (0x314)
#define image_1_start_task_spdsvc_natc_lookup        (0x2004)
#define image_1_start_task_ts_1588_handler        (0x223c)
#define image_1_start_task_xx_mirror_noinline        (0x25a8)
#define image_1_ts_1588_handler        (0x223c)
#define image_1_xx_mirror_noinline        (0x25a8)

#else

#define image_1_add_pbit_to_key        (0xa69)
#define image_1_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_1_check_skip_cso        (0xa51)
#define image_1_debug_routine        (0xc)
#define image_1_debug_routine_handler        (0x1)
#define image_1_dos_attack_handler        (0x7c2)
#define image_1_drop_pkt_and_serial        (0x83e)
#define image_1_dyn_code_func        (0x1f00)
#define image_1_flow_policer        (0x1217)
#define image_1_group_flow_lkp_and_fwd        (0xab1)
#define image_1_ingress_filter_action_point_update        (0xa74)
#define image_1_ingress_filters_handler        (0x89c)
#define image_1_initialization_task        (0x2)
#define image_1_is_iptv_capable        (0x7d9)
#define image_1_mcast_flow_master_lookup        (0xa87)
#define image_1_memcpy_abs_to_sbpm        (0x3e)
#define image_1_parser_exception_handler        (0x749)
#define image_1_proccessing_loopback        (0x71b)
#define image_1_processing_policer_action        (0x122b)
#define image_1_processing_wakeup_request        (0xc5)
#define image_1_spdsvc_natc_lookup        (0x801)
#define image_1_start_task_add_pbit_to_key        (0xa69)
#define image_1_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_1_start_task_check_skip_cso        (0xa51)
#define image_1_start_task_debug_routine        (0xc)
#define image_1_start_task_dos_attack_handler        (0x7c2)
#define image_1_start_task_drop_pkt_and_serial        (0x83e)
#define image_1_start_task_dyn_code_func        (0x1f00)
#define image_1_start_task_flow_policer        (0x1217)
#define image_1_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_1_start_task_ingress_filter_action_point_update        (0xa74)
#define image_1_start_task_ingress_filters_handler        (0x89c)
#define image_1_start_task_initialization_task        (0x2)
#define image_1_start_task_is_iptv_capable        (0x7d9)
#define image_1_start_task_mcast_flow_master_lookup        (0xa87)
#define image_1_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_1_start_task_parser_exception_handler        (0x749)
#define image_1_start_task_proccessing_loopback        (0x71b)
#define image_1_start_task_processing_policer_action        (0x122b)
#define image_1_start_task_processing_wakeup_request        (0xc5)
#define image_1_start_task_spdsvc_natc_lookup        (0x801)
#define image_1_start_task_ts_1588_handler        (0x88f)
#define image_1_start_task_xx_mirror_noinline        (0x96a)
#define image_1_ts_1588_handler        (0x88f)
#define image_1_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_2_add_pbit_to_key        (0x29a4)
#define image_2_c_cpu_recycle_wakeup_request        (0x4994)
#define image_2_c_cpu_rx_copy_wakeup_request        (0x4fc0)
#define image_2_c_cpu_rx_wakeup_request        (0x4b24)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_2_check_skip_cso        (0x2944)
#define image_2_cpu_recycle_int_coalescing        (0x4af8)
#define image_2_cpu_rx_int_coalescing        (0x4f10)
#define image_2_cpu_rx_meter_budget_allocator        (0x4f5c)
#define image_2_debug_routine        (0x30)
#define image_2_debug_routine_handler        (0x4)
#define image_2_dos_attack_handler        (0x1f08)
#define image_2_drop_pkt_and_serial        (0x20f8)
#define image_2_dyn_code_func        (0x7c00)
#define image_2_flow_policer        (0x485c)
#define image_2_general_timer_wakeup_request        (0x491c)
#define image_2_get_pd_from_fifo        (0x590c)
#define image_2_group_flow_lkp_and_fwd        (0x2ac4)
#define image_2_ingress_filter_action_point_update        (0x29d0)
#define image_2_ingress_filters_handler        (0x2270)
#define image_2_initialization_task        (0x8)
#define image_2_is_iptv_capable        (0x1f64)
#define image_2_mcast_flow_master_lookup        (0x2a1c)
#define image_2_memcpy_abs_to_sbpm        (0xf8)
#define image_2_packet_cso_hw_offload        (0x5830)
#define image_2_parser_exception_handler        (0x1d24)
#define image_2_proccessing_loopback        (0x1c6c)
#define image_2_processing_policer_action        (0x48ac)
#define image_2_processing_wakeup_request        (0x314)
#define image_2_spdsvc_natc_lookup        (0x2004)
#define image_2_start_task_add_pbit_to_key        (0x29a4)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x4994)
#define image_2_start_task_c_cpu_rx_copy_wakeup_request        (0x4fc0)
#define image_2_start_task_c_cpu_rx_wakeup_request        (0x4b24)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_2_start_task_check_skip_cso        (0x2944)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x4af8)
#define image_2_start_task_cpu_rx_int_coalescing        (0x4f10)
#define image_2_start_task_cpu_rx_meter_budget_allocator        (0x4f5c)
#define image_2_start_task_debug_routine        (0x30)
#define image_2_start_task_dos_attack_handler        (0x1f08)
#define image_2_start_task_drop_pkt_and_serial        (0x20f8)
#define image_2_start_task_dyn_code_func        (0x7c00)
#define image_2_start_task_flow_policer        (0x485c)
#define image_2_start_task_general_timer_wakeup_request        (0x491c)
#define image_2_start_task_get_pd_from_fifo        (0x590c)
#define image_2_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_2_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_2_start_task_ingress_filters_handler        (0x2270)
#define image_2_start_task_initialization_task        (0x8)
#define image_2_start_task_is_iptv_capable        (0x1f64)
#define image_2_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_2_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_2_start_task_packet_cso_hw_offload        (0x5830)
#define image_2_start_task_parser_exception_handler        (0x1d24)
#define image_2_start_task_proccessing_loopback        (0x1c6c)
#define image_2_start_task_processing_policer_action        (0x48ac)
#define image_2_start_task_processing_wakeup_request        (0x314)
#define image_2_start_task_spdsvc_natc_lookup        (0x2004)
#define image_2_start_task_ts_1588_handler        (0x223c)
#define image_2_start_task_xx_mirror_noinline        (0x25a8)
#define image_2_ts_1588_handler        (0x223c)
#define image_2_xx_mirror_noinline        (0x25a8)

#else

#define image_2_add_pbit_to_key        (0xa69)
#define image_2_c_cpu_recycle_wakeup_request        (0x1265)
#define image_2_c_cpu_rx_copy_wakeup_request        (0x13f0)
#define image_2_c_cpu_rx_wakeup_request        (0x12c9)
#define image_2_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_2_check_skip_cso        (0xa51)
#define image_2_cpu_recycle_int_coalescing        (0x12be)
#define image_2_cpu_rx_int_coalescing        (0x13c4)
#define image_2_cpu_rx_meter_budget_allocator        (0x13d7)
#define image_2_debug_routine        (0xc)
#define image_2_debug_routine_handler        (0x1)
#define image_2_dos_attack_handler        (0x7c2)
#define image_2_drop_pkt_and_serial        (0x83e)
#define image_2_dyn_code_func        (0x1f00)
#define image_2_flow_policer        (0x1217)
#define image_2_general_timer_wakeup_request        (0x1247)
#define image_2_get_pd_from_fifo        (0x1643)
#define image_2_group_flow_lkp_and_fwd        (0xab1)
#define image_2_ingress_filter_action_point_update        (0xa74)
#define image_2_ingress_filters_handler        (0x89c)
#define image_2_initialization_task        (0x2)
#define image_2_is_iptv_capable        (0x7d9)
#define image_2_mcast_flow_master_lookup        (0xa87)
#define image_2_memcpy_abs_to_sbpm        (0x3e)
#define image_2_packet_cso_hw_offload        (0x160c)
#define image_2_parser_exception_handler        (0x749)
#define image_2_proccessing_loopback        (0x71b)
#define image_2_processing_policer_action        (0x122b)
#define image_2_processing_wakeup_request        (0xc5)
#define image_2_spdsvc_natc_lookup        (0x801)
#define image_2_start_task_add_pbit_to_key        (0xa69)
#define image_2_start_task_c_cpu_recycle_wakeup_request        (0x1265)
#define image_2_start_task_c_cpu_rx_copy_wakeup_request        (0x13f0)
#define image_2_start_task_c_cpu_rx_wakeup_request        (0x12c9)
#define image_2_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_2_start_task_check_skip_cso        (0xa51)
#define image_2_start_task_cpu_recycle_int_coalescing        (0x12be)
#define image_2_start_task_cpu_rx_int_coalescing        (0x13c4)
#define image_2_start_task_cpu_rx_meter_budget_allocator        (0x13d7)
#define image_2_start_task_debug_routine        (0xc)
#define image_2_start_task_dos_attack_handler        (0x7c2)
#define image_2_start_task_drop_pkt_and_serial        (0x83e)
#define image_2_start_task_dyn_code_func        (0x1f00)
#define image_2_start_task_flow_policer        (0x1217)
#define image_2_start_task_general_timer_wakeup_request        (0x1247)
#define image_2_start_task_get_pd_from_fifo        (0x1643)
#define image_2_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_2_start_task_ingress_filter_action_point_update        (0xa74)
#define image_2_start_task_ingress_filters_handler        (0x89c)
#define image_2_start_task_initialization_task        (0x2)
#define image_2_start_task_is_iptv_capable        (0x7d9)
#define image_2_start_task_mcast_flow_master_lookup        (0xa87)
#define image_2_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_2_start_task_packet_cso_hw_offload        (0x160c)
#define image_2_start_task_parser_exception_handler        (0x749)
#define image_2_start_task_proccessing_loopback        (0x71b)
#define image_2_start_task_processing_policer_action        (0x122b)
#define image_2_start_task_processing_wakeup_request        (0xc5)
#define image_2_start_task_spdsvc_natc_lookup        (0x801)
#define image_2_start_task_ts_1588_handler        (0x88f)
#define image_2_start_task_xx_mirror_noinline        (0x96a)
#define image_2_ts_1588_handler        (0x88f)
#define image_2_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_3_add_pbit_to_key        (0x31dc)
#define image_3_c_cpu_recycle_wakeup_request        (0x51cc)
#define image_3_c_cpu_tx_wakeup_request        (0x4d4)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x498)
#define image_3_check_skip_cso        (0x317c)
#define image_3_cpu_recycle_int_coalescing        (0x5330)
#define image_3_cpu_tx_send_pd_to_recycle        (0xac0)
#define image_3_cpu_tx_sync_tasks        (0xb2c)
#define image_3_debug_routine        (0x30)
#define image_3_debug_routine_handler        (0x4)
#define image_3_dos_attack_handler        (0x2740)
#define image_3_drop_pkt_and_serial        (0x2930)
#define image_3_dyn_code_func        (0x7c00)
#define image_3_flow_policer        (0x5094)
#define image_3_general_timer_wakeup_request        (0x5154)
#define image_3_group_flow_lkp_and_fwd        (0x32fc)
#define image_3_ingress_filter_action_point_update        (0x3208)
#define image_3_ingress_filters_handler        (0x2aa8)
#define image_3_initialization_task        (0x8)
#define image_3_is_iptv_capable        (0x279c)
#define image_3_mcast_flow_master_lookup        (0x3254)
#define image_3_memcpy_abs_to_fpm        (0x2d8)
#define image_3_memcpy_abs_to_sbpm        (0xf8)
#define image_3_parser_exception_handler        (0x255c)
#define image_3_proccessing_loopback        (0x24a4)
#define image_3_processing_policer_action        (0x50e4)
#define image_3_processing_wakeup_request        (0xb4c)
#define image_3_spdsvc_natc_lookup        (0x283c)
#define image_3_start_task_add_pbit_to_key        (0x31dc)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x51cc)
#define image_3_start_task_c_cpu_tx_wakeup_request        (0x4d4)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x498)
#define image_3_start_task_check_skip_cso        (0x317c)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x5330)
#define image_3_start_task_cpu_tx_send_pd_to_recycle        (0xac0)
#define image_3_start_task_cpu_tx_sync_tasks        (0xb2c)
#define image_3_start_task_debug_routine        (0x30)
#define image_3_start_task_dos_attack_handler        (0x2740)
#define image_3_start_task_drop_pkt_and_serial        (0x2930)
#define image_3_start_task_dyn_code_func        (0x7c00)
#define image_3_start_task_flow_policer        (0x5094)
#define image_3_start_task_general_timer_wakeup_request        (0x5154)
#define image_3_start_task_group_flow_lkp_and_fwd        (0x32fc)
#define image_3_start_task_ingress_filter_action_point_update        (0x3208)
#define image_3_start_task_ingress_filters_handler        (0x2aa8)
#define image_3_start_task_initialization_task        (0x8)
#define image_3_start_task_is_iptv_capable        (0x279c)
#define image_3_start_task_mcast_flow_master_lookup        (0x3254)
#define image_3_start_task_memcpy_abs_to_fpm        (0x2d8)
#define image_3_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_3_start_task_parser_exception_handler        (0x255c)
#define image_3_start_task_proccessing_loopback        (0x24a4)
#define image_3_start_task_processing_policer_action        (0x50e4)
#define image_3_start_task_processing_wakeup_request        (0xb4c)
#define image_3_start_task_spdsvc_natc_lookup        (0x283c)
#define image_3_start_task_ts_1588_handler        (0x2a74)
#define image_3_start_task_xx_mirror_noinline        (0x2de0)
#define image_3_ts_1588_handler        (0x2a74)
#define image_3_xx_mirror_noinline        (0x2de0)

#else

#define image_3_add_pbit_to_key        (0xc77)
#define image_3_c_cpu_recycle_wakeup_request        (0x1473)
#define image_3_c_cpu_tx_wakeup_request        (0x135)
#define image_3_check_cpu_rx_gdx_queue_occupancy        (0x126)
#define image_3_check_skip_cso        (0xc5f)
#define image_3_cpu_recycle_int_coalescing        (0x14cc)
#define image_3_cpu_tx_send_pd_to_recycle        (0x2b0)
#define image_3_cpu_tx_sync_tasks        (0x2cb)
#define image_3_debug_routine        (0xc)
#define image_3_debug_routine_handler        (0x1)
#define image_3_dos_attack_handler        (0x9d0)
#define image_3_drop_pkt_and_serial        (0xa4c)
#define image_3_dyn_code_func        (0x1f00)
#define image_3_flow_policer        (0x1425)
#define image_3_general_timer_wakeup_request        (0x1455)
#define image_3_group_flow_lkp_and_fwd        (0xcbf)
#define image_3_ingress_filter_action_point_update        (0xc82)
#define image_3_ingress_filters_handler        (0xaaa)
#define image_3_initialization_task        (0x2)
#define image_3_is_iptv_capable        (0x9e7)
#define image_3_mcast_flow_master_lookup        (0xc95)
#define image_3_memcpy_abs_to_fpm        (0xb6)
#define image_3_memcpy_abs_to_sbpm        (0x3e)
#define image_3_parser_exception_handler        (0x957)
#define image_3_proccessing_loopback        (0x929)
#define image_3_processing_policer_action        (0x1439)
#define image_3_processing_wakeup_request        (0x2d3)
#define image_3_spdsvc_natc_lookup        (0xa0f)
#define image_3_start_task_add_pbit_to_key        (0xc77)
#define image_3_start_task_c_cpu_recycle_wakeup_request        (0x1473)
#define image_3_start_task_c_cpu_tx_wakeup_request        (0x135)
#define image_3_start_task_check_cpu_rx_gdx_queue_occupancy        (0x126)
#define image_3_start_task_check_skip_cso        (0xc5f)
#define image_3_start_task_cpu_recycle_int_coalescing        (0x14cc)
#define image_3_start_task_cpu_tx_send_pd_to_recycle        (0x2b0)
#define image_3_start_task_cpu_tx_sync_tasks        (0x2cb)
#define image_3_start_task_debug_routine        (0xc)
#define image_3_start_task_dos_attack_handler        (0x9d0)
#define image_3_start_task_drop_pkt_and_serial        (0xa4c)
#define image_3_start_task_dyn_code_func        (0x1f00)
#define image_3_start_task_flow_policer        (0x1425)
#define image_3_start_task_general_timer_wakeup_request        (0x1455)
#define image_3_start_task_group_flow_lkp_and_fwd        (0xcbf)
#define image_3_start_task_ingress_filter_action_point_update        (0xc82)
#define image_3_start_task_ingress_filters_handler        (0xaaa)
#define image_3_start_task_initialization_task        (0x2)
#define image_3_start_task_is_iptv_capable        (0x9e7)
#define image_3_start_task_mcast_flow_master_lookup        (0xc95)
#define image_3_start_task_memcpy_abs_to_fpm        (0xb6)
#define image_3_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_3_start_task_parser_exception_handler        (0x957)
#define image_3_start_task_proccessing_loopback        (0x929)
#define image_3_start_task_processing_policer_action        (0x1439)
#define image_3_start_task_processing_wakeup_request        (0x2d3)
#define image_3_start_task_spdsvc_natc_lookup        (0xa0f)
#define image_3_start_task_ts_1588_handler        (0xa9d)
#define image_3_start_task_xx_mirror_noinline        (0xb78)
#define image_3_ts_1588_handler        (0xa9d)
#define image_3_xx_mirror_noinline        (0xb78)

#endif


#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_4_add_pbit_to_key        (0x29a4)
#define image_4_c_spu_request_wakeup_request        (0x491c)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_4_check_skip_cso        (0x2944)
#define image_4_debug_routine        (0x30)
#define image_4_debug_routine_handler        (0x4)
#define image_4_dos_attack_handler        (0x1f08)
#define image_4_drop_pkt_and_serial        (0x20f8)
#define image_4_dyn_code_func        (0x7c00)
#define image_4_flow_policer        (0x485c)
#define image_4_group_flow_lkp_and_fwd        (0x2ac4)
#define image_4_ingress_filter_action_point_update        (0x29d0)
#define image_4_ingress_filters_handler        (0x2270)
#define image_4_initialization_task        (0x8)
#define image_4_is_iptv_capable        (0x1f64)
#define image_4_mcast_flow_master_lookup        (0x2a1c)
#define image_4_memcpy_abs_to_sbpm        (0xf8)
#define image_4_parser_exception_handler        (0x1d24)
#define image_4_proccessing_loopback        (0x1c6c)
#define image_4_processing_policer_action        (0x48ac)
#define image_4_processing_wakeup_request        (0x314)
#define image_4_spdsvc_natc_lookup        (0x2004)
#define image_4_start_task_add_pbit_to_key        (0x29a4)
#define image_4_start_task_c_spu_request_wakeup_request        (0x491c)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_4_start_task_check_skip_cso        (0x2944)
#define image_4_start_task_debug_routine        (0x30)
#define image_4_start_task_dos_attack_handler        (0x1f08)
#define image_4_start_task_drop_pkt_and_serial        (0x20f8)
#define image_4_start_task_dyn_code_func        (0x7c00)
#define image_4_start_task_flow_policer        (0x485c)
#define image_4_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_4_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_4_start_task_ingress_filters_handler        (0x2270)
#define image_4_start_task_initialization_task        (0x8)
#define image_4_start_task_is_iptv_capable        (0x1f64)
#define image_4_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_4_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_4_start_task_parser_exception_handler        (0x1d24)
#define image_4_start_task_proccessing_loopback        (0x1c6c)
#define image_4_start_task_processing_policer_action        (0x48ac)
#define image_4_start_task_processing_wakeup_request        (0x314)
#define image_4_start_task_spdsvc_natc_lookup        (0x2004)
#define image_4_start_task_ts_1588_handler        (0x223c)
#define image_4_start_task_xx_mirror_noinline        (0x25a8)
#define image_4_ts_1588_handler        (0x223c)
#define image_4_xx_mirror_noinline        (0x25a8)

#else

#define image_4_add_pbit_to_key        (0xa69)
#define image_4_c_spu_request_wakeup_request        (0x1247)
#define image_4_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_4_check_skip_cso        (0xa51)
#define image_4_debug_routine        (0xc)
#define image_4_debug_routine_handler        (0x1)
#define image_4_dos_attack_handler        (0x7c2)
#define image_4_drop_pkt_and_serial        (0x83e)
#define image_4_dyn_code_func        (0x1f00)
#define image_4_flow_policer        (0x1217)
#define image_4_group_flow_lkp_and_fwd        (0xab1)
#define image_4_ingress_filter_action_point_update        (0xa74)
#define image_4_ingress_filters_handler        (0x89c)
#define image_4_initialization_task        (0x2)
#define image_4_is_iptv_capable        (0x7d9)
#define image_4_mcast_flow_master_lookup        (0xa87)
#define image_4_memcpy_abs_to_sbpm        (0x3e)
#define image_4_parser_exception_handler        (0x749)
#define image_4_proccessing_loopback        (0x71b)
#define image_4_processing_policer_action        (0x122b)
#define image_4_processing_wakeup_request        (0xc5)
#define image_4_spdsvc_natc_lookup        (0x801)
#define image_4_start_task_add_pbit_to_key        (0xa69)
#define image_4_start_task_c_spu_request_wakeup_request        (0x1247)
#define image_4_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_4_start_task_check_skip_cso        (0xa51)
#define image_4_start_task_debug_routine        (0xc)
#define image_4_start_task_dos_attack_handler        (0x7c2)
#define image_4_start_task_drop_pkt_and_serial        (0x83e)
#define image_4_start_task_dyn_code_func        (0x1f00)
#define image_4_start_task_flow_policer        (0x1217)
#define image_4_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_4_start_task_ingress_filter_action_point_update        (0xa74)
#define image_4_start_task_ingress_filters_handler        (0x89c)
#define image_4_start_task_initialization_task        (0x2)
#define image_4_start_task_is_iptv_capable        (0x7d9)
#define image_4_start_task_mcast_flow_master_lookup        (0xa87)
#define image_4_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_4_start_task_parser_exception_handler        (0x749)
#define image_4_start_task_proccessing_loopback        (0x71b)
#define image_4_start_task_processing_policer_action        (0x122b)
#define image_4_start_task_processing_wakeup_request        (0xc5)
#define image_4_start_task_spdsvc_natc_lookup        (0x801)
#define image_4_start_task_ts_1588_handler        (0x88f)
#define image_4_start_task_xx_mirror_noinline        (0x96a)
#define image_4_ts_1588_handler        (0x88f)
#define image_4_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_5_add_pbit_to_key        (0x4108)
#define image_5_c_common_reprocessing_wakeup_request        (0x6080)
#define image_5_c_spdsvc_gen_wakeup_request        (0x621c)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x1a3c)
#define image_5_check_skip_cso        (0x40a8)
#define image_5_debug_routine        (0x30)
#define image_5_debug_routine_handler        (0x4)
#define image_5_dos_attack_handler        (0x366c)
#define image_5_drop_pkt_and_serial        (0x385c)
#define image_5_dyn_code_func        (0x7c00)
#define image_5_flow_policer        (0x5fc0)
#define image_5_group_flow_lkp_and_fwd        (0x4228)
#define image_5_ingress_filter_action_point_update        (0x4134)
#define image_5_ingress_filters_handler        (0x39d4)
#define image_5_initialization_task        (0x8)
#define image_5_is_iptv_capable        (0x36c8)
#define image_5_mcast_flow_master_lookup        (0x4180)
#define image_5_memcpy_abs_to_sbpm        (0x185c)
#define image_5_parser_exception_handler        (0x3488)
#define image_5_proccessing_loopback        (0x33d0)
#define image_5_processing_policer_action        (0x6010)
#define image_5_processing_wakeup_request        (0x1a78)
#define image_5_spdsvc_natc_lookup        (0x3768)
#define image_5_start_task_add_pbit_to_key        (0x4108)
#define image_5_start_task_c_common_reprocessing_wakeup_request        (0x6080)
#define image_5_start_task_c_spdsvc_gen_wakeup_request        (0x621c)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x1a3c)
#define image_5_start_task_check_skip_cso        (0x40a8)
#define image_5_start_task_debug_routine        (0x30)
#define image_5_start_task_dos_attack_handler        (0x366c)
#define image_5_start_task_drop_pkt_and_serial        (0x385c)
#define image_5_start_task_dyn_code_func        (0x7c00)
#define image_5_start_task_flow_policer        (0x5fc0)
#define image_5_start_task_group_flow_lkp_and_fwd        (0x4228)
#define image_5_start_task_ingress_filter_action_point_update        (0x4134)
#define image_5_start_task_ingress_filters_handler        (0x39d4)
#define image_5_start_task_initialization_task        (0x8)
#define image_5_start_task_is_iptv_capable        (0x36c8)
#define image_5_start_task_mcast_flow_master_lookup        (0x4180)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x185c)
#define image_5_start_task_parser_exception_handler        (0x3488)
#define image_5_start_task_proccessing_loopback        (0x33d0)
#define image_5_start_task_processing_policer_action        (0x6010)
#define image_5_start_task_processing_wakeup_request        (0x1a78)
#define image_5_start_task_spdsvc_natc_lookup        (0x3768)
#define image_5_start_task_tcpspdtest_gen_wakeup_request        (0xaf8)
#define image_5_start_task_tcpspdtest_wakeup_request        (0x2b0)
#define image_5_start_task_ts_1588_handler        (0x39a0)
#define image_5_start_task_xx_mirror_noinline        (0x3d0c)
#define image_5_tcpspdtest_gen_wakeup_request        (0xaf8)
#define image_5_tcpspdtest_task_upload_init        (0xaf8)
#define image_5_tcpspdtest_wakeup_request        (0x2b0)
#define image_5_ts_1588_handler        (0x39a0)
#define image_5_xx_mirror_noinline        (0x3d0c)

#else

#define image_5_add_pbit_to_key        (0x1042)
#define image_5_c_common_reprocessing_wakeup_request        (0x1820)
#define image_5_c_spdsvc_gen_wakeup_request        (0x1887)
#define image_5_check_cpu_rx_gdx_queue_occupancy        (0x68f)
#define image_5_check_skip_cso        (0x102a)
#define image_5_debug_routine        (0xc)
#define image_5_debug_routine_handler        (0x1)
#define image_5_dos_attack_handler        (0xd9b)
#define image_5_drop_pkt_and_serial        (0xe17)
#define image_5_dyn_code_func        (0x1f00)
#define image_5_flow_policer        (0x17f0)
#define image_5_group_flow_lkp_and_fwd        (0x108a)
#define image_5_ingress_filter_action_point_update        (0x104d)
#define image_5_ingress_filters_handler        (0xe75)
#define image_5_initialization_task        (0x2)
#define image_5_is_iptv_capable        (0xdb2)
#define image_5_mcast_flow_master_lookup        (0x1060)
#define image_5_memcpy_abs_to_sbpm        (0x617)
#define image_5_parser_exception_handler        (0xd22)
#define image_5_proccessing_loopback        (0xcf4)
#define image_5_processing_policer_action        (0x1804)
#define image_5_processing_wakeup_request        (0x69e)
#define image_5_spdsvc_natc_lookup        (0xdda)
#define image_5_start_task_add_pbit_to_key        (0x1042)
#define image_5_start_task_c_common_reprocessing_wakeup_request        (0x1820)
#define image_5_start_task_c_spdsvc_gen_wakeup_request        (0x1887)
#define image_5_start_task_check_cpu_rx_gdx_queue_occupancy        (0x68f)
#define image_5_start_task_check_skip_cso        (0x102a)
#define image_5_start_task_debug_routine        (0xc)
#define image_5_start_task_dos_attack_handler        (0xd9b)
#define image_5_start_task_drop_pkt_and_serial        (0xe17)
#define image_5_start_task_dyn_code_func        (0x1f00)
#define image_5_start_task_flow_policer        (0x17f0)
#define image_5_start_task_group_flow_lkp_and_fwd        (0x108a)
#define image_5_start_task_ingress_filter_action_point_update        (0x104d)
#define image_5_start_task_ingress_filters_handler        (0xe75)
#define image_5_start_task_initialization_task        (0x2)
#define image_5_start_task_is_iptv_capable        (0xdb2)
#define image_5_start_task_mcast_flow_master_lookup        (0x1060)
#define image_5_start_task_memcpy_abs_to_sbpm        (0x617)
#define image_5_start_task_parser_exception_handler        (0xd22)
#define image_5_start_task_proccessing_loopback        (0xcf4)
#define image_5_start_task_processing_policer_action        (0x1804)
#define image_5_start_task_processing_wakeup_request        (0x69e)
#define image_5_start_task_spdsvc_natc_lookup        (0xdda)
#define image_5_start_task_tcpspdtest_gen_wakeup_request        (0x2be)
#define image_5_start_task_tcpspdtest_wakeup_request        (0xac)
#define image_5_start_task_ts_1588_handler        (0xe68)
#define image_5_start_task_xx_mirror_noinline        (0xf43)
#define image_5_tcpspdtest_gen_wakeup_request        (0x2be)
#define image_5_tcpspdtest_task_upload_init        (0x2be)
#define image_5_tcpspdtest_wakeup_request        (0xac)
#define image_5_ts_1588_handler        (0xe68)
#define image_5_xx_mirror_noinline        (0xf43)

#endif


#endif

/* IMAGE 6 LABELS */
#ifndef IMAGE_6_CODE_ADDRESSES
#define IMAGE_6_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_6_add_pbit_to_key        (0x29a4)
#define image_6_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_6_check_skip_cso        (0x2944)
#define image_6_debug_routine        (0x30)
#define image_6_debug_routine_handler        (0x4)
#define image_6_dos_attack_handler        (0x1f08)
#define image_6_drop_pkt_and_serial        (0x20f8)
#define image_6_dyn_code_func        (0x7c00)
#define image_6_flow_policer        (0x485c)
#define image_6_group_flow_lkp_and_fwd        (0x2ac4)
#define image_6_ingress_filter_action_point_update        (0x29d0)
#define image_6_ingress_filters_handler        (0x2270)
#define image_6_initialization_task        (0x8)
#define image_6_is_iptv_capable        (0x1f64)
#define image_6_mcast_flow_master_lookup        (0x2a1c)
#define image_6_memcpy_abs_to_sbpm        (0xf8)
#define image_6_parser_exception_handler        (0x1d24)
#define image_6_proccessing_loopback        (0x1c6c)
#define image_6_processing_policer_action        (0x48ac)
#define image_6_processing_wakeup_request        (0x314)
#define image_6_spdsvc_natc_lookup        (0x2004)
#define image_6_start_task_add_pbit_to_key        (0x29a4)
#define image_6_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_6_start_task_check_skip_cso        (0x2944)
#define image_6_start_task_debug_routine        (0x30)
#define image_6_start_task_dos_attack_handler        (0x1f08)
#define image_6_start_task_drop_pkt_and_serial        (0x20f8)
#define image_6_start_task_dyn_code_func        (0x7c00)
#define image_6_start_task_flow_policer        (0x485c)
#define image_6_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_6_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_6_start_task_ingress_filters_handler        (0x2270)
#define image_6_start_task_initialization_task        (0x8)
#define image_6_start_task_is_iptv_capable        (0x1f64)
#define image_6_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_6_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_6_start_task_parser_exception_handler        (0x1d24)
#define image_6_start_task_proccessing_loopback        (0x1c6c)
#define image_6_start_task_processing_policer_action        (0x48ac)
#define image_6_start_task_processing_wakeup_request        (0x314)
#define image_6_start_task_spdsvc_natc_lookup        (0x2004)
#define image_6_start_task_ts_1588_handler        (0x223c)
#define image_6_start_task_xx_mirror_noinline        (0x25a8)
#define image_6_ts_1588_handler        (0x223c)
#define image_6_xx_mirror_noinline        (0x25a8)

#else

#define image_6_add_pbit_to_key        (0xa69)
#define image_6_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_6_check_skip_cso        (0xa51)
#define image_6_debug_routine        (0xc)
#define image_6_debug_routine_handler        (0x1)
#define image_6_dos_attack_handler        (0x7c2)
#define image_6_drop_pkt_and_serial        (0x83e)
#define image_6_dyn_code_func        (0x1f00)
#define image_6_flow_policer        (0x1217)
#define image_6_group_flow_lkp_and_fwd        (0xab1)
#define image_6_ingress_filter_action_point_update        (0xa74)
#define image_6_ingress_filters_handler        (0x89c)
#define image_6_initialization_task        (0x2)
#define image_6_is_iptv_capable        (0x7d9)
#define image_6_mcast_flow_master_lookup        (0xa87)
#define image_6_memcpy_abs_to_sbpm        (0x3e)
#define image_6_parser_exception_handler        (0x749)
#define image_6_proccessing_loopback        (0x71b)
#define image_6_processing_policer_action        (0x122b)
#define image_6_processing_wakeup_request        (0xc5)
#define image_6_spdsvc_natc_lookup        (0x801)
#define image_6_start_task_add_pbit_to_key        (0xa69)
#define image_6_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_6_start_task_check_skip_cso        (0xa51)
#define image_6_start_task_debug_routine        (0xc)
#define image_6_start_task_dos_attack_handler        (0x7c2)
#define image_6_start_task_drop_pkt_and_serial        (0x83e)
#define image_6_start_task_dyn_code_func        (0x1f00)
#define image_6_start_task_flow_policer        (0x1217)
#define image_6_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_6_start_task_ingress_filter_action_point_update        (0xa74)
#define image_6_start_task_ingress_filters_handler        (0x89c)
#define image_6_start_task_initialization_task        (0x2)
#define image_6_start_task_is_iptv_capable        (0x7d9)
#define image_6_start_task_mcast_flow_master_lookup        (0xa87)
#define image_6_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_6_start_task_parser_exception_handler        (0x749)
#define image_6_start_task_proccessing_loopback        (0x71b)
#define image_6_start_task_processing_policer_action        (0x122b)
#define image_6_start_task_processing_wakeup_request        (0xc5)
#define image_6_start_task_spdsvc_natc_lookup        (0x801)
#define image_6_start_task_ts_1588_handler        (0x88f)
#define image_6_start_task_xx_mirror_noinline        (0x96a)
#define image_6_ts_1588_handler        (0x88f)
#define image_6_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 7 LABELS */
#ifndef IMAGE_7_CODE_ADDRESSES
#define IMAGE_7_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_7_add_pbit_to_key        (0x29a4)
#define image_7_c_spdsvc_analyzer_wakeup_request        (0x491c)
#define image_7_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_7_check_skip_cso        (0x2944)
#define image_7_debug_routine        (0x30)
#define image_7_debug_routine_handler        (0x4)
#define image_7_dos_attack_handler        (0x1f08)
#define image_7_drop_pkt_and_serial        (0x20f8)
#define image_7_dyn_code_func        (0x7c00)
#define image_7_flow_policer        (0x485c)
#define image_7_group_flow_lkp_and_fwd        (0x2ac4)
#define image_7_ingress_filter_action_point_update        (0x29d0)
#define image_7_ingress_filters_handler        (0x2270)
#define image_7_initialization_task        (0x8)
#define image_7_is_iptv_capable        (0x1f64)
#define image_7_mcast_flow_master_lookup        (0x2a1c)
#define image_7_memcpy_abs_to_sbpm        (0xf8)
#define image_7_parser_exception_handler        (0x1d24)
#define image_7_proccessing_loopback        (0x1c6c)
#define image_7_processing_policer_action        (0x48ac)
#define image_7_processing_wakeup_request        (0x314)
#define image_7_spdsvc_natc_lookup        (0x2004)
#define image_7_spdt_brcm_spdsvc_rx_handler        (0x4ce8)
#define image_7_spdt_udp_basic_rx_handler        (0x4a54)
#define image_7_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x4dbc)
#define image_7_spdt_udp_iperf3_rx_handler        (0x4b08)
#define image_7_spdt_unsupported_proto_rx_handler        (0x4d58)
#define image_7_start_task_add_pbit_to_key        (0x29a4)
#define image_7_start_task_c_spdsvc_analyzer_wakeup_request        (0x491c)
#define image_7_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_7_start_task_check_skip_cso        (0x2944)
#define image_7_start_task_debug_routine        (0x30)
#define image_7_start_task_dos_attack_handler        (0x1f08)
#define image_7_start_task_drop_pkt_and_serial        (0x20f8)
#define image_7_start_task_dyn_code_func        (0x7c00)
#define image_7_start_task_flow_policer        (0x485c)
#define image_7_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_7_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_7_start_task_ingress_filters_handler        (0x2270)
#define image_7_start_task_initialization_task        (0x8)
#define image_7_start_task_is_iptv_capable        (0x1f64)
#define image_7_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_7_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_7_start_task_parser_exception_handler        (0x1d24)
#define image_7_start_task_proccessing_loopback        (0x1c6c)
#define image_7_start_task_processing_policer_action        (0x48ac)
#define image_7_start_task_processing_wakeup_request        (0x314)
#define image_7_start_task_spdsvc_natc_lookup        (0x2004)
#define image_7_start_task_spdt_brcm_spdsvc_rx_handler        (0x4ce8)
#define image_7_start_task_spdt_udp_basic_rx_handler        (0x4a54)
#define image_7_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x4dbc)
#define image_7_start_task_spdt_udp_iperf3_rx_handler        (0x4b08)
#define image_7_start_task_spdt_unsupported_proto_rx_handler        (0x4d58)
#define image_7_start_task_ts_1588_handler        (0x223c)
#define image_7_start_task_xx_mirror_noinline        (0x25a8)
#define image_7_ts_1588_handler        (0x223c)
#define image_7_xx_mirror_noinline        (0x25a8)

#else

#define image_7_add_pbit_to_key        (0xa69)
#define image_7_c_spdsvc_analyzer_wakeup_request        (0x1247)
#define image_7_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_7_check_skip_cso        (0xa51)
#define image_7_debug_routine        (0xc)
#define image_7_debug_routine_handler        (0x1)
#define image_7_dos_attack_handler        (0x7c2)
#define image_7_drop_pkt_and_serial        (0x83e)
#define image_7_dyn_code_func        (0x1f00)
#define image_7_flow_policer        (0x1217)
#define image_7_group_flow_lkp_and_fwd        (0xab1)
#define image_7_ingress_filter_action_point_update        (0xa74)
#define image_7_ingress_filters_handler        (0x89c)
#define image_7_initialization_task        (0x2)
#define image_7_is_iptv_capable        (0x7d9)
#define image_7_mcast_flow_master_lookup        (0xa87)
#define image_7_memcpy_abs_to_sbpm        (0x3e)
#define image_7_parser_exception_handler        (0x749)
#define image_7_proccessing_loopback        (0x71b)
#define image_7_processing_policer_action        (0x122b)
#define image_7_processing_wakeup_request        (0xc5)
#define image_7_spdsvc_natc_lookup        (0x801)
#define image_7_spdt_brcm_spdsvc_rx_handler        (0x133a)
#define image_7_spdt_udp_basic_rx_handler        (0x1295)
#define image_7_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x136f)
#define image_7_spdt_udp_iperf3_rx_handler        (0x12c2)
#define image_7_spdt_unsupported_proto_rx_handler        (0x1356)
#define image_7_start_task_add_pbit_to_key        (0xa69)
#define image_7_start_task_c_spdsvc_analyzer_wakeup_request        (0x1247)
#define image_7_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_7_start_task_check_skip_cso        (0xa51)
#define image_7_start_task_debug_routine        (0xc)
#define image_7_start_task_dos_attack_handler        (0x7c2)
#define image_7_start_task_drop_pkt_and_serial        (0x83e)
#define image_7_start_task_dyn_code_func        (0x1f00)
#define image_7_start_task_flow_policer        (0x1217)
#define image_7_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_7_start_task_ingress_filter_action_point_update        (0xa74)
#define image_7_start_task_ingress_filters_handler        (0x89c)
#define image_7_start_task_initialization_task        (0x2)
#define image_7_start_task_is_iptv_capable        (0x7d9)
#define image_7_start_task_mcast_flow_master_lookup        (0xa87)
#define image_7_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_7_start_task_parser_exception_handler        (0x749)
#define image_7_start_task_proccessing_loopback        (0x71b)
#define image_7_start_task_processing_policer_action        (0x122b)
#define image_7_start_task_processing_wakeup_request        (0xc5)
#define image_7_start_task_spdsvc_natc_lookup        (0x801)
#define image_7_start_task_spdt_brcm_spdsvc_rx_handler        (0x133a)
#define image_7_start_task_spdt_udp_basic_rx_handler        (0x1295)
#define image_7_start_task_spdt_udp_basic_update_rx_bytes_and_timestamp        (0x136f)
#define image_7_start_task_spdt_udp_iperf3_rx_handler        (0x12c2)
#define image_7_start_task_spdt_unsupported_proto_rx_handler        (0x1356)
#define image_7_start_task_ts_1588_handler        (0x88f)
#define image_7_start_task_xx_mirror_noinline        (0x96a)
#define image_7_ts_1588_handler        (0x88f)
#define image_7_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 8 LABELS */
#ifndef IMAGE_8_CODE_ADDRESSES
#define IMAGE_8_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_8_add_pbit_to_key        (0x29a4)
#define image_8_c_spu_response_wakeup_request        (0x491c)
#define image_8_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_8_check_skip_cso        (0x2944)
#define image_8_debug_routine        (0x30)
#define image_8_debug_routine_handler        (0x4)
#define image_8_dos_attack_handler        (0x1f08)
#define image_8_drop_pkt_and_serial        (0x20f8)
#define image_8_dyn_code_func        (0x7c00)
#define image_8_flow_policer        (0x485c)
#define image_8_group_flow_lkp_and_fwd        (0x2ac4)
#define image_8_ingress_filter_action_point_update        (0x29d0)
#define image_8_ingress_filters_handler        (0x2270)
#define image_8_initialization_task        (0x8)
#define image_8_is_iptv_capable        (0x1f64)
#define image_8_mcast_flow_master_lookup        (0x2a1c)
#define image_8_memcpy_abs_to_sbpm        (0xf8)
#define image_8_parser_exception_handler        (0x1d24)
#define image_8_proccessing_loopback        (0x1c6c)
#define image_8_processing_policer_action        (0x48ac)
#define image_8_processing_wakeup_request        (0x314)
#define image_8_spdsvc_natc_lookup        (0x2004)
#define image_8_start_task_add_pbit_to_key        (0x29a4)
#define image_8_start_task_c_spu_response_wakeup_request        (0x491c)
#define image_8_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_8_start_task_check_skip_cso        (0x2944)
#define image_8_start_task_debug_routine        (0x30)
#define image_8_start_task_dos_attack_handler        (0x1f08)
#define image_8_start_task_drop_pkt_and_serial        (0x20f8)
#define image_8_start_task_dyn_code_func        (0x7c00)
#define image_8_start_task_flow_policer        (0x485c)
#define image_8_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_8_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_8_start_task_ingress_filters_handler        (0x2270)
#define image_8_start_task_initialization_task        (0x8)
#define image_8_start_task_is_iptv_capable        (0x1f64)
#define image_8_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_8_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_8_start_task_parser_exception_handler        (0x1d24)
#define image_8_start_task_proccessing_loopback        (0x1c6c)
#define image_8_start_task_processing_policer_action        (0x48ac)
#define image_8_start_task_processing_wakeup_request        (0x314)
#define image_8_start_task_spdsvc_natc_lookup        (0x2004)
#define image_8_start_task_ts_1588_handler        (0x223c)
#define image_8_start_task_xx_mirror_noinline        (0x25a8)
#define image_8_ts_1588_handler        (0x223c)
#define image_8_xx_mirror_noinline        (0x25a8)

#else

#define image_8_add_pbit_to_key        (0xa69)
#define image_8_c_spu_response_wakeup_request        (0x1247)
#define image_8_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_8_check_skip_cso        (0xa51)
#define image_8_debug_routine        (0xc)
#define image_8_debug_routine_handler        (0x1)
#define image_8_dos_attack_handler        (0x7c2)
#define image_8_drop_pkt_and_serial        (0x83e)
#define image_8_dyn_code_func        (0x1f00)
#define image_8_flow_policer        (0x1217)
#define image_8_group_flow_lkp_and_fwd        (0xab1)
#define image_8_ingress_filter_action_point_update        (0xa74)
#define image_8_ingress_filters_handler        (0x89c)
#define image_8_initialization_task        (0x2)
#define image_8_is_iptv_capable        (0x7d9)
#define image_8_mcast_flow_master_lookup        (0xa87)
#define image_8_memcpy_abs_to_sbpm        (0x3e)
#define image_8_parser_exception_handler        (0x749)
#define image_8_proccessing_loopback        (0x71b)
#define image_8_processing_policer_action        (0x122b)
#define image_8_processing_wakeup_request        (0xc5)
#define image_8_spdsvc_natc_lookup        (0x801)
#define image_8_start_task_add_pbit_to_key        (0xa69)
#define image_8_start_task_c_spu_response_wakeup_request        (0x1247)
#define image_8_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_8_start_task_check_skip_cso        (0xa51)
#define image_8_start_task_debug_routine        (0xc)
#define image_8_start_task_dos_attack_handler        (0x7c2)
#define image_8_start_task_drop_pkt_and_serial        (0x83e)
#define image_8_start_task_dyn_code_func        (0x1f00)
#define image_8_start_task_flow_policer        (0x1217)
#define image_8_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_8_start_task_ingress_filter_action_point_update        (0xa74)
#define image_8_start_task_ingress_filters_handler        (0x89c)
#define image_8_start_task_initialization_task        (0x2)
#define image_8_start_task_is_iptv_capable        (0x7d9)
#define image_8_start_task_mcast_flow_master_lookup        (0xa87)
#define image_8_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_8_start_task_parser_exception_handler        (0x749)
#define image_8_start_task_proccessing_loopback        (0x71b)
#define image_8_start_task_processing_policer_action        (0x122b)
#define image_8_start_task_processing_wakeup_request        (0xc5)
#define image_8_start_task_spdsvc_natc_lookup        (0x801)
#define image_8_start_task_ts_1588_handler        (0x88f)
#define image_8_start_task_xx_mirror_noinline        (0x96a)
#define image_8_ts_1588_handler        (0x88f)
#define image_8_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 9 LABELS */
#ifndef IMAGE_9_CODE_ADDRESSES
#define IMAGE_9_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_9___umulsi3        (0x5d94)
#define image_9_add_pbit_to_key        (0x29a4)
#define image_9_budget_allocator_tick        (0x5aa0)
#define image_9_c_g9991_flow_control_wakeup_request        (0x5c5c)
#define image_9_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_9_check_skip_cso        (0x2944)
#define image_9_debug_routine        (0x30)
#define image_9_debug_routine_handler        (0x4)
#define image_9_dos_attack_handler        (0x1f08)
#define image_9_drop_pkt_and_serial        (0x20f8)
#define image_9_dualq_pi2_stats        (0x4b94)
#define image_9_dyn_code_func        (0x7c00)
#define image_9_flow_policer        (0x485c)
#define image_9_general_timer_wakeup_request        (0x5be4)
#define image_9_get_queue_delay        (0x4b50)
#define image_9_group_flow_lkp_and_fwd        (0x2ac4)
#define image_9_handle_flush        (0x4ee0)
#define image_9_ingress_filter_action_point_update        (0x29d0)
#define image_9_ingress_filters_handler        (0x2270)
#define image_9_initialization_task        (0x8)
#define image_9_is_iptv_capable        (0x1f64)
#define image_9_laqm_deque_check        (0x4cd4)
#define image_9_mcast_flow_master_lookup        (0x2a1c)
#define image_9_memcpy_abs_to_sbpm        (0xf8)
#define image_9_parser_exception_handler        (0x1d24)
#define image_9_pi2_deque_check        (0x4c24)
#define image_9_pi2_get_queue_delay        (0x49e4)
#define image_9_pi2_probability_calc        (0x4a50)
#define image_9_pi2_timer        (0x491c)
#define image_9_proccessing_loopback        (0x1c6c)
#define image_9_processing_policer_action        (0x48ac)
#define image_9_processing_wakeup_request        (0x314)
#define image_9_spdsvc_natc_lookup        (0x2004)
#define image_9_start_task___umulsi3        (0x5d94)
#define image_9_start_task_add_pbit_to_key        (0x29a4)
#define image_9_start_task_budget_allocator_tick        (0x5aa0)
#define image_9_start_task_c_g9991_flow_control_wakeup_request        (0x5c5c)
#define image_9_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_9_start_task_check_skip_cso        (0x2944)
#define image_9_start_task_debug_routine        (0x30)
#define image_9_start_task_dos_attack_handler        (0x1f08)
#define image_9_start_task_drop_pkt_and_serial        (0x20f8)
#define image_9_start_task_dualq_pi2_stats        (0x4b94)
#define image_9_start_task_dyn_code_func        (0x7c00)
#define image_9_start_task_flow_policer        (0x485c)
#define image_9_start_task_general_timer_wakeup_request        (0x5be4)
#define image_9_start_task_get_queue_delay        (0x4b50)
#define image_9_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_9_start_task_handle_flush        (0x4ee0)
#define image_9_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_9_start_task_ingress_filters_handler        (0x2270)
#define image_9_start_task_initialization_task        (0x8)
#define image_9_start_task_is_iptv_capable        (0x1f64)
#define image_9_start_task_laqm_deque_check        (0x4cd4)
#define image_9_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_9_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_9_start_task_parser_exception_handler        (0x1d24)
#define image_9_start_task_pi2_deque_check        (0x4c24)
#define image_9_start_task_pi2_get_queue_delay        (0x49e4)
#define image_9_start_task_pi2_probability_calc        (0x4a50)
#define image_9_start_task_pi2_timer        (0x491c)
#define image_9_start_task_proccessing_loopback        (0x1c6c)
#define image_9_start_task_processing_policer_action        (0x48ac)
#define image_9_start_task_processing_wakeup_request        (0x314)
#define image_9_start_task_spdsvc_natc_lookup        (0x2004)
#define image_9_start_task_tm_tx_handle_rate_limit        (0x57d4)
#define image_9_start_task_tm_tx_mirroring_handle        (0x5894)
#define image_9_start_task_tm_tx_task_wakeup_request        (0x4fe0)
#define image_9_start_task_tm_update_fifo_first_wakeup_request        (0x4e00)
#define image_9_start_task_ts_1588_handler        (0x223c)
#define image_9_start_task_tx_mirror        (0x5930)
#define image_9_start_task_xx_mirror_noinline        (0x25a8)
#define image_9_tm_tx_handle_rate_limit        (0x57d4)
#define image_9_tm_tx_mirroring_handle        (0x5894)
#define image_9_tm_tx_task_wakeup_request        (0x4fe0)
#define image_9_tm_update_fifo_first_wakeup_request        (0x4e00)
#define image_9_ts_1588_handler        (0x223c)
#define image_9_tx_mirror        (0x5930)
#define image_9_xx_mirror_noinline        (0x25a8)

#else

#define image_9___umulsi3        (0x1765)
#define image_9_add_pbit_to_key        (0xa69)
#define image_9_budget_allocator_tick        (0x16a8)
#define image_9_c_g9991_flow_control_wakeup_request        (0x1717)
#define image_9_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_9_check_skip_cso        (0xa51)
#define image_9_debug_routine        (0xc)
#define image_9_debug_routine_handler        (0x1)
#define image_9_dos_attack_handler        (0x7c2)
#define image_9_drop_pkt_and_serial        (0x83e)
#define image_9_dualq_pi2_stats        (0x12e5)
#define image_9_dyn_code_func        (0x1f00)
#define image_9_flow_policer        (0x1217)
#define image_9_general_timer_wakeup_request        (0x16f9)
#define image_9_get_queue_delay        (0x12d4)
#define image_9_group_flow_lkp_and_fwd        (0xab1)
#define image_9_handle_flush        (0x13b8)
#define image_9_ingress_filter_action_point_update        (0xa74)
#define image_9_ingress_filters_handler        (0x89c)
#define image_9_initialization_task        (0x2)
#define image_9_is_iptv_capable        (0x7d9)
#define image_9_laqm_deque_check        (0x1335)
#define image_9_mcast_flow_master_lookup        (0xa87)
#define image_9_memcpy_abs_to_sbpm        (0x3e)
#define image_9_parser_exception_handler        (0x749)
#define image_9_pi2_deque_check        (0x1309)
#define image_9_pi2_get_queue_delay        (0x1279)
#define image_9_pi2_probability_calc        (0x1294)
#define image_9_pi2_timer        (0x1247)
#define image_9_proccessing_loopback        (0x71b)
#define image_9_processing_policer_action        (0x122b)
#define image_9_processing_wakeup_request        (0xc5)
#define image_9_spdsvc_natc_lookup        (0x801)
#define image_9_start_task___umulsi3        (0x1765)
#define image_9_start_task_add_pbit_to_key        (0xa69)
#define image_9_start_task_budget_allocator_tick        (0x16a8)
#define image_9_start_task_c_g9991_flow_control_wakeup_request        (0x1717)
#define image_9_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_9_start_task_check_skip_cso        (0xa51)
#define image_9_start_task_debug_routine        (0xc)
#define image_9_start_task_dos_attack_handler        (0x7c2)
#define image_9_start_task_drop_pkt_and_serial        (0x83e)
#define image_9_start_task_dualq_pi2_stats        (0x12e5)
#define image_9_start_task_dyn_code_func        (0x1f00)
#define image_9_start_task_flow_policer        (0x1217)
#define image_9_start_task_general_timer_wakeup_request        (0x16f9)
#define image_9_start_task_get_queue_delay        (0x12d4)
#define image_9_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_9_start_task_handle_flush        (0x13b8)
#define image_9_start_task_ingress_filter_action_point_update        (0xa74)
#define image_9_start_task_ingress_filters_handler        (0x89c)
#define image_9_start_task_initialization_task        (0x2)
#define image_9_start_task_is_iptv_capable        (0x7d9)
#define image_9_start_task_laqm_deque_check        (0x1335)
#define image_9_start_task_mcast_flow_master_lookup        (0xa87)
#define image_9_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_9_start_task_parser_exception_handler        (0x749)
#define image_9_start_task_pi2_deque_check        (0x1309)
#define image_9_start_task_pi2_get_queue_delay        (0x1279)
#define image_9_start_task_pi2_probability_calc        (0x1294)
#define image_9_start_task_pi2_timer        (0x1247)
#define image_9_start_task_proccessing_loopback        (0x71b)
#define image_9_start_task_processing_policer_action        (0x122b)
#define image_9_start_task_processing_wakeup_request        (0xc5)
#define image_9_start_task_spdsvc_natc_lookup        (0x801)
#define image_9_start_task_tm_tx_handle_rate_limit        (0x15f5)
#define image_9_start_task_tm_tx_mirroring_handle        (0x1625)
#define image_9_start_task_tm_tx_task_wakeup_request        (0x13f8)
#define image_9_start_task_tm_update_fifo_first_wakeup_request        (0x1380)
#define image_9_start_task_ts_1588_handler        (0x88f)
#define image_9_start_task_tx_mirror        (0x164c)
#define image_9_start_task_xx_mirror_noinline        (0x96a)
#define image_9_tm_tx_handle_rate_limit        (0x15f5)
#define image_9_tm_tx_mirroring_handle        (0x1625)
#define image_9_tm_tx_task_wakeup_request        (0x13f8)
#define image_9_tm_update_fifo_first_wakeup_request        (0x1380)
#define image_9_ts_1588_handler        (0x88f)
#define image_9_tx_mirror        (0x164c)
#define image_9_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 10 LABELS */
#ifndef IMAGE_10_CODE_ADDRESSES
#define IMAGE_10_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_10___umulsi3        (0x5d94)
#define image_10_add_pbit_to_key        (0x29a4)
#define image_10_budget_allocator_tick        (0x5aa0)
#define image_10_c_g9991_flow_control_wakeup_request        (0x5c5c)
#define image_10_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_10_check_skip_cso        (0x2944)
#define image_10_debug_routine        (0x30)
#define image_10_debug_routine_handler        (0x4)
#define image_10_dos_attack_handler        (0x1f08)
#define image_10_drop_pkt_and_serial        (0x20f8)
#define image_10_dualq_pi2_stats        (0x4d04)
#define image_10_dyn_code_func        (0x7c00)
#define image_10_flow_policer        (0x485c)
#define image_10_general_timer_wakeup_request        (0x5be4)
#define image_10_get_queue_delay        (0x4cc0)
#define image_10_group_flow_lkp_and_fwd        (0x2ac4)
#define image_10_handle_flush        (0x5050)
#define image_10_ingress_filter_action_point_update        (0x29d0)
#define image_10_ingress_filters_handler        (0x2270)
#define image_10_initialization_task        (0x8)
#define image_10_is_iptv_capable        (0x1f64)
#define image_10_laqm_deque_check        (0x4e44)
#define image_10_mcast_flow_master_lookup        (0x2a1c)
#define image_10_memcpy_abs_to_sbpm        (0xf8)
#define image_10_parser_exception_handler        (0x1d24)
#define image_10_pi2_deque_check        (0x4d94)
#define image_10_pi2_get_queue_delay        (0x4b54)
#define image_10_pi2_probability_calc        (0x4bc0)
#define image_10_pi2_timer        (0x4a8c)
#define image_10_proccessing_loopback        (0x1c6c)
#define image_10_processing_policer_action        (0x48ac)
#define image_10_processing_wakeup_request        (0x314)
#define image_10_spdsvc_natc_lookup        (0x2004)
#define image_10_start_task___umulsi3        (0x5d94)
#define image_10_start_task_add_pbit_to_key        (0x29a4)
#define image_10_start_task_budget_allocator_tick        (0x5aa0)
#define image_10_start_task_c_g9991_flow_control_wakeup_request        (0x5c5c)
#define image_10_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_10_start_task_check_skip_cso        (0x2944)
#define image_10_start_task_debug_routine        (0x30)
#define image_10_start_task_dos_attack_handler        (0x1f08)
#define image_10_start_task_drop_pkt_and_serial        (0x20f8)
#define image_10_start_task_dualq_pi2_stats        (0x4d04)
#define image_10_start_task_dyn_code_func        (0x7c00)
#define image_10_start_task_flow_policer        (0x485c)
#define image_10_start_task_general_timer_wakeup_request        (0x5be4)
#define image_10_start_task_get_queue_delay        (0x4cc0)
#define image_10_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_10_start_task_handle_flush        (0x5050)
#define image_10_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_10_start_task_ingress_filters_handler        (0x2270)
#define image_10_start_task_initialization_task        (0x8)
#define image_10_start_task_is_iptv_capable        (0x1f64)
#define image_10_start_task_laqm_deque_check        (0x4e44)
#define image_10_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_10_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_10_start_task_parser_exception_handler        (0x1d24)
#define image_10_start_task_pi2_deque_check        (0x4d94)
#define image_10_start_task_pi2_get_queue_delay        (0x4b54)
#define image_10_start_task_pi2_probability_calc        (0x4bc0)
#define image_10_start_task_pi2_timer        (0x4a8c)
#define image_10_start_task_proccessing_loopback        (0x1c6c)
#define image_10_start_task_processing_policer_action        (0x48ac)
#define image_10_start_task_processing_wakeup_request        (0x314)
#define image_10_start_task_spdsvc_natc_lookup        (0x2004)
#define image_10_start_task_tm_tx_handle_rate_limit        (0x5944)
#define image_10_start_task_tm_tx_mirroring_handle        (0x5a04)
#define image_10_start_task_tm_tx_task_wakeup_request        (0x5150)
#define image_10_start_task_tm_update_fifo_first_wakeup_request        (0x4f70)
#define image_10_start_task_ts_1588_handler        (0x223c)
#define image_10_start_task_tx_mirror        (0x491c)
#define image_10_start_task_xx_mirror_noinline        (0x25a8)
#define image_10_tm_tx_handle_rate_limit        (0x5944)
#define image_10_tm_tx_mirroring_handle        (0x5a04)
#define image_10_tm_tx_task_wakeup_request        (0x5150)
#define image_10_tm_update_fifo_first_wakeup_request        (0x4f70)
#define image_10_ts_1588_handler        (0x223c)
#define image_10_tx_mirror        (0x491c)
#define image_10_xx_mirror_noinline        (0x25a8)

#else

#define image_10___umulsi3        (0x1765)
#define image_10_add_pbit_to_key        (0xa69)
#define image_10_budget_allocator_tick        (0x16a8)
#define image_10_c_g9991_flow_control_wakeup_request        (0x1717)
#define image_10_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_10_check_skip_cso        (0xa51)
#define image_10_debug_routine        (0xc)
#define image_10_debug_routine_handler        (0x1)
#define image_10_dos_attack_handler        (0x7c2)
#define image_10_drop_pkt_and_serial        (0x83e)
#define image_10_dualq_pi2_stats        (0x1341)
#define image_10_dyn_code_func        (0x1f00)
#define image_10_flow_policer        (0x1217)
#define image_10_general_timer_wakeup_request        (0x16f9)
#define image_10_get_queue_delay        (0x1330)
#define image_10_group_flow_lkp_and_fwd        (0xab1)
#define image_10_handle_flush        (0x1414)
#define image_10_ingress_filter_action_point_update        (0xa74)
#define image_10_ingress_filters_handler        (0x89c)
#define image_10_initialization_task        (0x2)
#define image_10_is_iptv_capable        (0x7d9)
#define image_10_laqm_deque_check        (0x1391)
#define image_10_mcast_flow_master_lookup        (0xa87)
#define image_10_memcpy_abs_to_sbpm        (0x3e)
#define image_10_parser_exception_handler        (0x749)
#define image_10_pi2_deque_check        (0x1365)
#define image_10_pi2_get_queue_delay        (0x12d5)
#define image_10_pi2_probability_calc        (0x12f0)
#define image_10_pi2_timer        (0x12a3)
#define image_10_proccessing_loopback        (0x71b)
#define image_10_processing_policer_action        (0x122b)
#define image_10_processing_wakeup_request        (0xc5)
#define image_10_spdsvc_natc_lookup        (0x801)
#define image_10_start_task___umulsi3        (0x1765)
#define image_10_start_task_add_pbit_to_key        (0xa69)
#define image_10_start_task_budget_allocator_tick        (0x16a8)
#define image_10_start_task_c_g9991_flow_control_wakeup_request        (0x1717)
#define image_10_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_10_start_task_check_skip_cso        (0xa51)
#define image_10_start_task_debug_routine        (0xc)
#define image_10_start_task_dos_attack_handler        (0x7c2)
#define image_10_start_task_drop_pkt_and_serial        (0x83e)
#define image_10_start_task_dualq_pi2_stats        (0x1341)
#define image_10_start_task_dyn_code_func        (0x1f00)
#define image_10_start_task_flow_policer        (0x1217)
#define image_10_start_task_general_timer_wakeup_request        (0x16f9)
#define image_10_start_task_get_queue_delay        (0x1330)
#define image_10_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_10_start_task_handle_flush        (0x1414)
#define image_10_start_task_ingress_filter_action_point_update        (0xa74)
#define image_10_start_task_ingress_filters_handler        (0x89c)
#define image_10_start_task_initialization_task        (0x2)
#define image_10_start_task_is_iptv_capable        (0x7d9)
#define image_10_start_task_laqm_deque_check        (0x1391)
#define image_10_start_task_mcast_flow_master_lookup        (0xa87)
#define image_10_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_10_start_task_parser_exception_handler        (0x749)
#define image_10_start_task_pi2_deque_check        (0x1365)
#define image_10_start_task_pi2_get_queue_delay        (0x12d5)
#define image_10_start_task_pi2_probability_calc        (0x12f0)
#define image_10_start_task_pi2_timer        (0x12a3)
#define image_10_start_task_proccessing_loopback        (0x71b)
#define image_10_start_task_processing_policer_action        (0x122b)
#define image_10_start_task_processing_wakeup_request        (0xc5)
#define image_10_start_task_spdsvc_natc_lookup        (0x801)
#define image_10_start_task_tm_tx_handle_rate_limit        (0x1651)
#define image_10_start_task_tm_tx_mirroring_handle        (0x1681)
#define image_10_start_task_tm_tx_task_wakeup_request        (0x1454)
#define image_10_start_task_tm_update_fifo_first_wakeup_request        (0x13dc)
#define image_10_start_task_ts_1588_handler        (0x88f)
#define image_10_start_task_tx_mirror        (0x1247)
#define image_10_start_task_xx_mirror_noinline        (0x96a)
#define image_10_tm_tx_handle_rate_limit        (0x1651)
#define image_10_tm_tx_mirroring_handle        (0x1681)
#define image_10_tm_tx_task_wakeup_request        (0x1454)
#define image_10_tm_update_fifo_first_wakeup_request        (0x13dc)
#define image_10_ts_1588_handler        (0x88f)
#define image_10_tx_mirror        (0x1247)
#define image_10_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 11 LABELS */
#ifndef IMAGE_11_CODE_ADDRESSES
#define IMAGE_11_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_11___umulsi3        (0x6100)
#define image_11_add_pbit_to_key        (0x29a4)
#define image_11_budget_allocator_tick        (0x5e0c)
#define image_11_c_g9991_flow_control_wakeup_request        (0x5fc8)
#define image_11_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_11_check_skip_cso        (0x2944)
#define image_11_debug_routine        (0x30)
#define image_11_debug_routine_handler        (0x4)
#define image_11_dos_attack_handler        (0x1f08)
#define image_11_drop_pkt_and_serial        (0x20f8)
#define image_11_dualq_pi2_stats        (0x4f00)
#define image_11_dyn_code_func        (0x7c00)
#define image_11_flow_policer        (0x485c)
#define image_11_general_timer_wakeup_request        (0x5f50)
#define image_11_get_queue_delay        (0x4ebc)
#define image_11_ghost_reporting_wakeup_request        (0x491c)
#define image_11_group_flow_lkp_and_fwd        (0x2ac4)
#define image_11_handle_flush        (0x524c)
#define image_11_ingress_filter_action_point_update        (0x29d0)
#define image_11_ingress_filters_handler        (0x2270)
#define image_11_initialization_task        (0x8)
#define image_11_is_iptv_capable        (0x1f64)
#define image_11_laqm_deque_check        (0x5040)
#define image_11_mcast_flow_master_lookup        (0x2a1c)
#define image_11_memcpy_abs_to_sbpm        (0xf8)
#define image_11_parser_exception_handler        (0x1d24)
#define image_11_pi2_deque_check        (0x4f90)
#define image_11_pi2_get_queue_delay        (0x4d50)
#define image_11_pi2_probability_calc        (0x4dbc)
#define image_11_pi2_timer        (0x4c88)
#define image_11_proccessing_loopback        (0x1c6c)
#define image_11_processing_policer_action        (0x48ac)
#define image_11_processing_wakeup_request        (0x314)
#define image_11_spdsvc_natc_lookup        (0x2004)
#define image_11_start_task___umulsi3        (0x6100)
#define image_11_start_task_add_pbit_to_key        (0x29a4)
#define image_11_start_task_budget_allocator_tick        (0x5e0c)
#define image_11_start_task_c_g9991_flow_control_wakeup_request        (0x5fc8)
#define image_11_start_task_check_cpu_rx_gdx_queue_occupancy        (0x2d8)
#define image_11_start_task_check_skip_cso        (0x2944)
#define image_11_start_task_debug_routine        (0x30)
#define image_11_start_task_dos_attack_handler        (0x1f08)
#define image_11_start_task_drop_pkt_and_serial        (0x20f8)
#define image_11_start_task_dualq_pi2_stats        (0x4f00)
#define image_11_start_task_dyn_code_func        (0x7c00)
#define image_11_start_task_flow_policer        (0x485c)
#define image_11_start_task_general_timer_wakeup_request        (0x5f50)
#define image_11_start_task_get_queue_delay        (0x4ebc)
#define image_11_start_task_ghost_reporting_wakeup_request        (0x491c)
#define image_11_start_task_group_flow_lkp_and_fwd        (0x2ac4)
#define image_11_start_task_handle_flush        (0x524c)
#define image_11_start_task_ingress_filter_action_point_update        (0x29d0)
#define image_11_start_task_ingress_filters_handler        (0x2270)
#define image_11_start_task_initialization_task        (0x8)
#define image_11_start_task_is_iptv_capable        (0x1f64)
#define image_11_start_task_laqm_deque_check        (0x5040)
#define image_11_start_task_mcast_flow_master_lookup        (0x2a1c)
#define image_11_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_11_start_task_parser_exception_handler        (0x1d24)
#define image_11_start_task_pi2_deque_check        (0x4f90)
#define image_11_start_task_pi2_get_queue_delay        (0x4d50)
#define image_11_start_task_pi2_probability_calc        (0x4dbc)
#define image_11_start_task_pi2_timer        (0x4c88)
#define image_11_start_task_proccessing_loopback        (0x1c6c)
#define image_11_start_task_processing_policer_action        (0x48ac)
#define image_11_start_task_processing_wakeup_request        (0x314)
#define image_11_start_task_spdsvc_natc_lookup        (0x2004)
#define image_11_start_task_tm_tx_handle_rate_limit        (0x5b40)
#define image_11_start_task_tm_tx_mirroring_handle        (0x5c00)
#define image_11_start_task_tm_tx_task_wakeup_request        (0x534c)
#define image_11_start_task_tm_update_fifo_first_wakeup_request        (0x516c)
#define image_11_start_task_ts_1588_handler        (0x223c)
#define image_11_start_task_tx_mirror        (0x5c9c)
#define image_11_start_task_xx_mirror_noinline        (0x25a8)
#define image_11_tm_tx_handle_rate_limit        (0x5b40)
#define image_11_tm_tx_mirroring_handle        (0x5c00)
#define image_11_tm_tx_task_wakeup_request        (0x534c)
#define image_11_tm_update_fifo_first_wakeup_request        (0x516c)
#define image_11_ts_1588_handler        (0x223c)
#define image_11_tx_mirror        (0x5c9c)
#define image_11_xx_mirror_noinline        (0x25a8)

#else

#define image_11___umulsi3        (0x1840)
#define image_11_add_pbit_to_key        (0xa69)
#define image_11_budget_allocator_tick        (0x1783)
#define image_11_c_g9991_flow_control_wakeup_request        (0x17f2)
#define image_11_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_11_check_skip_cso        (0xa51)
#define image_11_debug_routine        (0xc)
#define image_11_debug_routine_handler        (0x1)
#define image_11_dos_attack_handler        (0x7c2)
#define image_11_drop_pkt_and_serial        (0x83e)
#define image_11_dualq_pi2_stats        (0x13c0)
#define image_11_dyn_code_func        (0x1f00)
#define image_11_flow_policer        (0x1217)
#define image_11_general_timer_wakeup_request        (0x17d4)
#define image_11_get_queue_delay        (0x13af)
#define image_11_ghost_reporting_wakeup_request        (0x1247)
#define image_11_group_flow_lkp_and_fwd        (0xab1)
#define image_11_handle_flush        (0x1493)
#define image_11_ingress_filter_action_point_update        (0xa74)
#define image_11_ingress_filters_handler        (0x89c)
#define image_11_initialization_task        (0x2)
#define image_11_is_iptv_capable        (0x7d9)
#define image_11_laqm_deque_check        (0x1410)
#define image_11_mcast_flow_master_lookup        (0xa87)
#define image_11_memcpy_abs_to_sbpm        (0x3e)
#define image_11_parser_exception_handler        (0x749)
#define image_11_pi2_deque_check        (0x13e4)
#define image_11_pi2_get_queue_delay        (0x1354)
#define image_11_pi2_probability_calc        (0x136f)
#define image_11_pi2_timer        (0x1322)
#define image_11_proccessing_loopback        (0x71b)
#define image_11_processing_policer_action        (0x122b)
#define image_11_processing_wakeup_request        (0xc5)
#define image_11_spdsvc_natc_lookup        (0x801)
#define image_11_start_task___umulsi3        (0x1840)
#define image_11_start_task_add_pbit_to_key        (0xa69)
#define image_11_start_task_budget_allocator_tick        (0x1783)
#define image_11_start_task_c_g9991_flow_control_wakeup_request        (0x17f2)
#define image_11_start_task_check_cpu_rx_gdx_queue_occupancy        (0xb6)
#define image_11_start_task_check_skip_cso        (0xa51)
#define image_11_start_task_debug_routine        (0xc)
#define image_11_start_task_dos_attack_handler        (0x7c2)
#define image_11_start_task_drop_pkt_and_serial        (0x83e)
#define image_11_start_task_dualq_pi2_stats        (0x13c0)
#define image_11_start_task_dyn_code_func        (0x1f00)
#define image_11_start_task_flow_policer        (0x1217)
#define image_11_start_task_general_timer_wakeup_request        (0x17d4)
#define image_11_start_task_get_queue_delay        (0x13af)
#define image_11_start_task_ghost_reporting_wakeup_request        (0x1247)
#define image_11_start_task_group_flow_lkp_and_fwd        (0xab1)
#define image_11_start_task_handle_flush        (0x1493)
#define image_11_start_task_ingress_filter_action_point_update        (0xa74)
#define image_11_start_task_ingress_filters_handler        (0x89c)
#define image_11_start_task_initialization_task        (0x2)
#define image_11_start_task_is_iptv_capable        (0x7d9)
#define image_11_start_task_laqm_deque_check        (0x1410)
#define image_11_start_task_mcast_flow_master_lookup        (0xa87)
#define image_11_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_11_start_task_parser_exception_handler        (0x749)
#define image_11_start_task_pi2_deque_check        (0x13e4)
#define image_11_start_task_pi2_get_queue_delay        (0x1354)
#define image_11_start_task_pi2_probability_calc        (0x136f)
#define image_11_start_task_pi2_timer        (0x1322)
#define image_11_start_task_proccessing_loopback        (0x71b)
#define image_11_start_task_processing_policer_action        (0x122b)
#define image_11_start_task_processing_wakeup_request        (0xc5)
#define image_11_start_task_spdsvc_natc_lookup        (0x801)
#define image_11_start_task_tm_tx_handle_rate_limit        (0x16d0)
#define image_11_start_task_tm_tx_mirroring_handle        (0x1700)
#define image_11_start_task_tm_tx_task_wakeup_request        (0x14d3)
#define image_11_start_task_tm_update_fifo_first_wakeup_request        (0x145b)
#define image_11_start_task_ts_1588_handler        (0x88f)
#define image_11_start_task_tx_mirror        (0x1727)
#define image_11_start_task_xx_mirror_noinline        (0x96a)
#define image_11_tm_tx_handle_rate_limit        (0x16d0)
#define image_11_tm_tx_mirroring_handle        (0x1700)
#define image_11_tm_tx_task_wakeup_request        (0x14d3)
#define image_11_tm_update_fifo_first_wakeup_request        (0x145b)
#define image_11_ts_1588_handler        (0x88f)
#define image_11_tx_mirror        (0x1727)
#define image_11_xx_mirror_noinline        (0x96a)

#endif


#endif

/* IMAGE 12 LABELS */
#ifndef IMAGE_12_CODE_ADDRESSES
#define IMAGE_12_CODE_ADDRESSES

#ifndef PC_ADDRESS_INST_IND

#define image_12___umulsi3        (0x1e70)
#define image_12_budget_allocator_tick        (0x1c84)
#define image_12_debug_routine        (0x30)
#define image_12_debug_routine_handler        (0x4)
#define image_12_direct_flow_wakeup_request        (0x2d8)
#define image_12_dualq_pi2_stats        (0xa04)
#define image_12_dyn_code_func        (0x8000)
#define image_12_epon_tm_tx        (0x1914)
#define image_12_epon_tm_tx_credit_free        (0x1c4c)
#define image_12_epon_tm_tx_task_wakeup_request        (0x1b3c)
#define image_12_epon_tm_update_fifo_first_wakeup_request        (0x1af0)
#define image_12_general_timer_wakeup_request        (0x1dc8)
#define image_12_get_queue_delay        (0x9c0)
#define image_12_handle_flush        (0xdac)
#define image_12_initialization_task        (0x8)
#define image_12_laqm_deque_check        (0xb44)
#define image_12_memcpy_abs_to_sbpm        (0xf8)
#define image_12_pi2_deque_check        (0xa94)
#define image_12_pi2_get_queue_delay        (0x854)
#define image_12_pi2_probability_calc        (0x8c0)
#define image_12_pi2_timer        (0x790)
#define image_12_start_task___umulsi3        (0x1e70)
#define image_12_start_task_budget_allocator_tick        (0x1c84)
#define image_12_start_task_debug_routine        (0x30)
#define image_12_start_task_direct_flow_wakeup_request        (0x2d8)
#define image_12_start_task_dualq_pi2_stats        (0xa04)
#define image_12_start_task_dyn_code_func        (0x8000)
#define image_12_start_task_epon_tm_tx        (0x1914)
#define image_12_start_task_epon_tm_tx_credit_free        (0x1c4c)
#define image_12_start_task_epon_tm_tx_task_wakeup_request        (0x1b3c)
#define image_12_start_task_epon_tm_update_fifo_first_wakeup_request        (0x1af0)
#define image_12_start_task_general_timer_wakeup_request        (0x1dc8)
#define image_12_start_task_get_queue_delay        (0x9c0)
#define image_12_start_task_handle_flush        (0xdac)
#define image_12_start_task_initialization_task        (0x8)
#define image_12_start_task_laqm_deque_check        (0xb44)
#define image_12_start_task_memcpy_abs_to_sbpm        (0xf8)
#define image_12_start_task_pi2_deque_check        (0xa94)
#define image_12_start_task_pi2_get_queue_delay        (0x854)
#define image_12_start_task_pi2_probability_calc        (0x8c0)
#define image_12_start_task_pi2_timer        (0x790)
#define image_12_start_task_tm_tx_dbg_stat_by_size        (0x1828)
#define image_12_start_task_tm_tx_dbg_stat_get_cntr_id        (0x1e40)
#define image_12_start_task_tm_tx_handle_rate_limit        (0x16ac)
#define image_12_start_task_tm_tx_mirroring_handle        (0x176c)
#define image_12_start_task_tm_tx_task_wakeup_request        (0xeac)
#define image_12_start_task_tm_update_fifo_first_wakeup_request        (0xc70)
#define image_12_start_task_tx_mirror        (0x1980)
#define image_12_tm_tx_dbg_stat_by_size        (0x1828)
#define image_12_tm_tx_dbg_stat_get_cntr_id        (0x1e40)
#define image_12_tm_tx_handle_rate_limit        (0x16ac)
#define image_12_tm_tx_mirroring_handle        (0x176c)
#define image_12_tm_tx_task_wakeup_request        (0xeac)
#define image_12_tm_update_fifo_first_wakeup_request        (0xc70)
#define image_12_tx_mirror        (0x1980)

#else

#define image_12___umulsi3        (0x79c)
#define image_12_budget_allocator_tick        (0x721)
#define image_12_debug_routine        (0xc)
#define image_12_debug_routine_handler        (0x1)
#define image_12_direct_flow_wakeup_request        (0xb6)
#define image_12_dualq_pi2_stats        (0x281)
#define image_12_dyn_code_func        (0x2000)
#define image_12_epon_tm_tx        (0x645)
#define image_12_epon_tm_tx_credit_free        (0x713)
#define image_12_epon_tm_tx_task_wakeup_request        (0x6cf)
#define image_12_epon_tm_update_fifo_first_wakeup_request        (0x6bc)
#define image_12_general_timer_wakeup_request        (0x772)
#define image_12_get_queue_delay        (0x270)
#define image_12_handle_flush        (0x36b)
#define image_12_initialization_task        (0x2)
#define image_12_laqm_deque_check        (0x2d1)
#define image_12_memcpy_abs_to_sbpm        (0x3e)
#define image_12_pi2_deque_check        (0x2a5)
#define image_12_pi2_get_queue_delay        (0x215)
#define image_12_pi2_probability_calc        (0x230)
#define image_12_pi2_timer        (0x1e4)
#define image_12_start_task___umulsi3        (0x79c)
#define image_12_start_task_budget_allocator_tick        (0x721)
#define image_12_start_task_debug_routine        (0xc)
#define image_12_start_task_direct_flow_wakeup_request        (0xb6)
#define image_12_start_task_dualq_pi2_stats        (0x281)
#define image_12_start_task_dyn_code_func        (0x2000)
#define image_12_start_task_epon_tm_tx        (0x645)
#define image_12_start_task_epon_tm_tx_credit_free        (0x713)
#define image_12_start_task_epon_tm_tx_task_wakeup_request        (0x6cf)
#define image_12_start_task_epon_tm_update_fifo_first_wakeup_request        (0x6bc)
#define image_12_start_task_general_timer_wakeup_request        (0x772)
#define image_12_start_task_get_queue_delay        (0x270)
#define image_12_start_task_handle_flush        (0x36b)
#define image_12_start_task_initialization_task        (0x2)
#define image_12_start_task_laqm_deque_check        (0x2d1)
#define image_12_start_task_memcpy_abs_to_sbpm        (0x3e)
#define image_12_start_task_pi2_deque_check        (0x2a5)
#define image_12_start_task_pi2_get_queue_delay        (0x215)
#define image_12_start_task_pi2_probability_calc        (0x230)
#define image_12_start_task_pi2_timer        (0x1e4)
#define image_12_start_task_tm_tx_dbg_stat_by_size        (0x60a)
#define image_12_start_task_tm_tx_dbg_stat_get_cntr_id        (0x790)
#define image_12_start_task_tm_tx_handle_rate_limit        (0x5ab)
#define image_12_start_task_tm_tx_mirroring_handle        (0x5db)
#define image_12_start_task_tm_tx_task_wakeup_request        (0x3ab)
#define image_12_start_task_tm_update_fifo_first_wakeup_request        (0x31c)
#define image_12_start_task_tx_mirror        (0x660)
#define image_12_tm_tx_dbg_stat_by_size        (0x60a)
#define image_12_tm_tx_dbg_stat_get_cntr_id        (0x790)
#define image_12_tm_tx_handle_rate_limit        (0x5ab)
#define image_12_tm_tx_mirroring_handle        (0x5db)
#define image_12_tm_tx_task_wakeup_request        (0x3ab)
#define image_12_tm_update_fifo_first_wakeup_request        (0x31c)
#define image_12_tx_mirror        (0x660)

#endif


#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#ifndef PC_ADDRESS_INST_IND


#else


#endif


#endif

